// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define(["require","exports","./Util","./ComponentUtils"],function(u,v,p,q){function r(a,d){var b=a.reduce(function(a,b){b=b.indices[d];return a+(null==b?0:b.length)},0),c=new Uint32Array(b),k=0,e=0;a.forEach(function(a){var b=a.indices[d];if(null!=b){var f=b.length,g=b.byteLength;c.set(b,k);a.indices[d]=new Uint32Array(c.buffer,e,f);k+=f;e+=g}});return c}function t(a){var d={},b;b=p.getFirstObjectValue(a);b=b.data.length/b.size;if(b>l||null==n){for(;b>l;)l*=2;n=new Uint32Array(l);for(var c=0;c<l;c++)n[c]=
c}b=new Uint32Array(n.buffer,0,b);for(var k in a)d[k]=b;return d}var l=1,n=null;return function(){function a(d,b,c,k){void 0===b&&(b=a.DefaultIndices);void 0===c&&(c=a.DefaultOffsets);void 0===k&&(k="triangle");var e=[],h={},m={},f=Array.isArray(d);f?(e=d,m=b):(m=d,h=b,h===a.DefaultIndices&&(h=t(m)));if(f)if(1<e.length&&(c=e.map(function(a){return a.componentRange[0]}),c.push(e[e.length-1].componentRange[1]+1),c=new Uint32Array(c)),1===e.length){b=e[0];for(var g in m)d=b.indices,h[g]=d[g]}else for(g in m)h[g]=
r(e,g);else{d=p.getFirstObjectValue(h).length;f=b=void 0;c===a.DefaultOffsets?(b=0,f=d):(b=c[0],f=c[c.length-1]);var l=f-b,n=b*Uint32Array.BYTES_PER_ELEMENT;d={};for(g in h)d[g]=new Uint32Array(h[g].buffer,n,l);e.push({type:k,positionKey:"position",indices:d,componentRange:[b,f-1]})}this._id=a.getNewId();this._faces=e;this._vertexAttributes=m;this._indices=h;this._componentOffsets=q.createOffsets(c);this._primitiveType=k}Object.defineProperty(a.prototype,"id",{get:function(){return this._id},enumerable:!0,
configurable:!0});Object.defineProperty(a.prototype,"faces",{get:function(){return this._faces},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"vertexAttributes",{get:function(){return this._vertexAttributes},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"indices",{get:function(){return this._indices},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"componentOffsets",{get:function(){return this._componentOffsets},enumerable:!0,configurable:!0});
Object.defineProperty(a.prototype,"indexCount",{get:function(){return this._indices.position.length},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"positionKey",{get:function(){return"position"},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"primitiveType",{get:function(){return this._primitiveType},enumerable:!0,configurable:!0});a.prototype.toRenderData=function(){return{id:this._id.toString(),faces:this._faces[0],vertexAttr:this._vertexAttributes}};a.prototype.estimateGpuMemoryUsage=
function(){var a=0;this._indices.position&&(a+=12*this._indices.position.length);this._indices.normal&&(a+=12*this._indices.normal.length);this._indices.uv0&&(a+=8*this._indices.uv0.length);this._indices.color&&(a+=4*this._indices.color.length);return a};a.prototype.getId=function(){return this.id};a.prototype.getFaces=function(){return this.faces};a.prototype.getVertexAttr=function(){return this.vertexAttributes};a.getNewId=function(){return a._id++};a._id=0;a.AxisOrder={CG:0,GIS:1};a.DefaultIndices=
{};a.DefaultOffsets=new Uint32Array(0);return a}()});