// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/Accessor ../../../core/arrayUtils ../../../core/CollectionFlattener ../../../core/ObjectPool ../../../core/Logger ../../../core/watchUtils ../../../geometry/Point ../lib/glMatrix ../support/aaBoundingRect ../support/Evented ../support/mathUtils ../support/PreallocArray ../support/projectionUtils ../support/PromiseLightweight ../support/ResourceController ./OverlayManager ./PlanarTile ./SphericalTile ./SurfaceExtentHelper ./SurfaceTilingSchemeLogic ./TerrainConst ./TerrainRenderer ./terrainUtils ./TileGeometryFactory ./TilemapOnlyTile ./tileUtils ./tileUtils".split(" "),
function(J,oa,S,p,n,T,D,U,V,W,K,X,w,x,Y,Z,aa,F,L,ba,ca,da,ea,M,fa,k,ga,r,ha,ia,A,N){function O(k,c){return k[0]===c[0]&&k[1]===c[1]&&k[2]===c[2]}function P(k){return k&&("cancel"===k||"cancel"===k.dojoType)}function ja(k){k.remove()}var Q=w.vec3d,G=w.vec4d,R=w.mat4d,B=r.weakAssert,t=W.getLogger("esri.views.3d.terrain.TerrainSurface");J=function(w){function c(){var a=w.call(this)||this;a.defaultTileBackground=k.DEFAULT_TILE_BACKGROUND;a.hideSkirtsDistanceFromExtentMargin=ka;a.hideSkirtsMinimumCameraTilt=
la;a._clippingExtent=null;a._dataExtent=null;a._elevationBounds=[0,0];a._rootExtent=[0,0,0,0];a._iteratorPool=new V(N.IteratorPreorder);a._postorderIterator=new N.IteratorPostorder;a.visible=!1;a.suspended=!1;a._pendingUpdates=!1;a._lvPendingUpdates=!1;a._updateNextFrame=0;a._vectorTileLayerRequests=0;a._curOverlayOpacity=1;a._curEyePos=Q.create();a._curSplitLimits=[0,0,0,0,0,0];a._curFrustumPlanes=Array(6);a._viewProjectionMatrix=R.identity();a.tilemapStats={tilemapRequestsSent:0,tilemapRequestsPending:0,
tilemapRequestErrors:0,fullTilemaps:0,emptyTilemaps:0,tilesRequested:0,tileRequestsSent:0,tileRequestErrors:0,tilesNotPresent:0};a._layerViews=[[],[]];a._layerIndexByLayerViewId=[{},{}];a._basemapLayerViewHandles={};a._layerViewChangesHandle=null;a._viewChangeListenerHandles=[];a._frameUpdateLowerPrio=new aa(500);a._topLevelTilemapOnlyTiles=Array(k.TILEMAP_SIZE_EXP+1);a.loaded=!1;a.maxTextureScale=1.2;a.rootTiles=null;for(var b=0;b<a._topLevelTilemapOnlyTiles.length;b++)a._topLevelTilemapOnlyTiles[b]=
new ia([b-k.TILEMAP_SIZE_EXP,0,0]);for(b=0;6>b;b++)a._curFrustumPlanes[b]=G.create();return a}S(c,w);c.prototype.normalizeCtorArgs=function(a,b){this._view=a;this._stage=a._stage;this._set("manifold",b);return{}};c.prototype.initialize=function(){var a=this;this.tilePool="planar"===this.manifold?da.Pool:ea.Pool;this._renderer=new ga(this.manifold,null,this._view.pointsOfInterest);this._renderer.loaded=this._setLoaded.bind(this);this._renderer.updateTileBackground(this.tileBackground);this._renderer.install(this._view._stage);
this._set("overlayManager",new ca({terrainSurface:this,view:this._view}));this.watch("overlayManager.hasHighlights",this._handleHasHighlights.bind(this));var b={layers:this._view.map.allLayers,layerViews:this._view.allLayerViews,spatialReference:this._view.spatialReference};this.extentHelper="spherical"===this.manifold?new M.SurfaceExtentHelperGlobal(b):new M.SurfaceExtentHelperLocal(b);K.init(this.extentHelper,"stencilEnabledExtents",function(b){a._renderer.setStencilEnabledLayerExtents(b)});b=this._view.defaultsFromMap?
new U({root:this._view.map,rootCollectionNames:this._view.defaultsFromMap.mapCollectionPaths,getChildrenFunction:function(a){return a.layers}}):this._view.map.allLayers;b=new fa({layers:b,extentHelper:this.extentHelper,manifold:this.manifold,viewSpatialReference:this._view.spatialReference});this._set("tilingSchemeLogic",b);this.tilingSchemeLogic.watch("tilingScheme",this._updateTilingSchemeAndExtent.bind(this),!0);this.tilingSchemeLogic.watch("extent",this._updateTilingSchemeAndExtent.bind(this),
!0);this._updateTilingSchemeAndExtent();this._streamDataSupplier=this._view.resourceController.registerClient(this,ba.ClientType.TERRAIN);b={needsUpdate:this._needsIdleUpdate,idleFrame:this._idleUpdate};this._view.resourceController.registerFrameWorker(this._frameUpdate.bind(this));this._view.resourceController.registerIdleFrameWorker(this,b);this._viewChangeUpdate=this._viewChangeUpdate.bind(this);this._viewChangeListenerHandles.push(this._view.on("resize",this._viewChangeUpdate));this._viewChangeListenerHandles.push(K.on(this._view,
"navigation","currentViewChanged",this._viewChangeUpdate));this._viewChangeListenerHandles.push(this._view.watch("qualitySettings.tiledSurface.lodBias",this._viewChangeUpdate));this._layerViewChangesHandle=this._view.allLayerViews.on("change",this._handleLayerViewChanges.bind(this));this._handleLayerViewChanges({added:this._view.allLayerViews.toArray(),removed:[],moved:[]});this._clippingChangedHandle=this._view.watch("clippingArea",this._clippingChanged.bind(this));this._updateClippingExtent();this.notifyChange("extent")};
c.prototype.destroy=function(){this._removeAllTiles();this.tilingSchemeLogic.destroy();this._set("tilingSchemeLogic",null);this.extentHelper.destroy();this.extentHelper=null;for(var a in this._basemapLayerViewHandles)this._unregisterTiledLayerView(a);this._view.resourceController.deregisterFrameWorker();this._view.resourceController.deregisterIdleFrameWorker(this);this._view.resourceController.deregisterClient(this);this._viewChangeListenerHandles.forEach(ja);this._layerViewChangesHandle.remove();
this._clippingChangedHandle.remove();this.overlayManager&&(this.overlayManager.destroy(),this._set("overlayManager",null));this._renderer.uninstall(this._stage);this._streamDataSupplier=this._stage=this._view=this._renderer=null};Object.defineProperty(c.prototype,"cullBackFaces",{set:function(a){this._renderer.setCullBackFaces(a);this._set("cullBackFaces",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"extent",{get:function(){return this._clippingExtent||this._rootExtent},enumerable:!0,
configurable:!0});Object.defineProperty(c.prototype,"frontMostTransparent",{set:function(a){this._renderer.setFrontMostTransparent(a);this._set("frontMostTransparent",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"opacity",{set:function(a){this._renderer.setOpacity(a);this._set("opacity",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"ready",{get:function(){return!!this.rootTiles},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"renderOrder",
{set:function(a){this._renderer.setRenderOrder(a);this._set("renderOrder",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"skirts",{set:function(a){this._renderer.setDrawSkirts(a);this._set("skirts",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"tileBackground",{set:function(a){a!==this.tileBackground&&this._renderer.updateTileBackground(a);this._set("tileBackground",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"velvetOverground",
{set:function(a){a!==this.velvetOverground&&this._renderer.setVelvetOverground(a);this._set("velvetOverground",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"wireframe",{set:function(a){this._renderer.setWireframe(a);this._set("wireframe",a);this._view._stage.setRenderParams({earlyOcclusionPixelDraw:a})},enumerable:!0,configurable:!0});c.prototype.setVisibility=function(a){a!==this.visible&&(this.visible=a,this._renderer.setVisibility(a),this.setUpdatesDisabled(!a),a&&this._viewChangeUpdate())};
c.prototype.isVisible=function(){return this.visible&&this.ready};c.prototype.isSeeThrough=function(){return this._renderer.isTransparent()};c.prototype.setUpdatesDisabled=function(a){(this.suspended=a)||this._viewChangeUpdate()};c.prototype.intersect=function(a,b,d){this._renderer.intersect(a,b,d)};c.prototype.getElevation=function(a){if(!this.ready)return null;var b=k.LayerClass.ELEVATION,d=this.rootTiles,h=d[0].layerInfo[b].length;if(0===h)return null;C.length<h&&(C.length=h);if(a instanceof X){if(!F.pointToVector(a,
v,this.tilingScheme.spatialReference))return t.error("TerrainSurface.getElevation(): could not project given point to tiling scheme coordinate system"),null;a=v}for(var c=0;c<d.length;c++){var e=d[c];if(A.isPosWithinTile(e,a)){do{c=e.layerInfo[b];for(d=0;d<h;d++)null!=c[d].data&&(H[d]=c[d].data);d=0;a[0]>.5*(e.extent[0]+e.extent[2])&&(d+=1);a[1]<.5*(e.extent[1]+e.extent[3])&&(d+=2);e=e.children[d]}while(null!=e);break}}for(d=0;d<h;d++)C[d]=H[d]?H[d].samplerData:null;b=ha.elevationSampler(a[0],a[1],
C);for(d=0;d<h;d++)C[d]=void 0;return b};c.prototype.getElevationBounds=function(){return this._elevationBounds};c.prototype.getScale=function(a){if(this.tilingScheme){if(!F.pointToVector(a,v,this.spatialReference))return t.error("TerrainSurface.getElevation(): could not project given point to tiling scheme coordinate system"),null;if(this.rootTiles)for(var b=0;b<this.rootTiles.length;b++)if(a=this.rootTiles[b],A.isPosWithinTile(a,v)){for(;a.children[0];)b=0,v[0]>a.children[0].extent[2]&&(b+=1),v[1]<
a.children[0].extent[1]&&(b+=2),a=a.children[b];return this._getLodBiasCorrectedScale(a.lij[0])}}return 1E100};c.prototype.queryVisibleScaleRange=function(a,b,d,c){b=b?this.tilingScheme.levelAtScale(b):0;d=d?this.tilingScheme.levelAtScale(d):Infinity;var h=this._getLodBias();this._renderer.queryVisibleLevelRange(a,b+h,d+h,c)};c.prototype._setLoaded=function(){this.loaded||this._set("loaded",!0)};c.prototype._updateTilingSchemeAndExtent=function(){var a=this.tilingSchemeLogic.extent,b=this.tilingSchemeLogic.tilingScheme,
d=!1;a&&!x.equals(a,this._dataExtent)&&(d=!0,this._dataExtent?x.set(this._dataExtent,a):this._dataExtent=x.create(a));b!==this.tilingScheme&&(B(!!b,"tiling scheme cannot be reset to undefined"),d=!0,this.tilingScheme&&this._removeAllTiles(),this._set("tilingScheme",b),this._updateClippingExtent(),b&&(this._updateTiledLayers(),this._renderer.setTileSize(b.pixelSize[0]),this.overlayManager.setSpatialReference(b.spatialReference,"spherical"===this.manifold)));d&&this._updateRootTiles()};c.prototype._acquireTile=
function(a,b,d,c){var h=this.tilePool.acquire();E[0]=a;E[1]=b;E[2]=d;h.init(E,c,this,this.tilingScheme);return h};c.prototype._releaseTile=function(a){a.dispose();a.parent=null;a.parentSurface=null;this.tilePool.release(a)};c.prototype._updateRootTiles=function(){var a=this,b=this._clippingExtent||this._dataExtent,d=this.tilingScheme;if(b&&d){var c=v,g=d.rootTilesInExtent(b,c,Infinity);if(this.rootTiles){if(g.length>I){t.warn(k.TOO_MANY_ROOT_TILES_AFTER_CHANGE_ERROR);return}var b=this.rootTiles.map(function(a){return a.lij}),
e=D.difference(b,g,O);if(0<e.removed.length||0<e.added.length){var f=this.rootTiles.filter(function(b){return-1<D.findIndex(e.removed,O.bind(null,b.lij))?(a._purgeChildTiles(b),a._purgeTile(b),!1):!0});e.added.forEach(function(b){b=a._acquireTile(0,b[1],b[2],null);f.push(b);a._loadTile(b)});this._set("rootTiles",f);this._renderer.setRootTiles(this.rootTiles)}}else g.length>I&&(t.warn(k.TOO_MANY_ROOT_TILES_FOR_LAYER_ERROR),g=d.rootTilesInExtent(b,c,I)),this._set("rootTiles",g.map(function(b){b=a._acquireTile(0,
b[1],b[2],null);a._loadTile(b);return b})),this._renderer.setRootTiles(this.rootTiles);D.equals(c,this._rootExtent)||(this._rootExtent=G.create(c),this._hasFixedExtent()||this.notifyChange("extent"));this.setVisibility(!0);this._viewChangeUpdate();this.notifyChange("ready")}};c.prototype._viewChangeUpdate=function(){this._stage&&!this.suspended&&this.tilingScheme&&this.visible&&(this._updateViewDependentParameters(),this._updateOverlayOpacity(this._curEyePos),this._updateTiles(this.rootTiles))};c.prototype._updateTiles=
function(a){var b=this._iteratorPool.acquire();b.reset(a);var d=this._curSplitLimits,c=this._curFrustumPlanes,g=this._curEyePos,e;A.hasVisibleSiblings(a)?(a=this._elevationBounds[0],e=this._elevationBounds[1]):(a=Infinity,e=-Infinity);for(;!b.done;){var f=b.next();f.updateClippingStatus(this._clippingExtent);var l=!0;if(f.updateVisibility(c,g)){f.updateScreenDepth(this._viewProjectionMatrix);f.renderData&&(a=Math.min(f.elevationBounds[0],a),e=Math.max(f.elevationBounds[1],e));var q=f.shouldSplit(d,
g);q===m.SPLIT?(f.pendingUpdates&=~m.MERGE,f.renderData?(l=!1,f.pendingUpdates|=m.SPLIT,b.skip()):l=!1):(f.pendingUpdates&=~m.SPLIT,q===m.VSPLITMERGE&&f.updateAgents(k.LayerClass.ELEVATION),b.skip())}else b.skip();if(l&&!f.renderData){f.pendingUpdates|=m.MERGE;f.pendingUpdates&=~m.SPLIT;l=this._iteratorPool.acquire();for(l.reset(f);!l.done;)q=l.next(),q.updateVisibility(c,g),q.visible&&q.updateScreenDepth(this._viewProjectionMatrix);this._iteratorPool.release(l)}0!==f.pendingUpdates&&(this._pendingUpdates=
!0)}this._iteratorPool.release(b);isFinite(a)&&isFinite(e)&&(this._elevationBounds[0]!==a||this._elevationBounds[1]!==e)&&(this._elevationBounds[0]=a,this._elevationBounds[1]=e,this.emit("elevation-bounds-change",null))};c.prototype._updateViewDependentParameters=function(){var a=this._view.navigation.currentCamera,b=Math.tan(.5*a.fovX),d=Math.tan(.5*a.fovY),c=this.tilingScheme.pixelSize,g=Math.pow(2,-this._getLodBias());this._curSplitLimits[0]=b;this._curSplitLimits[1]=c[0]/a.width*this.maxTextureScale*
g;this._curSplitLimits[2]=d;this._curSplitLimits[3]=c[1]/a.height*this.maxTextureScale*g;this._curSplitLimits[4]=this.tilingScheme.getMaxLod();this._curSplitLimits[5]=this._view.qualitySettings.tiledSurface.angledSplitBias;a.copyFrustumPlanes(this._curFrustumPlanes);R.multiply(a.projectionMatrix,a.viewMatrix,this._viewProjectionMatrix);Q.set(a.eye,this._curEyePos);r.autoUpdateSkirtsVisibility(this,this._curEyePos)};c.prototype._setLayerViewsUpdating=function(){for(var a=0;a<k.LayerClass.LAYER_CLASS_COUNT;a++)for(var b=
this._layerViews[a],d=0;d<b.length;d++)b[d]._evaluateUpdatingState(this._pendingUpdates)};c.prototype._frameUpdateTraversal=function(a){if(!this.suspended){this._frameUpdateLowerPrio.clear();var b=this._renderer.resourceCounter.numTileTexturesComposited,d=this._iteratorPool.acquire();d.reset(this.rootTiles);for(var c=!1,g=!1;!d.done&&(1<a.remaining()||!c)&&this._renderer.resourceCounter.numTileTexturesComposited-b<ma;){var e=d.next();e.pendingUpdates&m.MERGE?(this._mergeTile(e),e.pendingUpdates&=
~m.MERGE,c=!0,d.skip()):e.pendingUpdates&m.SPLIT?(this._splitTile(e),e.pendingUpdates&=~m.SPLIT,c=!0,d.skip()):0<e.pendingUpdates&&this._frameUpdateLowerPrio.push(e);0!==e.pendingUpdates&&(g=!0)}this._pendingUpdates=g||!d.done;this._iteratorPool.release(d);return c}};c.prototype._updateTileGeometry=function(a){this._renderer._updateTileGeometry(a);y.spatialReference=this.spatialReference;y.tile=a;this.emit("tile-geometry-change",y)};c.prototype._updateTileTexture=function(a){this._renderer.updateTileTexture(a)};
c.prototype._frameUpdate=function(a){if(this.rootTiles){for(var b=this._frameUpdateTraversal(a);(1<a.remaining()||!b)&&0<this._frameUpdateLowerPrio.length;){var d=this._frameUpdateLowerPrio.pop();d.pendingUpdates&m.DECODE_ELEVATION?(this._decodeElevation(d),d.pendingUpdates&=~m.DECODE_ELEVATION,b=!0):d.pendingUpdates&m.UPDATE_GEOMETRY?(this._renderer.updateTileGeometryNeedsUpdate(d),this._updateTileGeometry(d),b=!0,d.pendingUpdates&=~m.UPDATE_GEOMETRY):d.pendingUpdates&m.UPDATE_TEXTURE&&(this._updateTileTexture(d),
d.pendingUpdates&=~m.UPDATE_TEXTURE,b=!0);0!==d.pendingUpdates&&(this._pendingUpdates=!0)}0<this._frameUpdateLowerPrio.length&&(this._pendingUpdates=!0);if(this._streamDataSupplier.hasPendingDownloads()||0!==this._vectorTileLayerRequests)this._pendingUpdates=!0;this._pendingUpdates===this._lvPendingUpdates||!this._pendingUpdates&&20!==++this._updateNextFrame||(this._setLayerViewsUpdating(),this._lvPendingUpdates=this._pendingUpdates,this._updateNextFrame=0)}};c.prototype._needsIdleUpdate=function(){return this.isVisible()&&
this.overlayManager&&this.overlayManager.overlaysNeedUpdate()};c.prototype._idleUpdate=function(){this.overlayManager.updateOverlay();this._updateOverlayOpacity(this._curEyePos)};c.prototype._updateClippingExtent=function(){if(!this.spatialReference)return!1;var a=[0,0,0,0],b=null;F.extentToBoundingRect(this._view.clippingArea,a,this.spatialReference)&&(b=a);if(D.equals(b,this._clippingExtent))return!1;this._clippingExtent=b;this._renderer.clippingExtent=b;this.notifyChange("extent");return!0};c.prototype._clippingChanged=
function(){this._updateClippingExtent()&&this._updateRootTiles()};c.prototype._getLodBias=function(){return Math.round(this._view.qualitySettings.tiledSurface.lodBias)};c.prototype._getLodBiasCorrectedScale=function(a){var b=this.tilingScheme.levels;a=Z.clamp(a-this._getLodBias(),0,b.length-1);return b[a].scale};c.prototype._cancelTilemapRequests=function(a){for(var b=0;b<k.LayerClass.LAYER_CLASS_COUNT;b++){var d=a.layerInfo[b];if(d)for(var c=0;c<d.length;c++){var g=d[c];g.tilemapRequest&&(g.tilemapRequest.cancel(),
g.tilemapRequest=null)}}};c.prototype._removeAllTiles=function(){var a=this;this.rootTiles&&(this.rootTiles.forEach(function(b){a._purgeChildTiles(b);a._purgeTile(b)}),this._set("rootTiles",null),this.notifyChange("ready"));for(var b=0;b<this._topLevelTilemapOnlyTiles.length;b++)this._cancelTilemapRequests(this._topLevelTilemapOnlyTiles[b]);this.setVisibility(!1)};c.prototype._purgeChildTiles=function(a){var b=this._postorderIterator;for(b.reset(a);!b.done;){for(var d=b.next(),c=0;4>c;c++)d.children[c]=
null;d!==a&&this._purgeTile(d)}};c.prototype._purgeTile=function(a){a.unload(this._renderer);this._cancelTilemapRequests(a);a.parent=null;this._releaseTile(a)};c.prototype._splitTile=function(a){var b=a.lij[0]+1,d=2*a.lij[1],c=2*a.lij[2];a.children[0]=this._createTile(b,d,c,a);a.children[1]=this._createTile(b,d,c+1,a);a.children[2]=this._createTile(b,d+1,c,a);a.children[3]=this._createTile(b,d+1,c+1,a);a.unload(this._renderer);u.spatialReference=this.spatialReference;u.extent=a.extent;u.scale=this._getLodBiasCorrectedScale(b);
this.emit("scale-change",u)};c.prototype._createTile=function(a,b,d,c){B(!!c,"_createTile sanity check");a=this._acquireTile(a,b,d,c);a.updateClippingStatus(this._clippingExtent);a.updateVisibility(this._curFrustumPlanes,this._curEyePos);a.visible&&(a.updateScreenDepth(this._viewProjectionMatrix),a.shouldSplit(this._curSplitLimits,this._curEyePos)===m.SPLIT&&(a.pendingUpdates|=m.SPLIT,this._pendingUpdates=!0));this._loadTile(a);return a};c.prototype._mergeTile=function(a){B(!a.renderData,"_mergeTile sanity check");
this._loadTile(a);this._purgeChildTiles(a);u.spatialReference=this.spatialReference;u.extent=a.extent;u.scale=this._getLodBiasCorrectedScale(a.lij[0]);this.emit("scale-change",u)};c.prototype._loadTile=function(a){a.load(this._renderer);this.overlayManager&&this.overlayManager.hasOverlays()&&this.overlayManager.setOverlayParamsOfTile(a,a.renderData,this._curOverlayOpacity);y.tile=a;y.spatialReference=this.tilingScheme.spatialReference;this.emit("tile-geometry-change",y)};c.prototype._handleHasHighlights=
function(a){this._renderer.setNeedsHighlight(a)};c.prototype._decodeElevation=function(a){var b=k.LayerClass.ELEVATION,d=a.layerInfo[b];if(d)for(var c=0;c<d.length;c++){var g=d[c];g.pendingUpdates&=~m.DECODE_ELEVATION;if(g.rawData){var e=a.decodeElevationData(g.rawData);g.rawData=null;if(e){g.data=e;var g=a.lij[0],f=this._iteratorPool.acquire();for(f.reset(a);!f.done;){var l=f.next();l.findElevationBoundsForLayer(c,g);l.computeElevationBounds()}this._iteratorPool.release(f);a.dataArrived(c,b,e);this._updateTiles(a);
z.spatialReference=this.spatialReference;z.extent=a.extent;this._emitElevationChange(z)}}}};c.prototype._handleLayerViewChanges=function(a){var b=this,d=!1;a.added.forEach(function(a){var c=a.layer;r.isTiledLayerView(a)?(b._registerTiledLayer(a),c.loaded&&(d=!0)):a.supportsDraping&&b.overlayManager&&b.overlayManager.registerLayerView(a)});a.removed.forEach(function(a){r.isTiledLayerView(a)?(d=!0,b._unregisterTiledLayerView(a.uid)):a.supportsDraping&&b.overlayManager&&b.overlayManager.unregisterLayerView(a)});
(d=d||0<a.moved.filter(r.isTiledLayerView).length)&&this._updateTiledLayers()};c.prototype._registerTiledLayer=function(a){var b=this,d=[];d.push(a.watch("suspended",function(){b._updateTiledLayers()}));d.push(a.watch("fullOpacity",function(){return b._updateTileTextures()}));a.on("data-changed",function(){var d=r.isElevationLayerView(a)?k.LayerClass.ELEVATION:k.LayerClass.MAP,c=b._layerIndexByLayerViewId[d][a.uid];null!=c&&b._invalidateLayerData(c,d)});this._basemapLayerViewHandles[a.uid]=d};c.prototype._unregisterTiledLayerView=
function(a){var b=this._basemapLayerViewHandles[a];if(b){for(var d=0;d<b.length;d++)b[d].remove();delete this._basemapLayerViewHandles[a]}};c.prototype._updateTiledLayers=function(){var a=this;if(this.tilingScheme){var b=this._view.allLayerViews,d=[[],[]],c=k.LayerClass,g=null,e=x.create(x.NEGATIVE_INFINITY);b.forEach(function(b){var f=b.layer;if(b.layer&&b&&!b.suspended&&r.isTiledLayerView(b)){var h=b.fullExtent;h?a.tilingScheme.compatibleWith(b.tileInfo)?(x.expand(e,h),r.isElevationLayerView(b)?
d[c.ELEVATION].push(b):(Infinity!==b.maxDataLevel&&(null===g||b.maxDataLevel>g)&&(g=b.maxDataLevel),d[c.MAP].push(b))):t.warn("Terrain: tiling scheme of layer "+f.id+" is incompatible with other tiled layers, will not be drawn"):t.warn("Terrain: Map or elevation layer does not have fullExtent: "+f.id)}},this);for(var b=function(a){var b=f._layerViews[a],e=d[a];e.reverse();var g=b.length!==e.length,h=e.length,l=Array(h),k=Array(b.length);f._layerIndexByLayerViewId[a]={};for(var q=0;q<h;q++){f._layerIndexByLayerViewId[a][e[q].uid]=
q;var m=b.indexOf(e[q]);l[q]=m;q!==m&&(g=!0);-1<m&&(k[m]=q)}if(g){f._topLevelTilemapOnlyTiles.forEach(function(b){return b.modifyLayers(k,l,a)});b=f._postorderIterator;if(f.rootTiles)for(b.reset(f.rootTiles);!b.done;)b.next().modifyLayers(k,l,a);f._layerViews[a]=e;if(f.rootTiles){for(b.reset(f.rootTiles);!b.done;)e=b.next(),e.restartAgents(a),a===c.ELEVATION&&e.computeElevationBounds();f._updateTiles(f.rootTiles)}a===c.ELEVATION&&f.tilingScheme&&(z.spatialReference=f.tilingScheme.spatialReference,
z.extent=na,f._emitElevationChange(z))}},f=this,l=0;l<c.LAYER_CLASS_COUNT;l++)b(l);this.tilingScheme.levels.length-1<g&&(this.tilingScheme.ensureMaxLod(g),this._viewChangeUpdate())}};c.prototype._emitElevationChange=function(a){this.emit("elevation-change",a)};c.prototype._hasFixedExtent=function(){return!!this._clippingExtent};c.prototype.layerViewByIndex=function(a,b){return this._layerViews[b][a]};c.prototype.numLayers=function(a){return this._layerViews[a].length};c.prototype.numTotalLayers=function(){return this._layerViews.reduce(function(a,
b){return b.length+a},0)};c.prototype._updateTileTextures=function(){var a=this._iteratorPool.acquire();for(a.reset(this.rootTiles);!a.done;)a.next().updateTexture();this._iteratorPool.release(a)};c.prototype._invalidateLayerData=function(a,b){var c=this._iteratorPool.acquire();for(c.reset(this.rootTiles);!c.done;)c.next().removeLayerAgent(a,b);for(c.reset(this.rootTiles);!c.done;)c.next().invalidateLayerData(a,b);this._iteratorPool.release(c)};c.prototype.requestTileData=function(a,b,c){var d=this;
this.tilemapStats.tilesRequested++;var g=this.layerViewByIndex(b,c),e=g.layer;if(e.tilemapCache){var f=this.getTilemapTile(a),l=f.layerInfo[c][b];if(l.tilemap){if(!f.tileDataAvailable(a,b,c))return this.tilemapStats.tilesNotPresent++,this._dispatchDataEvent(a,"dataMissing",c,g,{notInTilemap:!0}),b=new L.Promise,b.reject(),b}else{l.tilemapRequest||(l.tilemapRequest=this.requestTilemap(f,b,c,g,e));var k,m=new L.Promise(function(){k&&k.cancel()});l.tilemapRequest.always(function(){l.tilemapRequest=null;
if(!m.isCancelled()){var b=d._layerIndexByLayerViewId[c][g.uid];null!=b&&(f.tileDataAvailable(a,b,c)?(k=d._requestTileData(a,b,c,g),k.then(function(){return m.resolve()})):(d.tilemapStats.tilesNotPresent++,d._dispatchDataEvent(a,"dataMissing",c,g,{notInTilemap:!0}),m.reject()))}});return m}}return this._requestTileData(a,b,c,g)};c.prototype._requestTileData=function(a,b,c,h){this.tilemapStats.tileRequestsSent++;return c===k.LayerClass.ELEVATION?this._requestElevationTileData(a,b,c,h):this._requestMapTileData(a,
b,c,h)};c.prototype._requestElevationTileData=function(a,b,c,h){function d(b){var d=f._layerIndexByLayerViewId[c][h.uid];null!=d?(d=a.layerInfo[c][d],d.rawData=b,a.pendingUpdates|=m.DECODE_ELEVATION,d.pendingUpdates|=m.DECODE_ELEVATION,f._pendingUpdates=!0):t.warn("TerrainSurface: received data from unknown layer %d %s",c,a.lij.toString())}function e(b){P(b)||(f.tilemapStats.tileRequestErrors++,f._dispatchDataEvent(a,"dataMissing",c,h,b))}var f=this,l;r.isElevationLayerView(h)?(b=h.layer,r.useFetchTileForLayer(b)?
(l=b.fetchTile(a.lij[0],a.lij[1],a.lij[2],k.ELEVATION_NODATA_VALUE),l.then(function(a){return d(a)},e)):(b=h.getTileUrl(a.lij[0],a.lij[1],a.lij[2]),l=this._streamDataSupplier.request(b,"binary"),l.then(function(a,b){b.url=a;d(b)},e))):B(!1,"_requestElevationTileData can only be called for elevation layer views");return l};c.prototype._requestMapTileData=function(a,b,c,h){function d(b){f._dispatchDataEvent(a,"dataArrived",c,h,b)}function e(b){P(b)||(f._dispatchDataEvent(a,"dataMissing",c,h,b),f.tilemapStats.tileRequestErrors++)}
var f=this;if(r.isVectorTileLayerView(h)){var l=h.tileHandler;b=h.schemeHelper.getCompatibleLevelRowCol(a.lij);b=l.getVectorTileWithLRC(b[0],b[1],b[2],0);b.then(d).otherwise(e).always(function(){f._vectorTileLayerRequests=l.ongoingRequestCount});this._vectorTileLayerRequests=l.ongoingRequestCount}else r.useFetchTileForLayer(h.layer)&&r.isTileLayerView(h)?(b=h.layer.fetchTile(a.lij[0],a.lij[1],a.lij[2]),b.then(d).otherwise(e)):(b=h.getTileUrl(a.lij[0],a.lij[1],a.lij[2]),b=this._streamDataSupplier.request(b,
"image"),b.then(function(a,b){return d(b)},e));return b};c.prototype.requestTilemap=function(a,b,c,h,g){var d=this,f=a.lij[0]+k.TILEMAP_SIZE_EXP,l=a.lij[1]<<k.TILEMAP_SIZE_EXP,m=a.lij[2]<<k.TILEMAP_SIZE_EXP;this.tilemapStats.tilemapRequestsSent++;this.tilemapStats.tilemapRequestsPending++;return g.tilemapCache.fetchTilemap(f,l,m,{timeout:6E3}).then(function(e){d.tilemapStats.tilemapRequestsPending--;b=d._layerIndexByLayerViewId[c][h.uid];null!=b&&(a.layerInfo[c][b].tilemap=e)}).otherwise(function(a){d.tilemapStats.tilemapRequestsPending--;
d.tilemapStats.tilemapRequestErrors++})};c.prototype.getTilemapTile=function(a){var b=a.lij[0];return b>k.TILEMAP_SIZE_EXP?A.getTileNLevelsUp(a,k.TILEMAP_SIZE_EXP):this._topLevelTilemapOnlyTiles[b]};c.prototype._dispatchDataEvent=function(a,b,c,h,g){h=this._layerIndexByLayerViewId[c][h.uid];if(null!=h)a[b](h,c,g);else t.warn("TerrainSurface: received data from unknown layer")};c.prototype._updateTileOverlayParams=function(){if(this.rootTiles){var a=this._iteratorPool.acquire();for(a.reset(this.rootTiles);!a.done;){var b=
a.next();b.renderData&&this.overlayManager&&this.overlayManager.setOverlayParamsOfTile(b,b.renderData,this._curOverlayOpacity)}this._iteratorPool.release(a);this._renderer.setNeedsRender()}};c.prototype._updateOverlayOpacity=function(a){if(this.overlayManager&&(a=this.overlayManager.updateOpacity(a),!isNaN(a))){if(a!==this._curOverlayOpacity&&this.rootTiles){var b=this._iteratorPool.acquire();for(b.reset(this.rootTiles);!b.done;){var c=b.next();c.renderData&&c.renderData.overlayTexId&&(c.renderData.overlayOpacity=
a)}this._iteratorPool.release(b)}this._curOverlayOpacity=a;this._renderer.setNeedsRender()}};c.prototype.getStats=function(){var a=0,b=0,c=0,h=[],g=this._iteratorPool.acquire();for(g.reset(this.rootTiles);!g.done;){var e=g.next();a++;e.renderData&&(b++,e.visible&&(c++,e=e.lij[0],h[e]=null!=h[e]?h[e]+1:1))}this._iteratorPool.release(g);return{numNodes:a,numLeaves:b,numVisible:c,numVisiblePerLevel:h}};c.prototype.getTile=function(a){var b=a.split("/").map(function(a){return+a});if(0===b[0])return this.rootTiles.forEach(function(a){if(a.lij[1]===
b[1]&&a.lij[2]===b[2])return a}),null;var c=Math.pow(2,b[0]),h=Math.floor(b[1]/c),g=Math.floor(b[2]/c),e;this.rootTiles.some(function(a){return a.lij[1]===h&&a.lij[2]===g?(e=a,!0):!1});if(e){for(c=1<<b[0]-1;e.lij[0]<b[0];){var f=b[1]&c?2:0;0<(b[2]&c)&&f++;if(!e.children[f])return console.log("Tile "+a+" doesn't exist, smallest ancestor is "+A.tile2str(e)),null;e=e.children[f];c>>=1}B(e.lij[0]===b[0]&&e.lij[1]===b[1]&&e.lij[2]===b[2],"not the right tile?");return e}return null};c.prototype.hasPendingUpdates=
function(){if(this._streamDataSupplier.hasPendingDownloads()||0!==this._vectorTileLayerRequests)return!0;var a=this._iteratorPool.acquire();for(a.reset(this.rootTiles);!a.done;)if(0<a.next().pendingUpdates)return this._iteratorPool.release(a),!0;this._iteratorPool.release(a);return!1};c.prototype.setBorders=function(a){this._renderer.setBorders(a)};c.prototype.setDisableRendering=function(a){this._renderer.setDisableRendering(a)};p([n.property({value:!1})],c.prototype,"cullBackFaces",null);p([n.property({readOnly:!0})],
c.prototype,"extent",null);p([n.property({value:!1})],c.prototype,"frontMostTransparent",null);p([n.property({readOnly:!0})],c.prototype,"loaded",void 0);p([n.property({value:1})],c.prototype,"opacity",null);p([n.property({readOnly:!0})],c.prototype,"overlayManager",void 0);p([n.property({readOnly:!0})],c.prototype,"manifold",void 0);p([n.property()],c.prototype,"maxTextureScale",void 0);p([n.property({readOnly:!0})],c.prototype,"ready",null);p([n.property({value:1})],c.prototype,"renderOrder",null);
p([n.property({readOnly:!0})],c.prototype,"rootTiles",void 0);p([n.property({value:!0})],c.prototype,"skirts",null);p([n.property({readOnly:!0,aliasOf:"tilingScheme.spatialReference"})],c.prototype,"spatialReference",void 0);p([n.property({value:k.DEFAULT_TILE_BACKGROUND})],c.prototype,"tileBackground",null);p([n.property({readOnly:!0})],c.prototype,"tilingScheme",void 0);p([n.property({readOnly:!0,aliasOf:"tilingSchemeLogic.tilingSchemeLocked"})],c.prototype,"tilingSchemeLocked",void 0);p([n.property({readOnly:!0})],
c.prototype,"tilingSchemeLogic",void 0);p([n.property({value:!0})],c.prototype,"velvetOverground",null);p([n.property({value:!1})],c.prototype,"wireframe",null);return c=p([n.subclass("esri.views.3d.terrain.TerrainSurface")],c)}(n.declared(T,Y.Evented));var ka=1.2,la=80/180*Math.PI,na=[-Infinity,-Infinity,Infinity,Infinity],I=k.MAX_ROOT_TILES,ma=12,m=k.TileUpdateTypes,v=G.create(),E=[0,0,0],H=Array(10),C=Array(10),y={spatialReference:null,tile:null},z={spatialReference:null,extent:null},u={spatialReference:null,
extent:null,scale:0};return J});