// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ./tsSupport/declareExtendsHelper ./tsSupport/decorateHelper dojo/aspect ./accessorSupport/decorators ./accessorSupport/ensureType ./Accessor ./ArrayPool ./Evented ./ObjectPool ./Scheduler ./lang".split(" "),function(E,R,I,A,J,u,F,K,v,L,M,N,O){function w(f){return f?f.isInstanceOf&&f.isInstanceOf(G)?!0:!1:!1}function B(f){return f?w(f)?f.toArray():f.length?Array.prototype.slice.apply(f):[]:[]}function C(f){if(f&&f.length)return f[0]}function H(f,b,h,a){b&&b.forEach(function(c,
b,e){f.push(c);H(f,h.call(a,c,b,e),h,a)})}(function(){return function(){}})();E=function(){function f(){this.target=null;this.defaultPrevented=this.cancellable=!1}f.prototype.preventDefault=function(){this.cancellable&&(this.defaultPrevented=!0)};f.prototype.reset=function(b){this.defaultPrevented=!1;this.item=b};return f}();var P=function(){},h=new M(E,!0,function(f){f.item=null;f.target=null}),p=new Set,q=new Set,r=new Set,D=new Map,Q=0,G=function(f){function b(a){a=f.call(this,a)||this;a._boundDispatch=
a._dispatchColChange.bind(a);a._chgListeners=[];a._notifications=null;a._timer=null;a.length=0;a._items=[];Object.defineProperty(a,"uid",{value:Q++});return a}I(b,f);l=b;b.ofType=function(a){if(!a)return l;if(D.has(a))return D.get(a);var c=l.createSubclass({declaredClass:"esri.core.Collection\x3c"+("function"===typeof a?a.prototype.declaredClass:a.base.prototype.declaredClass)+"\x3e"}),b={Type:a,ensureType:"function"===typeof a?F.ensureType(a):F.ensureOneOfType(a)};Object.defineProperty(c.prototype,
"itemType",{value:b});D.set(a,c);return c};b.prototype.normalizeCtorArgs=function(a){return a?Array.isArray(a)||w(a)?{items:a}:a:{}};Object.defineProperty(b.prototype,"items",{get:function(){return this._items},set:function(a){this._emitBeforeChanges()||(this._splice.apply(this,[0,this.length].concat(B(a))),this._emitAfterChanges())},enumerable:!0,configurable:!0});b.prototype.on=function(a,c){var b;Array.isArray(a)?b=a:-1<a.indexOf(",")&&(b=a.split(/\s*,\s*/));if(b){var e=[];for(a=0;a<b.length;a++)e.push(this.on(b[a],
c));e.remove=function(){for(var a=0;a<e.length;a++)e[a].remove()};return e}if("change"===a){var d=this._chgListeners,k={removed:!1,callback:c};d.push(k);this._notifications&&this._notifications.push({listeners:d.slice(),items:this._items.slice(),changes:[]});return{remove:function(){this.remove=P;k.removed=!0;d.splice(d.indexOf(k),1)}}}return J.after(this,"on"+a,c,!0)};b.prototype.hasEventListener=function(a){return"change"===a?0<this._chgListeners.length:this.inherited(arguments)};b.prototype.add=
function(a,c){if(this._emitBeforeChanges())return this;c=this.getNextIndex(c);this._splice(c,0,a);this._emitAfterChanges();return this};b.prototype.addMany=function(a,c){void 0===c&&(c=this._items.length);if(this._emitBeforeChanges())return this;c=this.getNextIndex(c);this._splice.apply(this,[c,0].concat(B(a)));this._emitAfterChanges();return this};b.prototype.removeAll=function(){if(!this.length||this._emitBeforeChanges())return[];var a=this._splice(0,this.length)||[];this._emitAfterChanges();return a};
b.prototype.clone=function(){return this._createNewInstance({items:this._items.map(O.clone)})};b.prototype.concat=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];a=a.map(B);return this._createNewInstance({items:(b=this._items).concat.apply(b,a)});var b};b.prototype.drain=function(a,c){if(this.length&&!this._emitBeforeChanges()){for(var b=this._splice(0,this.length),e=b.length,d=0;d<e;d++)a.call(c,b[d],d,b);this._emitAfterChanges()}};b.prototype.every=function(a,c){return this._items.every(a,
c)};b.prototype.filter=function(a,c){var b;b=2===arguments.length?this._items.filter(a,c):this._items.filter(a);return this._createNewInstance({items:b})};b.prototype.find=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,e=b.length,d=0;d<e;d++){var k=b[d];if(a.call(c,k,d,b))return k}};b.prototype.findIndex=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,e=b.length,d=0;d<e;d++)if(a.call(c,
b[d],d,b))return d;return-1};b.prototype.flatten=function(a,c){var b=[];H(b,this,a,c);return new l(b)};b.prototype.forEach=function(a,c){for(var b=this._items,e=b.length,d=0;d<e;d++)a.call(c,b[d],d,b)};b.prototype.getItemAt=function(a){return this._items[a]};b.prototype.getNextIndex=function(a){var c=this.length;a=null==a?c:a;0>a?a=0:a>c&&(a=c);return a};b.prototype.includes=function(a,c){void 0===c&&(c=0);return arguments.length?-1!==this._items.indexOf(a,c):!1};b.prototype.indexOf=function(a,c){void 0===
c&&(c=0);return this._items.indexOf(a,c)};b.prototype.join=function(a){void 0===a&&(a=",");return this._items.join(a)};b.prototype.lastIndexOf=function(a,c){void 0===c&&(c=this.length-1);return this._items.lastIndexOf(a,c)};b.prototype.map=function(a,c){a=this._items.map(a,c);return new l({items:a})};b.prototype.reorder=function(a,c){void 0===c&&(c=this.length-1);var b=this.indexOf(a);if(-1!==b){0>c?c=0:c>=this.length&&(c=this.length-1);if(b!==c){if(this._emitBeforeChanges())return a;this._splice(b,
1);this._splice(c,0,a);this._emitAfterChanges()}return a}};b.prototype.pop=function(){if(this.length&&!this._emitBeforeChanges()){var a=C(this._splice(this.length-1,1));this._emitAfterChanges();return a}};b.prototype.push=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[this.length,0].concat(a));this._emitAfterChanges();return this.length};b.prototype.reduce=function(a,c){var b=this._items;return 2===arguments.length?
b.reduce(a,c):b.reduce(a)};b.prototype.reduceRight=function(a,c){var b=this._items;return 2===arguments.length?b.reduceRight(a,c):b.reduceRight(a)};b.prototype.remove=function(a){return this.removeAt(this.indexOf(a))};b.prototype.removeAt=function(a){if(!(0>a||a>=this.length||this._emitBeforeChanges()))return a=C(this._splice(a,1)),this._emitAfterChanges(),a};b.prototype.removeMany=function(a){if(!a||!a.length||this._emitBeforeChanges())return[];a=w(a)?a.toArray():a;for(var c=this._items,b=[],e=a.length,
d=0;d<e;d++){var k=c.indexOf(a[d]);if(-1<k){for(var f=d+1,t=k+1,n=Math.min(a.length-f,c.length-t),g=0;g<n&&a[f+g]===c[t+g];)g++;f=1+g;(k=this._splice(k,f))&&0<k.length&&b.push.apply(b,k);d+=f-1}}this._emitAfterChanges();return b};b.prototype.reverse=function(){if(this._emitBeforeChanges())return this;var a=this._splice(0,this.length);a&&(a.reverse(),this._splice.apply(this,[0,0].concat(a)));this._emitAfterChanges();return this};b.prototype.shift=function(){if(this.length&&!this._emitBeforeChanges()){var a=
C(this._splice(0,1));this._emitAfterChanges();return a}};b.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.length);return this._createNewInstance({items:this._items.slice(a,b)})};b.prototype.some=function(a,b){return this._items.some(a,b)};b.prototype.sort=function(a){if(!this.length||this._emitBeforeChanges())return this;var b=this._splice(0,this.length);arguments.length?b.sort(a):b.sort();this._splice.apply(this,[0,0].concat(b));return this};b.prototype.splice=function(a,b){for(var c=
[],e=2;e<arguments.length;e++)c[e-2]=arguments[e];if(this._emitBeforeChanges())return[];c=this._splice.apply(this,[a,b].concat(c))||[];this._emitAfterChanges();return c};b.prototype.toArray=function(){return this._items.slice()};b.prototype.toJSON=function(){return this.toArray()};b.prototype.toLocaleString=function(){return this._items.toLocaleString()};b.prototype.toString=function(){return this._items.toString()};b.prototype.unshift=function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];
if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[0,0].concat(a));this._emitAfterChanges();return this.length};b.prototype._createNewInstance=function(a){return new this.constructor(a)};b.prototype._splice=function(a,b){for(var c=this,e=[],d=2;d<arguments.length;d++)e[d-2]=arguments[d];var f=this._items,x=this.constructor.prototype.itemType,t,n;!this._notifications&&this.hasEventListener("change")&&(this._notifications=[{listeners:this._chgListeners.slice(),items:this._items.slice(),
changes:[]}],this._timer&&this._timer.remove(),this._timer=N.schedule(this._boundDispatch));if(b){n=f.splice(a,b);if(this.hasEventListener("before-remove")){d=h.acquire();d.target=this;d.cancellable=!0;for(var g=0,y=n.length;g<y;g++)t=n[g],d.reset(t),this.emit("before-remove",d),d.defaultPrevented&&(n.splice(g,1),f.splice(a,0,t),a+=1,--g,--y);h.release(d)}this.length=this._items.length;if(this.hasEventListener("after-remove")){d=h.acquire();d.target=this;d.cancellable=!1;y=n.length;for(g=0;g<y;g++)d.reset(n[g]),
this.emit("after-remove",d);h.release(d)}this._notifyChangeEvent(null,n)}if(e&&e.length){x&&(e=e.map(x.ensureType));if(this.hasEventListener("before-add")){var m=h.acquire();m.target=this;m.cancellable=!0;e=e.filter(function(a){m.reset(a);c.emit("before-add",m);return!m.defaultPrevented});h.release(m)}f.splice.apply(f,[a,0].concat(e));this.length=this._items.length;if(this.hasEventListener("after-add")){d=h.acquire();d.target=this;d.cancellable=!1;f=0;for(x=e;f<x.length;f++)t=x[f],d.reset(t),this.emit("after-add",
d);h.release(d)}this._notifyChangeEvent(e,null)}return n};b.prototype._emitBeforeChanges=function(){var a=!1;if(this.hasEventListener("before-changes")){var b=h.acquire();b.target=this;b.cancellable=!0;this.emit("before-changes",b);a=b.defaultPrevented;h.release(b)}return a};b.prototype._emitAfterChanges=function(){if(this.hasEventListener("after-changes")){var a=h.acquire();a.target=this;a.cancellable=!1;this.emit("after-changes",a);h.release(a)}};b.prototype._notifyChangeEvent=function(a,b){this.hasEventListener("change")&&
this._notifications[this._notifications.length-1].changes.push({added:a,removed:b})};b.prototype._dispatchColChange=function(){this._timer&&(this._timer.remove(),this._timer=null);if(this._notifications){var a=this._notifications;this._notifications=null;for(var b=function(a){var b=a.changes;p.clear();q.clear();r.clear();for(var c=0;c<b.length;c++){var d=b[c],e=d.added,d=d.removed;if(e)if(0===r.size&&0===q.size)for(var g=0,h=e;g<h.length;g++)e=h[g],p.add(e);else for(g=0,h=e;g<h.length;g++)e=h[g],
q.has(e)?(r.add(e),q.delete(e)):r.has(e)||p.add(e);if(d)if(0===r.size&&0===p.size)for(g=0;g<d.length;g++)e=d[g],q.add(e);else for(g=0;g<d.length;g++)e=d[g],p.has(e)?p.delete(e):(r.delete(e),q.add(e))}var m=v.acquire();p.forEach(function(a){m.push(a)});var l=v.acquire();q.forEach(function(a){l.push(a)});var u=f._items,w=a.items,z=v.acquire();r.forEach(function(a){w.indexOf(a)!==u.indexOf(a)&&z.push(a)});if(a.listeners&&(m.length||l.length||z.length))for(b={target:f,added:m,removed:l,moved:z},c=a.listeners.length,
e=0;e<c;e++)d=a.listeners[e],d.removed||d.callback.call(f,b);v.release(m);v.release(l);v.release(z)},f=this,e=0;e<a.length;e++)b(a[e]);p.clear();q.clear();r.clear()}};b.isCollection=w;A([u.property()],b.prototype,"length",void 0);A([u.property()],b.prototype,"items",null);return b=l=A([u.subclass("esri.core.Collection")],b);var l}(u.declared(K,L));return G});