// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define(["dojo/_base/window","dojo/sniff","../kernel"],function(e,a,p){function l(){if(d)return d;d={available:!1,version:0,supportsHighPrecisionFragment:!1};var a=function(a,b){for(var c=["webgl","experimental-webgl","webkit-3d","moz-webgl"],d=null,q=0;q<c.length;++q){try{d=a.getContext(c[q],b)}catch(u){}if(d)break}return d},c;try{if(!g.WebGLRenderingContext)throw 0;c=document.createElement("canvas")}catch(w){return d}var b=a(c,{failIfMajorPerformanceCaveat:!0});!b&&(b=a(c))&&(d.majorPerformanceCaveat=
!0);if(!b)return d;a=b.getParameter(b.VERSION);if(!a)return d;if(a=a.match(/^WebGL\s+([\d.]*)/))d.version=parseFloat(a[1]),d.available=.94<=d.version,a=b.getShaderPrecisionFormat(b.FRAGMENT_SHADER,b.HIGH_FLOAT),d.supportsHighPrecisionFragment=a&&0<a.precision,d.supportsVertexShaderSamplers=0<b.getParameter(b.MAX_VERTEX_TEXTURE_IMAGE_UNITS),d.supportsElementIndexUint=null!=b.getExtension("OES_element_index_uint");return d}var b=a("ff"),h=a("ie"),n=void 0===h&&7<=a("trident"),m=a("webkit"),k=a("opera"),
r=a("chrome"),t=a("safari"),g=e.global;e=navigator.userAgent;var f;(f=e.match(/(iPhone|iPad|CPU)\s+OS\s+(\d+\_\d+)/i))&&a.add("esri-iphone",parseFloat(f[2].replace("_",".")));(f=e.match(/Android\s+(\d+\.\d+)/i))&&a.add("esri-android",parseFloat(f[1]));(f=e.match(/Fennec\/(\d+\.\d+)/i))&&a.add("esri-fennec",parseFloat(f[1]));0<=e.indexOf("BlackBerry")&&0<=e.indexOf("WebKit")&&a.add("esri-blackberry",1);a.add("esri-touch",a("esri-iphone")||a("esri-android")||a("esri-blackberry")||6<=a("esri-fennec")||
(b||m)&&document.createTouch?!0:!1);(f=e.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry|Opera Mini|IEMobile/i))&&a.add("esri-mobile",f);a.add("esri-pointer",navigator.pointerEnabled||navigator.msPointerEnabled);p._getDOMAccessor=function(a){var c="";b?c="Moz":m?c="Webkit":h?c="ms":k&&(c="O");return c+a.charAt(0).toUpperCase()+a.substr(1)};a.add("esri-phonegap",!!g.cordova);a.add("esri-cors",a("esri-phonegap")||"XMLHttpRequest"in g&&"withCredentials"in new XMLHttpRequest);a.add("esri-canvas-svg-support",
function(){return!(a("trident")||a("ie"))});if(a("host-webworker"))return a;a.add("esri-workers","Worker"in g);a.add("esri-script-sandbox",function(){return"MessageChannel"in g&&"HTMLIFrameElement"in g&&"sandbox"in HTMLIFrameElement.prototype});a.add("esri-transforms",n||9<=h||3.5<=b||4<=r||3.1<=t||10.5<=k||3.2<=a("esri-iphone")||2.1<=a("esri-android"));a.add("esri-transitions",n||10<=h||4<=b||4<=r||3.1<=t||10.5<=k||3.2<=a("esri-iphone")||2.1<=a("esri-android"));a.add("esri-transforms3d",n||10<=b||
12<=r||4<=t||3.2<=a("esri-iphone")||3<=a("esri-android"));a.add("esri-url-encodes-apostrophe",function(){var a=g.document.createElement("a");a.href="?'";return-1<a.href.indexOf("?%27")});3>a("esri-android")&&(a.add("esri-transforms",!1,!1,!0),a.add("esri-transitions",!1,!1,!0),a.add("esri-transforms3d",!1,!1,!0));p._css=function(d){var c=a("esri-transforms3d");void 0!==d&&null!==d?c=d:c&&(r||t&&!a("esri-iphone"))&&(c=!1);var e=c?"translate3d(":"translate(",f=c?r?",-1px)":",0px)":")",g=c?"scale3d(":
"scale(",l=c?",1)":")",q=c?"rotate3d(0,0,1,":"rotate(",n=c?"matrix3d(":"matrix(",u=c?",0,0,":",",p=c?",0,0,0,0,1,0,":",",v=c?",0,1)":")";return{names:{transition:m&&"-webkit-transition"||b&&"MozTransition"||k&&"OTransition"||h&&"msTransition"||"transition",transform:m&&"-webkit-transform"||b&&"MozTransform"||k&&"OTransform"||h&&"msTransform"||"transform",transformName:m&&"-webkit-transform"||b&&"-moz-transform"||k&&"-o-transform"||h&&"-ms-transform"||"transform",origin:m&&"-webkit-transform-origin"||
b&&"MozTransformOrigin"||k&&"OTransformOrigin"||h&&"msTransformOrigin"||"transformOrigin",endEvent:m&&"webkitTransitionEnd"||b&&"transitionend"||k&&"oTransitionEnd"||h&&"MSTransitionEnd"||"transitionend"},translate:function(a,b){return e+a+"px,"+b+"px"+f},scale:function(a){return g+a+","+a+l},rotate:function(a){return q+a+"deg)"},matrix:function(a){return a.m?(a=a.m,n+a[0].toFixed(10)+","+a[1].toFixed(10)+u+a[2].toFixed(10)+","+a[3].toFixed(10)+p+a[4].toFixed(10)+(b?"px,":",")+a[5].toFixed(10)+(b?
"px":"")+v):n+a.xx.toFixed(10)+","+a.yx.toFixed(10)+u+a.xy.toFixed(10)+","+a.yy.toFixed(10)+p+a.dx.toFixed(10)+(b?"px,":",")+a.dy.toFixed(10)+(b?"px":"")+v},matrix3d:function(a){a=a.m;return"matrix3d("+a[0].toFixed(10)+","+a[1].toFixed(10)+",0,0,"+a[2].toFixed(10)+","+a[3].toFixed(10)+",0,0,0,0,1,0,"+a[4].toFixed(10)+","+a[5].toFixed(10)+",0,1)"},getScaleFromMatrix:function(a){if(!a)return 1;a=a.toLowerCase();var b=-1<a.indexOf("matrix3d")?"matrix3d(":"matrix(";return Number(a.substring(b.length,
a.indexOf(",")))}}};var d;a.add("esri-webgl",function(){return!!l().available});a.add("esri-webgl-high-precision-fragment",function(){return!!l().supportsHighPrecisionFragment});a.add("esri-webgl-vertex-shader-samplers",function(){return!!l().supportsVertexShaderSamplers});a.add("esri-webgl-element-index-uint",function(){return!!l().supportsElementIndexUint});a.add("esri-webgl-major-performance-caveat",function(){return!!l().majorPerformanceCaveat});return a});