// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../support/widget ../../../core/accessorSupport/decorators ../../Widget ../../../../moment/moment ./DatePickerViewModel dojo/keys dojo/i18n!../nls/DatePicker".split(" "),function(y,z,r,g,c,k,w,n,p,d,h){var x=[d.DOWN_ARROW,d.END,d.ENTER,d.HOME,d.LEFT_ARROW,d.PAGE_DOWN,d.PAGE_UP,d.RIGHT_ARROW,d.SPACE,d.UP_ARROW];return function(q){function a(b){b=q.call(this)||this;b._activeDate=null;b._isOpen=
!1;b._closedByUserAction=!1;b.value=null;b.viewModel=new p;return b}r(a,q);a.prototype.render=function(){var b=this.viewModel.value.format("L"),e=this._isOpen,a=(l={},l["esri-icon-down-arrow"]=!e,l["esri-icon-up-arrow"]=e,l);return c.tsx("div",{class:"esri-date-picker esri-widget"},c.tsx("div",{afterUpdate:this._focusSelectedOrClosed,"aria-pressed":e.toString(),bind:this,class:c.join("esri-widget-button","esri-date-picker__calendar-toggle"),onclick:this._toggle,onkeydown:this._toggle,role:"button",
tabIndex:0},c.tsx("span",{class:"esri-date-picker__date"},b),c.tsx("span",{"aria-hidden":"true",classes:a})),e?this._renderCalendar():null);var l};a.prototype._focusSelectedOrClosed=function(b){this._closedByUserAction&&(this._closedByUserAction=!1,b.focus())};a.prototype._handleDatePickerKeydown=function(b){b.keyCode===d.ESCAPE&&(this._closedByUserAction=!0,this._close(),b.preventDefault(),b.stopPropagation())};a.prototype._renderCalendar=function(){var b=this._activeDate,a=this.get("viewModel.value");
return c.tsx("div",{bind:this,class:"esri-date-picker__calendar",key:"esri-date-picker__calendar",onkeydown:this._handleDatePickerKeydown},this._renderMonthPicker(b),this._renderDayPicker(b,a),this._renderYearPicker(b))};a.prototype._renderMonthPicker=function(b){var a=n.months().map(function(a,e){e=b.month()===e;return c.tsx("option",{selected:e},a)});return c.tsx("div",{class:"esri-date-picker__month-picker"},c.tsx("div",{"aria-label":h.goToPreviousMonth,bind:this,class:"esri-widget-button",onclick:this._setPreviousMonth,
onkeydown:this._setPreviousMonth,role:"button",tabIndex:0,title:h.goToPreviousMonth},c.tsx("span",{"aria-hidden":"true",class:"esri-icon-left"})),c.tsx("select",{"aria-live":"assertive",bind:this,class:"esri-date-picker__month-dropdown",id:this.id+"__month-picker",onchange:this._setMonth,onkeydown:this._setMonth},a),c.tsx("div",{"aria-label":h.goToNextMonth,bind:this,class:"esri-widget-button",onclick:this._setNextMonth,onkeydown:this._setNextMonth,role:"button",tabIndex:0,title:h.goToNextMonth},
c.tsx("span",{"aria-hidden":"true",class:"esri-icon-right"})))};a.prototype._renderDayPicker=function(b,a){var e=b.clone().day(n.localeData().firstDayOfWeek()),e=this._getWeekLabels(e),d=this._getDayId(b);b=this._renderMonth(b,a);return c.tsx("div",{afterCreate:this._handleDayPickerCreate,"aria-activedescendant":d,"aria-labelledby":this.id+"__month-picker "+this.id+"__selected-year",bind:this,class:"esri-date-picker__day-picker",id:this.id+"__day-picker",onkeydown:this._handleDayPickerKeydown,role:"grid",
tabIndex:0},c.tsx("div",{class:"esri-date-picker__week-item",role:"row"},e.map(function(b){return c.tsx("div",{"aria-label":b.name,class:c.join("esri-date-picker__day-item","esri-date-picker__day-item--header"),role:"columnheader",title:b.name},b.abbr)})),b)};a.prototype._getDayId=function(b){return this.id+"__"+b.format("YYYY-MM-DD")};a.prototype._handleDayPickerCreate=function(b){b.focus()};a.prototype._getWeekLabels=function(b){for(var a=[],c=0;7>c;c++)a.push({name:b.format("dddd"),abbr:b.format("dd")}),
b.add(1,"day");return a};a.prototype._handleDayPickerKeydown=function(b){var a=b.keyCode,c=b.ctrlKey,l=b.shiftKey,f=this._activeDate;if(-1!==x.indexOf(a)){if(a===d.LEFT_ARROW)f.subtract(1,"day");else if(a===d.RIGHT_ARROW)f.add(1,"day");else if(a===d.UP_ARROW)f.subtract(1,"week");else if(a===d.DOWN_ARROW)f.add(1,"week");else if(a===d.PAGE_UP)f.subtract(1,l?"year":"month");else if(a===d.PAGE_DOWN)f.add(1,l?"year":"month");else if(a===d.HOME)f.startOf(c?"year":"month");else if(a===d.END)f.endOf(c?"year":
"month");else if(a===d.ENTER||a===d.SPACE)this.viewModel.value=f.clone(),this._closedByUserAction=!0,this._close();b.preventDefault();b.stopPropagation()}};a.prototype._renderMonth=function(b,a){for(var d=n(),e=n.localeData(),f=b.clone().startOf("month"),g=b.clone().endOf("month"),e=f.clone().subtract(f.weekday()-e.firstDayOfWeek(),"day"),h=[],k=0;6>k;k++){for(var p=[],q=0;7>q;q++){var u=e.date(),v=e.isSame(b,"day"),t=e.isSame(a,"day"),r=this._getDayId(e),t=(m={},m["esri-date-picker__day-item--nearby-month"]=
!e.isBetween(f,g,null,"[]"),m["esri-date-picker__day-item--today"]=e.isSame(d,"day"),m["esri-date-picker__day-item--active"]=v,m["esri-date-picker__day-item--selected"]=t,m);p.push(c.tsx("div",{"aria-label":u.toString(),"aria-selected":v.toString(),bind:this,class:"esri-date-picker__day-item","data-iso-date":e.toISOString(),classes:t,id:r,onclick:this._handleSelectedDate,onkeydown:this._handleSelectedDate,role:"gridcell"},u));e.add(1,"day")}h.push(c.tsx("div",{class:"esri-date-picker__week-item",
role:"row"},p))}return h;var m};a.prototype._renderYearPicker=function(b){var a=b.clone();b=a.format("YYYY");var d=a.add(1,"year").format("YYYY"),a=a.subtract(2,"year").format("YYYY");return c.tsx("div",{class:"esri-date-picker__year-picker"},c.tsx("div",{"aria-label":h.goToPreviousYear,bind:this,class:"esri-date-picker__year-picker-item",onclick:this._setPreviousYear,onkeydown:this._setPreviousYear,tabIndex:0,title:h.goToPreviousYear},a),c.tsx("div",{class:c.join("esri-date-picker__year-picker-item",
"esri-date-picker__year-picker-item--selected"),id:this.id+"__selected-year"},b),c.tsx("div",{"aria-label":h.goToNextYear,bind:this,class:"esri-date-picker__year-picker-item",onclick:this._setNextYear,onkeydown:this._setNextYear,tabIndex:0,title:h.goToNextYear},d))};a.prototype._toggle=function(){this._isOpen?this._close():this._open(this.viewModel.value.clone())};a.prototype._setMonth=function(a){a=a.target;a=a.item(a.selectedIndex).value;this._activeDate.month(a)};a.prototype._close=function(){this._activeDate=
null;this._isOpen=!1};a.prototype._open=function(a){this._activeDate=a;this._isOpen=!0};a.prototype._setPreviousMonth=function(){this._activeDate.subtract(1,"month")};a.prototype._setNextMonth=function(){this._activeDate.add(1,"month")};a.prototype._setPreviousYear=function(){this._activeDate.subtract(1,"year")};a.prototype._setNextYear=function(){this._activeDate.add(1,"year")};a.prototype._handleSelectedDate=function(a){this.viewModel.value=n(a.target.getAttribute("data-iso-date"));this._closedByUserAction=
!0;this._close()};g([k.aliasOf("viewModel.value")],a.prototype,"value",void 0);g([k.property({type:p}),c.renderable("viewModel.value")],a.prototype,"viewModel",void 0);g([c.accessibleHandler()],a.prototype,"_toggle",null);g([c.accessibleHandler()],a.prototype,"_setPreviousMonth",null);g([c.accessibleHandler()],a.prototype,"_setNextMonth",null);g([c.accessibleHandler()],a.prototype,"_setPreviousYear",null);g([c.accessibleHandler()],a.prototype,"_setNextYear",null);g([c.accessibleHandler()],a.prototype,
"_handleSelectedDate",null);return a=g([k.subclass("esri.widgets.Directions.support.DatePicker")],a)}(k.declared(w))});