// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports dojo/has ../../../../../core/libs/gl-matrix/mat4 ../../../../webgl/FramebufferObject ../Dispatcher ../TextureManager ../GeometryUtils ../MaterialManager ../enums ./WGLTextPainter ./WGLIconPainter ./WGLFillPainter ./WGLLinePainter ./WGLBackgroundPainter ./TileInfoRenderer ./WGLHighlightPainter ./WGLHeatmapPainter ../Utils".split(" "),function(L,M,l,k,y,z,A,B,C,r,D,E,F,G,H,q,I,J,v){var x=new Uint8Array(4*v.C_HITTEST_SEARCH_SIZE*v.C_HITTEST_SEARCH_SIZE),K=new Uint32Array(x.buffer),
t=new z;return function(){function c(){this._textPainter=new D;this._iconPainter=new E;this._fillPainter=new F;this._linePainter=new G;this._backgroundPainter=new H;this._hlPainter=new I;this._heatmapPainter=new J;this._extrudeMatrix=new Float32Array(16);this._extrudeNoRotationMatrix=new Float32Array(16);this._extrudeRotateVector=new Float32Array([0,0,1]);this._extrudeScaleVector=new Float32Array([1,1,1]);this._state={rotation:0,width:0,height:0};this._cachedRotation=this._cachedHeight=this._cachedWidth=
0;this._textureManager=new A;this._materialManager=new C}c.prototype.initialize=function(a){this._materialManager.initialize(a)};c.prototype.update=function(a,b){this._state=a;if(this._state.width!==this._cachedWidth||this._state.height!==this._cachedHeight||this._state.rotation!==this._cachedRotation)this._extrudeScaleVector[0]=2/a.width,this._extrudeScaleVector[1]=-2/a.height,k.identity(this._extrudeMatrix),k.rotate(this._extrudeMatrix,this._extrudeMatrix,-a.rotation*B.C_DEG_TO_RAD,this._extrudeRotateVector),
k.scale(this._extrudeMatrix,this._extrudeMatrix,this._extrudeScaleVector),k.transpose(this._extrudeMatrix,this._extrudeMatrix),k.identity(this._extrudeNoRotationMatrix),k.scale(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix,this._extrudeScaleVector),k.transpose(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix),this._cachedWidth=this._state.width,this._cachedHeight=this._state.height,this._cachedRotation=this._state.rotation};Object.defineProperty(c.prototype,"textureManager",
{get:function(){return this._textureManager},enumerable:!0,configurable:!0});c.prototype.setHighlightOptions=function(a){this._hlPainter.setHighlightOptions(a)};c.prototype.drawHeatmap=function(a,b,n,f){var h=this;this._heatmapPainter.bindHeatmapSurface(a,b.displayWidth*f,b.displayHeight*f);this._drawClippingRects(a,b.children);a.setBlendingEnabled(!0);a.setStencilWriteMask(0);a.setBlendFunctionSeparate(1,1,1,0);a.setStencilTestEnabled(!0);b.wglRendererInfo.symbolLevels.forEach(function(d){b.children.forEach(function(g){t.replayList(a,
g.displayList,d,h,g,b.wglRendererInfo,r.WGLDrawPhase.GEOMETRY,n,f,!1)})});a.setStencilTestEnabled(!1);this._heatmapPainter.drawHeatmap(a,b.wglRendererInfo,.75);if(l("esri-feature-tiles-debug")){this._tileInforenderer||(this._tileInforenderer=new q);for(var e=this._tileInforenderer,d=0,p=b.children;d<p.length;d++){var c=p[d];c.attached&&c.visible&&e.render(a,c)}}};c.prototype.draw=function(a,b,n,f,h){var e=this;this._drawClippingRects(a,b.children);a.setBlendingEnabled(!0);a.setStencilWriteMask(0);
a.setBlendFunctionSeparate(1,771,1,771);a.setStencilTestEnabled(!0);b.wglRendererInfo.symbolLevels.forEach(function(d){b.children.forEach(function(c){c.displayList&&!c.displayList.empty&&t.replayList(a,c.displayList,d,e,c,b.wglRendererInfo,r.WGLDrawPhase.GEOMETRY,n,f,h)})});a.setStencilTestEnabled(!1);if(l("esri-feature-tiles-debug")){this._tileInforenderer||(this._tileInforenderer=new q);for(var d=this._tileInforenderer,p=0,c=b.children;p<c.length;p++){var m=c[p];m.attached&&m.visible&&d.render(a,
m)}}};c.prototype.highlight=function(a,b,c,f){var h=this,e=a.getViewport();this._hlPainter.setup(a,e.width,e.height);this._hlPainter.startMaskDraw(a);this._drawClippingRects(a,b.children);a.setBlendingEnabled(!0);a.setStencilWriteMask(0);a.setBlendFunctionSeparate(1,771,1,771);a.setStencilTestEnabled(!0);b.wglRendererInfo.symbolLevels.forEach(function(d){b.children.forEach(function(e){e.hlDisplayList&&!e.hlDisplayList.empty&&t.replayList(a,e.hlDisplayList,d,h,e,b.wglRendererInfo,r.WGLDrawPhase.HIGHLIGHT,
c,f,!1)})});this._hlPainter.draw(a)};c.prototype.hitTest=function(a,b,c,f,h){var e=this,d=v.C_HITTEST_SEARCH_SIZE,n=[0,0],k=[0,0];b=a.state;b.toMap(n,[0,0]);b.toMap(k,[d,d]);var m=f.children.filter(function(a){return!(n[0]>a.bounds[2]||k[0]<a.bounds[0]||n[1]<a.bounds[1]||k[1]>a.bounds[3])});if(0===m.length)return[];var g=a.context;this._hittestFBO||(this._hittestFBO=y.create(g,{colorTarget:0,depthStencilTarget:3,width:d,height:d}));b=g.getViewport();c=g.getBoundFramebufferObject();g.bindFramebuffer(this._hittestFBO);
g.setViewport(0,0,d,d);var u=g.gl;g.setClearColor(1,1,1,1);g.clear(u.COLOR_BUFFER_BIT);this._drawClippingRects(g,m);g.setBlendingEnabled(!1);g.setStencilWriteMask(0);g.setStencilTestEnabled(!0);f.wglRendererInfo.symbolLevels.forEach(function(b){m.forEach(function(d){d.displayList&&!d.displayList.empty&&t.replayList(g,d.displayList,b,e,d,f.wglRendererInfo,r.WGLDrawPhase.HITTEST,h,a.devicePixelRatio,!1)})});g.setStencilTestEnabled(!1);g.setBlendingEnabled(!0);this._hittestFBO.readPixels(0,0,d,d,6408,
5121,x);for(var d=d*d,u=new Set,w=0;w<d;w++){var l=K[w];4294967295!==l&&u.add(l)}g.bindFramebuffer(c);g.setViewport(b.x,b.y,b.width,b.height);var q=[];u.forEach(function(a){q.push(a)});return q};c.prototype.drawFill=function(a,b,c,f,h,e,d,k,l,m){this._fillPainter.draw(a,b,c,f,h,e,d,k,l,m,this._materialManager,this._textureManager)};c.prototype.drawLine=function(a,b,c,f,h,e,d,k,l){this._linePainter.draw(a,b,c,f,h,e,d,k,l,this._materialManager,this._textureManager,this._extrudeMatrix)};c.prototype.drawIcon=
function(a,b,c,f,h,e,d){this._iconPainter.draw(a,b,c,f,h,e,d,this._materialManager,this._textureManager,this._extrudeMatrix,this._extrudeNoRotationMatrix)};c.prototype.drawText=function(a,b,c,f,h,e,d){this._textPainter.draw(a,b,c,f,h,e,d,this._materialManager,this._textureManager,this._extrudeMatrix,this._extrudeNoRotationMatrix)};c.prototype._drawClippingRects=function(a,b){if(0!==b.length){a.setDepthWriteEnabled(!1);a.setDepthTestEnabled(!1);a.setStencilTestEnabled(!0);a.setBlendingEnabled(!1);
a.setColorMask(!1,!1,!1,!1);a.setStencilOp(7680,7680,7681);a.setClearStencil(0);a.clear(a.gl.STENCIL_BUFFER_BIT);a.setStencilWriteMask(255);for(var c=b.length,f,h=c,e=0;e<c;e++)f=b[e],f.stencilRef=h,a.setStencilFunctionSeparate(1032,519,h,255),h--,this._backgroundPainter.draw(a,f);a.setColorMask(!0,!0,!0,!0)}};return c}()});