// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ./GoogPriorityQueue ../../support/PromiseLightweight ../../lib/glMatrix ../../../../core/urlUtils".split(" "),function(t,u,l,q,p,m){var h=l.goog.structs.PriorityQueue;return function(){function c(a,b,k,c,e,f,g,r,h,l,n){void 0===n&&(n={initDepthFirst:!0,neighborhood:!0,perLevelTraversal:!1});var d=this;this.baseURL=a;this.startNodeUrl=b;this.rootId=k;this.poi=c;this.nodeIndex=e;this.streamDataSupplier=f;this.viewportQueries=g;this.processNodeIndexDocument=r;this.finishedLevelCallback=
h;this.logger=l;this.traversalOptions=n;this.queues=[];this.knownNodes=new Set;this.dataLoadingPerLevel=[];this.numIndicesLoading=this.currentLevel=0;this.cancelled=this.queueTraversalEnabled=!1;this.initQueryErrback=function(){d.initPromise.done()};this.initQueryCallback=function(a,b){if(d.cancelled)d.initPromise.done();else if(d.nodeTraversalState(b.id),d.enqueueConnected(a,b,0),d.isLeafNode(b))d.initPromise.done();else{for(var k=1E9,c=void 0,e=0;e<b.children.length;++e){var f=b.children[e];if(d.nodeIsVisible(f)&&
(!d.viewportQueries.hasLOD(b)||!d.viewportQueries.isTooHighLOD(b))){var g=d.viewportQueries.distToPOI(f,d.poi);g<k&&(k=g,c=f)}}c?(a=m.makeAbsolute(c.href,a),d.getNode(a,c.id,d.initQueryCallback,d.initQueryErrback)):d.initPromise.done()}};this.poi=p.vec3d.create(c)}c.prototype.updatePointOfInterest=function(a){p.vec3d.set(a,this.poi);this.reprioritizeQueues()};c.prototype.start=function(){var a=this;this._nodeTraversalState={};this._nodeIsVisibleCached={};this.dataLoadingPerLevel=[];this.currentLevel=
0;this.rootUrl=m.makeAbsolute(this.startNodeUrl,this.baseURL);this.traversalOptions.initDepthFirst?(this.initPromise=new q.Promise,this.getNode(this.rootUrl,this.rootId,this.initQueryCallback,this.initQueryErrback),this.initPromise.then(function(){a.cancelled||(a.queueTraversalEnabled=!0)})):(this.enqueue({id:this.rootId,hrefConcat:this.rootUrl,mbs:null},0),this.queueTraversalEnabled=!0)};c.prototype.continueTraversal=function(a){void 0===a&&(a=5);if(this.queueTraversalEnabled)for(var b=0;b<this.queues.length;b++)if(!this.traversalOptions.perLevelTraversal||
this.currentLevel===b){for(var c=this.queues[b];0<a--&&!c.isEmpty();)this.processQueueOne(b);this.traversalOptions.perLevelTraversal&&c.isEmpty()&&0===this.dataLoadingPerLevel[b]&&(this.finishedLevelCallback.call(null,this.currentLevel),this.currentLevel++)}};c.prototype.isQueueTraversalEnabled=function(){return this.queueTraversalEnabled};c.prototype.getQueueSize=function(){for(var a=0,b=0;b<this.queues.length;b++)a+=this.queues[b].getCount();return a};c.prototype.cancel=function(){this.queueTraversalEnabled=
!1;for(var a=0;a<this.queues.length;a++)this.queues[a].clear();this.cancelled=!0};c.prototype.isLoading=function(){return 0<this.numIndicesLoading||0<this.getQueueSize()};c.prototype.nodeIsVisible=function(a){if(null!=this._nodeIsVisibleCached[a.id])return this._nodeIsVisibleCached[a.id];this._nodeIsVisibleCached[a.id]=this.viewportQueries.isNodeVisible(a);return this._nodeIsVisibleCached[a.id]};c.prototype.nodeTraversalState=function(a){if(null!=this._nodeTraversalState[a])return this._nodeTraversalState[a];
var b=this.nodeIndex[a];if(null==b)return null;var c=null,d=!1;if(null!=b.parentNode){c=this.nodeIndex[b.parentNode.id];if(null==c)return null;var e=this._nodeTraversalState[c.id];null!=e&&(d=e.nodeIsTooHighLOD)}var e=this.viewportQueries.hasLOD(b),f=this.viewportQueries.isTooHighLOD(b),c=this.viewportQueries.isChosenLOD(b,c,f,d);this._nodeTraversalState[b.id]={visited:!0,nodeHasLOD:e,nodeIsTooHighLOD:f,isChosenLOD:c};return this._nodeTraversalState[a]};c.prototype.reprioritizeQueues=function(){for(var a=
0;a<this.queues.length;a++)this.queues[a]=this.reprioritizeQueue(this.queues[a])};c.prototype.reprioritizeQueue=function(a){for(var b=new h;!a.isEmpty();){var c=a.dequeue(),d=this.entryPriority(c);b.enqueue(d,c)}return b};c.prototype.processQueueOne=function(a){var b=this,c=this.queues[a].dequeue();this.dataLoadingPerLevel[a]++;var d=function(){return b.dataLoadingPerLevel[a]--},e=function(c,e){b.nodeTraversalState(e.id);b.enqueueConnected(c,e,a);b.processNodeIndexDocument(e).then(d,d)};this.getNode(c.hrefConcat,
c.id,function(a,c){if(b.traversalOptions.neighborhood&&null!=c.parentNode){var f=b.concatHref(c.parentNode,a);b.getNode(f,c.parentNode.id,function(){return e(a,c)},d)}else e(a,c)},d)};c.prototype.getNode=function(a,b,c,d){var e=this;this.numIndicesLoading++;this.nodeIndex[b]?(c(a,this.nodeIndex[b]),this.numIndicesLoading--):this.streamDataSupplier.request(a,"json").then(function(a,b){e.nodeIndex[b.id]=b;b.baseUrl=a;c(a,b);e.numIndicesLoading--},function(b){null!=d&&d(b);e.loadErrorCallback(a);e.numIndicesLoading--})};
c.prototype.isLeafNode=function(a){return null==a.children};c.prototype.concatHref=function(a,b){return m.makeAbsolute(a.href,b)};c.prototype.entryPriority=function(a){return a.id===this.rootId?0:this.viewportQueries.distToPOI(a,this.poi)};c.prototype.enqueue=function(a,b){this.traversalOptions.perLevelTraversal||(b=0);for(this.knownNodes.add(a.id);this.queues.length<=b;)this.queues.push(new h),this.dataLoadingPerLevel.push(0);var c=this.entryPriority(a);this.queues[b].enqueue(c,a)};c.prototype.queueEntryFromNode=
function(a,b){return{id:a.id,mbs:a.mbs,hrefConcat:b}};c.prototype.queueEntryFromNodeRef=function(a,b){return this.queueEntryFromNode(a,this.concatHref(a,b))};c.prototype.enqueueConnected=function(a,b,c){if(!this.cancelled&&null!=b){var d=this.nodeTraversalState(b.id);b.id===this.rootId||null==b.parentNode||this.knownNodes.has(b.parentNode.id)?b.id===this.rootId&&!this.knownNodes.has(b.id)&&this.nodeIsVisible(b)&&this.enqueue(this.queueEntryFromNode(b,a),c):this.enqueue(this.queueEntryFromNodeRef(b.parentNode,
a),c-1);if(b.children)for(var e=0,f=b.children;e<f.length;e++){var g=f[e],h=this.nodeIsVisible(g);this.knownNodes.has(g.id)||d.nodeHasLOD&&d.nodeIsTooHighLOD||!h||this.enqueue(this.queueEntryFromNodeRef(g,a),c+1)}if(this.traversalOptions.neighborhood&&b.neighbors)for(d=0,b=b.neighbors;d<b.length;d++)e=b[d],f=this.nodeIsVisible(e),!this.knownNodes.has(e.id)&&f&&this.enqueue(this.queueEntryFromNodeRef(e,a),c)}};c.prototype.loadErrorCallback=function(a){this.logger.warn("Error loading node: "+a)};return c}()});