// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang dojo/Deferred dojo/promise/all dojo/errors/CancelError ../../webgl-engine/lib/Util ./I3SUtil ./I3SBinaryReader ../../../../core/promiseUtils ../../../../core/urlUtils".split(" "),function(w,x,t,q,r,u,v,n,m,p,l){return function(){function e(a,d,b,c,g,k){this.useCompressedTextures=d;this.logger=b;this.defaultGeometrySchema=c;this.requiredAttributes=g;this.bypassFeatureData=k;this.loadShared=function(a){if(null==a.sharedResource)return p.resolve({});var b=l.makeAbsolute(a.sharedResource.href,
a.baseUrl)+"/";return this.loadJSON(b).then(function(a){e.fixTextureEncodings(a);e.addAbsoluteHrefTexture(a,b);return a})};this.loader=a;this.cancelled=!1}e.prototype.cancel=function(){this.cancelled=!0};e.prototype.loadJSON=function(a){var d=this.loader.request(a,"json"),b=new q;d.then(function(a,d){b.resolve(d)},function(c){b.reject(Error("Failed to load: "+a))});return b.promise};e.prototype.loadBinary=function(a){var d=this.loader.request(a,"binary"),b=new q;d.then(function(a,d){b.resolve(d)},
function(c){b.reject(Error("Failed to load: "+a))});return b.promise};e.prototype.loadImage=function(a){var d=this.loader.request(a,"image"),b=new q;d.then(function(a,d){b.resolve(d)},function(d){b.reject(Error("Failed to load: "+a))});return b.promise};e.prototype.loadAttribute=function(a,d,b){a=n.addTrailingSlash(l.makeAbsolute(b,a));return this.loadBinary(a).then(function(a){return m.readBinaryAttribute(d,a)})};e.prototype.loadAttributes=function(a,d,b){var c=this,g=b.map(function(b){return null==
a.attributeData||null==a.attributeData[b.index]?(c.logger.error("Missing attributeData for '"+b.name+"' on node '"+a.id+"'"),p.resolve(null)):c.loadAttribute(d,b.attributeStorageInfo,a.attributeData[b.index].href).otherwise(function(d){c.logger.error("Failed to load attributeData for '"+b.name+"' on node '"+a.id+"'");return null})});return r(g).then(function(a){for(var d={},c=0;c<b.length;++c)a[c]&&(d[b[c].name]=a[c]);return d})};e.prototype.prepareBinaryGeometryData=function(a,d,b,c){t.mixin(a.geometries[0].params,
b);a.faceRanges=[[0,b.header.fields.vertexCount/3-1]];c||null!=b.vertexAttributes.region||delete b.vertexAttributes.region;if(null!=b.featureAttributes){c=b.featureAttributes;if(c.faceRange){a.faceRanges=[];for(var g=m.createTypedView(d,c.faceRange),k=c.faceRange.valuesPerElement,h=b.header.fields.featureCount,f=0;f<h;f++)a.faceRanges[f]=[g[f*k],g[f*k+1]];a.componentOffsets=n.convertFlatRangesToOffsets(g,h,k)}if(c.id)for(a.featureIds=[],g=1,f=m.valueType2TypedArrayClassMap[c.id.valueType],"UInt64"===
c.id.valueType&&(f=Uint32Array,g=2),d=new f(d,c.id.byteOffset,c.id.count*c.id.valuesPerElement*g),f=0;f<b.header.fields.featureCount;f++)if(a.featureIds[f]=d[f*c.id.valuesPerElement*g],2===g){k=d[f*c.id.valuesPerElement*g+1];if(2097150<=k)throw Error("ID exceeded maximum range supported by javascript (max \x3d 53bit-1 \x3d 9007199254740991)");a.featureIds[f]+=4294967296*k}}};e.prototype.loadBundleData=function(a,d){var b=this,c=a.baseUrl,g={},k=this.loadShared(a),h=null;null!=this.requiredAttributes&&
(h=this.loadAttributes(a,c,this.requiredAttributes));var f=null;if(null!=a.geometryData){var e=a.geometryData[d],c=l.makeAbsolute(e.href,c);e.hrefConcat=c;f=this.loadBinary(c)}return k.then(function(c){b.handleCancelled();return(b.bypassFeatureData?p.resolve(null):b.loadFeatureData(a,d)).then(function(e){b.handleCancelled();var k=b.bypassFeatureData?b.meshPyramidGeometryData(a,c):b.collectGeometries(a,e,c);e=null!=f?f.then(function(f){g[a.geometryData[d].hrefConcat]=f;var e=Object.keys(c.materialDefinitions)[0],
e=c.materialDefinitions[e].params.vertexRegions,h=m.createGeometryDataIndex(f,b.defaultGeometrySchema,e);b.prepareBinaryGeometryData(k[0],f,h,e);return k}):p.resolve(k);var l=b.loadTextures(k,c).then(function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],g=d.i3sTexId;b[g]={i3sTexId:g,data:d.data,encoding:d.encoding}}return b});return r([l,e,h])}).then(function(a){var d=a[0],f=a[1];a=a[2];b.handleCancelled();var e=null;a&&(e={attributeData:a,loadedAttributes:b.requiredAttributes});return{allGeometryData:f,
attributeDataInfo:e,geometryBuffers:g,sharedResource:c,preloadedDomImages:d}})})};e.addAbsoluteHrefTexture=function(a,d){a=a.textureDefinitions;if(null!=a)for(var b=0,c=Object.keys(a);b<c.length;b++)for(var g=0,e=a[c[b]].images;g<e.length;g++){var h=e[g];Array.isArray(h.href)?h.hrefConcat=h.href.map(function(a){return l.makeAbsolute(a,d)}):h.hrefConcat=l.makeAbsolute(h.href,d)}};e.fixTextureEncodings=function(a){a=a.textureDefinitions;if(null!=a)for(var d in a){var b=a[d];if(Array.isArray(b.encoding))for(var c=
0;c<b.encoding.length;c++){var g=b.encoding[c];"data:"===g.substring(0,5)&&(b.encoding[c]=g.substring(5))}else g=b.encoding,"data:"===g.substring(0,5)&&(b.encoding=g.substring(5))}};e.prototype.loadTexture=function(a,d,b){var c=this;return b===n.DDS_ENCODING_STRING?this.loadBinary(a).then(function(a){c.handleCancelled();return{i3sTexId:d,data:a,encoding:b}}):this.loadImage(a).then(function(a){c.handleCancelled();return{i3sTexId:d,data:a,encoding:b}})};e.prototype.loadTextures=function(a,d){for(var b=
[],c=0;c<a.length;c++){var e=a[c].geometries;if(null!=e)for(var k=0;k<e.length;k++){var h=e[k].params.textureID||"none";if("none"!==h){null!=d.textureDefinitions&&null!=d.textureDefinitions[h]||this.logger.warn("textureDefinitions missing in shared resource. i3sTexId: "+h);var f=d.textureDefinitions[h];v.assert(void 0!==f,"geometry wants unknown texture "+h);if(0!==f.images.length){var l=f.images[f.images.length-1],m=n.getAppropriateTextureEncoding(f.encoding,this.useCompressedTextures),h=this.loadTexture(-1<
m?l.hrefConcat[m]:l.hrefConcat,h,-1<m?f.encoding[m]:f.encoding);b.push(h)}}}}return r(b)};e.prototype.meshPyramidGeometryData=function(a,d){a=d.materialDefinitions?Object.keys(d.materialDefinitions)[0]:null;d=d.textureDefinitions?Object.keys(d.textureDefinitions)[0]:null;return[{featureIds:[],geometries:[{type:"ArrayBufferView",params:{materialID:a,textureID:d}}],featureDataPosition:[0,0,0]}]};e.prototype.collectGeometries=function(a,d,b){a=[];b=0;for(d=d.featureData;b<d.length;b++){var c=d[b],e=
c.geometries;if(null!=e)for(var k=0;k<e.length;k++){var h=c.geometries[k];a.push({featureIds:[c.id],featureDataPosition:c.position,geometries:[h],faceRanges:[h.params.faceRange]})}else null!=c.position&&a.push({featureIds:[c.id],featureDataPosition:c.position,geometries:null})}return a};e.prototype.loadFeatureData=function(a,d){a=l.makeAbsolute(a.featureData[d].href,a.baseUrl);return this.loadJSON(a)};e.prototype.handleCancelled=function(){if(this.cancelled)throw new u;};return e}()});