// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang dojo/promise/all ../../../../request ../../../../core/promiseUtils ../../../../core/Error ../../../../core/urlUtils ../../../../geometry/SpatialReference ../../../../geometry/support/webMercatorUtils ../../../../tasks/QueryTask ../../../../tasks/support/Query ../../support/projectionUtils ../../lib/glMatrix ../../webgl-engine/lib/Util ./I3SBinaryReader".split(" "),function(S,h,E,u,F,n,m,G,v,H,I,J,w,l,K,L){function t(a){return a&&parseInt(a.substring(a.lastIndexOf("/")+
1,a.length),10)}function x(a,b,c,d,g,e){if(null!=c){var f=M;w.mbsToMbs(c.mbs,d,f,b);if(0!==y(a,f)){e.push(c);for(var f=null!=c.children?c.children.length:0,k=0;k<f;k++)x(a,b,g[c.children[k].id],d,g,e)}}}function y(a,b){var c=b[0],d=b[1],g=b[2];b=b[3];var e=0;if(c<a[0])var f=a[0]-c,e=e+f*f;d<a[1]&&(f=a[1]-d,e+=f*f);g<a[2]&&(f=a[2]-g,e+=f*f);c>a[3]&&(f=c-a[3],e+=f*f);d>a[4]&&(f=d-a[4],e+=f*f);g>a[5]&&(f=g-a[5],e+=f*f);if(e>b*b)return 0;if(0<e)return 1;e=Infinity;c-a[0]<e&&(e=c-a[0]);d-a[1]<e&&(e=d-
a[1]);g-a[2]<e&&(e=g-a[2]);a[3]-c<e&&(e=a[3]-c);a[4]-d<e&&(e=a[4]-d);a[5]-g<e&&(e=a[5]-g);return e>b?2:1}function z(a,b,c){void 0===c&&(c=["*"]);if(null!=a.maxRecordCount&&b.length>a.maxRecordCount){var d=N(b,a.maxRecordCount);return u(d.map(function(b){return z(a,b,c)})).then(O)}d=new J({objectIds:b,outFields:c,orderByFields:[a.objectIdField]});return(new I(a.parsedUrl.path)).execute(d).then(function(a){return a&&a.features&&a.features.length===b.length?a.features.map(function(a){return a.attributes}):
n.reject(new m("scenelayer:feature-not-in-companion","Feature not found in companion feature layer"))})}function P(a,b,c,d,g){void 0===d&&(d=["*"]);var e=d.some(function(a){return"*"===a}),f=e?null:d.map(function(a){return a.toLowerCase()});return u(b.attributeData.map(function(c,d){var k=a[d].name.toLowerCase();if(!e&&!f.some(function(a){return k===a}))return n.resolve(null);c=G.makeAbsolute(c.href,b.baseUrl);return F(c,{query:{token:g},responseType:"array-buffer"}).then(function(b){return L.readBinaryAttribute(a[d],
b.data)}).otherwise(function(){return null})})).then(function(b){for(var d=[],e=0;e<c.length;e++){for(var g=c[e],f={},k=0;k<b.length;k++)null!=b[k]&&(f[a[k].name]=A(b[k],g));d.push(f)}return d})}function A(a,b){b=a[b];return a instanceof Int16Array?b===Q?null:b:a instanceof Int32Array?b===R?null:b:b!==b?null:b}function N(a,b){var c=a.length;b=Math.ceil(c/b);for(var d=[],g=0;g<b;g++)d.push(a.slice(Math.floor(c*g/b),Math.floor(c*(g+1)/b)));return d}function O(a){for(var b=[],c=0;c<a.length;c++)b=b.concat(a[c]);
return b}function B(a){var b=new v(t(a.store.indexCRS||a.store.geographicCRS));return b.equals(a.spatialReference)?a.spatialReference:b}function C(a){var b=new v(t(a.store.vertexCRS||a.store.projectedCRS));return b.equals(a.spatialReference)?a.spatialReference:b}function r(a,b,c){if(!H.canProject(a,b))throw new m("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",{});if("local"===c&&a.isGeographic)throw new m("layerview:local-gcs-not-supported",
"Geographic coordinate systems are not supported in local scenes",{});}function D(a,b,c){var d=B(a);a=C(a);r(d,b,c);r(a,b,c)}Object.defineProperty(h,"__esModule",{value:!0});h.DDS_ENCODING_STRING="image/vnd-ms.dds";h.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS=["image/jpeg","image/png"];h.addTrailingSlash=function(a){"/"!==a[a.length-1]&&(a+="/");return a};h.extractWkid=t;h.processNormals=function(a,b,c){switch(b){case "none":b=a.normals;c=a.positions;var d=a.normalInd,g=a.positionInd;K.assert(a.normalInd.length===
a.positionInd.length);a=l.vec3d.create();for(var e=l.vec3d.create(),f=0;f<g.length;f+=3){var k=3*g[f],h=c[k],p=c[k+1],q=c[k+2],k=3*g[f+1];a[0]=c[k]-h;a[1]=c[k+1]-p;a[2]=c[k+2]-q;k=3*g[f+2];e[0]=c[k]-h;e[1]=c[k+1]-p;e[2]=c[k+2]-q;l.vec3d.cross(a,e,a);l.vec3d.normalize(a);for(k=0;3>k;k++)h=3*d[f+k],b[h]=a[0],b[h+1]=a[1],b[h+2]=a[2]}break;case "east-north-up":break;case "earth-centered":c(a.normals,w.SphericalRenderSpatialReference);break;case "vertex-reference-frame":break;default:throw Error("Received unexpected normalReferenceFrame: "+
b);}};h.getAppropriateTextureEncoding=function(a,b){if(Array.isArray(a)){if(b&&(b=a.indexOf(h.DDS_ENCODING_STRING),-1<b))return b;for(b=0;b<a.length;b++)if(-1<h.BROWSER_SUPPORTED_IMAGE_ENCODING_STRINGS.indexOf(a[b]))return b;throw Error("Could not find appropriate texture encoding (among "+a.toString()+")");}return-1};h.findIntersectingNodes=x;var M=l.vec4d.create();h.intersectBoundingBoxWithMbs=y;h.findFieldsCaseInsensitive=function(a,b,c){for(var d=[],g=0;g<a.length;g++){for(var e=a[g],f=e.toLowerCase(),
k=!1,h=0,p=b;h<p.length;h++){var q=p[h];if(f===q.name.toLowerCase()){d.push(q.name);k=!0;break}}k||void 0===c||c.push(e)}return d};h.whenGraphicAttributes=function(a,b,c,d,g){if(0===b.length)return n.resolve(b);var e=Object.keys(b[0].attributes).map(function(a){return a.toLowerCase()});d=d.filter(function(a){return 0>e.indexOf(a.toLowerCase())});if(0===d.length)return n.resolve(b);var f=function(a){for(var c=0;c<b.length;c++)E.mixin(b[c].attributes,a[c]);return b},h=a.companionFeatureLayer,l=a.attributeStorageInfo;
return h?(b.sort(function(a,b){return a.attributes[c]-b.attributes[c]}),a=b.map(function(a){return a.attributes[c]}),z(h,a,d).then(f)):l&&(g=g(),null!=g)?P(l,g.node,g.indices,d,a.token).then(f):n.reject(new m("scenelayer:no-attribute-source","This scene layer does not have a source for attributes available"))};var Q=-Math.pow(2,15),R=-Math.pow(2,31);h.getCachedAttributeValue=A;h.convertFlatRangesToOffsets=function(a,b,c){void 0===c&&(c=2);b=null!=b?b:a.length/c;for(var d=new Uint32Array(b+1),g=0;g<
b;g++){var e=a[g*c];d[g]=3*e;var f=(g-1)*c+1;if(0<=f&&e-1!==a[f])throw new m("Face ranges are not continuous");}d[d.length-1]=3*(a[(b-1)*c+1]+1);return d};h.getIndexCrs=B;h.getVertexCrs=C;h.checkSpatialReference=r;h.checkSpatialReferences=D;h.checkSceneLayerValid=function(a){var b;(b=null==a.store||null==a.store.defaultGeometrySchema)||(a=a.store.defaultGeometrySchema,b=!!(null!=a.geometryType&&"triangles"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null==a.vertexAttributes||
null==a.vertexAttributes.position));if(b)throw new m("scenelayer:unsupported-geometry-schema","The geometry schema of this scene layer is not supported.",{});};h.checkSceneLayerCompatibleWithView=function(a,b){D(a,b.spatialReference,b.viewingMode)};h.checkPointCloudLayerValid=function(a){var b;(b=null==a.store||null==a.store.defaultGeometrySchema)||(a=a.store.defaultGeometrySchema,b=!!(null==a.geometryType||"points"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null!=a.encoding&&
""!==a.encoding&&"lepcc-xyz"!==a.encoding||null==a.vertexAttributes||null==a.vertexAttributes.position));if(b)throw new m("pointcloud:unsupported-geometry-schema","The geometry schema of this point cloud scene layer is not supported.",{});};h.checkPointCloudLayerCompatibleWithView=function(a,b){r(a.spatialReference,b.spatialReference,b.viewingMode)};h.encodeSymbolColor=function(a,b,c){null==a||"ignore"===b?(c[0]=255,c[1]=255,c[2]=255,c[3]=255):(c[0]=Math.floor(255*a[0]),c[1]=Math.floor(255*a[1]),
c[2]=Math.floor(255*a[2]),a=Math.floor(85*a[3]),c[3]=0===a?0:"tint"===b?a:"replace"===b?a+85:a+170)}});