// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang ./utils ./metadata ./ensureType ./extensions ./decorators/cast".split(" "),function(z,m,q,n,k,g,p,r){function t(a){switch(a){case Number:return g.ensureNumber;case Boolean:return g.ensureBoolean;case String:return g.ensureString;case Date:return g.ensureDate;default:return Array.isArray(a)?g.ensureArray(a[0]):g.ensureType(a)}}Object.defineProperty(m,"__esModule",{value:!0});var u=Object.prototype.hasOwnProperty,v=/^_([a-zA-Z0-9]+)(Getter|Setter|Reader|Writer|Caster)$/,
w={Getter:"get",Setter:"set",Reader:"json.read.reader",Writer:"json.write.writer",Caster:"cast"},x=/^_(set|get)([a-zA-Z0-9]+)Attr$/;m.processPrototype=function(a){for(var y=a.declaredClass,e=a.properties||{},d=0,h=Object.getOwnPropertyNames(e);d<h.length;d++){var b=h[d],c=e[b],f=typeof c;null==c?k.setPropertyMetadata(a,b,{value:c}):Array.isArray(c)?k.setPropertyMetadata(a,b,{type:[c[0]],value:null}):"object"===f?n.getProperties(c)||c instanceof Date?k.setPropertyMetadata(a,b,{type:c.constructor,value:c}):
k.setPropertyMetadata(a,b,c):"boolean"===f?k.setPropertyMetadata(a,b,{type:Boolean,value:c}):"string"===f?k.setPropertyMetadata(a,b,{type:String,value:c}):"number"===f?k.setPropertyMetadata(a,b,{type:Number,value:c}):"function"===f&&k.setPropertyMetadata(a,b,{type:c,value:null})}d=0;for(h=Object.getOwnPropertyNames(a);d<h.length;d++){var f=h[d],c=a[f],e=b=void 0,l=v.exec(f);if(l)b=l[1],e=w[l[2]];else if(l=x.exec(f))b=l[2][0].toLowerCase()+l[2].substr(1),e=l[1].toLowerCase();b&&e&&(b=k.getPropertyMetadata(a,
b),q.setObject(e,c,b))}d=0;for(h=Object.getOwnPropertyNames(k.getPropertiesMetadata(a));d<h.length;d++)b=h[d],c=k.getPropertyMetadata(a,b),e=c.type,f=c.types,void 0===c.value&&u.call(a,b)&&(c.value=a[b]),!c.cast&&e?c.cast=t(e):!c.cast&&f&&(Array.isArray(f)?c.cast=g.ensureArrayTyped(g.ensureOneOfType(f[0])):c.cast=g.ensureOneOfType(f));p.processPrototypeMetadatas(k.getPropertiesMetadata(a),y);return k.getPropertiesMetadata(a)};m.processClass=function(a){for(var g=a.prototype,e=g.declaredClass,d=a._meta.bases,
h={},b=d.length-1;0<=b;b--)n.merge(h,k.getMetadata(d[b].prototype));var c=h.properties;p.processClassMetadatas(c,e);Object.defineProperty(a,"__accessorMetadata__",{value:{properties:c,autoDestroy:!!h.autoDestroy}});for(var f={},e=function(a){var b=c[a];f[a]={enumerable:!0,configurable:!0,get:function(){return this.__accessor__?this.__accessor__.get(a):b.value},set:function(c){var d=this.__accessor__;if(!d)Object.defineProperty(this,a,{enumerable:!0,configurable:!0,writable:!0,value:c});else if(!Object.isFrozen(this)){if(d.initialized&&
b.readOnly)throw new TypeError("[accessor] cannot assign to read-only property '"+a+"' of "+this.declaredClass);if(2===d.lifecycle&&b.constructOnly)throw new TypeError("[accessor] cannot assign to construct-only property '"+a+"' of "+this.declaredClass);d.set(a,c)}}}},d=0,b=Object.getOwnPropertyNames(c);d<b.length;d++)e(b[d]);Object.defineProperties(a.prototype,f);if(h.parameters)for(a=0,e=Object.getOwnPropertyNames(h.parameters);a<e.length;a++)d=e[a],b=Object.getOwnPropertyDescriptor(g,d)||{value:g[d]},
(b=r.autocastMethod(g,d,b))&&Object.defineProperty(g,d,b);return h}});