// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/_base/lang dojo/on dojo/dom dojo/dom-construct ../core/Accessor ../core/Evented ../core/HandleRegistry ../core/Scheduler ../core/watchUtils ../widgets/Popup ./PopupManager ./ui/DefaultUI ../core/accessorSupport/decorators".split(" "),function(A,B,q,f,r,t,h,g,u,v,w,x,m,n,y,z,e){var k=[0,0];return function(p){function b(){var a=p.call(this)||this;a.height=0;a.position=null;a.resizing=!1;a.root=null;
a.surface=null;a.suspended=!0;a.width=0;Object.defineProperty(a,"_measureInfo",{enumerable:!1,writable:!1,value:{task:null,freq:16,time:750}});a._domHandles=new w;a.watch("interacting",function(d){var c=a.surface;c&&c.setAttribute("data-interacting",d.toString())});return a}q(b,p);b.prototype.getDefaults=function(){return r.mixin(this.inherited(arguments),{popup:{},ui:{}})};b.prototype.initialize=function(){var a=this,d=this._measureInfo,c=null;m.init(this,"container",function(b,l,e,f){if(null!=b||
null!=l)c&&(c.remove(),c=null,d.freq=16,d.time=750),d.task&&(d.task.remove(),d.task=null),b?(c=t(window,"resize",function(){d.freq=16;d.time=750}),d.task=x.addFrameTask({prepare:function(d){var c=a._measureInfo;c.time+=d.deltaTime;c.time<c.freq||(c.time=0,a._measure()?(c.freq=16,a._set("resizing",!0)):(c.freq=Math.min(750,2*c.freq),512<=c.freq&&a._set("resizing",!1)))}})):a._set("resizing",!1),a._measure(),b=a.root,l=a.surface,e=a.width,f=a.height,b&&l&&e&&f&&(b.style.width=l.style.width=e+"px",b.style.height=
l.style.height=f+"px")})};b.prototype.destroy=function(){this.ui.destroy();this.popup&&this.popup.destroy();this.container=null};Object.defineProperty(b.prototype,"container",{set:function(a){var d=this._get("container");if(d!==a){d&&(d.classList.remove("esri-view"),this.popupManager.destroy(),this.popupManager=null,g.destroy(this.root),this._set("root",null));if(a){a.classList.add("esri-view");d=document.createElement("div");d.className="esri-view-root";a.insertBefore(d,a.firstChild);this._set("root",
d);var c=document.createElement("div");c.className="esri-view-surface";h.setSelectable(c,!1);d.appendChild(c);this._set("surface",c);this._forceReadyCycle();this.popupManager=new y({enabled:!0,view:this})}else this._set("width",0),this._set("height",0),this._set("position",null),this._set("suspended",!0),this._set("surface",null);this._set("container",a)}},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"popup",{set:function(a){var d=this._get("popup");a!==d&&(a||(a=new n({container:document.createElement("div")})),
this._domHandles.remove("view-popup"),d&&d.destroy(),a&&(a.viewModel.view=this,this._domHandles.add([m.init(this,"root",function(c,d){var b=a.container;b||(a.container=document.createElement("div"));var e=b&&b.parentNode;h.isDescendant(e,d)&&e.removeChild(b);c&&!e&&g.place(a.container,c)})],"view-popup")),this._set("popup",a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"size",{get:function(){return[this.width,this.height]},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"ui",{set:function(a){var d=this._get("ui");a!==d&&(this._domHandles.remove("ui"),d&&d.destroy(),a&&(a.view=this,this._domHandles.add([m.init(this,"root",function(c){a.container=c?g.create("div",null,c):null})],"ui")),this._set("ui",a))},enumerable:!0,configurable:!0});b.prototype.focus=function(){this.surface&&this.surface.focus()};b.prototype.pageToContainer=function(a,d,c){var b=this.position;a-=b[0];d-=b[1];c?(c[0]=a,c[1]=d):c=[a,d];return c};b.prototype.containerToPage=function(a,d,c){var b=
this.position;a+=b[0];d+=b[1];c?(c[0]=a,c[1]=d):c=[a,d];return c};b.prototype._measure=function(){var a=this.container,d=a?a.clientWidth:0,c=a?a.clientHeight:0;if(0===d||0===c||"hidden"===window.getComputedStyle(a).visibility)return this.suspended||this._set("suspended",!0),!1;var b=this.root,e=this.surface,f=this.width,h=this.height,g=this.position;if(d===f&&c===h)return this.suspended&&this._set("suspended",!1),!1;b&&e&&(b.style.width=e.style.width=d+"px",b.style.height=e.style.height=c+"px");this._set("width",
d);this._set("height",c);this._set("suspended",!1);b=(a.ownerDocument||window.document).defaultView;a=a.getBoundingClientRect();k[0]=a.left+b.pageXOffset;k[1]=a.top+b.pageYOffset;g&&k[0]===g[0]&&k[1]===g[1]||this._set("position",k.slice());this.emit("resize",{oldWidth:f,oldHeight:h,width:d,height:c});return!0};f([e.property({value:null,cast:function(a){return h.byId(a)}})],b.prototype,"container",null);f([e.property({readOnly:!0})],b.prototype,"height",void 0);f([e.property({type:n})],b.prototype,
"popup",null);f([e.property({readOnly:!0})],b.prototype,"position",void 0);f([e.property({readOnly:!0})],b.prototype,"resizing",void 0);f([e.property({readOnly:!0})],b.prototype,"root",void 0);f([e.property({value:null,dependsOn:["width","height"],readOnly:!0})],b.prototype,"size",null);f([e.property({readOnly:!0})],b.prototype,"surface",void 0);f([e.property({readOnly:!0})],b.prototype,"suspended",void 0);f([e.property({type:z})],b.prototype,"ui",null);f([e.property({readOnly:!0})],b.prototype,"width",
void 0);return b=f([e.subclass("esri.views.DOMContainer")],b)}(e.declared(u,v))});