// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/_base/lang ../core/accessorSupport/decorators ../core/HandleRegistry ../core/Logger ../core/promiseUtils ../Viewpoint ../geometry/Point ../geometry/ScreenPoint ../geometry/Extent ../geometry/SpatialReference ../geometry/support/webMercatorUtils ./View ./ViewAnimation ./2d/FrameTask ./2d/PaddedViewState ./2d/MapViewConstraints ./2d/AnimationManager ./2d/viewpointUtils".split(" "),function(G,H,w,f,q,
e,x,y,z,r,l,A,t,B,n,C,p,D,E,u,F,k){var h=y.getLogger("esri.views.MapView");return function(v){function c(a){var b=v.call(this,a)||this;b._frameTask=new D(b);b._mapViewBaseHandles=new x;b._setup=!1;b.fullOpacity=1;b.interacting=!1;b.initialExtent=null;b.resizeAlign="center";b.type="2d";b.constraints=new u;b.padding={top:0,right:0,bottom:0,left:0};var g=function(){this._set("updating",this.layerViewManager.factory.working||this.allLayerViews.some(function(a){return!0===a.updating}))}.bind(b),c=b._mapViewBaseHandles;
c.add([b.watch("viewpoint",function(a){return b._flipStationary()},!0),b.on("resize",function(a){return b._resizeHandler(a)}),b.watch("animationManager.animation",function(a){b.animation=a}),b.allLayerViews.on("change",function(){g();c.remove("layerViewsUpdating");c.add(b.allLayerViews.map(function(a){return a.watch("updating",g)}).toArray(),"layerViewsUpdating")})]);b.watch("ready",function(a){a?b._startup():b._tearDown()});return b}w(c,v);c.prototype.destroy=function(){this.destroyed||(this._set("ready",
!1),this._mapViewBaseHandles.removeAll(),this.layerViewManager.empty(),this._frameTask.destroy(),this._tearDown(),this._gotoTask=this._mapViewBaseHandles=this._frameTask=null)};Object.defineProperty(c.prototype,"animation",{set:function(a){var b=this,g=this._get("animation");a!==g&&(g&&g.stop(),!a||a.isFulfilled()?this._set("animation",null):(this._set("animation",a),g=function(){a===b._get("animation")&&(b._set("animation",null),b._frameTask.requestFrame())},a.then(g,g,function(a){b.state&&(b.state.viewpoint=
a)})))},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"center",{get:function(){if(!this._setup)return this._get("center");var a=this.content.center;return new l({x:a[0],y:a[1],spatialReference:this.content.spatialReference})},set:function(a){if(null!=a)if(this._normalizeInput(a))if(this._setup){var b=this.viewpoint;k.centerAt(b,b,a);this.viewpoint=b}else this._set("center",a),this.notifyChange("initialExtentRequired");else h.error("#center","incompatible spatialReference "+JSON.stringify(a.spatialReference)+
" with view's spatialReference "+JSON.stringify(this.spatialReference))},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"constraints",{set:function(a){var b=this,g=this._get("constraints");g&&(this._mapViewBaseHandles.remove("constraints"),g.destroy());this._set("constraints",a);a&&(this._setup&&(a.view=this,this.state.viewpoint=a.fit(this.content.viewpoint)),this._mapViewBaseHandles.add(a.on("update",function(){b._setup&&b.state&&(b.state.viewpoint=a.fit(b.content.viewpoint))}),
"constraints"))},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"extent",{get:function(){return this._setup?this.content.extent.clone():this._get("extent")},set:function(a){if(null!=a){var b=this._normalizeInput(a);b?b.width&&b.height?this._setup?(a=this.viewpoint,k.setExtent(a,a,b,this.size,{constraints:this.constraints}),this.viewpoint=a):(this._set("extent",b),this._set("center",null),this._set("viewpoint",null),this._set("scale",0),this._set("zoom",-1),this.notifyChange("initialExtentRequired")):
h.error("#extent","invalid extent size"):h.error("#center","incompatible spatialReference "+JSON.stringify(a.spatialReference)+" with view's spatialReference "+JSON.stringify(this.spatialReference))}},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"initialExtentRequired",{get:function(){var a=this.extent,b=this.center,g=this.scale,c=this.viewpoint,e=this.zoom;return this.get("map.initialViewProperties.viewpoint")||a||b&&(0!==g||-1!==e)||c?!1:!0},enumerable:!0,configurable:!0});
Object.defineProperty(c.prototype,"padding",{get:function(){return this._setup?this.state.padding:this._get("padding")},set:function(a){this._setup?(this.state.padding=a,this._set("padding",this.state.padding)):this._set("padding",a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"rotation",{get:function(){return this._setup?this.content.rotation:this._get("rotation")},set:function(a){if(!isNaN(a))if(this._setup){var b=this.viewpoint;k.rotateTo(b,b,a);this.viewpoint=b}else this._set("rotation",
a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"scale",{get:function(){return this._setup?this.content.scale:this._get("scale")},set:function(a){if(a&&!isNaN(a))if(this._setup){var b=this.viewpoint;k.scaleTo(b,b,a);this.viewpoint=b}else{this._set("scale",a);this._set("zoom",-1);if(a=this._get("extent"))this._set("extent",null),this._set("center",a.center);this.notifyChange("initialExtentRequired")}},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"stationary",
{get:function(){return!this.animation&&!this.interacting&&!this._get("resizing")&&!this._stationaryTimer},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"viewpoint",{get:function(){if(!this._setup)return this._get("viewpoint");var a=this.content;return a&&a.viewpoint.clone()},set:function(a){if(null!=a){var b=this._normalizeInput(a);b?this._setup?(a=k.create(),k.copy(a,b),this.constraints.constrain(a,this.content.viewpoint),this.state.viewpoint=a,this._frameTask.requestFrame(),
this._set("viewpoint",a)):(this._set("viewpoint",b),this._set("extent",null),this._set("center",null),this._set("zoom",-1),this._set("scale",0),this.notifyChange("initialExtentRequired")):!a.scale||isNaN(a.scale)?h.error("#viewpoint","invalid scale value of "+a.scale):a.targetGeometry?h.error("#viewpoint","incompatible spatialReference "+JSON.stringify(a.targetGeometry.spatialReference)+" with view's spatialReference "+JSON.stringify(this.spatialReference)):h.error("#viewpoint","geometry not defined")}},
enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"zoom",{get:function(){return this._setup?this.constraints.scaleToZoom(this.scale):this._get("zoom")},set:function(a){if(null!=a){if(!this._setup){this.notifyChange("initialExtentRequired");this._set("zoom",a);this._set("scale",0);var b=this._get("extent");b&&(this._set("extent",null),this._set("center",b.center))}this.constraints.effectiveLODs&&(b=this.viewpoint,k.scaleTo(b,b,this.constraints.zoomToScale(a)),this.viewpoint=b,this._set("zoom",
this.constraints.scaleToZoom(this.scale)))}},enumerable:!0,configurable:!0});c.prototype.goTo=function(a,b){if(this._setup)return b=q.mixin({animate:!0},b),a=k.createAsync(a,this),this._gotoTask={},b.animate?this._gotoAnimated(a,b):this._gotoImmediate(a,b);h.error("#goTo()","MapView cannot be used before it is ready")};c.prototype.hitTest=function(a,b){return z.reject("Should be implemented by subclasses")};c.prototype.toMap=function(a,b,c){if(!this._setup)return null;a&&null!=a.x&&(c=b,b=a.y,a=a.x);
var g=[0,0];this.state.toMap(g,[a,b]);c=c||new l;c.x=g[0];c.y=g[1];c.spatialReference=this.spatialReference;return c};c.prototype.isTileInfoRequired=function(){return!0};c.prototype.toScreen=function(a,b,c,d){if(!this._setup)return null;a&&null!=a.x&&(d=b,b=a.y,a=a.x);d=c||d||new A;a=[a,b];this.state.toScreen(a,a);d.x=a[0];d.y=a[1];return d};c.prototype.pixelSizeAt=function(a,b){if(!this._setup)return NaN;a&&null!=a.x&&(b=a.y,a=a.x);return this.content.pixelSizeAt([a,b])};c.prototype.requestLayerViewUpdate=
function(a){this._setup&&this._frameTask.requestLayerViewUpdate(a)};c.prototype.getDefaultSpatialReference=function(){return this.get("map.initialViewProperties.spatialReference")||this.get("defaultsFromMap.spatialReference")||null};c.prototype.isSpatialReferenceSupported=function(a,b){if(b||this._get("ready"))return!0;b=this._normalizeInput(this._get("center"),a);var c=this._normalizeInput(this._get("extent"),a),d=this._normalizeInput(this._get("viewpoint"),a),e=this._userSpatialReference,f=null,
k=null;(d=d&&d.targetGeometry)&&("extent"===d.type?f=d:"point"===d.type&&(k=d));d=this._normalizeInput(this.get("map.initialViewProperties.viewpoint.targetGeometry.extent"),a);a=this._normalizeInput(this.initialExtent,a);a=c||f||d||a;return b||k||a&&a.center?!0:(e&&h.error("The view could not be initialized with the spatialReference "+e.wkid+".","Try specifying an extent or a center and scale"),!1)};c.prototype._gotoImmediate=function(a,b){var c=this,d=this._gotoTask;!this.animation||"running"!==
this.animation.state&&"waiting-for-target"!==this.animation.state?this.animation=new p({target:a}):this.animation.target=a;a.then(function(a){d===c._gotoTask&&(c.viewpoint=c.animation.target=a,c.animation.finish())});return this.animation};c.prototype._gotoAnimated=function(a,b){var c=this;!this.animation||"running"!==this.animation.state&&"waiting-for-target"!==this.animation.state?this.animation=new p({target:a}):this.animation.target=a;var d=this.animation;d.state="waiting-for-target";a.then(function(g){d.target===
a&&c.animation===d&&(d.target=g,d.state="running",c.animationManager.animate(d,c.viewpoint,b),d.state===p.State.STOPPED&&d.stop())}).otherwise(function(){d.target===a&&c.animation===d&&(c.animation=null,d.finish())});return d};c.prototype._resizeHandler=function(a){var b=this.state;if(b){var c=this.content.viewpoint,d=this.content.size.concat();b.size=[a.width,a.height];k.resize(c,c,d,this.content.size,this.resizeAlign);c=this.constraints.constrain(c,null);this.state.viewpoint=c}};c.prototype._startup=
function(){if(!this._setup){var a=this.constraints,b=this._get("zoom"),c=this._get("scale"),d=this._normalizeInput(this._get("center")),e=this._normalizeInput(this._get("extent")),f=this._get("rotation"),h=this._normalizeInput(this._get("viewpoint"));a.view=this;a.effectiveLODs?-1!==b&&(c=a.zoomToScale(b)):b=-1;var l=null,n=null,p=0,b=h&&h.rotation,m=h&&h.targetGeometry;m&&("extent"===m.type?l=m:"point"===m.type&&(n=m,p=h.scale));h=this._normalizeInput(this.get("map.initialViewProperties.viewpoint.targetGeometry.extent"));
m=this._normalizeInput(this.initialExtent);e=e||l||h||m;d=d||n||e&&e.center;c=c||p||e&&k.extentToScale(e,this.size);f=new r({targetGeometry:d,scale:c,rotation:f||b||0});a.fit(f);this._set("animationManager",new F);this._set("state",new E({padding:this._get("padding"),size:this.size,viewpoint:f}));this._set("content",this.state.content);this._setup=!0}};c.prototype._tearDown=function(){if(this._setup){this._setup=!1;this._stationaryTimer&&(clearTimeout(this._stationaryTimer),this._stationaryTimer=
null,this.notifyChange("stationary"));var a=this._get("content"),b=a.center,c=a.spatialReference,b=new l({x:b[0],y:b[1],spatialReference:c});this._set("viewpoint",null);this._set("extent",null);this._set("center",b);this._set("zoom",-1);this._set("rotation",a.rotation);this._set("scale",a.scale);this._set("spatialReference",c);this.constraints.view=null;this.animationManager.destroy();this._set("animationManager",null);this._set("state",null);this._set("content",null);this.animation=null}};c.prototype._flipStationary=
function(){var a=this;this._stationaryTimer&&clearTimeout(this._stationaryTimer);this._stationaryTimer=setTimeout(function(){a._stationaryTimer=null;a.notifyChange("stationary")},160);this.notifyChange("stationary")};c.prototype._normalizeInput=function(a,b){void 0===b&&(b=this.spatialReference);var c=a&&a.targetGeometry||a;return b?c?b.equals(c.spatialReference)?a:n.canProject(c,b)?a&&"esri.Viewpoint"===a.declaredClass?(a.targetGeometry=n.project(c,b),a):n.project(c,b):null:null:a};f([e.property()],
c.prototype,"animation",null);f([e.property({readOnly:!0})],c.prototype,"animationManager",void 0);f([e.property({value:null,type:l,dependsOn:["content.center"]})],c.prototype,"center",null);f([e.property({type:u})],c.prototype,"constraints",null);f([e.property({readOnly:!0})],c.prototype,"content",void 0);f([e.property({value:null,type:t,dependsOn:["content.extent"]})],c.prototype,"extent",null);f([e.property()],c.prototype,"fullOpacity",void 0);f([e.property({readOnly:!0})],c.prototype,"interacting",
void 0);f([e.property({type:t})],c.prototype,"initialExtent",void 0);f([e.property({dependsOn:["map.initialViewProperties.viewpoint"]})],c.prototype,"initialExtentRequired",null);f([e.property({value:{top:0,right:0,bottom:0,left:0},cast:function(a){return q.mixin({top:0,right:0,bottom:0,left:0},a)}})],c.prototype,"padding",null);f([e.property()],c.prototype,"resizeAlign",void 0);f([e.property({value:0,type:Number,dependsOn:["content.rotation"]})],c.prototype,"rotation",null);f([e.property({value:0,
type:Number,dependsOn:["content.scale"]})],c.prototype,"scale",null);f([e.property({type:B,dependsOn:["map.initialViewProperties.spatialReference","defaultsFromMap.isSpatialReferenceDone"]})],c.prototype,"spatialReference",void 0);f([e.property({readOnly:!0})],c.prototype,"state",void 0);f([e.property()],c.prototype,"stationary",null);f([e.property({readOnly:!0})],c.prototype,"type",void 0);f([e.property({value:null,type:r,dependsOn:["content.viewpoint"]})],c.prototype,"viewpoint",null);f([e.property({value:-1,
dependsOn:["content.scale"]})],c.prototype,"zoom",null);return c=f([e.subclass("esri.views.MapViewBase")],c)}(e.declared(C))});