// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require ../core/promiseUtils dojo/_base/array dojo/on dojo/Deferred dojo/promise/all ../layers/support/layerUtils ../geometry/support/scaleUtils ../geometry/Extent ../tasks/support/Query ../layers/GroupLayer ../core/Accessor".split(" "),function(H,z,l,D,A,I,E,F,J,K,G,L){var B;return L.createSubclass({declaredClass:"esri.views.PopupManager",properties:{map:{dependsOn:["view.map"],readOnly:!0}},constructor:function(){this._featureLayersCache={}},destroy:function(){this._featureLayersCache={};
this.view=null},_clickHandle:null,_featureLayersCache:null,enabled:!1,_enabledSetter:function(b){this._clickHandle&&(b?this._clickHandle.resume():this._clickHandle.pause());this._set("enabled",b)},_mapGetter:function(){return this.get("view.map")||null},view:null,_viewSetter:function(b){this._clickHandle&&(this._clickHandle.remove(),this._clickHandle=null);b&&(this._clickHandle=D.pausable(b,"click",this._clickHandler.bind(this)),this.enabled||this._clickHandle.pause());this._set("view",b)},getMapLayer:function(b){var a;
if(b&&(a=b.findLayerById())&&(b=a.id,this._featureLayersCache[b])){var f=b.lastIndexOf("_");-1<f&&(b=b.substring(0,f),a=this.map.findLayerById(b))}return a},_closePopup:function(){var b=this.get("view.popup");b&&(b.clear(),b.close())},_showPopup:function(b,a){function f(c){return h.allLayerViews.find(function(a){return a.layer===c})}function g(c){if(null==c)return!1;var a=f(c);return null==a?!1:c.loaded&&!a.suspended&&(c.popupEnabled&&c.popupTemplate||"graphics"===c.type||"geo-rss"===c.type||"map-notes"===
c.type||"kml"===c.type||a.getPopupData)}function x(a){return(a=f(a))&&a.hasDraped}var h=this.view,y=h.popup,r=this,d=[],e="3d"===h.type;l.forEach(this.map.layers.toArray(),function(a){a.isInstanceOf(G)?l.forEach(a.layers.toArray(),function(a){!g(a)||e&&!x(a)||d.push(a)}):!g(a)||e&&!x(a)||d.push(a)});0<h.graphics.length&&d.push(h.graphics);(a&&h.graphics.includes(a)?a.popupTemplate:!a||g(a.layer))||(a=null);if(d.length||a){var p=[],t=!!a,v=r._calculateClickTolerance(d),n=b.mapPoint;if(n){var w=1;h.state&&
(w=h.state.resolution);var k=h.basemapTerrain;k&&k.overlayManager&&(w=k.overlayManager.overlayPixelSizeInMapUnits(n));v*=w;k&&!k.spatialReference.equals(h.spatialReference)&&(v*=F.getMetersPerUnitForSR(k.spatialReference)/F.getMetersPerUnitForSR(h.spatialReference));var k=n.clone().offset(-v,-v),n=n.clone().offset(v,v),q=new J(Math.min(k.x,n.x),Math.min(k.y,n.y),Math.max(k.x,n.x),Math.max(k.y,n.y),h.spatialReference),n=function(c){var g;if("imagery"===c.type){g=new K;g.geometry=b.mapPoint;var d=f(c),
e={rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0};e.layerView=d;g=c.queryVisibleRasters(g,e).then(function(a){t=t||0<a.length;return a})}else if("csv"===c.type||!r._featureLayersCache[c.id]&&"function"!==typeof c.queryFeatures){if("map-image"===c.type||"wms"===c.type)return d=f(c),d.getPopupData(q);var e=[],h;"esri.core.Collection\x3cesri.Graphic\x3e"===c.declaredClass?(d=c,h=!0):"graphics"===c.type?(d=c.graphics,h=!0):(d=(d=f(c))&&d.loadedGraphics,h=!1);d&&(e=d.filter(function(a){return a&&
(!h||a.popupTemplate)&&a.visible&&q.intersects(a.geometry)}).toArray());0<e.length&&(t=!0,g="scene"===c.type?r._fetchSceneAttributes(c,e):z.resolve(e))}else d=c.createQuery(),d.geometry=q,g=c.queryFeatures(d).then(function(b){b=b.features;if(a&&a.layer===c&&c.objectIdField){var g=c.objectIdField,d=a.attributes[g];b=b.filter(function(a){return a.attributes[g]!==d})}if(!a&&"function"===typeof f(c).getGraphics3DGraphics){var e=[],h=f(c).getGraphics3DGraphics(),r;for(r in h)e.push(h[r].graphic.attributes[c.objectIdField]);
b=b.filter(function(a){return-1!==e.indexOf(a.attributes[c.objectIdField])})}t=t||0<b.length;return b});return g};if(e&&!a||!e)var p=d.map(n).filter(function(a){return!!a}),u=function(a){return a.reduce(function(a,b){return a.concat(b.items?u(b.items):b)},[])},p=u(p);a&&(a.layer&&"scene"===a.layer.type?p.unshift(this._fetchSceneAttributes(a.layer,[a])):a.popupTemplate&&(n=new A,p.unshift(n.resolve([a]))));l.some(p,function(a){return!a.isFulfilled()})||t?p.length&&y.open({promises:p,location:b.mapPoint}):
r._closePopup()}else r._closePopup()}else r._closePopup()},_fetchSceneAttributes:function(b,a){return this.view.whenLayerView(b).then(function(f){var g=this._getOutFields(b.popupTemplate),x=a.map(function(a){return f.whenGraphicAttributes(a,g).otherwise(function(){return a})});return z.eachAlways(x)}.bind(this)).then(function(a){return a.map(function(a){return a.value})})},_getSubLayerFeatureLayers:function(b,a){var f=a||new A,g=[];a=b.length;var x=Math.floor(this.view.extent.width/this.view.width),
h=this.view.scale,y=!1,r=this,d=0;a:for(;d<a;d++){var e=b[d],p=e.dynamicLayerInfos||e.layerInfos;if(p){var t=null;e._params&&(e._params.layers||e._params.dynamicLayers)&&(t=e.visibleLayers);for(var t=E._getVisibleLayers(p,t),v=E._getLayersForScale(h,p),n=p.length,w=0;w<n;w++){var k=p[w],q=k.id,u=e.popupTemplates[q];if(!k.subLayerIds&&u&&u.popupTemplate&&-1<l.indexOf(t,q)&&-1<l.indexOf(v,q)){if(!B){y=!0;break a}var c=e.id+"_"+q,m=this._featureLayersCache[c];m&&m.loadError||(m||((m=u.layerUrl)||(m=
k.source?this._getLayerUrl(e.url,"/dynamicLayer"):this._getLayerUrl(e.url,q)),m=new B(m,{id:c,drawMode:!1,mode:B.MODE_SELECTION,outFields:this._getOutFields(u.popupTemplate),resourceInfo:u.resourceInfo,source:k.source}),this._featureLayersCache[c]=m),m.setDefinitionExpression(e.layerDefinitions&&e.layerDefinitions[q]),m.setGDBVersion(e.gdbVersion),m.popupTemplate=u.popupTemplate,m.setMaxAllowableOffset(x),m.setUseMapTime(!!e.useMapTime),e.layerDrawingOptions&&e.layerDrawingOptions[q]&&e.layerDrawingOptions[q].renderer&&
m.setRenderer(e.layerDrawingOptions[q].renderer),g.push(m))}}}}if(y){var z=new A;H(["../layers/FeatureLayer"],function(a){B=a;z.resolve()});z.then(function(){r._getSubLayerFeatureLayers(b,f)})}else{var C=[];l.forEach(g,function(a){if(!a.loaded){var b=new A;D.once(a,"load, error",function(){b.resolve()});C.push(b.promise)}});C.length?I(C).then(function(){g=l.filter(g,function(a){return!a.loadError&&a.isVisibleAtScale(h)});f.resolve(g)}):(g=l.filter(g,function(a){return a.isVisibleAtScale(h)}),f.resolve(g))}return f.promise},
_getLayerUrl:function(b,a){var f=b.indexOf("?");return-1===f?b+"/"+a:b.substring(0,f)+"/"+a+b.substring(f)},_getOutFields:function(b){var a=["*"];if("esri.PopupTemplate"===b.declaredClass){var f=null==b.content||Array.isArray(b.content)&&b.content.every(function(a){return"attachments"===a.type||"fields"===a.type&&null==a.fieldInfos||"text"===a.type&&-1===a.text.indexOf("{")});b.fieldInfos&&!b.expressionInfos&&f&&(a=[],l.forEach(b.fieldInfos,function(b){var f=b.fieldName&&b.fieldName.toLowerCase();
f&&"shape"!==f&&0!==f.indexOf("relationships/")&&a.push(b.fieldName)}))}return a},_calculateClickTolerance:function(b){var a=6;l.forEach(b,function(b){if(b=b.renderer)"simple"===b.type?((b=b.symbol)&&b.xoffset&&(a=Math.max(a,Math.abs(b.xoffset))),b&&b.yoffset&&(a=Math.max(a,Math.abs(b.yoffset)))):"unique-value"!==b.type&&"class-breaks"!==b.type||l.forEach(b.uniqueValueInfos||b.classBreakInfos,function(b){(b=b.symbol)&&b.xoffset&&(a=Math.max(a,Math.abs(b.xoffset)));b&&b.yoffset&&(a=Math.max(a,Math.abs(b.yoffset)))})});
return a},_clickHandler:function(b){function a(a){return f.allLayerViews.find(function(b){return b.layer===a})}var f=this.view,g=b.screenPoint,l=this;if(0===b.button&&f.popup&&f.ready){var h="3d"===f.type,y=f.map.allLayers.some(function(b){if(b.isInstanceOf(G))return!1;var d;null==b?d=!1:(d=a(b),d=null==d?!1:b.loaded&&!d.suspended&&(b.popupEnabled&&b.popupTemplate||"graphics"===b.type||d.getPopupData));d&&!(d=!h)&&(d=(b=a(b))&&b.hasDraped);return d?!0:!1});null!=g?this.view.hitTest(g.x,g.y).then(function(a){y||
0<a.results.length?l._showPopup(b,0<a.results.length?a.results[0].graphic:null):l._closePopup()}):l._showPopup(b)}}})});