// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/tsSupport/paramHelper ../core/accessorSupport/decorators dojo/_base/lang ../request ./Task ./support/FeatureSet ./support/Query ../geometry/Extent ../geometry/support/normalizeUtils".split(" "),function(w,x,r,g,l,f,e,h,t,p,m,u,n){return function(q){function d(a){a=q.call(this,a)||this;a.gdbVersion=null;a.source=null;return a}r(d,q);d.prototype.execute=function(a,d){var c=this;return n.normalizeCentralMeridian(a.geometry?
[a.geometry]:[]).then(function(b){b=c._encode(e.mixin({},c.parsedUrl.query,{f:"json"},a.toJSON({geometry:b&&b[0]})));if(c.source){var v={source:c.source.toJSON()};b.layer=JSON.stringify(v)}c.gdbVersion&&(b.gdbVersion=c.gdbVersion);b={query:b,callbackParamName:"callback"};if(c.requestOptions||d)b=e.mixin({},c.requestOptions,d,b);return h(c.parsedUrl.path+"/query",b)}).then(function(b){return a.returnJSON?b.data:c._handleExecuteResponse(b)})};d.prototype.executeRelationshipQuery=function(a,d){a=this._encode(e.mixin({},
this.parsedUrl.query,{f:"json"},a.toJSON()));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);a={query:a,callbackParamName:"callback"};if(this.requestOptions||d)a=e.mixin({},this.requestOptions,d,a);return h(this.parsedUrl.path+"/queryRelatedRecords",a).then(this._handleExecuteRelationshipQueryResponse)};d.prototype.executeForIds=function(a,d){var c=this;return n.normalizeCentralMeridian(a.geometry?[a.geometry]:[]).then(function(b){b=c._encode(e.mixin({},c.parsedUrl.query,{f:"json",returnIdsOnly:!0},
a.toJSON({geometry:b&&b[0]})));if(c.source){var k={source:c.source.toJSON()};b.layer=JSON.stringify(k)}c.gdbVersion&&(b.gdbVersion=c.gdbVersion);b={query:b,callbackParamName:"callback"};if(c.requestOptions||d)b=e.mixin({},c.requestOptions,d,b);return h(c.parsedUrl.path+"/query",b)}).then(this._handleExecuteForIdsResponse)};d.prototype.executeForCount=function(a,d){var c=this;return n.normalizeCentralMeridian(a.geometry?[a.geometry]:[]).then(function(b){b=c._encode(e.mixin({},c.parsedUrl.query,{f:"json",
returnIdsOnly:!0,returnCountOnly:!0},a.toJSON({geometry:b&&b[0]})));if(c.source){var k={source:c.source.toJSON()};b.layer=JSON.stringify(k)}c.gdbVersion&&(b.gdbVersion=c.gdbVersion);b={query:b,callbackParamName:"callback"};if(c.requestOptions||d)b=e.mixin({},c.requestOptions,d,b);return h(c.parsedUrl.path+"/query",b)}).then(this._handleExecuteForCountResponse)};d.prototype.executeForExtent=function(a,d){var c=this;return n.normalizeCentralMeridian(a.geometry?[a.geometry]:[]).then(function(b){b=c._encode(e.mixin({},
c.parsedUrl.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},a.toJSON({geometry:b&&b[0]})));if(c.source){var k={source:c.source.toJSON()};b.layer=JSON.stringify(k)}c.gdbVersion&&(b.gdbVersion=c.gdbVersion);b={query:b,callbackParamName:"callback"};if(c.requestOptions||d)b=e.mixin({},c.requestOptions,d,b);return h(c.parsedUrl.path+"/query",b)}).then(this._handleExecuteForExtentResponse)};d.prototype._handleExecuteResponse=function(a){return p.fromJSON(a.data)};d.prototype._handleExecuteRelationshipQueryResponse=
function(a){a=a.data;var d=a.geometryType,c=a.spatialReference,b={};a.relatedRecordGroups.forEach(function(a){var e=p.fromJSON({geometryType:d,spatialReference:c,features:a.relatedRecords});if(null!=a.objectId)b[a.objectId]=e;else for(var f in a)a.hasOwnProperty(f)&&"relatedRecords"!==f&&(b[a[f]]=e)});return b};d.prototype._handleExecuteForIdsResponse=function(a){return a.data.objectIds};d.prototype._handleExecuteForCountResponse=function(a){a=a.data;var d=a.features,c=a.objectIds;if(c)a=c.length;
else{if(d)throw Error("Unable to perform query. Please check your parameters.");a=a.count}return a};d.prototype._handleExecuteForExtentResponse=function(a){a=a.data;if(a.hasOwnProperty("extent"))a.extent=u.fromJSON(a.extent);else{if(a.features)throw Error("Layer does not support extent calculation.");if(a.hasOwnProperty("count"))throw Error("Layer does not support extent calculation.");}return a};g([f.property()],d.prototype,"gdbVersion",void 0);g([f.property()],d.prototype,"source",void 0);g([l(0,
f.cast(m))],d.prototype,"execute",null);g([l(0,f.cast(m))],d.prototype,"executeForIds",null);g([l(0,f.cast(m))],d.prototype,"executeForCount",null);g([l(0,f.cast(m))],d.prototype,"executeForExtent",null);return d=g([f.subclass("esri.tasks.QueryTask")],d)}(f.declared(t))});