// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/ObjectPool ../../../core/HandleRegistry ./LayerView2D ../engine/Bitmap ../engine/BitmapSource ../engine/BitmapContainer ../engine/Canvas2DContainer ../engine/Tiled ../../../geometry/support/webMercatorUtils ../tiling/TileStrategy ../tiling/TileKey ../tiling/TileInfoView ../tiling/TileQueue ../../layers/RefreshableLayerView".split(" "),function(D,
E,h,k,g,l,m,n,p,q,r,t,u,v,w,x,y,z,A){var B=function(e){function c(a){a=e.call(this,a)||this;a.key=new x(0,0,0,0);return a}h(c,e);c.prototype.acquire=function(a){};c.prototype.release=function(){this.key.set(0,0,0,0)};c.pool=new l(c,!0);return c}(u(p)),C=[102113,102100,3857,3785,900913];return function(e){function c(){var a=null!==e&&e.apply(this,arguments)||this;a._handles=new m;a._tileStrategy=null;a._tileInfoView=null;a._fetchQueue=null;a._tileRequests=new Map;a.container=new t;a.layer=null;return a}
h(c,e);c.prototype.hitTest=function(a,b){return null};c.prototype.update=function(a){this._fetchQueue.pause();this._fetchQueue.state=a.state;this._tileStrategy.update(a);this._fetchQueue.resume();this.notifyChange("updating")};c.prototype.attach=function(){var a=this,b=this.layer.activeLayer,d;b.tileMatrixSetId?d=b.tileMatrixSet:(d=this._getTileMatrixSetBySpatialReference(b),b.tileMatrixSetId=d.id);var c=d.tileInfo.spatialReference,f=b.fullExtent&&b.fullExtent.clone();c.isWebMercator?f=v.geographicToWebMercator(f):
c.isWGS84||(f=d.fullExtent);this._tileContainer=new r;this.container.addChild(this._tileContainer);this._tileInfoView=new y(d.tileInfo,f);this._fetchQueue=new z({tileInfoView:this._tileInfoView,process:function(b){return a.fetchTile(b)}});this._tileStrategy=new w({cachePolicy:"keep",acquireTile:function(b){return a.acquireTile(b)},releaseTile:function(b){return a.releaseTile(b)},tileInfoView:this._tileInfoView});this._handles.add(b.watch("styleId",function(b){a.refresh()}));this._handles.add(this.layer.watch("activeLayer",
function(b){if(!b.tileMatrixSetId){var d=a._getTileMatrixSetBySpatialReference(a.layer.activeLayer);b.tileMatrixSetId=d.id}a.refresh()}))};c.prototype.detach=function(){this._handles.removeAll();this._tileStrategy.destroy();this._fetchQueue.clear();this.container.removeChild(this._tileContainer);this._fetchQueue=this._tileStrategy=this._tileInfoView=this._tileContainer=null};c.prototype.moveStart=function(){this.requestUpdate()};c.prototype.viewChange=function(){this.requestUpdate()};c.prototype.moveEnd=
function(){this.requestUpdate()};c.prototype.refresh=function(){var a=this;this._fetchQueue.reset();this._tileStrategy.tiles.forEach(function(b){if(b.source){b.source=null;var d=a._fetchQueue.push(b.key).then(function(a){b.source=a;b.requestRender()});a._tileRequests.set(b,d)}})};c.prototype.getTileBounds=function(a,b){return this._tileStrategy.tileInfoView.getTileBounds(a,b)};c.prototype.getTileCoords=function(a,b){return this._tileStrategy.tileInfoView.getTileCoords(a,b)};c.prototype.getTileResolution=
function(a){return this._tileStrategy.tileInfoView.getTileResolution(a)};c.prototype.acquireTile=function(a){var b=this,d=B.pool.acquire();d.key.set(a);this._tileInfoView.getTileCoords(d.coords,d.key);d.resolution=this._tileInfoView.getTileResolution(d.key);a=this._tileInfoView.tileInfo.size;d.width=a[0];d.height=a[1];a=this._fetchQueue.push(d.key).then(function(a){d.source=a;d.once("attach",function(){return b.requestUpdate()});b._tileContainer.addChild(d)});this._tileRequests.set(d,a);this.requestUpdate();
return d};c.prototype.releaseTile=function(a){var b=this._tileRequests.get(a);b.isFulfilled()||b.cancel();this._tileRequests.delete(a);this._tileContainer.removeChild(a);this.requestUpdate()};c.prototype.fetchTile=function(a){var b=this;return this.layer.fetchTile(a.level,a.row,a.col).then(function(d){d=q.pool.acquire(d);d.coords=b.getTileCoords(d.coords,a);d.resolution=b.getTileResolution(a);return d})};c.prototype._getTileMatrixSetBySpatialReference=function(a){var b=this.view.spatialReference,
d=b.wkid,c=a.tileMatrixSets.find(function(a){return a.tileInfo.spatialReference.wkid===d});!c&&b.isWebMercator&&(c=a.tileMatrixSets.find(function(a){return-1<C.indexOf(a.tileInfo.spatialReference.wkid)}));return c};k([g.property({dependsOn:["updateRequested","attached"]})],c.prototype,"updating",void 0);return c=k([g.subclass("esri.views.2d.layers.WMTSLayerView2D")],c)}(g.declared(n,A))});