// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
require({cache:{"esri/portal/support/jsonContext":function(){define(["require","exports","../Portal","../../core/urlUtils"],function(h,f,d,b){Object.defineProperty(f,"__esModule",{value:!0});f.createForItem=function(e){return{origin:"portal-item",url:b.urlToObject(e.itemUrl),portal:e.portal||d.getDefault()}}})},"esri/layers/support/vectorTileLayerLoader":function(){define("require exports dojo/has dojo/_base/lang ../../core/promiseUtils ../../core/urlUtils ../../config ../../request".split(" "),function(h,
f,d,b,e,a,c,u){function k(b){if(b){var c=a.getOrigin(b);a.canUseXhr(c)||-1!==m.indexOf(c)||m.push(c);return b}}function q(b,c,e){if(null!=c.sources){e&&-1!==e.path.indexOf("root.json")&&(e.path=e.path.substr(0,e.path.indexOf("root.json")),b.styleUrl=e.path);var d=l(c,e),k=c.sprite||null,p=c.glyphs||null;d&&d.url&&(d=e&&e.path?e.path:d.url,c.sprite&&!a.isAbsolute(c.sprite)&&(k=a.normalize(a.join(d,c.sprite))),c.glyphs&&!a.isAbsolute(c.glyphs)&&(p=a.normalize(a.join(d,c.glyphs))));b.style=c;b.spriteUrl=
k;b.glyphsUrl=p;return r(b,c,e)}if(c.hasOwnProperty("tileInfo"))return b.layerDefinition=c,b.serviceUrl=e.path,t(b,c,e)}function t(c,b,e){b=b.defaultStyles;a.isAbsolute(b)?c.styleUrl=a.normalize(b):c.styleUrl=a.normalize(a.join(e.path,b));k(c.styleUrl);return u(a.join(c.styleUrl,"root.json"),{responseType:"json"}).then(function(b){var e=b.data.sprite||null,d=b.data.glyphs||null;e&&!a.isAbsolute(e)&&(e=a.normalize(a.join(c.styleUrl,e)));d&&!a.isAbsolute(d)&&(d=a.normalize(a.join(c.styleUrl,d)));c.spriteUrl=
e;c.glyphsUrl=d;return c.style=b.data})}function r(c,b,d){(b=l(b,d))||e.reject("Source isn't available in the syle object!");if(b.url)return c.serviceUrl=b.url,a.isAbsolute(c.serviceUrl)||(c.serviceUrl=a.join(d.path,c.serviceUrl)),k(c.serviceUrl),u(c.serviceUrl,{query:{f:"json"},responseType:"json"}).then(function(a){c.layerDefinition=n(a.data);return c});c.layerDefinition=n(b);return e.resolve(c)}function l(c,b){if(!c.sources)return null;var e=c.sources;c=null;if(e.esri)c=e.esri,b&&c.url&&!a.isAbsolute(c.url)&&
(e=b.path.substring(0,b.path.lastIndexOf("/")),c.url=a.join(e,c.url));else{for(var d=0,k=Object.keys(e);d<k.length;d++)if(b=k[d],-1!==b.toLocaleLowerCase().indexOf("street")&&"vector"===c.type){c=e[b];break}if(!c)for(d=0,k=Object.keys(e);d<k.length&&(b=k[d],c=e[b],"vector"!==c.type);d++);}return c}function n(a){if(a.hasOwnProperty("tileInfo"))return a;for(var c={xmin:-2.0037507067161843E7,ymin:-2.0037507067161843E7,xmax:2.0037507067161843E7,ymax:2.0037507067161843E7,spatialReference:{wkid:102100}},
b=(c.xmax-c.xmin)/512,e=[],d=a.hasOwnProperty("minzoom")?parseFloat(a.minzoom):0,q=a.hasOwnProperty("maxzoom")?parseFloat(a.maxzoom):16;d<q;d++){var u=b/Math.pow(2,d);e.push({level:d,scale:Math.floor(3779.527559055118*u),resolution:u})}a.tiles.forEach(k);return{capabilities:"TilesOnly",initialExtent:c,fullExtent:c,minScale:e[0].scale,maxScale:e[e.length-1].scale,tiles:a.tiles,tileInfo:{rows:512,cols:512,dpi:96,format:"pbf",origin:{x:-2.0037508342787E7,y:2.0037508342787E7},lods:e,spatialReference:{wkid:102100}}}}
Object.defineProperty(f,"__esModule",{value:!0});var m=c.defaults&&c.defaults.io.corsEnabledServers||c.request.corsEnabledServers;f.loadMetadata=function(c){if(!c)return e.reject("invalid input URL!");var d={layerDefinition:null,parsedUrl:null,serviceUrl:null,style:null,styleUrl:null,url:null,spriteUrl:null,glyphsUrl:null};if("string"!==typeof c)return q(d,c,null).then(function(){return d});c=d.url=a.normalize(c);var f=d.parsedUrl=a.urlToObject(c);k(c);return u(f.path,{responseType:"json",query:b.mixin({f:"json"},
f.query)}).then(function(c){return q(d,c.data,f)}).then(function(){return d})}})},"esri/views/vectorTiles/style/StyleRepository":function(){define(["require","exports","./StyleLayer","dojo/has"],function(h,f,d,b){return function(){function e(a,c){this.styleJSON=a;this.version=parseFloat(a.version);this.sprite=c?c.spriteUrl:a.sprite;this.glyphs=c?c.glyphsUrl:a.glyphs;if(b("stable-symbol-rendering")){var d=(a.layers||[]).filter(function(c){return c.layout&&c.layout["text-font"]})[0];d&&(a.layers||[]).forEach(function(c){c.layout&&
c.layout["text-font"]&&(c.layout["text-font"]=d.layout["text-font"])})}this.layers=(a.layers||[]).map(e._create);this._identifyRefLayers()}e.prototype._identifyRefLayers=function(){for(var a=[],c=[],b=0,e=this.layers;b<e.length;b++){var d=e[b];if(1===d.type){var f=d.sourceLayer,f=f+("|"+JSON.stringify(d.minzoom)),f=f+("|"+JSON.stringify(d.maxzoom)),f=f+("|"+JSON.stringify(d.filter));a.push({key:f,layer:d})}2===d.type&&(f=d.sourceLayer,f+="|"+JSON.stringify(d.minzoom),f+="|"+JSON.stringify(d.maxzoom),
f+="|"+JSON.stringify(d.filter),f+="|"+JSON.stringify(d.layout&&d.layout["line-cap"]),f+="|"+JSON.stringify(d.layout&&d.layout["line-join"]),c.push({key:f,layer:d}))}this._assignRefLayers(a);this._assignRefLayers(c)};e.prototype._assignRefLayers=function(a){a.sort(function(c,a){return c.key<a.key?-1:c.key>a.key?1:0});for(var c,b,d=a.length,e=0;e<d;e++){var f=a[e];if(f.key===c)f.layer.refLayerId=b;else if(c=f.key,b=f.layer.id,1===f.layer.type&&!f.layer.hasPaintProperty("fill-outline-color"))for(var h=
e+1;h<d;h++){var l=a[h];if(l.key===c){if(l.layer.hasPaintProperty("fill-outline-color")){a[e]=l;a[h]=f;b=l.layer.id;break}}else break}}};e._create=function(a,c,b){c=1-1/(b.length+1)*(1+c);switch(a.type){case "background":return new d.StyleLayer(0,a,c);case "fill":return new d.StyleLayer(1,a,c);case "line":return new d.StyleLayer(2,a,c);case "symbol":return new d.StyleLayer(3,a,c);case "raster":throw Error("Unsupported vector tile raster layer");case "circle":throw Error("Unsupported vector tile circle layer");
}throw Error("Unknown vector tile layer");};return e}()})},"esri/views/vectorTiles/style/StyleLayer":function(){define(["require","exports","./StyleDefinition","./StyleProperty","./Filter"],function(h,f,d,b,e){Object.defineProperty(f,"__esModule",{value:!0});h=function(){function a(c,a,b){this.type=c;this.id=a.id;this.source=a.source;this.sourceLayer=a["source-layer"];this.minzoom=a.minzoom;this.maxzoom=a.maxzoom;this.filter=a.filter;this.layout=a.layout;this.paint=a.paint;this.z=b;switch(c){case 0:this._layoutDefinition=
d.StyleDefinition.backgroundLayoutDefinition;this._paintDefinition=d.StyleDefinition.backgroundPaintDefinition;break;case 1:this._layoutDefinition=d.StyleDefinition.fillLayoutDefinition;this._paintDefinition=d.StyleDefinition.fillPaintDefinition;break;case 2:this._layoutDefinition=d.StyleDefinition.lineLayoutDefinition;this._paintDefinition=d.StyleDefinition.linePaintDefinition;break;case 3:this._layoutDefinition=d.StyleDefinition.symbolLayoutDefinition,this._paintDefinition=d.StyleDefinition.symbolPaintDefinition}this._layoutProperties=
this._parseLayout(this.layout);this._paintProperties=this._parsePaint(this.paint)}a.prototype.getFeatureFilter=function(){return void 0!==this._featureFilter?this._featureFilter:this._featureFilter=e.createFilter(this.filter)};a.prototype.hasLayoutProperty=function(c){var a=this._layoutProperties;return a&&a[c]?!0:!1};a.prototype.hasPaintProperty=function(a){var c=this._paintProperties;return c?void 0!==c[a]:!1};a.prototype.getLayoutValue=function(a,b){var c,d=this._layoutProperties;d&&(d=d[a])&&
(c=d.getValue(b));a=this._layoutDefinition[a];void 0===c&&(c=a["default"]);"enum"===a.type&&(c=a.values.indexOf(c));return c};a.prototype.getPaintValue=function(a,b){var c,d=this._paintProperties;d&&(d=d[a])&&(c=d.getValue(b));a=this._paintDefinition[a];void 0===c&&(c=a["default"]);"enum"===a.type&&(c=a.values.indexOf(c));return c};a.prototype._parseLayout=function(a){var c={},d;for(d in a)c[d]=new b(this._layoutDefinition[d],a[d]);return c};a.prototype._parsePaint=function(a){var c={},d;for(d in a)c[d]=
new b(this._paintDefinition[d],a[d]);return c};return a}();f.StyleLayer=h;h=function(){return function(a,c){this.cap=a.getLayoutValue("line-cap",c);this.join=a.getLayoutValue("line-join",c);this.miterLimit=a.getLayoutValue("line-miter-limit",c);this.roundLimit=a.getLayoutValue("line-round-limit",c)}}();f.LineLayout=h;h=function(){return function(a,c,b){this.allowOverlap=a.getLayoutValue("icon-allow-overlap",c);this.ignorePlacement=a.getLayoutValue("icon-ignore-placement",c);this.optional=a.getLayoutValue("icon-optional",
c);this.rotationAlignment=a.getLayoutValue("icon-rotation-alignment",c);this.size=a.getLayoutValue("icon-size",c);this.rotate=a.getLayoutValue("icon-rotate",c);this.padding=a.getLayoutValue("icon-padding",c);this.keepUpright=a.getLayoutValue("icon-keep-upright",c);this.offset=a.getLayoutValue("icon-offset",c);2===this.rotationAlignment&&(this.rotationAlignment=b?0:1)}}();f.IconLayout=h;h=function(){return function(a,c,b){this.allowOverlap=a.getLayoutValue("text-allow-overlap",c);this.ignorePlacement=
a.getLayoutValue("text-ignore-placement",c);this.optional=a.getLayoutValue("text-optional",c);this.rotationAlignment=a.getLayoutValue("text-rotation-alignment",c);this.font=a.getLayoutValue("text-font",c);this.maxWidth=a.getLayoutValue("text-max-width",c);this.lineHeight=a.getLayoutValue("text-line-height",c);this.letterSpacing=a.getLayoutValue("text-letter-spacing",c);this.justify=a.getLayoutValue("text-justify",c);this.anchor=a.getLayoutValue("text-anchor",c);this.maxAngle=a.getLayoutValue("text-max-angle",
c);this.size=a.getLayoutValue("text-size",c);this.rotate=a.getLayoutValue("text-rotate",c);this.padding=a.getLayoutValue("text-padding",c);this.keepUpright=a.getLayoutValue("text-keep-upright",c);this.transform=a.getLayoutValue("text-transform",c);this.offset=a.getLayoutValue("text-offset",c);2===this.rotationAlignment&&(this.rotationAlignment=b?0:1)}}();f.TextLayout=h})},"esri/views/vectorTiles/style/StyleDefinition":function(){define(["require","exports"],function(h,f){Object.defineProperty(f,"__esModule",
{value:!0});h=function(){function d(){}d.backgroundLayoutDefinition={visibility:{type:"enum",values:["visible","none"],"default":"visible"}};d.fillLayoutDefinition={visibility:{type:"enum",values:["visible","none"],"default":"visible"}};d.lineLayoutDefinition={visibility:{type:"enum",values:["visible","none"],"default":"visible"},"line-cap":{type:"enum",values:["butt","round","square"],"default":"butt"},"line-join":{type:"enum",values:["bevel","round","miter"],"default":"miter"},"line-miter-limit":{type:"number",
"default":2},"line-round-limit":{type:"number","default":1.05}};d.symbolLayoutDefinition={visibility:{type:"enum",values:["visible","none"],"default":"visible"},"symbol-placement":{type:"enum",values:["point","line"],"default":"point"},"symbol-spacing":{type:"number",minimum:1,"default":250},"symbol-avoid-edges":{type:"boolean","default":!1},"icon-image":{type:"string"},"icon-allow-overlap":{type:"boolean","default":!1},"icon-ignore-placement":{type:"boolean","default":!1},"icon-optional":{type:"boolean",
"default":!1},"icon-rotation-alignment":{type:"enum",values:["map","viewport","auto"],"default":"auto"},"icon-size":{type:"number",minimum:0,"default":1},"icon-rotate":{type:"number","default":0},"icon-padding":{type:"number",minimum:0,"default":2},"icon-keep-upright":{type:"boolean","default":!1},"icon-offset":{type:"array",value:"number",length:2,"default":[0,0]},"text-field":{type:"string"},"text-rotation-alignment":{type:"enum",values:["map","viewport","auto"],"default":"auto"},"text-font":{type:"array",
value:"string","default":["Open Sans Regular","Arial Unicode MS Regular"]},"text-size":{type:"number",minimum:0,"default":16},"text-max-width":{type:"number",minimum:0,"default":10},"text-line-height":{type:"number","default":1.2},"text-letter-spacing":{type:"number","default":0},"text-justify":{type:"enum",values:["left","center","right"],"default":"center"},"text-anchor":{type:"enum",values:"center left right top bottom top-left top-right bottom-left bottom-right".split(" "),"default":"center"},
"text-max-angle":{type:"number",minimum:0,"default":45},"text-rotate":{type:"number","default":0},"text-padding":{type:"number",minimum:0,"default":2},"text-keep-upright":{type:"boolean","default":!0},"text-transform":{type:"enum",values:["none","uppercase","lowercase"],"default":"none"},"text-offset":{type:"array",value:"number",length:2,"default":[0,0]},"text-allow-overlap":{type:"boolean","default":!1},"text-ignore-placement":{type:"boolean","default":!1},"text-optional":{type:"boolean","default":!1}};
d.backgroundPaintDefinition={"background-opacity":{type:"number",minimum:0,maximum:1,"default":1},"background-color":{type:"color","default":[0,0,0,1]},"background-pattern":{type:"string"}};d.fillPaintDefinition={"fill-opacity":{type:"number",minimum:0,maximum:1,"default":1},"fill-antialias":{type:"boolean","default":!0},"fill-color":{type:"color","default":[0,0,0,1]},"fill-outline-color":{type:"color","default":[0,0,0,0]},"fill-translate":{type:"array",value:"number",length:2,"default":[0,0]},"fill-translate-anchor":{type:"enum",
values:["map","viewport"],"default":"map"},"fill-pattern":{type:"string"}};d.linePaintDefinition={"line-opacity":{type:"number",minimum:0,maximum:1,"default":1},"line-color":{type:"color","default":[0,0,0,1]},"line-translate":{type:"array",value:"number",length:2,"default":[0,0]},"line-translate-anchor":{type:"enum",values:["map","viewport"],"default":"map"},"line-width":{type:"number",minimum:0,"default":1},"line-gap-width":{type:"number",minimum:0,"default":0},"line-offset":{type:"number","default":0},
"line-blur":{type:"number",minimum:0,"default":0},"line-dasharray":{type:"array",value:"number","default":[]},"line-pattern":{type:"string"}};d.symbolPaintDefinition={"icon-opacity":{type:"number",minimum:0,maximum:1,"default":1},"icon-color":{type:"color","default":[0,0,0,1]},"icon-halo-color":{type:"color","default":[0,0,0,0]},"icon-halo-width":{type:"number",minimum:0,"default":0},"icon-halo-blur":{type:"number",minimum:0,"default":0},"icon-translate":{type:"array",value:"number",length:2,"default":[0,
0]},"icon-translate-anchor":{type:"enum",values:["map","viewport"],"default":"map"},"text-opacity":{type:"number",minimum:0,maximum:1,"default":1},"text-color":{type:"color","default":[0,0,0,1]},"text-halo-color":{type:"color","default":[0,0,0,0]},"text-halo-width":{type:"number",minimum:0,"default":0},"text-halo-blur":{type:"number",minimum:0,"default":0},"text-translate":{type:"array",value:"number",length:2,"default":[0,0]},"text-translate-anchor":{type:"enum",values:["map","viewport"],"default":"map"}};
d.rasterPaintDefinition={"raster-opacity":{type:"number",minimum:0,maximum:1,"default":1},"raster-hue-rotate":{type:"number","default":0},"raster-brightness-min":{type:"number",minimum:0,maximum:1,"default":0},"raster-brightness-max":{type:"number",minimum:0,maximum:1,"default":1},"raster-saturation":{type:"number",minimum:-1,maximum:1,"default":0},"raster-contrast":{type:"number",minimum:-1,maximum:1,"default":0},"raster-fade-duration":{type:"number",minimum:0,"default":300}};d.circlePaintDefinition=
{"circle-opacity":{type:"number",minimum:0,maximum:1,"default":1},"circle-radius":{type:"number",minimum:0,"default":5},"circle-color":{type:"color","default":[0,0,0,1]},"circle-blur":{type:"number",minimum:0,"default":0},"circle-translate":{type:"array",value:"number",length:2,"default":[0,0]},"circle-translate-anchor":{type:"enum",values:["map","viewport"],"default":"map"}};return d}();f.StyleDefinition=h})},"esri/views/vectorTiles/style/StyleProperty":function(){define(["require","exports","../../../Color",
"../GeometryUtils"],function(h,f,d,b){return function(){function e(a,c){switch(a.type){case "number":a=!0;break;case "color":a=!0;c=e._parseColor(c);break;case "array":a="number"===a.value;break;default:a=!1}this.getValue=a?this._interpolate(c):this._piecewise(c)}e.prototype._piecewise=function(a){var c=a.stops;return c?function(a){var b=c.length;if(0!==b){for(var d=0,e=0;e<b;e++)if(c[e][0]<=a)d=e;else break;return c[d][1]}}:function(){return a}};e.prototype._interpolate=function(a){var c=a.stops;
if(c){var d=a.base||1;return function(a){for(var e,f,k=c.length,l=0;l<k;l++){var h=c[l];if(h[0]<=a)e=h;else{f=h;break}}if(e&&f){l=f[0]-e[0];a-=e[0];a=1===d?a/l:(Math.pow(d,a)-1)/(Math.pow(d,l)-1);if(Array.isArray(e[1])){e=e[1];f=f[1];k=[];for(l=0;l<e.length;l++)k.push(b.interpolate(e[l],f[l],a));return k}return b.interpolate(e[1],f[1],a)}if(e)return e[1];if(f)return f[1]}}return function(){return a}};e._parseColor=function(a){if(Array.isArray(a))return a;if("string"===typeof a)return a=new d(a),d.toUnitRGBA(a);
if(a&&a.stops)return a.stops=a.stops.map(function(a){return[a[0],e._parseColor(a[1])]}),a;throw Error("Incorrect color definition "+a);};return e}()})},"esri/views/vectorTiles/GeometryUtils":function(){define(["require","exports"],function(h,f){function d(b,a){b%=a;return 0<=b?b:b+a}Object.defineProperty(f,"__esModule",{value:!0});f.C_INFINITY=Number.POSITIVE_INFINITY;f.C_PI=Math.PI;f.C_2PI=2*f.C_PI;f.C_PI_BY_2=f.C_PI/2;f.C_RAD_TO_256=128/f.C_PI;f.C_256_TO_RAD=f.C_PI/128;f.C_DEG_TO_256=256/360;f.C_DEG_TO_RAD=
f.C_PI/180;f.C_SQRT2=1.414213562;f.C_SQRT2_INV=1/f.C_SQRT2;var b=1/Math.LN2;f.positiveMod=d;f.radToByte=function(b){return d(b*f.C_RAD_TO_256,256)};f.degToByte=function(b){return d(b*f.C_DEG_TO_256,256)};f.log2=function(d){return Math.log(d)*b};f.sqr=function(b){return b*b};f.clamp=function(b,a,c){return Math.min(Math.max(b,a),c)};f.interpolate=function(b,a,c){return b*(1-c)+a*c};f.between=function(b,a,c){return b>=a&&b<=c||b>=c&&b<=a}})},"esri/views/vectorTiles/style/Filter":function(){define(["require",
"exports"],function(h,f){return function(){function d(b,e,a){this._op=b;"$type"===e?(this._val=a instanceof Array?a.map(function(a){return d._types.indexOf(a)}):d._types.indexOf(a),this._op+=11):(this._key=e,this._val=a)}d.prototype.filter=function(b){switch(this._op){case 0:return this._val;case 1:return b.values[this._key]===this._val;case 2:return b.values[this._key]!==this._val;case 3:return b.values[this._key]<this._val;case 4:return b.values[this._key]>this._val;case 5:return b.values[this._key]<=
this._val;case 6:return b.values[this._key]>=this._val;case 7:return-1!==this._val.indexOf(b.values[this._key]);case 8:return-1===this._val.indexOf(b.values[this._key]);case 9:for(var d=0,a=this._val;d<a.length;d++){var c=a[d];if(c.filter(b))return!0}return!1;case 10:d=0;for(a=this._val;d<a.length;d++)if(c=a[d],!c.filter(b))return!1;return!0;case 11:d=0;for(a=this._val;d<a.length;d++)if(c=a[d],c.filter(b))return!1;return!0;case 12:return b.type===this._val;case 13:return b.type!==this._val;case 14:return b.type<
this._val;case 15:return b.type>this._val;case 16:return b.type>=this._val;case 17:return b.type<=this._val;case 18:return-1!==this._val.indexOf(b.type);case 19:return-1===this._val.indexOf(b.type)}};d.createFilter=function(b){if(!b)return new d(0,void 0,!0);var e=b[0];if(1>=b.length)return new d(0,void 0,"any"!==e);switch(e){case "\x3d\x3d":return new d(1,b[1],b[2]);case "!\x3d":return new d(2,b[1],b[2]);case "\x3e":return new d(4,b[1],b[2]);case "\x3c":return new d(3,b[1],b[2]);case "\x3e\x3d":return new d(6,
b[1],b[2]);case "\x3c\x3d":return new d(5,b[1],b[2]);case "in":return new d(7,b[1],b.slice(2));case "!in":return new d(8,b[1],b.slice(2));case "any":return new d(9,void 0,b.slice(1).map(d.createFilter.bind(this)));case "all":return new d(10,void 0,b.slice(1).map(d.createFilter.bind(this)));case "none":return new d(11,void 0,b.slice(1).map(d.createFilter.bind(this)));default:throw Error("invalid operator: "+e);}};d._types=["Unknown","Point","LineString","Polygon"];return d}()})},"esri/views/vectorTiles/SchemaHelper":function(){define(["require",
"exports"],function(h,f){return function(){function d(b,d){this.lockedSchemaPixelSize=b;this.isWGS84=d}d.prototype.getCompatibleLevelRowCol=function(b){var d=b[0],a=b[1];b=b[2];this.isWGS84?(a>>=1,b>>=1):256===this.lockedSchemaPixelSize&&0<d&&(d--,a>>=1,b>>=1);return[d,a,b]};d.prototype.getSchemaShift=function(b,d){var a=0,c=0;if(256===this.lockedSchemaPixelSize||this.isWGS84)b[2]%2&&(a=2*d),b[1]%2&&(c=2*d);return[a,c]};d.prototype.adjustLevel=function(b){return this.isWGS84?b:256===this.lockedSchemaPixelSize?
0<b?b-1:0:b};d.create256x256CompatibleTileInfo=function(b){if(!b)return null;if(256===b.rows&&256===b.cols)return b;for(var d=b.format,a=b.compressionQuality,c=b.dpi,f=b.origin,k=b.spatialReference,h=4326===k.wkid,t=[],r,l,n=b.lods.length,m=0;m<n;m++){var p=b.lods[m];r=p.scale;l=h?p.resolution:2*p.resolution;t.push({level:p.level,scale:r,resolution:l})}return{rows:256,cols:256,dpi:c,format:d,compressionQuality:a,origin:f,spatialReference:k,lods:t}};d.create512x512CompatibleTileInfo=function(b){if(!b||
256===b.rows||256===b.cols)return null;for(var d=b.format,a=b.compressionQuality,c=b.dpi,f=b.origin,h=b.spatialReference,q=[],t,r,l=b.lods.length,n=0;n<l;n++){var m=b.lods[n];t=m.scale;r=.5*m.resolution;q.push({level:m.level,scale:t,resolution:r})}return{rows:512,cols:512,dpi:c,format:d,compressionQuality:a,origin:f,spatialReference:h,lods:q}};return d}()})},"*noref":1}});
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/_base/lang ../core/accessorSupport/decorators ../core/Error ../core/MultiOriginJSONSupport ../core/urlUtils ../core/promiseUtils ../core/lang ../request ../geometry/Extent ../geometry/SpatialReference ../portal/support/jsonContext ./TiledLayer ./mixins/OperationalLayer ./mixins/PortalLayer ./mixins/ScaleRangeLayer ./mixins/ArcGISCachedService ./support/TileInfo ./support/vectorTileLayerLoader ../views/vectorTiles/style/StyleRepository ../views/vectorTiles/SchemaHelper".split(" "),function(h,
f,d,b,e,a,c,u,k,q,t,r,l,n,m,p,x,y,z,A,v,B,C,w){return function(f){function g(a,b){a=f.call(this)||this;a.currentStyleInfo=null;a.fullExtent=null;a.operationalLayerType="VectorTileLayer";a.tileInfo=null;a.type="vector-tile";a.url=null;return a}d(g,f);g.prototype.normalizeCtorArgs=function(a,b){return"string"===typeof a?e.mixin({},{url:a},b):a};g.prototype.load=function(){var a=this,b=this.loadFromPortal({supportedTypes:["Vector Tile Service"],supportsData:!1}).then(function(){if(a.portalItem&&a.portalItem.id){var b=
a.portalItem.itemUrl+"/resources/styles/root.json";return r(b,{query:{f:"json"}}).then(function(c){c.data&&a.read({url:b},m.createForItem(a.portalItem))})}}).always(function(){return a.loadStyle()});this.addResolvingPromise(b);return this};Object.defineProperty(g.prototype,"attributionDataUrl",{get:function(){var a=this.currentStyleInfo;return(a=a&&a.serviceUrl&&k.urlToObject(a.serviceUrl))?this._getDefaultAttribution(a.path):null},enumerable:!0,configurable:!0});Object.defineProperty(g.prototype,
"serviceUrl",{get:function(){return this.currentStyleInfo&&this.currentStyleInfo.serviceUrl||null},enumerable:!0,configurable:!0});Object.defineProperty(g.prototype,"spatialReference",{get:function(){return this.tileInfo&&this.tileInfo.spatialReference||null},enumerable:!0,configurable:!0});Object.defineProperty(g.prototype,"styleUrl",{get:function(){return this.currentStyleInfo&&this.currentStyleInfo.styleUrl||null},enumerable:!0,configurable:!0});g.prototype.writeStyleUrl=function(a,b){a&&k.isProtocolRelative(a)&&
(a="https:"+a);a&&!t.endsWith(a,"root.json")&&(a=k.join(a,"root.json"));b.styleUrl=a};g.prototype.readTileIndexType=function(a,b){return b.type};g.prototype.readTileIndexUrl=function(a,b){return k.join(this.serviceUrl,b.tileMap)};g.prototype.readTileServers=function(a,b){var c=this;a=b.tiles;this.serviceUrl&&a.forEach(function(a,b,d){d[b]=k.join(c.serviceUrl,a)});return a};g.prototype.readVersion=function(a,b){return b.version?parseFloat(b.version):parseFloat(b.currentVersion)};g.prototype.readCompatibleTileInfo256=
function(a,b){return v.fromJSON(w.create256x256CompatibleTileInfo(b.tileInfo))};g.prototype.readCompatibleTileInfo512=function(a,b){return v.fromJSON(w.create512x512CompatibleTileInfo(b.tileInfo))};g.prototype.loadStyle=function(a){a=a||this.url;if(this._loadingPromise&&"string"===typeof a&&this.url===a)return this._loadingPromise;var b=this._loadingPromise;this._loadingPromise=this._getSourceAndStyle(a);b&&!b.isFulfilled()&&b.cancel();return this._loadingPromise};g.prototype.getTileUrl=function(a,
b,c){var d=this.tileServers[b%this.tileServers.length];return d=d.replace(/\{z\}/gi,a.toString()).replace(/\{y\}/gi,b.toString()).replace(/\{x\}/gi,c.toString())};g.prototype.write=function(a,b){return b&&b.origin&&!this.styleUrl?(b.messages&&b.messages.push(new c("vectortilelayer:unsupported","VectorTileLayer ("+this.title+", "+this.id+") with style defined by JSON only are not supported",{layer:this})),null):this.inherited(arguments,[a,b])};g.prototype._getSourceAndStyle=function(a){var b=this;
return a?B.loadMetadata(a).then(function(a){b._set("currentStyleInfo",{serviceUrl:a.serviceUrl,styleUrl:a.styleUrl,spriteUrl:a.spriteUrl,glyphsUrl:a.glyphsUrl,style:a.style,layerDefinition:a.layerDefinition});b._set("styleRepository",new C(a.style,a));b.read(a.layerDefinition)}):q.reject(Error("invalid style!"))};g.prototype._getDefaultAttribution=function(a){var b=a.match(/^https?:\/\/(basemaps|basemapsbeta)\.arcgis\.com(\/[^\/]+)?\/arcgis\/rest\/services\/([^\/]+(\/[^\/]+)*)\/vectortileserver/i);
if(b&&(a=b[3]&&b[3].toLowerCase()))for(var b=b[2]||"",c=0,d=["World_Basemap","World_Basemap_WGS84"];c<d.length;c++){var e=d[c];if(-1<e.toLowerCase().indexOf(a))return k.normalize("//static.arcgis.com/attribution/Vector"+b+"/"+e)}};b([a.shared({"2d":"../views/2d/layers/VectorTileLayerView2D","3d":"../views/3d/layers/VectorTileLayerView3D"})],g.prototype,"viewModulePaths",void 0);b([a.property({readOnly:!0,dependsOn:["currentStyleInfo"]})],g.prototype,"attributionDataUrl",null);b([a.property({readOnly:!0})],
g.prototype,"currentStyleInfo",void 0);b([a.property({type:l,readOnly:!0})],g.prototype,"fullExtent",void 0);b([a.property({readOnly:!0,dependsOn:["currentStyleInfo"]})],g.prototype,"serviceUrl",null);b([a.property({type:n,dependsOn:["tileInfo"],readOnly:!0})],g.prototype,"spatialReference",null);b([a.property({readOnly:!0})],g.prototype,"styleRepository",void 0);b([a.property({readOnly:!0,dependsOn:["currentStyleInfo"],json:{write:{ignoreOrigin:!0}}})],g.prototype,"styleUrl",null);b([a.writer("styleUrl")],
g.prototype,"writeStyleUrl",null);b([a.property({readOnly:!0})],g.prototype,"tileIndexType",void 0);b([a.reader("tileIndexType",["tileIndexType","type"])],g.prototype,"readTileIndexType",null);b([a.property({readOnly:!0})],g.prototype,"tileIndexUrl",void 0);b([a.reader("tileIndexUrl",["tileIndexUrl","tileMap"])],g.prototype,"readTileIndexUrl",null);b([a.property({readOnly:!0,type:v})],g.prototype,"tileInfo",void 0);b([a.property({readOnly:!0})],g.prototype,"tileServers",void 0);b([a.reader("tileServers",
["tiles"])],g.prototype,"readTileServers",null);b([a.property({json:{read:!1},readOnly:!0,value:"vector-tile"})],g.prototype,"type",void 0);b([a.property({json:{origins:{webDocument:{read:{source:"styleUrl"}},portalItem:{read:{source:"url"}}},write:!1,read:!1}})],g.prototype,"url",void 0);b([a.property({readOnly:!0})],g.prototype,"version",void 0);b([a.reader("version",["version","currentVersion"])],g.prototype,"readVersion",null);b([a.property({readOnly:!0})],g.prototype,"compatibleTileInfo256",
void 0);b([a.reader("compatibleTileInfo256",["tileInfo"])],g.prototype,"readCompatibleTileInfo256",null);b([a.property({readOnly:!0})],g.prototype,"compatibleTileInfo512",void 0);b([a.reader("compatibleTileInfo512",["tileInfo"])],g.prototype,"readCompatibleTileInfo512",null);return g=b([a.subclass("esri.layers.VectorTileLayer")],g)}(a.declared(p,x,y,z,u,A))});