// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/accessorSupport/decorators ../../../../core/Accessor ../../viewpointUtils ../../../navigation/Momentum ../../libs/gl-matrix/vec2".split(" "),function(t,u,q,h,e,r,m,n,k){return function(p){function c(b){var a=p.call(this,b)||this;a.animationTime=0;a.momentumFinished=!1;a.rotateMomentumEstimator=new n.RotationMomentumEstimator(.05,6,.15,.95);a.rotateMomentum=null;a.rotationDirection=
1;a.zoomMomentumEstimator=new n.ZoomMomentumEstimator(.05);a.zoomMomentum=null;a.zoomDirection=1;a.viewpoint=m.create();a.watch("momentumFinished",function(b){b&&a.navigation.stop()});return a}q(c,p);c.prototype.begin=function(b,a){this.navigation.begin();this.rotateMomentumEstimator.reset();this.zoomMomentumEstimator.reset();this.addToRotateEstimator(a,0);this.addToZoomEstimator(a,a.startState.radius/a.currentState.radius)};c.prototype.update=function(b,a){var c=a.currentState,d=c.angle,f=c.radius,
c=c.center,l=a.previousState,g=l.radius,e=l.angle,l=a.startState.radius/f;g&&(f/=g,d=180*(d-e)/Math.PI,this.rotationDirection=0<=d?1:-1,this.zoomDirection=1<=f?1:-1,b.constraints.rotationEnabled||(d=0),this.addToRotateEstimator(a,d),this.addToZoomEstimator(a,l),this.center=c,this.navigation.setViewpoint([c.x,c.y],1/f,d))};c.prototype.end=function(b,a){this.addToRotateEstimator(a,0);this.addToZoomEstimator(a,a.startState.radius/a.currentState.radius);this.rotateMomentum=this.rotateMomentumEstimator.evaluateMomentum();
this.zoomMomentum=this.zoomMomentumEstimator.evaluateMomentum();this.animationTime=0;if(this.rotateMomentum||this.zoomMomentum)this.onAnimationUpdate(b);this.navigation.end()};c.prototype.addToRotateEstimator=function(b,a){this.rotateMomentumEstimator.add(a,.001*b.currentState.timestamp)};c.prototype.addToZoomEstimator=function(b,a){this.zoomMomentumEstimator.add(a,.001*b.currentState.timestamp)};c.prototype.canZoomIn=function(b){var a=b.scale;b=b.constraints.effectiveMaxScale;return 0===b||a>b};
c.prototype.canZoomOut=function(b){var a=b.scale;b=b.constraints.effectiveMinScale;return 0===b||a<b};c.prototype.onAnimationUpdate=function(b){var a=this;this.navigation.animationManager.animateContinous(b.viewpoint,function(c,d){var f=!a.canZoomIn(b)&&1<a.zoomDirection||!a.canZoomOut(b)&&1>a.zoomDirection;a.momentumFinished=!a.rotateMomentum||a.rotateMomentum.isFinished(a.animationTime)||f;d*=.001;a.notifyChange("momentumFinished");if(!a.momentumFinished){var f=Math.abs(a.rotateMomentum.valueDelta(a.animationTime,
d))*a.rotationDirection*2,e=a.zoomMomentum?Math.abs(a.zoomMomentum.valueDelta(a.animationTime,d)):1,g=k.create(),h=k.create();k.set(g,a.center.x,a.center.y);m.getPaddingScreenTranslation(h,b.size,b.padding);k.add(g,g,h);m.scaleAndRotateBy(c,b.viewpoint,e,f,g,b.size)}a.animationTime+=d})};c.prototype.stopMomentumNavigation=function(){if(this.rotateMomentum||this.zoomMomentum)this.rotateMomentum&&(this.rotateMomentumEstimator.reset(),this.rotateMomentum=null),this.zoomMomentum&&(this.zoomMomentumEstimator.reset(),
this.zoomMomentum=null),this.navigation.stop()};h([e.property()],c.prototype,"viewpoint",void 0);h([e.property()],c.prototype,"navigation",void 0);return c=h([e.subclass("esri.views.2d.navigation.actions.Pinch")],c)}(e.declared(r))});