// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../../geometry/support/webMercatorUtils ../../config ../../Graphic ../../core/Accessor ../../core/Error ../../core/Evented ../../core/promiseUtils ../../geometry/Point ../../portal/Portal ../../symbols/PictureMarkerSymbol ../../tasks/support/ProjectParameters ../../tasks/GeometryService dojo/_base/lang".split(" "),function(l,z,m,d,c,n,h,p,q,k,r,e,t,u,v,w,x,y){return function(g){function b(){var a=
null!==g&&g.apply(this,arguments)||this;a._geolocationUsable=!0;a._iconPath=l.toUrl("../../images/support/sdk_gps_location.png");a.geolocationOptions={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};a.goToLocationEnabled=!0;a.graphic=new p({symbol:new v({url:a._iconPath,width:21,height:21})});a.scale=null;a.view=null;return a}m(b,g);b.prototype.initialize=function(){var a=navigator.geolocation,b=window.hasOwnProperty("isSecureContext"),b=b&&window.isSecureContext||!b&&"https:"===window.location.protocol;
b&&a||(this._geolocationUsable=!1);a||console.log(this.declaredClass,"navigator.geolocation unsupported.");b||console.log(this.declaredClass,"navigator.geolocation requires a secure origin.")};b.prototype.destroy=function(){this._clear();this.view=null};b.prototype._clear=function(){this.view&&this.view.graphics.remove(this.graphic)};b.prototype._clonePosition=function(a){return a?{coords:y.mixin({},a.coords),timestamp:a.timestamp}:a};b.prototype._getGeometryServiceUrl=function(){if(h.geometryServiceUrl)return e.resolve(h.geometryServiceUrl);
var a=u.getDefault();return a.load().always(function(){return a.get("helperServices.geometry.url")})};b.prototype._projectPoint=function(a){var b=this.get("view.spatialReference");return b.isWGS84?e.resolve(a):b.isWebMercator?e.resolve(n.geographicToWebMercator(a)):this._getGeometryServiceUrl().then(function(f){if(!f)return e.reject(new k("geometry-service:missing-url","Geometry service URL is missing"));f=new x({url:f});var c=new w({geometries:[a],outSR:b});return f.project(c).then(function(a){return a[0]})})};
b.prototype._getScale=function(a){a=a&&a.coords&&a.coords.accuracy;return this.scale||a||5E4};b.prototype._createPoint=function(a){return(a=a&&a.coords)?new t({longitude:a.longitude,latitude:a.latitude,z:a.altitude||null,spatialReference:{wkid:4326}}):null};b.prototype._animatePoint=function(a,b,c){return this.goToLocationEnabled?this.view.goTo({target:a,scale:c}).then(function(){return b}):e.resolve(b)};b.prototype._setPosition=function(a){var b=this;a=this._clonePosition(a);var c=this._createPoint(a),
d=this._getScale(a);return c?this._projectPoint(c).then(function(c){b.graphic&&(b.graphic.geometry=c);b._animatePoint(c,a,d)}).then(function(){return a}):e.reject(new k("positioning:invalid-point","Cannot position invalid point"))};d([c.property()],b.prototype,"geolocationOptions",void 0);d([c.property()],b.prototype,"goToLocationEnabled",void 0);d([c.property()],b.prototype,"graphic",void 0);d([c.property()],b.prototype,"scale",void 0);d([c.property()],b.prototype,"view",void 0);return b=d([c.subclass("esri.widgets.support.GeolocationPositioning")],
b)}(c.declared(q,r))});