// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/paramHelper ../../core/accessorSupport/decorators ../../core/Collection ../../core/JSONSupport ../../core/accessorSupport/ensureType ../../core/watchUtils ../../tasks/support/FeatureSet ../../Graphic ../../PopupTemplate ../../renderers/support/jsonUtils ./kmlUtils".split(" "),function(v,w,p,d,x,b,e,q,m,n,r,g,t,u,h){function k(b){var a=r.fromJSON(b.featureSet).features,d=u.fromJSON(b.layerDefinition.drawingInfo.renderer),
c=t.fromJSON(b.popupInfo);return a.map(function(a){var b=d.getSymbol(a);a.symbol=b;a.popupTemplate=c;return a})}return function(l){function a(){var c=null!==l&&l.apply(this,arguments)||this;c._sublayersHandles=null;c._networkLinkHandle=null;c.description=null;c.id=null;c.mapImages=null;c.networkLink=null;c.points=null;c.polylines=null;c.polygons=null;c.title=null;return c}p(a,l);f=a;a.prototype.initialize=function(){var c=this;this._networkLinkHandle=n.init(this,"networkLink",function(a){a&&n.whenTrueOnce(c,
"visible",function(){c._fetchService(c._get("networkLink").href).then(function(a){a=m.default(e.ofType(f),h.sublayersFromJSON(a));c.sublayers?c.sublayers.addMany(a):c.sublayers=a;c.layer&&c.layer.notifyChange("visibleSublayers")});c._networkLinkHandle.remove();c._networkLinkHandle=null})})};Object.defineProperty(a.prototype,"layer",{set:function(c){this._set("layer",c);this.sublayers&&this.sublayers.forEach(function(a){return a.layer=c})},enumerable:!0,configurable:!0});a.prototype.readMapImages=
function(a,b){return new e(a)};a.prototype.readPointCollection=function(a,b){return k(a)};a.prototype.readPolylineCollection=function(a,b){return k(a)};a.prototype.readPolygonCollection=function(a,b){return k(a)};Object.defineProperty(a.prototype,"sublayers",{set:function(a){var c=this,b=this._get("sublayers");b&&(b.forEach(function(a){a.parent=null;a.layer=null}),this._sublayersHandles.forEach(function(a){return a.remove()}),this._sublayersHandles=null);a&&(a.forEach(function(a){a.parent=c;a.layer=
c.layer}),this._sublayersHandles=[a.on("after-add",function(a){a=a.item;a.parent=c;a.layer=c.layer}),a.on("after-remove",function(a){a=a.item;a.parent=null;a.layer=null})]);this._set("sublayers",a)},enumerable:!0,configurable:!0});a.prototype.castSublayers=function(a){return m.default(e.ofType(f),a)};Object.defineProperty(a.prototype,"visible",{get:function(){return this._get("visible")},set:function(a){this._get("visible")!==a&&(this._set("visible",a),this.layer&&this.layer.notifyChange("visibleSublayers"))},
enumerable:!0,configurable:!0});a.prototype.readVisible=function(a,b){return!!b.visibility};a.prototype._fetchService=function(a){return h.fetchService(a,this.layer.outSpatialReference,this.layer.refreshInterval).then(function(a){return h.parseKML(a.data)})};d([b.property()],a.prototype,"description",void 0);d([b.property()],a.prototype,"id",void 0);d([b.property({value:null})],a.prototype,"layer",null);d([b.property()],a.prototype,"mapImages",void 0);d([b.reader("mapImages",["mapImages"])],a.prototype,
"readMapImages",null);d([b.property({readOnly:!0,value:null})],a.prototype,"networkLink",void 0);d([b.property({json:{write:{allowNull:!0}}})],a.prototype,"parent",void 0);d([b.property({type:e.ofType(g)})],a.prototype,"points",void 0);d([b.reader("points",["points"])],a.prototype,"readPointCollection",null);d([b.property({type:e.ofType(g)})],a.prototype,"polylines",void 0);d([b.reader("polylines",["polylines"])],a.prototype,"readPolylineCollection",null);d([b.property({type:e.ofType(g)})],a.prototype,
"polygons",void 0);d([b.reader("polygons",["polygons"])],a.prototype,"readPolygonCollection",null);d([b.property({value:null,json:{write:{allowNull:!0}}})],a.prototype,"sublayers",null);d([b.cast("sublayers")],a.prototype,"castSublayers",null);d([b.property({value:null,json:{read:{source:"name"}}})],a.prototype,"title",void 0);d([b.property({value:!0})],a.prototype,"visible",null);d([b.reader("visible",["visibility"])],a.prototype,"readVisible",null);return a=f=d([b.subclass("esri.layers.support.KMLSublayer")],
a);var f}(b.declared(q))});