// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Error ../../core/Evented ../../core/HandleRegistry ../../core/promiseUtils ../../core/watchUtils ../../styles/basic ./FeatureLayerSearchSource ./LocatorSearchSource ../../tasks/Locator dojo/has ../../Graphic ../../geometry/Point ../../symbols/PictureMarkerSymbol ../../symbols/SimpleFillSymbol ../../symbols/SimpleLineSymbol ../../symbols/SimpleMarkerSymbol ../../symbols/TextSymbol ../../PopupTemplate ../../geometry/SpatialReference ./support/geometryUtils ./SearchSource dojo/i18n!./nls/Search ../../core/accessorSupport/decorators".split(" "),
function(A,R,B,d,C,D,u,E,F,g,l,G,v,n,H,I,z,r,J,K,L,M,N,O,P,w,Q,k,c){function f(c,b){return c.hasOwnProperty(b)&&null!=c[b]&&""!==c[b]}var t=D.ofType({key:function(c){return c.featureLayer?"feature-layer":"locator"},base:Q,typeMap:{"feature-layer":v,locator:n}}),q=P.WGS84,m=new n({locator:new H({url:"//geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer"}),singleLineFieldName:"SingleLine",outFields:["Addr_type","Match_addr","StAddr","City"],name:k.esriLocatorName,localSearchOptions:{minScale:3E5,
distance:5E4},placeholder:k.placeholder,resultSymbol:new J({url:A.toUrl(I("trident")?"../../images/search/search-symbol-32.png":"../../images/search/search-symbol-32.svg"),size:24,width:24,height:24})});return function(p){function b(a){a=p.call(this)||this;a._handles=new F;a._viewReadyPromise=null;a._viewAnimation=null;a._popupTemplate=new O({title:k.searchResult,content:"{Match_addr}"});a.activeSource=null;a.activeSourceIndex=0;a.allPlaceholder=k.allPlaceholder;a.autoNavigate=!0;a.autoSelect=!0;
a.defaultSource=m;a.locationToAddressDistance=1500;a.maxInputLength=128;a.maxResults=6;a.maxSuggestions=6;a.minSuggestCharacters=1;a.placeholder="";a.popupOpenOnSelect=!0;a.popupTemplate=null;a.popupEnabled=!0;a.resultGraphicEnabled=!0;a.resultGraphic=null;a.results=null;a.selectedSuggestion=null;a.searchAllEnabled=!0;a.selectedResult=null;a.sources=new t([m]);a.suggestionDelay=150;a.suggestions=null;a.suggestionsEnabled=!0;a.view=null;return a}B(b,p);b.prototype.initialize=function(){var a=this;
this._handles.add([l.init(this,"activeSourceIndex",function(e){a._updateActiveSource();a._setPlaceholder(e)}),l.init(this,"allPlaceholder",function(){a._setPlaceholder(a.activeSourceIndex)}),l.init(this,"sources",function(){a._setDefaultActiveSourceIndex();a._setPlaceholder(a.activeSourceIndex)}),l.init(this,"searchAllEnabled",function(){return a._setDefaultActiveSourceIndex()})])};b.prototype.destroy=function(){this.clearGraphics();this._viewReadyPromise&&this._viewReadyPromise.cancel();this._handles.destroy();
this._handles=null};Object.defineProperty(b.prototype,"popup",{get:function(){return this.get("view.popup")||null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"searchTerm",{get:function(){return this._get("searchTerm")||""},set:function(a){this._set("searchTerm",a||"");this.clearGraphics();this.selectedSuggestion&&this.selectedSuggestion.text!==a&&this._set("selectedSuggestion",null);""===a&&this._clear()},enumerable:!0,configurable:!0});b.prototype.clear=function(){this.searchTerm=
""};b.prototype.clearGraphics=function(){this._closePopup();this.view&&this.view.graphics.remove(this.resultGraphic);this._set("resultGraphic",null)};b.prototype.search=function(a){var e=this;this.emit("search-start");var b=this._getLocationSearch(a),h=this._createSuggestionForSearch(a);return this._ready(this.view).then(function(){return e._getResultsFromSources(b,h).then(function(a){var b={activeSourceIndex:e.activeSourceIndex,searchTerm:h.text,numResults:0,numErrors:0,errors:[],results:[]};e._formatResponse(b,
a,h);e._set("searchTerm",h.text);h.key&&h.sourceIndex&&e._set("selectedSuggestion",h);e._set("results",b.results);e.emit("search-complete",b);return e._selectFirstResult(b.results).then(function(){return b})})})};b.prototype.select=function(a){var e=this;this.clearGraphics();if(!a)return g.reject(new u("searchviewmodel:missing-parameter","searchResult is required."));var b=this.view,h=f(a,"sourceIndex")?a.sourceIndex:this._getSourceIndexOfResult(a),c=this.sources.getItemAt(h);if(!c)return g.reject(new u("searchviewmodel:missing-source",
"source not found for selection."));var d=c instanceof v?this._getSourcePopupTemplate(c):null,y=c.resultSymbol||this._getDefaultSymbol(a),k=f(c,"resultGraphicEnabled")?c.resultGraphicEnabled:this.resultGraphicEnabled,l=f(c,"autoNavigate")?c.autoNavigate:this.autoNavigate,n=f(c,"popupOpenOnSelect")?c.popupOpenOnSelect:this.popupOpenOnSelect,m=f(c,"popupEnabled")?c.popupEnabled:this.popupEnabled,r=m?d||this.popupTemplate||this._popupTemplate:null,d=a.feature,p=this.popup,t=d.attributes,q=d.geometry;
if(!d)return g.reject(new u("searchviewmodel:missing-feature","The SearchResult must contain a feature for selection."));d=w.getPointFromGeometry(q);return(b?w.getPointWithElevation(d,b):g.resolve(d)).then(function(x){y instanceof N&&(y.text=a.name);var d=new z({geometry:q,symbol:y,attributes:t,popupTemplate:r});return(b&&l?e._goToSearchResult(b,a.extent):g.resolve()).then(function(){e._viewAnimation=null;k&&b&&b.graphics.push(d);p&&m&&n&&p.open({features:[d],location:x});e._set("selectedResult",
a);e._set("resultGraphic",d);e.emit("select-result",{result:a,source:c,sourceIndex:h});return a})})};b.prototype.suggest=function(a,b){var e=this,c=a||this.searchTerm;this.emit("suggest-start",{searchTerm:c});return this._suggestTimer(b).then(function(){return e._suggestImmediate(c).then(function(a){e._set("suggestions",a.results);e.emit("suggest-complete",a);return a})})};b.prototype._clear=function(){this._viewAnimation&&(this._viewAnimation.stop(),this._viewAnimation=null);this._set("results",
null);this._set("suggestions",null);this._set("selectedResult",null);this._set("selectedSuggestion",null);this.emit("search-clear")};b.prototype._closePopup=function(){var a=this.get("view.popup"),b=this.resultGraphic;if(a&&this.popupEnabled&&b){var c=a.selectedFeature;c&&c===b&&a.close()}};b.prototype._suggestTimer=function(a){return g.after(null!=a?a:this.suggestionDelay)};b.prototype._getLocationSearch=function(a){if(a instanceof z)return w.getPointFromGeometry(a.geometry);if(a instanceof r)return a;
if(Array.isArray(a)&&2===a.length)return new r({longitude:a[0],latitude:a[1]})};b.prototype._createSuggestionForSearch=function(a){if(a&&f(a,"key")&&f(a,"text")&&f(a,"sourceIndex"))return a;a="string"===typeof a?a:this.searchTerm;var b=this.selectedSuggestion,c=this.selectedResult;return b&&c&&b.text===c.name?b:{text:a,key:null,sourceIndex:null}};b.prototype._getFirstResult=function(a){var b=null;a&&a.some(function(a){a=a.results[0];var e=!!a;e&&(b=a);return e});return b};b.prototype._selectFirstResult=
function(a){return this.autoSelect&&a?(a=this._getFirstResult(a))?this.select(a):g.resolve():g.resolve()};b.prototype._suggestImmediate=function(a){var b=this;return this._ready(this.view).then(function(){return b._getSuggestionsFromSources(a)}).then(function(e){var c={activeSourceIndex:b.activeSourceIndex,searchTerm:a,numResults:0,numErrors:0,errors:[],results:[]};b._formatResponse(c,e);return c})};b.prototype._formatSourceResponse=function(a,b,c){var e=b&&b.value||[];b=b&&b.error;var d=this.sources.getItemAt(c);
b?(a.errors.push({sourceIndex:c,source:d,error:b}),a.numErrors++):(a.results.push({sourceIndex:c,source:d,results:e}),a.numResults+=e.length)};b.prototype._formatResponse=function(a,b,c){var e=this;if(b)if(-1===a.activeSourceIndex){var d=c&&f(c,"sourceIndex")&&-1!==c.sourceIndex?c.sourceIndex:void 0;b.forEach(function(b,c){e._formatSourceResponse(a,b,void 0!==d?d:c)})}else this._formatSourceResponse(a,b[0],a.activeSourceIndex)};b.prototype._getResultsFromSources=function(a,b){var c=this,e=!a&&f(b,
"sourceIndex")?b.sourceIndex:this.activeSourceIndex,d=[];-1===e?this.sources.forEach(function(e,h){d.push(c._getResultsFromSource(a,b,h))}):d.push(this._getResultsFromSource(a,b,e));return g.eachAlways(d)};b.prototype._getSuggestionsFromSources=function(a){var b=this,c=this.activeSourceIndex,d=[];-1===c?this.sources.forEach(function(c,e){d.push(b._getSuggestionsFromSource(a,e))}):d.push(this._getSuggestionsFromSource(a,c));return g.eachAlways(d)};b.prototype._getResultsFromSource=function(a,b,c){var e=
this.sources.getItemAt(c),d=this.get("view.spatialReference")||q,x=f(e,"maxResults")?e.maxResults:this.maxResults,g=e instanceof v&&f(e,"exactMatch")?e.exactMatch:!1,k=e instanceof n&&f(e,"locationToAddressDistance")?e.locationToAddressDistance:this.locationToAddressDistance;return e.getResults({view:this.view,sourceIndex:c,location:a,suggestResult:b,spatialReference:d,exactMatch:g,maxResults:x,distance:k})};b.prototype._getSuggestionsFromSource=function(a,b){var c=this.sources.getItemAt(b),e=f(c,
"suggestionsEnabled")?c.suggestionsEnabled:this.suggestionsEnabled,d=a.trim().length,k=f(c,"minSuggestCharacters")?c.minSuggestCharacters:this.minSuggestCharacters;return e&&d>=k?(e=this.get("view.spatialReference")||q,d=f(c,"maxSuggestions")?c.maxSuggestions:this.maxSuggestions,c.getSuggestions({view:this.view,sourceIndex:b,suggestTerm:a,spatialReference:e,maxSuggestions:d})):g.resolve()};b.prototype.createDefaultSymbol=function(a,b){if("point"===b)return new M({color:a.color,size:a.size,outline:{color:a.outline.color,
width:a.outline.width}});if("polyline"===b)return new L({color:a.color,width:a.width});if("polygon"===b)return new K({color:a.color,outline:{color:a.outline.color,width:a.outline.width}})};b.prototype._updateActiveSource=function(){var a=this.sources.getItemAt(this.activeSourceIndex)||null;this._set("activeSource",a)};b.prototype._getPlaceHolderText=function(a){var b=this.sources.getItemAt(a),c=this.allPlaceholder,c=void 0===c?k.allPlaceholder:c;return-1===a?c:b?b.placeholder:""};b.prototype._setPlaceholder=
function(a){this._set("placeholder",this._getPlaceHolderText(a))};b.prototype._setDefaultActiveSourceIndex=function(){this.activeSourceIndex=1!==this.sources.length&&this.searchAllEnabled?-1:0};b.prototype._getSourcePopupTemplate=function(a){var b=a.featureLayer;if(b)return f(a,"popupTemplate")?a.popupTemplate:b.popupTemplate};b.prototype._getSourceIndexOfResult=function(a){var b=null;this.results.some(function(c){return c.results.some(function(e){if(e===a)return b=c.sourceIndex,!0})});return b};
b.prototype._goToSearchResult=function(a,b){var c=!!b,d={animate:c};a="3d"===a.type?a.goTo({target:b,tilt:0},d):a.goTo({target:b},d);c&&(this._viewAnimation=a);return a};b.prototype._ready=function(a){this._viewReadyPromise&&this._viewReadyPromise.cancel();return a?this._viewReadyPromise=a.always().then(function(){return null}):g.resolve()};b.prototype._getDefaultSymbol=function(a){var b=this.get("view.map.basemap.id");if(a=a&&a.feature&&a.feature.geometry&&a.feature.geometry.type)if(b=(b=G.getSchemes({theme:"default",
basemap:b||"topo",geometryType:a}))&&b.primaryScheme)return b.color&&f(b,"opacity")&&(b.color.a=b.opacity),this.createDefaultSymbol(b,a);return m.resultSymbol};b.ALL_INDEX=-1;d([c.property({readOnly:!0})],b.prototype,"activeSource",void 0);d([c.property()],b.prototype,"activeSourceIndex",void 0);d([c.property()],b.prototype,"allPlaceholder",void 0);d([c.property()],b.prototype,"autoNavigate",void 0);d([c.property()],b.prototype,"autoSelect",void 0);d([c.property({readOnly:!0})],b.prototype,"defaultSource",
void 0);d([c.property()],b.prototype,"locationToAddressDistance",void 0);d([c.property()],b.prototype,"maxInputLength",void 0);d([c.property()],b.prototype,"maxResults",void 0);d([c.property()],b.prototype,"maxSuggestions",void 0);d([c.property()],b.prototype,"minSuggestCharacters",void 0);d([c.property({readOnly:!0})],b.prototype,"placeholder",void 0);d([c.property({dependsOn:["view.popup"],readOnly:!0})],b.prototype,"popup",null);d([c.property()],b.prototype,"popupOpenOnSelect",void 0);d([c.property()],
b.prototype,"popupTemplate",void 0);d([c.property()],b.prototype,"popupEnabled",void 0);d([c.property()],b.prototype,"resultGraphicEnabled",void 0);d([c.property({readOnly:!0})],b.prototype,"resultGraphic",void 0);d([c.property({readOnly:!0})],b.prototype,"results",void 0);d([c.property({readOnly:!0})],b.prototype,"selectedSuggestion",void 0);d([c.property()],b.prototype,"searchAllEnabled",void 0);d([c.property({readOnly:!0})],b.prototype,"selectedResult",void 0);d([c.property()],b.prototype,"searchTerm",
null);d([c.property({type:t})],b.prototype,"sources",void 0);d([c.property()],b.prototype,"suggestionDelay",void 0);d([c.property({readOnly:!0})],b.prototype,"suggestions",void 0);d([c.property()],b.prototype,"suggestionsEnabled",void 0);d([c.property()],b.prototype,"view",void 0);d([c.property()],b.prototype,"clear",null);return b=d([c.subclass("esri.widgets.Search.SearchViewModel")],b)}(c.declared(C,E))});