// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/HandleRegistry ../../../core/promiseUtils ../../../geometry/Extent ./LayerView3D ./support/overlayImageUtils ./support/projectExtentUtils ../support/aaBoundingRect ../lib/glMatrix ../webgl-engine/Stage ../webgl-engine/lib/Texture ../webgl-engine/lib/RenderGeometry ../webgl-engine/materials/Material ../webgl-engine/lib/Util".split(" "),function(C,
D,r,h,f,t,u,p,v,q,w,l,x,m,y,z,A,B){return function(n){function b(){var a=null!==n&&n.apply(this,arguments)||this;a.supportsDraping=!0;a.hasDraped=!0;a.fullExtentInViewSpatialReference=null;a._handles=new t;a._images=[];a._extents=[];return a}r(b,n);Object.defineProperty(b.prototype,"drawingOrder",{get:function(){return this._get("drawingOrder")},set:function(a){if(a!==this._get("drawingOrder")){this._set("drawingOrder",a);var c={};this._images.forEach(function(k){k&&k.material&&(k.material.setRenderPriority(a),
c[k.material.getId()]=!0)});B.objectEmpty(c)||(this.view._stage.getTextureGraphicsRenderer().updateRenderOrder(c),this.emit("draped-data-change"))}},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this.addResolvingPromise(w.toView(this).then(function(c){return a._set("fullExtentInViewSpatialReference",c)}));this.addResolvingPromise(this.getHeightModelInfoResolvingPromise());this._handles.add(this.watch("suspended",
function(){return a._suspendedChangeHandler()}));var c=this.notifyChange.bind(this,"suspended");this.view.resourceController.registerIdleFrameWorker(this,{idleBegin:function(){a._isScaleRangeActive()&&c()}});this._isScaleRangeLayer()&&this._handles.add([this.layer.watch("minScale",c),this.layer.watch("maxScale",c)],"layer");this._handles.add([this.watch("fullOpacity",this._opacityChangeHandler.bind(this)),this.layer.on("redraw",this._layerRedrawHandler.bind(this))],"layer")};b.prototype.destroy=function(){this.clear();
this._handles.destroy();this.view.resourceController.deregisterIdleFrameWorker(this)};b.prototype.setDrapingExtent=function(a,c,k,b,e){var d=l.width(c)/l.height(c),g={width:b,height:b};1.0001<d?g.height=Math.round(b/d):.9999>d&&(g.width=Math.round(b*d));if("imageMaxWidth"in this.layer||"imageMaxHeight"in this.layer)b=this.layer.imageMaxWidth,d=this.layer.imageMaxHeight,g.width>b&&(g.height=Math.floor(g.height*b/g.width),g.width=b),g.height>d&&(g.width=Math.floor(g.width*d/g.height),g.height=d);this._extents[a]=
{extent:l.create(c),spatialReference:k,imageSize:g,renderLocalOrigin:e};this.suspended||this._fetch(a)};b.prototype.getGraphicsFromStageObject=function(a,c){return u.reject()};b.prototype.clear=function(){for(var a=0;a<this._images.length;a++)this._clearImage(a)};b.prototype.canResume=function(){if(!this.inherited(arguments))return!1;if(this._isScaleRangeLayer()){var a=this.layer,c=a.minScale,a=a.maxScale;if(0<c||0<a){var b=this.view.scale;if(b<a||0<c&&b>c)return!1}}return!0};b.prototype.isUpdating=
function(){for(var a=0,c=this._images;a<c.length;a++)if(c[a].loadingPromise)return!0;return!1};b.prototype.processResult=function(a,c){if(c instanceof HTMLImageElement||c instanceof HTMLCanvasElement)a.image=c};b.prototype.updateImage=function(a){return!1};b.prototype.refetch=function(){for(var a=0;a<this._extents.length;a++)this._extents[a]&&this._fetch(a)};b.prototype.beforeFetch=function(){};b.prototype.findExtentInfoAt=function(a){for(var c=0,b=this._extents;c<b.length;c++){var d=b[c],e=d.extent;
if((new p(e[0],e[1],e[2],e[3],d.spatialReference)).contains(a))return d}return null};b.prototype._fetch=function(a){var c=this;if(!this.suspended){this.beforeFetch();var b=this._extents[a],d=b.extent,e=new p(d[0],d[1],d[2],d[3],b.spatialReference);this._images[a]||(this._images[a]={texture:null,material:null,rendergeometry:null,loadingPromise:null,image:null,pixelData:null,worldExtent:l.create(d)});var f=this._images[a];f.loadingPromise&&f.loadingPromise.cancel();f.loadingPromise=this.layer.fetchImage(e,
b.imageSize.width,b.imageSize.height,{allowImageDataAccess:!0});f.loadingPromise.then(function(b){l.set(f.worldExtent,d);c.processResult(f,b);c._createStageObjects(a,f.image);0===a&&c._images[1]&&c._images[1].rendergeometry&&c._createStageObjects(1,null);c._evaluateUpdatingState();c.emit("draped-data-change")}).otherwise(function(a){a&&"CancelError"===a.name||c._evaluateUpdatingState()}).always(function(){f.loadingPromise=null});this._evaluateUpdatingState()}};b.prototype._clearImage=function(a){a=
this._images[a];var c=this.view._stage;a&&(a.rendergeometry&&(c.getTextureGraphicsRenderer().removeRenderGeometries([a.rendergeometry]),a.rendergeometry=null),a.texture&&(c.remove(m.ModelContentType.TEXTURE,a.texture.getId()),a.texture=null),a.material&&(c.remove(m.ModelContentType.MATERIAL,a.material.getId()),a.material=null),a.loadingPromise&&(a.loadingPromise.cancel(),a.loadingPromise=null),a.image=null,a.pixelData=null)};b.prototype._evaluateUpdatingState=function(){this.notifyChange("updating")};
b.prototype._createStageObjects=function(a,c){var b=this.view._stage,d=b.getTextureGraphicsRenderer(),e=this._images[a];c&&(e.texture&&b.remove(m.ModelContentType.TEXTURE,e.texture.getId()),e.texture=new y(c,"dynamicLayer",{width:c.width,height:c.height,wrapClamp:!0}),b.add(m.ModelContentType.TEXTURE,e.texture));e.material?c&&e.material.setParameterValues({textureId:e.texture.getId()}):(e.material=new A({ambient:[1,1,1],diffuse:[0,0,0],transparent:!0,opacity:this.fullOpacity,textureId:e.texture.getId(),
receiveSSAO:!1},"dynamicLayer"),e.material.setRenderPriority(this.drawingOrder),b.add(m.ModelContentType.MATERIAL,e.material));c=this._extents[a].renderLocalOrigin;if(0===a)a=q.createGeometryForExtent(e.worldExtent,-1);else if(1===a){a=this._images[0].worldExtent;if(!a)return;a=q.createOuterImageGeometry(a,e.worldExtent,-1)}else{console.error("DynamicLayerView3D._createStageObjects: Invalid extent idx");return}b=new z(a);b.material=e.material;b.origin=c;b.transformation=x.mat4d.identity();b.name=
"dynamicLayer";b.uniqueName="dynamicLayer#"+a.id;d.addRenderGeometries([b]);e.rendergeometry&&d.removeRenderGeometries([e.rendergeometry]);e.rendergeometry=b};b.prototype._isScaleRangeLayer=function(){return"minScale"in this.layer&&"maxScale"in this.layer};b.prototype._isScaleRangeActive=function(){return this._isScaleRangeLayer()?0<this.layer.minScale||0<this.layer.maxScale:!1};b.prototype._opacityChangeHandler=function(a){for(var b=0,f=this._images;b<f.length;b++){var d=f[b];d&&d.material&&d.material.setParameterValues({opacity:a})}this.emit("draped-data-change")};
b.prototype._layerRedrawHandler=function(){for(var a=!1,b=0;b<this._images.length;b++){var f=this._images[b];this.updateImage(f)&&(a=!0,this._createStageObjects(b,f.image))}a&&this.emit("draped-data-change")};b.prototype._suspendedChangeHandler=function(){if(this.suspended)this.clear(),this.emit("draped-data-change");else for(var a=0;a<this._extents.length;a++)this._fetch(a)};h([f.property()],b.prototype,"layer",void 0);h([f.property({dependsOn:["view.scale","layer.minScale","layer.maxScale"]})],
b.prototype,"suspended",void 0);h([f.property({type:Boolean})],b.prototype,"supportsDraping",void 0);h([f.property({type:Boolean})],b.prototype,"hasDraped",void 0);h([f.property({value:0,type:Number})],b.prototype,"drawingOrder",null);h([f.property({readOnly:!0})],b.prototype,"fullExtentInViewSpatialReference",void 0);return b=h([f.subclass("esri.views.3d.layers.DynamicLayerView3D")],b)}(f.declared(v))});