// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/Logger ./graphics/Graphics3DLayerViewCore ./support/LayerViewUpdatingPercentage ../../../Graphic ../../../geometry/Point ../../../geometry/Polyline ../../../renderers/support/renderingInfoUtils ../../../core/Collection ../../../core/HandleRegistry ../../../core/promiseUtils ../lib/glMatrix ./LayerView3D ./i3s/I3SUtil ./i3s/I3SQueryEngine ./i3s/FeatureChangeNotifier ../support/aaBoundingBox ../support/PreallocArray ../support/projectionUtils".split(" "),
function(y,Y,H,m,h,I,J,K,G,L,M,N,O,P,D,Q,R,u,S,T,k,z,U){function V(e,b){e.xmin-=b;e.ymin-=b;e.xmax+=b;e.ymax+=b;e.hasZ&&(e.zmin-=b,e.zmax+=b);e.hasM&&(e.mmin-=b,e.mmax+=b);return e}var F=I.getLogger("esri.views.3d.layers.SceneLayerGraphicsView3D");y=function(e){function b(a){a=e.call(this)||this;a._queryEngine=null;a.supportsHeightUnitConversion=!0;a._isUpdating=!1;a._definitionExpressionErrors=0;a._maxDefinitionExpressionErrors=20;a._nodesAddedToStage={};a.loadedGraphics=new O;a.supportsDraping=
!0;a._overlayUpdating=null;a._controllerCreated=!1;a._handles=new P;return a}H(b,e);b.prototype.initialize=function(){var a=this;u.checkSpatialReferences(this.layer,this.view.spatialReference,this.view.viewingMode);this.addResolvingPromise(this.getHeightModelInfoResolvingPromise());this._handles.add([this.layer.watch("renderer",function(c,d){return a._rendererChange(c,d)}),this.layer.watch("objectIdFilter",function(){return a._objectIdFilterChange()}),this.layer.watch("_controller.parsedDefinitionExpression",
function(){return a._definitionExpressionChange()})]);this._layerViewCore=new J({owner:this,layer:this.layer,spatialIndexRequired:!1,labelingEnabled:!0,frustumVisibilityEnabled:!1,elevationAlignmentEnabled:!0,elevationFeatureExpressionEnabled:!1,verticalScaleEnabled:this.supportsHeightUnitConversion,highlightsEnabled:!0,updateSuspendResumeExtent:function(){return a._updateSuspendResumeExtent()},updateClippingExtent:function(c){return a._updateClippingExtent(c)},getGraphicsInExtent:function(c,d,t){return a._getGraphicsInExtent(c,
d,t)}});this.addResolvingPromise(this._layerViewCore.initialize());this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this._createController()};b.prototype.destroy=function(){this._layerViewCore&&(this._layerViewCore.destroy(),this._layerViewCore=null);this._controller&&(this._controller.destroy(),this._controller=null);this._nodesAddedToStage=this._intersectingGraphicIds=this._elevationUpdateNodes=null;this._handles&&(this._handles.destroy(),this._handles=null)};Object.defineProperty(b.prototype,
"hasDraped",{get:function(){return this._layerViewCore.graphicsCore.hasDraped},enumerable:!0,configurable:!0});b.prototype.whenGraphicAttributes=function(a,c){var d=this;return u.whenGraphicAttributes(this.layer,[a],this._getObjectIdField(),c,function(){var c=d._findGraphicNodeAndIndex(a);return{node:c.node,indices:[c.index]}}).then(function(a){return a[0]})};b.prototype.getGraphicsFromStageObject=function(a,c){if(!this.loadedGraphics)return D.reject();var d=a.getMetadata().graphicId;a=this.loadedGraphics.find(function(a){return a.uid===
d});c=this._getObjectIdField();return a&&a.attributes&&a.attributes[c]?D.resolve(a):D.reject()};b.prototype.whenGraphicBounds=function(a){return this._layerViewCore.graphicsCore.whenGraphicBounds(a)};b.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};b.prototype.isUpdating=function(){return this._isUpdating||!this._controllerCreated?!0:!(!this._controller||!this._controller.updating)};b.prototype.getRenderingInfo=function(a){if((a=
N.getRenderingInfo(a,{renderer:this.layer.renderer}))&&a.color){var c=a.color;c[0]/=255;c[1]/=255;c[2]/=255}return a};b.prototype.getSymbolUpdateType=function(){return this._layerViewCore.graphicsCore.getSymbolUpdateType()};b.prototype._findGraphicNodeAndIndex=function(a){a=a.attributes[this.layer.objectIdField];for(var c=0,d=Object.keys(this._nodesAddedToStage);c<d.length;c++)for(var b=d[c],f=this._nodesAddedToStage[b].bundles,g=0;g<f.length;g++){var v=this._findGraphicIndex(f[g],a);if(0<=v)return{node:this._controller.nodeIndex[b],
nodeId:b,bundleNr:g,index:v}}return null};b.prototype._forAllFeatures=function(a,c){for(var d=0,b=Object.keys(this._nodesAddedToStage);d<b.length;d++)for(var f=b[d],g=this._nodesAddedToStage[f].bundles,v=0;v<g.length;v++){for(var e=g[v],r=0;r<e.length;r++)for(var A=e[r].graphics,n=0;n<A.length;n++){var k=A[n],h=e[r].featureIds[n];k.visible&&a(h,r,k)}null!=c&&c({nodeId:f,bundleNr:v})}};b.prototype._getGraphicIndices=function(a,c,d){a=this._nodesAddedToStage[a].bundles[c];c=this._getObjectIdField();
for(var b=[],f=0;f<d.length;f++){var g=this._findGraphicIndex(a,d[f].attributes[c]);0<=g&&b.push(g)}return b};b.prototype._findGraphicIndex=function(a,c){for(var d=0;d<a.length;d++)for(var b=0,f=a[d].featureIds;b<f.length;b++)if(f[b]===c)return d;return-1};b.prototype._getGraphicsInExtent=function(a,c,d){k[2]=-Infinity;k[3]=Infinity;var b=k.fromRect(W,a);null==this._elevationUpdateNodes&&(this._elevationUpdateNodes=new z(10));a=this._elevationUpdateNodes;a.clear();this._controller&&this._controller.updateElevationChanged(b,
c,a);c=a.length;this._intersectingGraphicIds||(this._intersectingGraphicIds=new z(10));b=this._intersectingGraphicIds;b.clear();for(var f=0;f<c;f++){var g=this._nodesAddedToStage[a.data[f].id];if(null!=g)for(var g=g.bundles,e=0;e<g.length;e++)for(var x=g[e],r=0;r<x.length;r++)for(var A=x[r].graphics,n=0;n<A.length;n++)b.push(A[n].uid)}d(this._intersectingGraphicIds.data,this._intersectingGraphicIds.length)};b.prototype._evaluateUpdatingState=function(){var a=!1;if(this._layerViewCore.elevationAlignment){var c;
c=0+this._layerViewCore.elevationAlignment.numNodesUpdating();c+=this._layerViewCore.graphicsCore.numNodesUpdating();var b;b=(b=(b=!this._controllerCreated)||this._overlayUpdating)||this._layerViewCore.graphicsCore.needsIdleUpdate();a=a||0<c||b}this._isUpdating!==a&&(this._isUpdating=a,this.notifyChange("updating"))};b.prototype._notifySuspendedChange=function(){};b.prototype._notifyDrapedDataChange=function(){this.notifyChange("hasDraped");this.emit("draped-data-change")};b.prototype.highlight=function(a,
c){return this._layerViewCore.highlight(a,c,this.layer.objectIdField)};b.prototype._createController=function(){var a=this;this.layer.createGraphicsController({layerView:this,layerViewRequiredFunctions:{addBundle:function(c,b,t){return a._addBundle(c,b,t)},isBundleAlreadyAddedToStage:function(c,b){return a._isBundleAlreadyAddedToStage(c,b)},isOverMemory:function(){return a._isOverMemory()},removeNodeData:function(c){return a._removeNodeData(c)},getAddedNodeIDs:function(){return a._getAddedNodeIDs()},
areAllBundlesLoaded:function(c){return a._areAllBundlesLoaded(c)}},layerViewOptionalFunctions:{traversalOptions:{initDepthFirst:!1,neighborhood:!1,perLevelTraversal:!0,allowPartialOverlaps:!1,errorMetricPreference:["distanceRangeFromDefaultCamera","screenSpaceRelative"]},getLoadedAttributes:function(c){return a._getLoadedAttributes(c)},setAttributeData:function(c,b,t){return a._setAttributeData(c,b,t)}}}).then(function(c){a._controller=c;a._featureChangeNotifier=new T.FeatureChangeNotifier(a,c);c.watch("rootNodeVisible",
function(){a.notifyChange("suspended")})}).always(function(){a._controllerCreated=!0;a._evaluateUpdatingState()})};b.prototype._addBundle=function(a,c,b){var d=b.allGeometryData,f=b.attributeDataInfo;b=[];var g=this._controller.crsIndex,e=this._getObjectIdField();null==this._nodesAddedToStage[a.id]&&(this._nodesAddedToStage[a.id]={bundles:[],attributeData:f?f.attributeData:null,loadedAttributes:f?f.loadedAttributes:null});this._nodesAddedToStage[a.id].bundles[c]=b;var x;if(this.layer.objectIdFilter){var r=
this.layer.objectIdFilter.ids,k="include"===this.layer.objectIdFilter.method;x=function(a){return 0<=r.indexOf(a)===k}}for(var f=this.layer.fullExtent&&V(this.layer.fullExtent.clone(),.5),n=[],h=0;h<d.length;h++)for(var m=d[h],u=m.featureDataPosition,y=m.geometries||X,z=m.featureIds,B=0;B<y.length;B++){var q=y[B],C=[],l=z[B<z.length?B:0],w={};if(null!=l){if(x&&!x(l))continue;w[e]=l}var p=q.params.type,E=l=void 0;"Embedded"===q.type&&(l=q.params.vertexAttributes.position,E=3);q=void 0;if("lines"===
p){q=[];for(p=0;p<l.length;p+=E)q.push([l[p]+a.mbs[0],l[p+1]+a.mbs[1]]);l=new M(g);l.addPath(q);q=l;C.push(new G(q,null,w))}else if("points"===p)for(p=0;p<l.length;p+=E)q=new L({x:l[p]+u[0],y:l[p+1]+u[1],z:2<E?l[p+2]+u[2]:void 0,spatialReference:g}),f&&!f.contains(q)&&F.error("Service Error: Point coordinates outside of layer extent"),C.push(new G(q,null,w));w=0;for(l=C;w<l.length;w++)l[w].layer=this.layer;n.push.apply(n,C);b.push({featureIds:m.featureIds,graphics:C})}this.loadedGraphics.addMany(n);
this._featureChangeNotifier.notify(n.length,0);a=this._nodesAddedToStage[a.id];this._setBundleAttributes(a.bundles[c],a.loadedAttributes,a.attributeData);this._filterNode(a);return D.resolve()};b.prototype._areAllBundlesLoaded=function(a){var b=this._nodesAddedToStage[a.id];if(null==b)return!1;for(var d=0;d<a.featureData.length;d++)if(null==b.bundles[d])return!1;return!0};b.prototype._isBundleAlreadyAddedToStage=function(a,b){return null!=this._nodesAddedToStage[a.id]&&null!=this._nodesAddedToStage[a.id].bundles[b]};
b.prototype._isOverMemory=function(){return!1};b.prototype._removeNodeData=function(a){var b=this._nodesAddedToStage[a.id];if(null!=b){var b=b.bundles,d=[],t;for(t in b)for(var f in b[t])d.push.apply(d,b[t][f].graphics);this.loadedGraphics.removeMany(d);this._featureChangeNotifier.notify(0,d.length);delete this._nodesAddedToStage[a.id]}};b.prototype._getAddedNodeIDs=function(){return Object.keys(this._nodesAddedToStage)};b.prototype._getLoadedAttributes=function(a){if(a=this._nodesAddedToStage[a.id])return a.loadedAttributes};
b.prototype._setAttributeData=function(a,b,d){if(a=this._nodesAddedToStage[a.id])a.loadedAttributes=b,a.attributeData=d,this._setNodeAttributes(a,b,d),this._filterNode(a),this._layerViewCore.labeling.layerLabelsEnabled()&&this._layerViewCore.labeling.updateLabelingInfo()};b.prototype._setNodeAttributes=function(a,b,d){a=a.bundles;for(var c in a)this._setBundleAttributes(a[c],b,d)};b.prototype._setBundleAttributes=function(a,b,d){for(var c=0;c<a.length;c++)for(var f=0,g=a[c].graphics;f<g.length;f++){var e=
g[f];e.attributes||(e.attributes={});if(b)for(var h=0,k=b;h<k.length;h++){var m=k[h].name;d[m]&&(e.attributes[m]=u.getCachedAttributeValue(d[m],c))}}};b.prototype._updateSuspendResumeExtent=function(){this.layer.fullExtent?(this._suspendResumeExtent||(this._suspendResumeExtent=Q.vec4d.create()),U.extentToBoundingRect(this.layer.fullExtent,this._suspendResumeExtent,this.view.spatialReference)||(this._suspendResumeExtent=null)):this._suspendResumeExtent=null;return this._suspendResumeExtent};b.prototype._updateClippingExtent=
function(a){this._controller&&this._controller.updateClippingArea(a);return!1};b.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};b.prototype._rendererChange=function(a,b){var c=this,e=a?a.requiredFields:[],f=b?b.requiredFields:[];e.length===f.length&&e.every(function(a,b){return e[b]===f[b]})||Object.keys(this._nodesAddedToStage).forEach(function(a){c._removeNodeData({id:a})})};b.prototype._objectIdFilterChange=function(){var a=this;Object.keys(this._nodesAddedToStage).forEach(function(b){a._removeNodeData({id:b})});
this._controller&&this._controller.restartNodeLoading()};b.prototype._definitionExpressionChange=function(){this._definitionExpressionErrors=0};b.prototype._evaluateClause=function(a,b){try{return!!a.calculateValue(b)}catch(d){return this._definitionExpressionErrors<this._maxDefinitionExpressionErrors&&F.error("Error while evaluating definitionExpression: "+d),this._definitionExpressionErrors++,this._definitionExpressionErrors===this._maxDefinitionExpressionErrors&&F.error("Further errors are ignored"),
!1}};b.prototype._filterNode=function(a){var b=this._controller.parsedDefinitionExpression,d;for(d in a.bundles)for(var e=0,f=a.bundles[d];e<f.length;e++)for(var g=0,h=f[e].graphics;g<h.length;g++){var k=h[g];k.visible=null!=b?this._evaluateClause(b,k):!0}};b.prototype.queryExtent=function(a){return this._ensureQueryEngine().queryExtent(a)};b.prototype.queryFeatureCount=function(a){return this._ensureQueryEngine().queryFeatureCount(a)};b.prototype.queryFeatures=function(a){var b=this;return this._ensureQueryEngine().queryFeatures(a).then(function(a){for(var c=
0,d=a.features;c<d.length;c++)d[c].layer=b.layer;return a})};b.prototype.queryObjectIds=function(a){return this._ensureQueryEngine().queryObjectIds(a)};b.prototype._ensureQueryEngine=function(){this._queryEngine||(this._queryEngine=this._createQueryEngine());return this._queryEngine};b.prototype._createQueryEngine=function(){var a=this,b={id:0,index:0,graphic:null};return new S({forAll:function(c,e){a._forAllFeatures(function(a,d,e){b.id=a;b.index=d;b.graphic=e;c(b)},e)},createGraphic:function(a){return a.graphic.clone()},
requestFields:function(b,c,e){return u.whenGraphicAttributes(a.layer,c,a._getObjectIdField(),e,function(){var d=a._getGraphicIndices(b.nodeId,b.bundleNr,c);return{node:a._controller.nodeIndex[b.nodeId],indices:d}})},createExtentBuilder:function(){var b=k.create(k.NEGATIVE_INFINITY),c=a.layer.spatialReference;return{add:function(a){return k.expand(b,a.graphic.geometry)},getExtent:function(){return k.toExtent(b,c)}}}},{enableObjectId:!0,enableOutFields:!!this.layer.objectIdField})};b.prototype.getStats=
function(){var a=this.inherited(arguments)||{};a.nodecount=Object.keys(this._nodesAddedToStage).length;a.featurecount=this.loadedGraphics.length;return a};m([h.property()],b.prototype,"loadedGraphics",void 0);m([h.property()],b.prototype,"layer",void 0);m([h.property()],b.prototype,"hasDraped",null);m([h.property()],b.prototype,"_controller",void 0);m([h.property({dependsOn:["_controller.updating"]})],b.prototype,"updating",void 0);m([h.property({aliasOf:"_controller.updatingPercentage"})],b.prototype,
"updatingPercentageValue",void 0);return b=m([h.subclass("esri.views.3d.layers.SceneLayerGraphicsView3D")],b)}(h.declared(R,K));var X=[{type:"Embedded",params:{type:"points",vertexAttributes:{position:[0,0,0]}}}],W=k.create(k.POSITIVE_INFINITY);return y});