// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../layers/IntegratedMeshLayer ../../../core/arrayUtils ../../../core/watchUtils ../../../core/promiseUtils ../../../core/Logger ../../../core/Collection ../../../core/lang ../../../geometry/support/scaleUtils ../../../symbols/support/unitConversionUtils dojo/_base/lang dojo/has ../../../Graphic ../../../symbols/Symbol3D ../../../tasks/support/Query ./LayerView3D ./i3s/I3SUtil ./i3s/I3SBinaryReader ./i3s/I3SElevationProvider ./i3s/I3SProjectionUtil ./i3s/I3SQueryEngine ./i3s/Highlights ./i3s/FeatureChangeNotifier ./graphics/graphicUtils ./support/LayerViewUpdatingPercentage ../support/projectionUtils ../support/aaBoundingBox ../webgl-engine/Stage ../webgl-engine/lib/Layer ../webgl-engine/lib/Geometry ../webgl-engine/lib/GeometryData ../webgl-engine/lib/Object3D ../webgl-engine/lib/Texture ../webgl-engine/materials/Material ./support/attributeUtils ../webgl-engine/lib/Util ../lib/glMatrix".split(" "),
function(R,Aa,Y,x,A,S,Z,t,E,aa,ba,ca,da,T,ea,fa,B,ga,ha,ia,D,ja,ka,M,la,ma,na,U,oa,L,u,pa,qa,ra,N,sa,K,ta,O,q,G){function ua(n,c,a,b){var d=!1,e;c.encoding===D.DDS_ENCODING_STRING?e=K.DDS_ENCODING:d=!(q.isPowerOfTwo(n.width)&&q.isPowerOfTwo(n.height));n=c.usedByEngineMats.some(function(a){return a.getParams().atlasRegions})||c.atlas;a=(a||!n)&&!d;return{mipmap:a,wrapClamp:n||!c.wrap,disableAnisotropy:n&&a&&b,encoding:e,noUnpackFlip:!0}}var n=pa.ModelContentType,y=aa.getLogger("esri.views.3d.layers.SceneLayerView3D"),
V=[1,1,1,1],va=[.8,.8,.8],wa=[.5,.5,.5];R=function(P){function c(){var a=null!==P&&P.apply(this,arguments)||this;a._queryEngine=null;a._highlights=new ma(a);a._elevationProvider=null;a._featureChangeNotifier=null;a._controllerCreated=!1;a._hasColors=!1;a._hasTextures=!1;a._hasData=!1;a._definitionExpressionErrors=0;a._maxDefinitionExpressionErrors=20;return a}Y(c,P);Object.defineProperty(c.prototype,"hasTexturesOrVertexColors",{get:function(){return this._hasData?this._hasTextures||this._hasColors?
"yes":"probably-not":"unknown"},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"elevationOffset",{get:function(){var a=null!=this.layer?this.layer.elevationInfo:null;if(null!=a&&"absolute-height"===a.mode){var b=da.getMetersPerVerticalUnitForSR(this.layer.spatialReference),d=T.getMetersPerUnit(a.unit);return(a.offset||0)*d/b}return 0},enumerable:!0,configurable:!0});c.prototype.initialize=function(){var a=this;D.checkSceneLayerValid(this.layer);D.checkSceneLayerCompatibleWithView(this.layer,
this.view);this.addResolvingPromise(this.getHeightModelInfoResolvingPromise());var b=this.layer.version,b=!fa("trident")||1<b.major||1===b.major&&3<b.minor;this._useCompressedTextures=this.view.has("s3tc")&&b;this._disableAtlasAnisotropy=(this._enableAtlasMipMaps=this.view.has("standardDerivatives"))&&!this.view.has("shaderTextureLOD");this._initGraphicsController();this.maxGpuMemory=1E3;this.geoMemoryEstimate=this.texMemoryEstimate=this.gpuMemoryEstimate=0;this._stage=this.view._stage;this._matId2Meta=
{};this._texId2Meta={};this._nodeId2Meta={};for(var b=new Uint8Array(256),d=0;d<b.length;d++)b[d]=255;this._whiteTexture=new K(b,"white",{width:8,height:8});this._stage.add(n.TEXTURE,this._whiteTexture);this._addThisLayerToStage();this._elevationProvider=new ka({layerView:this,stageLayer:this._stageLayer});this.handles.add([t.init(this.view,"clippingArea",function(){return a._clippingAreaChanged()}),t.init(this.layer,"renderer",function(b){return a._rendererChange(b)}),t.init(this.layer,"objectIdFilter",
function(){return a._filterChange()}),t.init(this.layer,"elevationInfo",function(){return a._elevationInfoChanged()}),t.init(this,"_controller.parsedDefinitionExpression",function(){return a._filterChange()}),t.watch(this,"fullOpacity",function(b){return a._opacityChange(b)}),t.watch(this,"elevationOffset",function(){return a._elevationOffsetChange()}),t.init(this,"suspended",function(b){return a.setVisibility(!b)})],"sceneLayerHandles")};c.prototype.destroy=function(){this.handles.remove("sceneLayerHandles");
this._stage.remove(n.TEXTURE,this._whiteTexture.getId());this._removeThisLayerFromStage();this._stage=null;null!=this._controller&&(this._controller.destroy(),this._controller=null);this._highlights.destroy();this._nodeId2Meta=this._texId2Meta=this._matId2Meta=null};c.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};c.prototype.isUpdating=function(){return this._controllerCreated?!(!this._controller||!this._controller.updating):
!0};c.prototype.memEstimateTextureAdded=function(a){a=a.getEstimatedTexMemRequiredMB();this.gpuMemoryEstimate+=a;this.texMemoryEstimate+=a};c.prototype.memEstimateTextureRemoved=function(a){a=a.getEstimatedTexMemRequiredMB();this.gpuMemoryEstimate-=a;this.texMemoryEstimate-=a};c.prototype.memEstimateGeometryAdded=function(a){a=a.estimateGpuMemoryUsage()/1E6;this.gpuMemoryEstimate+=a;this.geoMemoryEstimate+=a};c.prototype.memEstimateGeometryRemoved=function(a){a=a.estimateGpuMemoryUsage()/1E6;this.gpuMemoryEstimate-=
a;this.geoMemoryEstimate-=a};c.prototype.isBundleAlreadyAddedToStage=function(a,b){return null!=this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle[b]};c.prototype._initGraphicsController=function(){var a=this;this.layer.createGraphicsController({layerView:this,layerViewRequiredFunctions:{addBundle:function(b,d,e){return a._addBundle(b,d,e)},isBundleAlreadyAddedToStage:function(b,d){return a.isBundleAlreadyAddedToStage(b,
d)},isOverMemory:function(){return a._isOverMemory()},removeNodeData:function(b){return a._removeNodeDataFromStage(b.id)},getAddedNodeIDs:function(){return a._getAddedNodeIDs()},areAllBundlesLoaded:function(b){return a._areAllBundlesLoaded(b)}},layerViewOptionalFunctions:{setPolygonOffset:function(b,d){return a._setPolygonOffset(b,d?1:0)},traversalOptions:{initDepthFirst:!0,neighborhood:!0,perLevelTraversal:!1,allowPartialOverlaps:!1},textureOptions:{useCompressedTextures:this._useCompressedTextures},
getLoadedAttributes:function(b){return a._getLoadedAttributes(b)},setAttributeData:function(b,d,e){return a._setAttributeData(b,d,e)}}}).then(function(b){a._controller=b;a._featureChangeNotifier=new na.FeatureChangeNotifier(a,b);b.watch("rootNodeVisible",function(){a.notifyChange("suspended")})}).always(function(){a._controllerCreated=!0;a.notifyChange("updating")})};c.prototype.setMaxGpuMemory=function(a){this.maxGpuMemory=a};c.prototype.setVisibility=function(a){if(this._stage&&this._stageLayer){var b=
this._stageLayer.getId(),d=0<=this._stage.getViewContent().indexOf(b);!!a!==d&&(b=[b],a?(this._stage.addToViewContent(b),a=this._isIntegratedMesh()?"im":"scene",this.view.elevationProvider.register(a,this._elevationProvider),this._elevationProvider.visibilityChanged()):(this._stage.removeFromViewContent(b),this._elevationProvider.visibilityChanged(),this.view.elevationProvider.unregister(this._elevationProvider)))}};c.prototype.getStats=function(){var a={nodesInIndex:0,knownFeatures:0,activeMaterials:0,
"Total GPU Memory Estimate":this.gpuMemoryEstimate+"MB","Geometry Memory Estimate":this.geoMemoryEstimate+"MB","Texture Memory Estimate":this.texMemoryEstimate+"MB"};if(!this._controller)return a;a.nodesInIndex=Object.keys(this._controller.nodeIndex).length;a.activeMaterials=Object.keys(this._matId2Meta).length;return a};c.prototype._addThisLayerToStage=function(){var a=this._stage;this._initTexture=new K(null,"i3sInitTexture");a.add(n.TEXTURE,this._initTexture);var b=this.layer.id;this._stageLayer=
b=new qa(b,{},b);a.add(n.LAYER,b)};c.prototype._removeThisLayerFromStage=function(){if(null!=this._stageLayer){var a=this._stage;a.remove(n.TEXTURE,this._initTexture.getId());this._removeAllNodeDataFromStage();q.assert(q.objectEmpty(this._nodeId2Meta));q.assert(q.objectEmpty(this._matId2Meta));q.assert(q.objectEmpty(this._texId2Meta));a.remove(n.LAYER,this._stageLayer.getId());this._matId2Meta={};this._texId2Meta={};this._nodeId2Meta={};this._stageLayer=void 0;this.gpuMemoryEstimate=0}};c.prototype._getLoadedAttributes=
function(a){if((a=this._nodeId2Meta[a.id])&&1===a.engineObjects.length)return a.engineObjects[0].getMetadata().loadedAttributes};c.prototype._setAttributeData=function(a,b,d){var e=this._nodeId2Meta[a.id];if(e&&1===e.engineObjects.length){var e=e.engineObjects[0],f=e.getMetadata();f.loadedAttributes=b;f.attributeData=d;this._setObjectSymbology(e);this._applyFilters(a);this._elevationProvider.visibilityChanged(e)}};c.prototype._isOverMemory=function(){if(this.gpuMemoryEstimate>this.maxGpuMemory&&this.gpuMemoryEstimate!==
this.warnGpuMemoryEstimate){this.warnGpuMemoryEstimate=this.gpuMemoryEstimate;var a=function(a){return a.toLocaleString(void 0,{maximumFractionDigits:1})+" Mb"};y.warn("GPU Memory Limit exceeded!\nLimit: "+a(this.maxGpuMemory)+" Current: "+a(this.gpuMemoryEstimate)+"\n(Textures: "+a(this.texMemoryEstimate)+" Geometry: "+a(this.geoMemoryEstimate)+")")}return this.gpuMemoryEstimate>this.maxGpuMemory};c.prototype._getAddedNodeIDs=function(){return Object.keys(this._nodeId2Meta)};c.prototype._calcEngineMaterialTransparencyParams=
function(a,b,d){var e=this.fullOpacity,f=1-q.clamp(q.fallbackIfUndefined(b.transparency,0),0,1);a=1>f||1>e||a&&ca.endsWith(a.channels,"a")||!0===b.useVertexColorAlpha||d;return{opacity:f,layerOpacity:e,transparent:a}};c.prototype._calcEngineMaterialDoubleSidedParams=function(a){return null!=a.doubleSided?a.doubleSided:!0};c.prototype._calcEngineMaterialCullFaceParams=function(a){return a.cullFace?a.cullFace:null!=a.doubleSided?a.doubleSided?"none":"back":"none"};c.prototype._createEngineMaterial=
function(a,b,d,e,f){var g,c;null!=a&&(g=(c=this._texId2Meta[b])&&c.engineTex?c.engineTex.getId():this._initTexture.getId());var k=d.params,m=q.fallbackIfUndefined(k.diffuse,va),l,F;null!=a&&(F=D.getAppropriateTextureEncoding(a.encoding,this._useCompressedTextures),l=-1<F?a.encoding[F]:a.encoding);"standard"!==d.type&&y.warn("Unknown material type '"+d.type+"', must be 'standard'");void 0===k.reflectivity&&y.warn("Material parameter 'reflectivity' is missing.");d=this._isIntegratedMesh();g={ambient:m,
diffuse:m,specular:q.fallbackIfUndefined(k.specular,wa),shininess:q.fallbackIfUndefined(k.shininess,64),atlasRegions:k.vertexRegions,textureId:g,vertexColors:this._hasVertexColors(),symbolColors:this._hasSymbolColors(),flipV:!1,doubleSided:this._calcEngineMaterialDoubleSidedParams(k),cullFace:this._calcEngineMaterialCullFaceParams(k),writeStencil:d,receiveSSAO:!d,groundNormalShading:d};d||(m=this._calcEngineMaterialTransparencyParams(a,k),ea.mixin(g,m));g=new ta(g,e);g.metadata={i3sMatId:e,i3sTexId:b,
i3sTex:a,i3sMatParams:k};if(null!=a&&(c?c.usedByEngineMats.push(g):(c={id:b,usedByEngineMats:[g],images:a.images,encoding:l,encodingIdx:F,atlas:!0===a.atlas,wrap:"none"!==a.wrap[0]||"none"!==a.wrap[1]},this._texId2Meta[b]=c),null!=f[b]))for(null==c.engineTex&&(a=f[b].data,f=ua(a,c,this._enableAtlasMipMaps,this._disableAtlasAnisotropy),c.engineTex=new K(a,c.id,f),this._stage.add(n.TEXTURE,c.engineTex),this.memEstimateTextureAdded(c.engineTex)),a=c.engineTex.getId(),f=0,c=c.usedByEngineMats;f<c.length;f++)c[f].setParameterValues({textureId:a});
this._matId2Meta[e]||(this._matId2Meta[e]={});this._matId2Meta[e][b]={engineMat:g,refCount:1};return g};c.prototype._createVertexArrays=function(a,b,d){var e=a.params.vertexAttributes;a={};for(var f=0,c=Object.keys(e);f<c.length;f++){var h=c[f];if("classification"!==h&&(d||h!==q.VertexAttrConstants.NORMAL)){var k=e[h],m=ja.valueType2TypedArrayClassMap[k.valueType];if(null!=m){var l=new m(b,k.byteOffset,k.count*k.valuesPerElement),m=new m(l);a[h]={data:m,size:k.valuesPerElement}}else y.error("unsupported vertex attribute value type: "+
k.valueType)}}b=Array.isArray(e.position)?e.position.length/3:e.position.count;if(this._hasVertexColors()&&null==a[q.VertexAttrConstants.COLOR])for(e=new Uint8Array(4*b),a[q.VertexAttrConstants.COLOR]={data:e,size:4},f=0;f<e.length;f++)e[f]=255;this._hasSymbolColors()&&(e=new Uint8Array(4*b),a[q.VertexAttrConstants.SYMBOLCOLOR]={data:e,size:4});d&&null==a[q.VertexAttrConstants.NORMAL]&&(e=new Float32Array(3*b),a[q.VertexAttrConstants.NORMAL]={data:e,size:3});return a};c.prototype._hasNonWhiteColors=
function(a){if("color"in a){a=a.color.data;for(var b=0;b<a.length;b++)if(255!==a[b])return!0}return!1};c.prototype._createEngineMats=function(a,b,d){var e=a.params.materialID,f=b.materialDefinitions[e];q.assert(void 0!==f,"geometry wants unknown material "+e);a=a.params.textureID||"none";var c;"none"!==a&&(null!=b.textureDefinitions&&null!=b.textureDefinitions[a]||y.warn("textureDefinitions missing in shared resource"),c=b.textureDefinitions[a]);this._matId2Meta[e]&&this._matId2Meta[e][a]?(d=this._matId2Meta[e][a],
b=d.engineMat,d.refCount++):b=this._createEngineMaterial(c,a,f,e,d);return[b]};c.prototype._areAllBundlesLoaded=function(a){if(null==this._nodeId2Meta[a.id]||null==this._nodeId2Meta[a.id].engineObjectsPerBundle)return!1;for(var b=0;b<a.featureData.length;b++)if(null==this._nodeId2Meta[a.id].engineObjectsPerBundle[b])return!1;return!0};c.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};c.prototype._findGraphicNodeAndIndex=function(a){a=O.attributeLookup(a.attributes,
this._getObjectIdField());for(var b=0,d=Object.keys(this._nodeId2Meta);b<d.length;b++)for(var e=d[b],f=this._nodeId2Meta[e].engineObjects,c=0;c<f.length;c++){var h=f[c].getMetadata().featureIds.indexOf(a);if(-1!==h)return{node:this._controller.nodeIndex[e],nodeId:e,bundleNr:c,index:h}}return null};c.prototype._getGraphicIndices=function(a,b,d){a=this._nodeId2Meta[a.id].engineObjects;if(!a||!a[b])return[];b=a[b].getMetadata();a=[];for(var e=this._getObjectIdField(),c=0;c<d.length;c++){var g=O.attributeLookup(d[c].attributes,
e),g=b.featureIds.indexOf(g);-1!==g&&a.push(g)}return a};c.prototype.whenGraphicBounds=function(a){a=this._findGraphicNodeAndIndex(a);if(null!=a&&(a=this._boundingBoxCornerPoints(a.index,this._nodeId2Meta[a.nodeId].engineObjects[a.bundleNr],new Float64Array(24)),L.bufferToBuffer(a,this.view.renderSpatialReference,0,a,this.view.spatialReference,0,8))){var b=u.create(u.NEGATIVE_INFINITY);u.expandBuffer(b,a,0,8);return E.resolve({boundingBox:b,screenSpaceObjects:[]})}return E.reject()};c.prototype.whenGraphicAttributes=
function(a,b){var d=this;return D.whenGraphicAttributes(this.layer,[a],this._getObjectIdField(),b,function(){var b=d._findGraphicNodeAndIndex(a);return{node:b.node,indices:[b.index]}}).then(function(a){return a[0]})};c.prototype.getGraphicsFromStageObject=function(a,b){if(this.layer instanceof S)return E.reject();var d=a.getMetadata();a=a.getFaceRangeIndexFromTriangleNr(b);return null!=a&&null!=d.featureIds&&a<d.featureIds.length?(d=this._createGraphic(a,d),E.resolve(d)):E.reject()};c.prototype._addBundle=
function(a,b,d){if(this._isOverMemory())return E.reject();var e=d.allGeometryData,c=d.attributeDataInfo,g=d.geometryBuffers,h=d.preloadedDomImages,k=d.sharedResource;d=this._stage;var m={};m[n.OBJECT]={};m[n.GEOMETRY]={};m[n.MATERIAL]={};m[n.TEXTURE]={};var l=this._stageLayer,q=l.getId();if(null!=this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle&&this._nodeId2Meta[a.id].engineObjectsPerBundle[b])return this._applyFilters(a),E.resolve();null==this._nodeId2Meta[a.id]&&(this._nodeId2Meta[a.id]=
{engineObjects:[],engineObjectsPerBundle:[]});this._nodeId2Meta[a.id].engineObjectsPerBundle[b]=[];for(var W=0,Q=this._hasColors,v=0;v<e.length;v++){for(var r=e[v],p=r.faceRanges,xa=r.componentOffsets,w=r.featureIds,y=g[a.geometryData[b].hrefConcat],X=a.id+"|"+w[0],A=[],t=[],x=[],u=void 0,C=function(b){var d=!z._isIntegratedMesh(),e=z._createVertexArrays(b,y,d),c=z._createEngineMats(b,k,h);Q=Q||z._hasNonWhiteColors(e);var f=new N(e,N.DefaultIndices,xa||N.DefaultOffsets),g=z._controller.crsIndex,l=
z._controller.crsVertex,r=z.view.renderSpatialReference,p=G.vec4d.set(a.mbs,ya);p[2]+=z.elevationOffset;u=M.reprojectPoints(M.ReprojectionTypes.PER_VERTEX,e.position.data,p,g,l,r);d&&z._controller.isMeshPyramid&&D.processNormals({normals:f.vertexAttributes.normal.data,positions:f.vertexAttributes.position.data,normalInd:f.indices.normal,positionInd:f.indices.position},z.layer.normalReferenceFrame||"none",function(a,b){return M.reprojectNormalsPerVertex(a,p,g,b,r)});d=u.localTrafo;null!=b.transformation&&
(b=G.mat4d.create(b.transformation),G.mat4d.multiply(d,b,d));b=A.length;f=new ra(f,X+(0<b?"_"+b:""));A.push(f);t.push(d);x.push(c);z.memEstimateGeometryAdded(f.getData());for(b=0;b<c.length;b++)d=c[b],m[n.MATERIAL][d.getId()]=d;m[n.GEOMETRY][f.getId()]=f},z=this,H=0,r=r.geometries;H<r.length;H++)C(r[H]);p={i3sNode:a.id,ceLayer:q,faceRanges:p,featureIds:w,attributeData:c?c.attributeData:null,loadedAttributes:c?c.loadedAttributes:null,layerUid:this.layer.uid};W+=null!=p.featureIds?p.featureIds.length:
1;p=new sa({idHint:a.id,name:X,geometries:A,materials:x,transformations:t,castShadow:!0,metadata:p});w=G.mat4d.create();G.mat4d.identity(w);G.mat4d.multiply(w,u.globalTrafo,w);p.setObjectTransformation(w);this._nodeId2Meta[a.id].engineObjectsPerBundle[b].push(p);this._nodeId2Meta[a.id].engineObjects.push(p);m[n.OBJECT][p.getId()]=p;this._setObjectSymbology(p);this._applyFilters(a);this._highlights.objectCreated(p);this._elevationProvider.objectCreated(p)}d.beginMod();b=m[n.OBJECT];for(var I in b)b.hasOwnProperty(I)&&
l.addObject(b[I]);for(var J in m)if(m.hasOwnProperty(J)){I=m[J];for(var B in I)I.hasOwnProperty(B)&&null==d.get(J,B)&&d.add(J,I[B])}d.endMod();!this._hasTextures&&null!=a.textureData&&0<a.textureData.length&&(this._hasTextures=!0);this._hasColors=Q;this._hasData=!0;this.notifyChange("hasTexturesOrVertexColors");this._featureChangeNotifier.notify(W,0);return E.resolve()};c.prototype._clippingAreaChanged=function(){var a=this,b=[];L.extentToBoundingBox(this.view.clippingArea,b,this.view.renderSpatialReference)?
this._clippingArea=b:this._clippingArea=null;this._updateFilters();if(this._controller){var d=this._controller.nodeIndex;d&&Object.keys(this._nodeId2Meta).forEach(function(b){return a._applyFilters(d[b])});this._controller.updateClippingArea(this.view.clippingArea)}};c.prototype._filterChange=function(){this._updateFilters();if(this._controller){var a=this._controller.nodeIndex;if(a)for(var b=0,d=Object.keys(this._nodeId2Meta);b<d.length;b++)this._applyFilters(a[d[b]])}};c.prototype._updateFilters=
function(){var a=this,b=[];if(this.layer.objectIdFilter){var d=new Float64Array(this.layer.objectIdFilter.ids),e="include"===this.layer.objectIdFilter.method;d.sort();b.push(function(b,c){return a._objectIdFilter(d,e,c)})}if(this._controller&&this._controller.parsedDefinitionExpression&&this._controller.definitionExpressionFields){this._definitionExpressionErrors=0;var c=this._controller.parsedDefinitionExpression,g=this._controller.definitionExpressionFields;b.push(function(b,d){return a._sqlFilter(b,
c,g,d)})}this._clippingArea&&b.push(function(b,d){return a._boundingboxFilter(b,a._clippingArea,d)});this._filters=b};c.prototype._sqlFilter=function(a,b,d,e){var c={},g=new B(null,null,c);g.layer=this.layer;var h=this.layer.objectIdField,k=0,m=0,l=function(a){var f=a.getMetadata();a=f.featureIds;for(var l=f.attributeData,f=d.every(function(a){return null!=l[a]||a===h}),p=0;p<a.length&&k<e.length;p++)if(e[k]===a[p]){var n=!0;if(f){c[h]=a[p];for(var n=0,w=d;n<w.length;n++){var F=w[n];F!==h&&(c[F]=
D.getCachedAttributeValue(l[F],p))}n=q._evaluateClause(b,g)}n&&(e[m]=e[k],m++);k++}},q=this,n=0;for(a=this._nodeId2Meta[a.id].engineObjects;n<a.length;n++)l(a[n]);e.length=m};c.prototype._evaluateClause=function(a,b){try{return a.testFeature(b)}catch(d){return this._definitionExpressionErrors<this._maxDefinitionExpressionErrors&&y.error("Error while evaluating definitionExpression: "+d),this._definitionExpressionErrors++,this._definitionExpressionErrors===this._maxDefinitionExpressionErrors&&y.error("Further errors are ignored"),
!1}};c.prototype._objectIdFilter=function(a,b,d){for(var e=0,c=0;e<d.length;)0<=Z.binaryIndexOf(a,d[e])===b&&(d[c]=d[e],c++),e++;d.length=c};c.prototype._boundingboxFilter=function(a,b,d){var e=[0,0,0,0];L.mbsToMbs(a.mbs,this._controller.crsIndex,e,this.view.renderSpatialReference);e=null!=b?D.intersectBoundingBoxWithMbs(b,e):2;if(2!==e){var c=0,g=0;for(a=this._nodeId2Meta[a.id].engineObjects;g<a.length;g++){var h=a[g],k=h.getMetadata().featureIds;if(0===e){for(var m=0,h=0;h<k.length&&c+m<d.length;h+=
1)d[c+m]===k[h]&&m++;d.splice(c,m)}else{var l=h.getObjectTransformation(),m=h.getGeometryRecords()[0].getShaderTransformation();G.mat4d.multiply(l,m);if(0===l[1]&&0===l[2]&&0===l[3]&&0===l[4]&&0===l[6]&&0===l[7]&&0===l[8]&&0===l[9]&&0===l[11]&&1===l[15])for(var m=(b[0]-l[12])/l[0],n=(b[1]-l[13])/l[5],q=(b[2]-l[14])/l[10],A=(b[3]-l[12])/l[0],v=(b[4]-l[13])/l[5],l=(b[5]-l[14])/l[10],r=h.getGeometryRecords()[0].geometry.getData(),p=r.getFaces()[0].indices.position,r=r.getVertexAttr().position.data,y=
h.getMetadata().faceRanges,w=void 0,t=void 0,u=void 0,x=void 0,B=void 0,C=void 0,h=0;h<y.length&&c<d.length;h+=1)if(d[c]===k[h]){for(var w=y[h],E=w[0],K=w[1],w=t=u=Number.MAX_VALUE,x=B=C=-Number.MAX_VALUE;E<=K;E+=1)for(var z=0;3>z;z+=1)var H=3*p[3*E+z],I=r[H],J=r[H+1],H=r[H+2],w=Math.min(I,w),t=Math.min(J,t),u=Math.min(H,u),x=Math.max(I,x),B=Math.max(J,B),C=Math.max(H,C);w>A||x<m||t>v||B<n||u>l||C<q?d.splice(c,1):c++}}}}};c.prototype._applyFilters=function(a){if(this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjects){for(var b=
this._nodeId2Meta[a.id].engineObjects,d=0;d<b.length;d++){var e=b[d];e.unhideAllComponents()}if(0!==this._filters.length){for(var d=[],c=0;c<b.length;c++)e=b[c],d=d.concat(e.getMetadata().featureIds);e=d.length;for(c=0;c<this._filters.length;c++)this._filters[c](a,d);if(d.length!==e)for(c=a=0;c<b.length;c++)for(var e=b[c],g=e.getGeometryRecords()[0],h=e.getMetadata().featureIds,k=0;k<h.length;k+=1){var m=h[k];a>=d.length||d[a]!==m?e.setComponentVisibility(g,k,!1):a++}}}};c.prototype._removeAllNodeDataFromStage=
function(){for(var a=0,b=Object.keys(this._nodeId2Meta);a<b.length;a++)this._removeNodeDataFromStage(b[a])};c.prototype._removeNodeDataFromStage=function(a){if(null!=this._nodeId2Meta[a]&&null!=this._nodeId2Meta[a].engineObjects){for(var b=this._stage,d=this._stageLayer,c=0,f=this._nodeId2Meta[a].engineObjects,g=0;g<f.length;++g){var h=f[g];this._highlights.objectDeleted(h);this._elevationProvider.objectDeleted(h);var k=h.getMetadata(),c=c+(null!=k.featureIds?k.featureIds.length:1);d.removeObject(h);
for(var k=h.getGeometryRecords(),m=0;m<k.length;m++){var l=k[m];this.memEstimateGeometryRemoved(l.geometry.getData());b.remove(n.GEOMETRY,l.geometry.getId());for(var F=0;F<l.materials.length;F++){var t=l.materials[F],u=t.getId(),v=t.metadata.i3sMatId,r=t.metadata.i3sTexId||"none",p=this._matId2Meta[v][r];q.assert(0<p.refCount);p.refCount--;0===p.refCount&&this._removeMaterial(u,r,v,t,b)}}b.remove(n.OBJECT,h.getId())}delete this._nodeId2Meta[a];this._featureChangeNotifier.notify(0,c)}};c.prototype._removeMaterial=
function(a,b,d,c,f){f.remove(n.MATERIAL,a);if("none"!==b){a=this._texId2Meta[b];var e=a.usedByEngineMats;c=e.indexOf(c);q.assert(-1<c);e[c]=e[e.length-1];e.pop();1>e.length&&((c=a.engineTex)&&c!==this._initTexture&&(this.memEstimateTextureRemoved(c),f.remove(n.TEXTURE,a.engineTex.getId())),a.engineTex=void 0,delete this._texId2Meta[b])}delete this._matId2Meta[d][b];q.objectEmpty(this._matId2Meta[d])&&delete this._matId2Meta[d]};c.prototype._setPolygonOffset=function(a,b){if(null!=this._nodeId2Meta[a.id]&&
null!=this._nodeId2Meta[a.id].engineObjectsPerBundle){b={polygonOffset:b};for(var d=0;d<this._nodeId2Meta[a.id].engineObjectsPerBundle.length;d++)for(var c=this._nodeId2Meta[a.id].engineObjectsPerBundle[d],f=0;f<c.length;f++)for(var g=c[f].getGeometryRecords(),h=0;h<g.length;h++)for(var k=g[h].materials,m=0;m<k.length;m++)k[m].setParameterValues(b)}};c.prototype._rendererChange=function(a){(this._currentRenderer=a)&&(a.colorInfo||a.sizeInfo)&&y.warn("renderer.colorInfo and renderer.sizeInfo are not supported for Scene Services. Use visualVariables instead.");
if(a){var b=0;for(a=a.getSymbols();b<a.length;b++){var d=a[b];"mesh-3d"!==d.type&&y.error("Symbols of type '"+d.type+"' are not supported for 3D Object Scene Services.")}}};c.prototype._getRenderingInfo=function(a){var b=this._currentRenderer,d=b&&b.getSymbol(a);if(!(d instanceof ga))return null;var d={symbol:d},c,f;if(b&&b.visualVariables)for(a=b.getVisualVariableValues(a),b=0;b<a.length;b++){var g=a[b],h=g.variable.type;"color"===h?c=g.value:"opacity"===h&&(f=g.value)}c&&(d.color=[c.r/255,c.g/255,
c.b/255]);null!=f?d.opacity=f:c&&null!=c.a&&(d.opacity=c.a);return d};c.prototype._getSymbolFillColor=function(a){var b=0;for(a=a.symbolLayers.items;b<a.length;b++){var d=a[b];if("fill"===d.type&&(d=d.material,d=null!=d?d.color:null,null!=d))return[d.r/255,d.g/255,d.b/255,d.a]}return null};c.prototype._getSymbolFillColorMixMode=function(a){var b=0;for(a=a.symbolLayers.items;b<a.length;b++){var d=a[b];if("fill"===d.type&&(d=d.material,d=null!=d?d.colorMixMode:null,null!=d))return d}return null};c.prototype._hasSymbolColors=
function(){return!this._isIntegratedMesh()};c.prototype._isIntegratedMesh=function(){return this.layer instanceof S};c.prototype._hasVertexColors=function(){return null!=this.layer.store.defaultGeometrySchema.vertexAttributes.color&&(null==this.layer.cachedDrawingInfo||!this.layer.cachedDrawingInfo.color)};c.prototype._setObjectSymbology=function(a){if(this._hasSymbolColors()){for(var b=a.getMetadata(),d=b.faceRanges?b.faceRanges.length:1,c=new B(null,null,{}),f=c.attributes,g=this.layer.objectIdField,
h=this._currentRenderer&&this._currentRenderer.requiredFields,k=a.geometryRecords[0].geometry.data.vertexAttributes[q.VertexAttrConstants.SYMBOLCOLOR].data,m=!1,l=new Uint8Array(4),n=0;n<d;n++){null!=g&&null!=b.featureIds&&(f[g]=b.featureIds[n]);if(null!=h&&null!=b.attributeData)for(var t=0,u=h;t<u.length;t++){var v=u[t];null!=b.attributeData[v]&&(f[v]=D.getCachedAttributeValue(b.attributeData[v],n))}var r=this._getRenderingInfo(c),t=null!=b.faceRanges?b.faceRanges[n]:null;if(r){var u=this._getSymbolFillColorMixMode(r.symbol),
v=r.color,p=r.opacity;null==v||null==p?(r=this._getSymbolFillColor(r.symbol),v=U.overrideColor(v,p,r,r&&r[3],V)):v=U.overrideColor(v,p,null,null,V);1>v[3]&&(m=!0);D.encodeSymbolColor(v,u,l)}else D.encodeSymbolColor(null,null,l);this._setFaceRangeColor(t,k,l)}a.geometryColorAttrsUpdated(0);a=a.getGeometryRecords();for(b=0;b<a.length;b++)for(d=a[b],c=0;c<d.materials.length;c++)f=d.materials[c],g=f.getParams().transparent,h=f.getParams().opacity,f.metadata.symbolIsTransparent=m,k=this._calcEngineMaterialTransparencyParams(f.metadata.i3sTex,
f.metadata.i3sMatParams,f.metadata.symbolIsTransparent),g===k.transparent&&h===k.opacity||f.setParameterValues({transparent:k.transparent,opacity:k.opacity})}};c.prototype._setFaceRangeColor=function(a,b,d){var c=12*a[1]+12;for(a=12*a[0];a<c;a+=4)b[a+0]=d[0],b[a+1]=d[1],b[a+2]=d[2],b[a+3]=d[3]};c.prototype._elevationInfoChanged=function(){var a=this.layer.elevationInfo&&this.layer.elevationInfo.unit;a&&!T.supportsUnit(a)&&y.warn("elevationInfo.unit","'"+a+"' is not a valid unit")};c.prototype._elevationOffsetChange=
function(){this._removeAllNodeDataFromStage();null!=this._controller&&this._controller.restartNodeLoading()};c.prototype._opacityChange=function(a){for(var b in this._matId2Meta)for(var d in this._matId2Meta[b]){a=this._matId2Meta[b][d].engineMat;var c=a.getParams(),f=this._calcEngineMaterialTransparencyParams(a.metadata.i3sTex,a.metadata.i3sMatParams,a.metadata.symbolIsTransparent);c.transparent===f.transparent&&c.layerOpacity===f.layerOpacity||a.setParameterValues(f)}};c.prototype.queryExtent=function(a){return this._ensureQueryEngine().queryExtent(a)};
c.prototype.queryFeatureCount=function(a){return this._ensureQueryEngine().queryFeatureCount(a)};c.prototype.queryFeatures=function(a){return this._ensureQueryEngine().queryFeatures(a)};c.prototype.queryObjectIds=function(a){return this._ensureQueryEngine().queryObjectIds(a)};c.prototype._ensureQueryEngine=function(){this._queryEngine||(this._queryEngine=this._createQueryEngine());return this._queryEngine};c.prototype._createQueryEngine=function(){var a=this,b={id:0,index:0,object:null,bbCorners:new Float64Array(24)};
return new la({forAll:function(d,c){a._forAllFeatures(function(c,e,h){b.id=c;b.index=e;b.object=h;a._boundingBoxCornerPoints(b.index,b.object,b.bbCorners);d(b)},c)},createGraphic:function(b){return a._createGraphic(b.index,b.object.getMetadata())},requestFields:function(b,c,f){return D.whenGraphicAttributes(a.layer,c,a._getObjectIdField(),f,function(){var d=a._getGraphicIndices(b.node,b.bundleNr,c);return{node:b.node,indices:d}})},createExtentBuilder:function(){return a._createExtentBuilder()}},{enableObjectId:!0,
enableOutFields:!!this.layer.objectIdField})};c.prototype._createExtentBuilder=function(){var a=this.view.renderSpatialReference,b=this.view.spatialReference,c=u.create(u.NEGATIVE_INFINITY),e=new Float64Array(24);return{add:function(d){L.bufferToBuffer(d.bbCorners,a,0,e,b,0,8)&&u.expandBuffer(c,e,0,8)},getExtent:function(){return u.toExtent(c,b)}}};c.prototype._forAllFeatures=function(a,b,c){for(var d=0,f=Object.keys(this._nodeId2Meta);d<f.length;d++)for(var g=f[d],h=this._nodeId2Meta[g].engineObjects,
k=0;k<h.length;k++)this._forAllFeaturesOfObject(h[k],a,c),b&&b({node:this._controller.nodeIndex[g],bundleNr:k})};c.prototype._forAllFeaturesOfObject=function(a,b,c){for(var d=a.getMetadata().featureIds,f=a.getGeometryRecords()[0],g=0;g<d.length;g++)(c||a.getComponentVisibility(f,g))&&b(d[g],g,a,f)};c.prototype._createGraphic=function(a,b){var c={};null!=b.featureIds&&(c[this._getObjectIdField()]=b.featureIds[a]);if(null!=b.attributeData)for(var e=0,f=Object.keys(b.attributeData);e<f.length;e++){var g=
f[e];c[g]=D.getCachedAttributeValue(b.attributeData[g],a)}a=new B(null,null,c);a.layer=this.layer;return a};c.prototype._boundingBoxCornerPoints=function(a,b,c){a=b.geometries[0].getComponentAABB(a,za);for(var d=0;8>d;++d)C[0]=d&1?a[0]:a[3],C[1]=d&2?a[1]:a[4],C[2]=d&4?a[2]:a[5],G.mat4d.multiplyVec3(b.objectTransformation,C),c[3*d]=C[0],c[3*d+1]=C[1],c[3*d+2]=C[2];return c};c.prototype.highlight=function(a,b){var c=this,e=this._highlights;if(a instanceof ha){b=e.acquireSet(b);var f=b.set,g=b.handle;
this.queryObjectIds(a).then(function(a){return e.setFeatureIds(f,a)});return g}if("number"===typeof a||a instanceof B)return this.highlight([a],b);a instanceof ba&&(a=a.toArray());if(Array.isArray(a)&&0<a.length){if(a[0]instanceof B)return a=a.map(function(a){return O.attributeLookup(a.attributes,c._getObjectIdField())}),g=e.acquireSet(b),b=g.set,g=g.handle,e.setFeatureIds(b,a),g;if("number"===typeof a[0])return g=e.acquireSet(b),b=g.set,g=g.handle,e.setFeatureIds(b,a),g}return{remove:function(){}}};
x([A.property()],c.prototype,"layer",void 0);x([A.property()],c.prototype,"_controller",void 0);x([A.property({dependsOn:["_controller.updating"]})],c.prototype,"updating",void 0);x([A.property({readOnly:!0,aliasOf:"_controller.updatingPercentage"})],c.prototype,"updatingPercentageValue",void 0);x([A.property({readOnly:!0})],c.prototype,"hasTexturesOrVertexColors",null);x([A.property({readOnly:!0,dependsOn:["layer.elevationInfo"]})],c.prototype,"elevationOffset",null);return c=x([A.subclass("esri.views.3d.layers.SceneLayerView3D")],
c)}(A.declared(ia,oa));var C=G.vec3d.create(),za=[0,0,0,0,0,0],ya=G.vec4d.create();return R});