// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper dojo/promise/all dojo/errors/CancelError ../../../views/3d/support/ResourceController ../../../core/sql/WhereClause ../../../views/3d/layers/i3s/I3SNodeLoader ../../../views/3d/layers/i3s/I3SIndexTraversal ../../../views/3d/layers/i3s/I3SUtil ../../../views/3d/layers/i3s/I3SLodHandling ../../../views/3d/layers/i3s/I3SViewportQueries ../../../views/3d/layers/i3s/IdleQueue ../../../layers/SceneLayer ../../../layers/IntegratedMeshLayer ../../../core/accessorSupport/decorators ../../../core/Accessor ../../../core/Evented ../../../core/Promise ../../../core/Logger ../../../core/promiseUtils ../../../core/watchUtils ../../../core/HandleRegistry ../../../views/3d/support/PromiseLightweight ../../../views/3d/support/projectionUtils ../../../views/3d/lib/glMatrix".split(" "),
function(L,M,n,e,p,q,r,t,u,v,h,w,x,y,z,A,d,B,C,D,E,F,G,H,I,J,g){function l(d,b){b=b.toLowerCase();for(var a=0;a<d.length;a++)if(d[a].name.toLowerCase()===b)return a;return-1}var k=E.getLogger("esri.layers.graphics.controllers.I3SOnDemandController");return function(m){function b(a){a=m.call(this)||this;a.nodeIndex={};a.screenSizeFactor=0;a.updating=!0;a.updatingPercentage=0;a._lodFactorProperty=null;a._isIdle=!1;a._computedMbs={};a._numNodesLoading=0;a._numAttributesLoading=0;a._progressMaxNumNodes=
1;a._poi=null;a._requiredAttributesDirty=!0;a._updatesDisabled=!1;a._restartNodeLoading=!1;a._handles=new H;a._idleQueue=new y.IdleQueue;return a}n(b,m);Object.defineProperty(b.prototype,"isMeshPyramid",{get:function(){return"mesh-pyramids"===this.layer.profile||"MeshPyramid"===this.layer.store.lodType},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"streamDataSupplier",{get:function(){return this.layerView.view.resourceController.registerClient(this.layerView,r.ClientType.SCENE,
{addUrlToken:this.addUrlToken,trackRequests:!0})},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"parsedDefinitionExpression",{get:function(){if(this.layer&&this.layer.definitionExpression)try{var a=t.create(this.layer.definitionExpression);if(!a.isStandardized())return k.error("definitionExpression is using non standard function"),null;var c=[],b=a.getFields();h.findFieldsCaseInsensitive(b,this.layer.fields,c);return 0<c.length?(k.error("definitionExpression references unknown fields: "+
c.join(", ")),null):a}catch(f){return k.error("Failed to parse definitionExpression: "+f),null}else return null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"definitionExpressionFields",{get:function(){if(this.parsedDefinitionExpression){var a=this.parsedDefinitionExpression.getFields();return h.findFieldsCaseInsensitive(a,this.layer.fields)}return null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"crsVertex",{get:function(){return h.getVertexCrs(this.layer)},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"crsIndex",{get:function(){return h.getIndexCrs(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"rootNodeVisible",{get:function(){var a=this._rootNodeId&&this.nodeIndex[this._rootNodeId];return a&&this._viewportQueries?this._viewportQueries.isNodeVisible(a):!0},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;this.updateEventListener={needsUpdate:function(){return a._needsAnimationFrameHandler()},
idleFrame:function(c){return a._animationFrameHandler(c)},idleBegin:function(){a._startNodeLoading();a._updateIdleState(!0)},idleEnd:function(){a.cancelNodeLoading();a._updateIdleState(!1)}};this.updateEventListenerWhileSuspended={idleBegin:function(){return a._startNodeLoadingWhileSuspended()}};this._lodHandling=new w(this.layerViewRequiredFunctions,this.layerViewOptionalFunctions,function(){return a._evaluateUpdatingState()});this.layerView._controller=this;var c=this.layer;this._defaultGeometrySchema=
c.store.defaultGeometrySchema;this._fields=c.fields;this._attributeStorageInfo=c.attributeStorageInfo;this._rootNodeUrl=c.store.rootNode;c=this._rootNodeUrl.split("/");this._rootNodeId=c[c.length-1];this.layer instanceof z?"mesh"===this.layer.geometryType?this._lodFactorProperty="qualitySettings.sceneService.3dObject.lodFactor":"point"===this.layer.geometryType&&(this._lodFactorProperty="qualitySettings.sceneService.point.lodFactor"):this.layer instanceof A&&(this._lodFactorProperty="qualitySettings.sceneService.integratedMesh.lodFactor");
this._centerOnSurface=this.layerView.view.pointsOfInterest.centerOnSurfaceFrequent;c=p([this.layer,this.layerView]).then(function(){if(!a.destroyed&&a.layerView&&!a.layerView.destroyed){a.setClippingArea(a.layerView.view.clippingArea);var c=a.layerView.view.resourceController,b=!1;a._handles.add(G.init(a.layerView,"suspended",function(K){b&&c.deregisterIdleFrameWorker(a);K?c.registerIdleFrameWorker(a,a.updateEventListenerWhileSuspended):c.registerIdleFrameWorker(a,a.updateEventListener);b=!0}),"layerview");
var d=a.layerView.view.pointsOfInterest;a._handles.add([a._centerOnSurface.watch("renderLocation",function(){return a._pointOfInterestChanged()}),d.events.on("camera-parameters-changed",function(){return a.restartNodeLoading()})],"view");a._handles.add(a.layer.watch("elevationInfo",function(c){return a._elevationInfoChanged(c)}),"layer");a._lodFactorProperty&&a._handles.add(a.layerView.view.watch(a._lodFactorProperty,function(){return a._qualityChanged()}),"quality")}});this.addResolvingPromise(c)};
b.prototype.destroy=function(){this.layerView.view.resourceController.deregisterIdleFrameWorker(this);this.layerView.view.resourceController.deregisterClient(this.layerView);this._handles.destroy();this._nodeLoader=null};b.prototype._getRequiredAttributes=function(){if(null==this._attributeStorageInfo||!this._fields)return[];var a=Object.create(null);this.layer.renderer&&this.layer.renderer.collectRequiredFields(a);this.layer.labelsVisible&&this.layer.labelingInfo&&this.layer.labelingInfo.forEach(function(c){c._collectRequiredFields(a)});
if(null!=this.definitionExpressionFields)for(var c=0,b=this.definitionExpressionFields;c<b.length;c++)a[b[c]]=!0;var f=this._attributeStorageInfo,d=this._fields,e=this.layer.objectIdField;return Object.keys(a).map(function(a){var c=l(f,a);a=l(d,a);return 0<=c&&0<=a?{index:c,name:d[a].name,field:d[a],attributeStorageInfo:f[c]}:null}).filter(function(a){return null!=a&&a.name!==e}).sort(function(a,c){return c.index-a.index}).filter(function(a,c,b){return 0===c||b[c-1].index!==a.index})};b.prototype._requiredFieldsChange=
function(){this._requiredAttributesDirty=!0;this.restartNodeLoading()};b.prototype._labelingChanged=function(){var a=this._requiredAttributes,c=this._getRequiredAttributes();a.length===c.length&&a.every(function(a){return 0<=l(c,a.name)})||this._requiredFieldsChange()};b.prototype.setClippingArea=function(a){var c=[];J.extentToBoundingBox(a,c,this.layerView.view.renderSpatialReference)?this._clippingArea=c:this._clippingArea=null};b.prototype._qualityChanged=function(){this.restartNodeLoading()};
b.prototype._pointOfInterestChanged=function(){this._poi&&(this._calculatePointOfInterest(this._poi),this._indexLoader&&this._indexLoader.updatePointOfInterest(this._poi))};b.prototype._calculatePointOfInterest=function(a){void 0===a&&(a=g.vec3d.create());var c=g.vec3d.create(),b=g.vec3d.create(),f=this._centerOnSurface.renderLocation,d=this.layerView.view.renderCoordsHelper;g.vec3d.subtract(f,this.camPos,c);g.vec3d.normalize(c);d.worldUpAtPosition(f,b);c=Math.acos(g.vec3d.dot(b,c))-.5*Math.PI;g.vec3d.lerp(this.camPos,
f,Math.max(0,Math.min(1,c/(.5*Math.PI))),a);return a};b.prototype.updateClippingArea=function(a){this.setClippingArea(a);this.restartNodeLoading()};b.prototype.getBaseUrl=function(){return h.addTrailingSlash(this.layer.parsedUrl.path)};b.prototype.updateElevationChanged=function(a,c,b){h.findIntersectingNodes(a,c,this.nodeIndex.root,this.crsIndex,this.nodeIndex,b);for(a=0;a<b.length;a++)c=b.data[a],this._computedMbs[c.id]&&(this._computedMbs[c.id][3]=-1),c.id===this._rootNodeId&&this.notifyChange("rootNodeVisible");
b.length&&this.restartNodeLoading()};b.prototype._elevationInfoChanged=function(a){a=0;for(var c=Object.keys(this._computedMbs);a<c.length;a++)this._computedMbs[c[a]][3]=-1;this._initViewData()};b.prototype.restartNodeLoading=function(){this._restartNodeLoading=!0;this._evaluateUpdatingState()};b.prototype.schedule=function(){return this._idleQueue.push()};b.prototype._needsAnimationFrameHandler=function(){return!0};b.prototype._animationFrameHandler=function(a){this._restartNodeLoading&&(this.cancelNodeLoading(),
this._startNodeLoading());if(null!=this._nodeLoader){var c=5-this._numNodesLoading;for(null!=this._indexLoader&&0<c&&this._indexLoader.continueTraversal(c);0<this._idleQueue.length()&&!a.done();)this._idleQueue.process();this._evaluateUpdatingState();this._lodHandling.lodGlobalHandling()}};b.prototype._evaluateUpdatingState=function(){var a=null!=this._indexLoader?this._indexLoader.getQueueSize()+3*this._numNodesLoading:0,c=!(!(0<a||0<this._numAttributesLoading||this._indexLoader&&this._indexLoader.isLoading()||
this._restartNodeLoading||0<this._idleQueue.length()||this._lodHandling&&this._lodHandling.requiresLODGlobalHandling)&&this._isIdle);0===a&&(this._progressMaxNumNodes=1);this._progressMaxNumNodes=Math.max(a,this._progressMaxNumNodes);c!==this._get("updating")&&this._set("updating",c);a=100*a/this._progressMaxNumNodes;a!==this._get("updatingPercentage")&&this._set("updatingPercentage",a)};b.prototype._initViewData=function(){var a=this.layerView.view,c=a.navigation.currentCamera,b=a.renderCoordsHelper;
this.camPos=g.vec3d.create(a.pointsOfInterest.renderPointOfView);this.screenSizeFactor=1/c.perPixelRatio;this._poi=this._calculatePointOfInterest();var f=this._lodFactorProperty&&this.layerView.view.get(this._lodFactorProperty)||1;this._viewportQueries=new x(this._computedMbs,this.crsIndex,b,c,this._clippingArea,null!=this.layerViewOptionalFunctions.traversalOptions?this.layerViewOptionalFunctions.traversalOptions.errorMetricPreference:null,a.elevationProvider,this.layer.elevationInfo,{screenspaceErrorBias:f,
maxDistance:25E7,angleDependentLoD:.5>f});this.notifyChange("rootNodeVisible")};b.prototype._startNodeLoadingWhileSuspended=function(){var a=this;this._initViewData();this._removeInvisibleNodes(function(c){return a._viewportQueries.isNodeVisible(c)})};b.prototype._startNodeLoading=function(){var a=this;this._restartNodeLoading=!1;if(!this._updatesDisabled&&null!=this.streamDataSupplier){this._initViewData();var c=this.layerViewOptionalFunctions.textureOptions,b=this.isMeshPyramid&&null!=this._defaultGeometrySchema&&
null!=this._defaultGeometrySchema.ordering;null!=this.layerViewOptionalFunctions.getLoadedAttributes&&this._requiredAttributesDirty&&(this._requiredAttributes=this._getRequiredAttributes(),this._requiredAttributesDirty=!1,this._handles.add([this.layer.watch("renderer",function(){return a._requiredFieldsChange()}),this.layer.watch("definitionExpression",function(){return a._requiredFieldsChange()}),this.layer.watch("labelsVisible",function(){return a._labelingChanged()}),this.layer.watch("labelingInfo",
function(){return a._labelingChanged()})],"requiredAttributes"));this._nodeLoader=new u(this.streamDataSupplier,null!=c?c.useCompressedTextures:!1,k,this._defaultGeometrySchema,this._requiredAttributes,b);this._indexLoader=new v(this.getBaseUrl(),this._rootNodeUrl,this._rootNodeId,this._poi,this.nodeIndex,this.streamDataSupplier,this._viewportQueries,function(c){return a._processNodeIndexDocument(c)},function(c){return a._lodHandling.finishedLevel(c)},k,this.layerViewOptionalFunctions.traversalOptions);
this._indexLoader.start();this._removeInvisibleNodes(function(c){return a._indexLoader.nodeIsVisible(c)});c=this.layerViewOptionalFunctions.traversalOptions;this._lodHandling.startNodeLoading(function(c){return a._indexLoader.nodeIsVisible(c)},function(c){return a._indexLoader.nodeTraversalState(c)},this.nodeIndex,this._rootNodeId,{mode:null!=c&&c.perLevelTraversal?"perLevel":"global",allowPartialOverlaps:!!c.allowPartialOverlaps});this.layerViewOptionalFunctions.additionalStartNodeLoadingHandler&&
this.layerViewOptionalFunctions.additionalStartNodeLoadingHandler();this._evaluateUpdatingState()}};b.prototype.isNodeLoading=function(){return null!=this._nodeLoader&&null!=this._indexLoader};b.prototype.cancelNodeLoading=function(){this.isNodeLoading()&&(this._indexLoader.cancel(),this._nodeLoader.cancel(),this.streamDataSupplier.cancelAll(),this._idleQueue.cancelAll(),this._numNodesLoading=0,this._indexLoader=this._nodeLoader=void 0,this._poi=null,this.layerViewOptionalFunctions.additionalCancelNodeLoadingHandler&&
this.layerViewOptionalFunctions.additionalCancelNodeLoadingHandler(),this._evaluateUpdatingState())};b.prototype._removeInvisibleNodes=function(a){for(var c={},b=this.layerViewRequiredFunctions.getAddedNodeIDs(),f=0;f<b.length;f++){var d=b[f],e=this.nodeIndex[d];this._isNodeVisibleWithParents(e,a)?c[d]=e:this._removeNodeData(e)}return c};b.prototype._isNodeVisibleWithParents=function(a,c){var b=a;do a=c(b),b=b.parentNode,b=null!=b?this.nodeIndex[b.id]:null;while(a&&null!=b);return a};b.prototype._removeNodeData=
function(a){this._lodHandling.setLodGlobalDirty();this.layerViewRequiredFunctions.removeNodeData(a)};b.prototype._processNodeIndexDocument=function(a){var c=this,b=new I.Promise;if(null!=a.featureData&&0<a.featureData.length)if(this.layerViewRequiredFunctions.areAllBundlesLoaded(a)){var d=this.layerViewOptionalFunctions.getLoadedAttributes,d=null!=d?d(a):void 0;null!=d&&d!==this._requiredAttributes&&(this._nodeLoader.loadAttributes(a,a.baseUrl,this._requiredAttributes).then(function(b){c.layerViewOptionalFunctions.setAttributeData(a,
c._requiredAttributes,b)}).otherwise(function(b){c.layerViewOptionalFunctions.setAttributeData(a,c._requiredAttributes,{})}).then(function(){c._numAttributesLoading--;c._evaluateUpdatingState()}),this._numAttributesLoading++,this._evaluateUpdatingState());this._lodHandling.shouldLoadNode(a)&&this._lodHandling.lodSwapBundleLoaded(a)}else if(this._lodHandling.shouldLoadNode(a)){if(this.layerViewRequiredFunctions.isOverMemory())return b.done(),b;for(var d=[],e=0;e<a.featureData.length;e++)this.layerViewRequiredFunctions.isBundleAlreadyAddedToStage(a,
e)||d.push(this._loadAndAddBundle(a,e));this._numNodesLoading++;this._evaluateUpdatingState();F.eachAlways(d).then(function(){c._numNodesLoading--;c._evaluateUpdatingState();b.done()});return b}b.done();return b};b.prototype._loadAndAddBundle=function(a,b){var c=this;return this._idleQueue.push().then(function(){return c._nodeLoader.loadBundleData(a,b)}).then(function(d){c._lodHandling.lodSwapBundleLoaded(a);return c._idleQueue.push().then(function(){return c.layerViewRequiredFunctions.addBundle(a,
b,d)})}).then(function(){if(null!=c.layerViewOptionalFunctions.setPolygonOffset){var b=c._lodHandling.shouldSetPolygonOffset(a);b&&c.layerViewOptionalFunctions.setPolygonOffset(a,b)}}).otherwise(function(c){c instanceof q||k.error("Failed to load node '"+a.id+"' bundle "+b+": "+c)})};b.prototype._updateIdleState=function(a){a!==this._isIdle&&(this._isIdle=a,this._evaluateUpdatingState())};e([d.property({readOnly:!0})],b.prototype,"isMeshPyramid",null);e([d.property({readOnly:!0})],b.prototype,"streamDataSupplier",
null);e([d.property({readOnly:!0,dependsOn:["layer.definitionExpression"]})],b.prototype,"parsedDefinitionExpression",null);e([d.property({readOnly:!0,dependsOn:["parsedDefinitionExpression"]})],b.prototype,"definitionExpressionFields",null);e([d.property({readOnly:!0})],b.prototype,"crsVertex",null);e([d.property({readOnly:!0})],b.prototype,"crsIndex",null);e([d.property({readOnly:!0})],b.prototype,"nodeIndex",void 0);e([d.property()],b.prototype,"camPos",void 0);e([d.property()],b.prototype,"screenSizeFactor",
void 0);e([d.property()],b.prototype,"layerView",void 0);e([d.property()],b.prototype,"layerViewRequiredFunctions",void 0);e([d.property()],b.prototype,"layerViewOptionalFunctions",void 0);e([d.property()],b.prototype,"layer",void 0);e([d.property()],b.prototype,"addUrlToken",void 0);e([d.property({readOnly:!0})],b.prototype,"updating",void 0);e([d.property({readOnly:!0})],b.prototype,"updatingPercentage",void 0);e([d.property({readOnly:!0})],b.prototype,"rootNodeVisible",null);return b=e([d.subclass("esri.layers.graphics.controllers.I3SOnDemandController")],
b)}(d.declared(B,D,C))});