// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/Accessor ../../../core/Error ../../../core/Evented ../../../core/HandleRegistry ../../../core/Logger ../../../core/Promise ../../../core/promiseUtils ../../../geometry/Extent ./support/TileSet ../../../views/2d/tiling/TileQueue ../../../views/2d/tiling/TileStrategy ../../../views/2d/tiling/TileInfoView ../../../views/2d/tiling/TileKey ../../support/GraphicsManager ../../support/TileInfo".split(" "),
function(F,G,m,g,e,n,p,q,r,t,u,h,v,w,x,y,z,A,B,C){var D=t.getLogger("esri.views.2d.layers.MapImageLayerView2D"),E=function(){function e(){this.key=new A(0,0,0,0)}e.prototype.dispose=function(){};return e}();return function(k){function c(a){var b=k.call(this)||this;b._handles=new r;b._pendingQueries=new Map;b._tileRequests=new Map;b.layer=a.layer;b.layerView=a.layerView;b.graphics=a.graphics;b._tileInfo=C.create({spatialReference:b.layerView.view.spatialReference,size:512});b._tileInfoView=new z(b._tileInfo);
b._tileQueue=new x({tileInfoView:b._tileInfoView,process:function(a){return b._fetchTile(a)}});b._tileSet=new w({layer:b.layer,tileInfo:b._tileInfo});b._graphicsManager=new B({graphics:b.graphics,objectIdField:b.layer.objectIdField});b._tileStrategy=new y({cachePolicy:"purge",acquireTile:function(a){return b._acquireTile(a)},releaseTile:function(a){return b._releaseTile(a)},tileInfoView:b._tileInfoView});b._handles.add([b.layer.watch("definitionExpression",function(){return b._refresh()}),b.layer.on("edits",
function(a){return b._editsHandler(a)})],"layer");return b}m(c,k);c.prototype.destroy=function(){var a=this;this._pendingQueries.forEach(function(b){b.isFulfilled()||b.cancel()});this._tileStrategy.tiles.forEach(function(b){return a._releaseTile(b)});this._handles.destroy();this._graphicsManager.destroy();this._tileStrategy.destroy();this._tileQueue.clear();this._tileRequests.clear()};Object.defineProperty(c.prototype,"graphics",{set:function(a){var b=this,d=this._get("graphics");d!==a&&(this._handles.remove("graphics"),
d&&d.forEach(function(b){return b.layer=null}),a&&(a.forEach(function(a){return a.layer=b.layer}),this._handles.add([a.on("after-add",function(a){return a.item.layer=b.layer}),a.on("after-remove",function(a){return a.item.layer=null})],"graphics")),this._set("graphics",a))},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"updating",{get:function(){return 0<this._tileQueue.length},enumerable:!0,configurable:!0});c.prototype.update=function(a){var b=this;this._tileQueue.pause();this._tileQueue.state=
a.state;this._tileStrategy.update(a);this._graphicsManager.removeAll();this._tileStrategy.tiles.forEach(function(a){a.featureSet&&b._graphicsManager.add(a.featureSet.features,a.intentId)});this._tileQueue.resume();this.notifyChange("updating")};c.prototype._acquireTile=function(a){var b=this,d=new E;d.key.set(a);a=this._tileQueue.push(d.key).then(function(a){d.attached=!0;d.featureSet=a.featureSet;d.intentId=a.intentId;b._graphicsManager.removeIntent(d.intentId);b.layerView.requestUpdate()});this._tileRequests.set(d,
a);this.notifyChange("updating");return d};c.prototype._releaseTile=function(a){if(this._tileRequests.has(a)){var b=this._tileRequests.get(a);b.isFulfilled()||b.cancel();this._tileRequests.delete(a);this.layerView.requestUpdate()}};c.prototype._fetchTile=function(a){var b=this,d=this._graphicsManager.createIntentToAdd();a=this._tileSet.fetch(a).then(function(a){return{featureSet:a,intentId:d}});a.otherwise(function(a){b._graphicsManager.removeIntent(d);if(a&&"cancel"===a.dojoType)return h.reject(a);
a=new p("ondemandcontroller2d:tile-request-failed","Failed to query for features",{error:a});D.error(a);return h.reject(a)});return a};c.prototype._refresh=function(){var a=this;this._tileQueue.reset();this._tileStrategy.tiles.forEach(function(b){var d=a._graphicsManager.createIntentToAdd(),c=a._tileSet.fetch(b.key).then(function(c){a._graphicsManager.remove(b.featureSet.features);b.intentId=d;b.featureSet=c;a._graphicsManager.add(b.featureSet.features,b.intentId);return b});c.always(function(){return a._graphicsManager.removeIntent(d)});
return c});this.notifyChange("updating")};c.prototype._editsHandler=function(a){var b=this,d=function(a){return a.objectId},c=a.deletedFeatures.map(d);this._graphicsManager.delete(c);a=a.addedFeatures.concat(a.updatedFeatures).map(d);if(a.length){d=this.layer.createQuery();d.objectIds=a;d.outSpatialReference=this._tileInfo.spatialReference;var e=this._graphicsManager.createIntentToAdd(a);a=this.layer.queryFeatures(d);this._pendingQueries.set(e,a);this.notifyChange("updating");a.then(function(a){return b._refetchHandler(a,
e)}).always(function(){b._graphicsManager.removeIntent(e);b._pendingQueries.delete(e);b.notifyChange("updating")})}};c.prototype._refetchHandler=function(a,b){var d=this,c=a.features;if(c){var e=this._tileInfo.spatialReference;a=function(a){var b=a.key.extent,f=new v({xmin:b[0],ymin:b[1],xmax:b[2],ymax:b[3],spatialReference:e});c.forEach(function(b){b.geometry&&f.intersects(b.geometry)&&d._addFeatureToTile(b,a)})};for(var f=0,l=this._tileStrategy.tiles;f<l.length;f++)a(l[f]);this._graphicsManager.add(c,
b)}};c.prototype._addFeatureToTile=function(a,b){var d=b.featureSet.features||[],c=this.layer.objectIdField,e=a.attributes&&a.attributes[c],f;d.some(function(a){(a.attributes&&a.attributes[c])===e&&(f=a);return!!f});f?(f.geometry=a.geometry,f.attributes=a.attributes):d.push(a);b.featureSet.features=d};g([e.property()],c.prototype,"graphics",null);g([e.property()],c.prototype,"layer",void 0);g([e.property()],c.prototype,"layerView",void 0);g([e.property()],c.prototype,"updating",null);return c=g([e.subclass("esri.layers.graphics.controllers.OnDemandController2D")],
c)}(e.declared(n,u,q))});