// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang ../../support/GraphicsManager ../../../core/Accessor ../../../core/Error ../../../core/Promise ../../../core/Evented ../../../core/HandleRegistry ../../../core/Logger ../../../core/promiseUtils ../../../geometry/support/scaleUtils".split(" "),function(m,n,p,e,q,r,t,u,f,g){var l=u.getLogger("esri.layers.graphics.controllers.SnapshotController");return p.createSubclass([q,r],{declaredClass:"esri.layers.graphics.controllers.SnapshotController",constructor:function(){this._handles=
new t;this._pendingQueries=new Map},initialize:function(){var a=this.layer.then(function(){this._verifyCapabilities()}.bind(this));this.addResolvingPromise(a);this.then(this._init.bind(this))},destroy:function(){this.cancelQuery();this._gManager&&(this._gManager.destroy(),this._gManager=null);this._handles.destroy();this._pendingQueries=this._handles=null},_cancelErrorMsg:"SnapshotController: query cancelled",_featureResolution:{value:.25,scale:945},_gManager:null,_handles:null,_maxFeatures:{point:16E3,
multipoint:8E3,polyline:4E3,polygon:4E3,multipatch:4E3},_source:null,_started:!1,properties:{_pendingQueries:null,updating:{value:!1,dependsOn:["_pendingQueries"],get:function(){return!!(this._pendingQueries&&0<this._pendingQueries.size)}},graphics:{value:null,set:function(a){this._get("graphics")!==a&&(this._handles.remove("graphics"),a&&(this._collectionChanged({added:a.toArray()}),this._handles.add(a.on("change",this._collectionChanged.bind(this)),"graphics")),this._set("graphics",a))}},extent:{},
hasAllFeatures:!1,hasFeatures:!1,layer:null,layerView:null,maxPageSize:null,pageSize:null,paginationEnabled:!1},update:function(a){this.startup()},startup:function(){this._started||(this._started=!0,this._resolutionParams=this._getResolutionParams(),this._queryFeatures())},refresh:function(){this.isResolved()&&this._started&&this._queryFeatures()},cancelQuery:function(){this._pendingQueries&&(this._pendingQueries.forEach(function(a,b){a.isFulfilled()||a.cancel(Error(this._cancelErrorMsg))}.bind(this)),
this._pendingQueries.clear(),this.notifyChange("updating"))},_init:function(){var a=this.layer;this.paginationEnabled=!!a.get("capabilities.query.supportsPagination");this._source=a.source;this.pageSize=null==this.maxPageSize?a.maxRecordCount:Math.min(a.maxRecordCount,this.maxPageSize);this._gManager=new n({graphics:this.graphics,objectIdField:a.objectIdField});this._setupStateWatchers()},_getResolutionParams:function(){var a=this.layer,b=a.get("capabilities.query.supportsQuantization"),c;if("polyline"===
a.geometryType||"polygon"===a.geometryType){var d=g.getMetersPerUnit(this.layerView.view.spatialReference);null!=d&&(c=this._featureResolution.scale,d=this._featureResolution.value/d,c=a.maxScale?a.maxScale:a.minScale?Math.min(c,a.minScale):Math.min(c,g.getScale(this.layerView.view,a.fullExtent)),c*=d/this._featureResolution.scale)}return c?{maxAllowableOffset:b?null:c,quantizationParameters:b?{mode:"view",originPosition:"upperLeft",tolerance:c,extent:a.fullExtent}:null}:null},_setupStateWatchers:function(){this._handles.add([this.watch("extent",
this.refresh.bind(this)),this.layer.watch("definitionExpression",this.refresh.bind(this)),this.layer.on("edits",this._editsHandler.bind(this))])},_createQueryParams:function(){var a=this.layerView,b=this.layer.createQuery();b.outSpatialReference=a.view.spatialReference;b.geometry=this.extent;m.mixin(b,this._resolutionParams);this.paginationEnabled&&(b.start=0,b.num=this.pageSize);return b},_queryFeatures:function(){this.cancelQuery();this.hasAllFeatures=this.hasFeatures=!1;this._gManager.beginPagedUpdate();
this.emit("query-start");this._executeQuery(this._createQueryParams())},_executeQuery:function(a){var b=this._source.queryFeatures(a),c=this._gManager.createIntentToAdd();this._querySetup(c,b);b.then(this._processFeatureSet.bind(this,a,c)).otherwise(this._queryError.bind(this,c)).always(this._queryTeardown.bind(this,c))},_processFeatureSet:function(a,b,c){var d=c.exceededTransferLimit,h=c.features,k=this._maxFeatures[this.layer.geometryType]||0,e=h?h.length:0,f=this._gManager.numGraphics+e,g=f>=k;
g&&(l.warn('Feature limit exceeded on layer "',this.layer.title,'". Not all features are shown.'),(k=f-k)&&h.splice(e-k,k));a=d&&this.paginationEnabled&&!g?this._queryNextPage(a):!1;h&&this._gManager.addPage(h,b);this.hasFeatures=!0;a||(this._gManager.endPagedUpdate(),this.hasAllFeatures=!d,this.emit("query-end",{success:!0}));return c},_queryNextPage:function(a){a.start+=this.pageSize;this._executeQuery(a);return!0},_queryError:function(a,b){b&&"cancel"===b.dojoType&&!this.hasFeatures?this._gManager.revertPagedUpdate():
this._gManager.endPagedUpdate();this.emit("query-end",{success:!1});if(b&&"cancel"===b.dojoType)return f.reject(b);a=new e("snapshotcontroller:tile-request-failed","Failed to query for features",{error:b});l.error(a);return f.reject(a)},_querySetup:function(a,b){this._pendingQueries.set(a,b);this.notifyChange("updating")},_queryTeardown:function(a){this._gManager.removeIntent(a);this._pendingQueries.delete(a);this.notifyChange("updating")},_collectionChanged:function(a){var b,c,d;if(d=a.added)for(b=
0;c=d[b];b++)c.layer=this.layer;if(d=a.removed)for(b=0;c=d[b];b++)c.layer=null},_editsHandler:function(a){var b=function(a){return a.objectId},c=a.deletedFeatures.map(b);this._gManager.delete(c);a=a.addedFeatures.concat(a.updatedFeatures).map(b);a.length&&(b=this._createQueryParams(),b.objectIds=a,b=this._source.queryFeatures(b),a=this._gManager.createIntentToAdd(a),this._querySetup(a,b),b.then(this._processRefetch.bind(this,a)).otherwise(this._refetchError.bind(this,a)).always(this._queryTeardown.bind(this,
a)))},_processRefetch:function(a,b){(b=b.features)&&this._gManager.add(b,a)},_refetchError:function(a,b){},_verifyCapabilities:function(){if(!this.layer.get("capabilities.operations.supportsQuery"))throw new e("graphicscontroller:query-capability-required","Service requires query capabilities to be used as a feature layer",{layer:this.layer});}})});