// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../core/accessorSupport/decorators ../../../../core/HandleRegistry ../../../../core/Accessor ../../../../geometry/Point ../../lib/glMatrix ../Evented ./CenterOnSurface ./ViewState ./PropertiesPool ./disposeMembers ./SurfaceGeometryUpdates ../../webgl-engine/lib/Camera ../../webgl-engine/lib/Selector".split(" "),function(e,g,n,d,c,p,q,r,k,t,h,u,v,w,x,y,l){Object.defineProperty(g,
"__esModule",{value:!0});e=function(e){function b(a){a=e.call(this,a)||this;a.handles=new p;a.lastSeenCameraParameters=new y;a.surfaceAltitudeAtCenter=0;a.surfaceAltitudeAtCenterDirty=!0;a.surfaceAltitudeAtCenterWithContent=0;a.surfaceAltitudeAtCenterWithContentDirty=!0;a.propertiesPool=new v.default({pointOfView:r,renderPointOfView:Array},a);a.updateSurfaceAltitudeFrequentInterval=z;a.updateSurfaceAltitudeInfrequentInterval=A;a.events=new t.Evented;a.renderPointOfView=[0,0,0];return a}n(b,e);b.prototype.normalizeCtorArgs=
function(a){var b={viewState:new u.default({view:a.view}),surface:a.view.basemapTerrain,renderCoordsHelper:a.view.renderCoordsHelper,pickRay:a.view._stage.pickRay.bind(a.view._stage)};null!=a.updateSurfaceAltitudeFrequentInterval&&(b.updateSurfaceAltitudeFrequentInterval=a.updateSurfaceAltitudeFrequentInterval);null!=a.updateSurfaceAltitudeInfrequentInterval&&(b.updateSurfaceAltitudeInfrequentInterval=a.updateSurfaceAltitudeInfrequentInterval);return b};b.prototype.initialize=function(){var a=this;
this.surfaceSelector=new l(this.viewState.mode);this.surfaceSelector.enableBackfacesTerrain="global"===this.viewState.mode?!1:!0;this.surfaceSelector.enableInvisibleTerrain=!1;this.contentSelector=new l(this.viewState.mode);this.contentSelector.enableTerrain=!1;var b=this.viewState,c=this.surface,d=this.renderCoordsHelper,e=this.estimateSurfaceAltitudeAtCenter.bind(this);this._set("centerOnSurfaceInfrequent",new h.default({viewState:b,surface:c,renderCoordsHelper:d,estimateSurfaceAltitudeAtCenter:e,
altitudeEstimationInterval:this.updateSurfaceAltitudeInfrequentInterval}));this._set("centerOnSurfaceFrequent",new h.default({viewState:b,surface:c,renderCoordsHelper:d,estimateSurfaceAltitudeAtCenter:e,altitudeEstimationInterval:this.updateSurfaceAltitudeFrequentInterval}));this._set("centerOnContent",new h.default({viewState:b,surface:c,renderCoordsHelper:d,estimateSurfaceAltitudeAtCenter:this.estimateSurfaceAltitudeAtCenterWithContent.bind(this),altitudeEstimationInterval:this.updateSurfaceAltitudeFrequentInterval}));
this._set("surfaceGeometryUpdates",new x.default({viewState:b,surface:c,renderCoordsHelper:d,centerOnSurfaceInstances:[this.centerOnSurfaceFrequent,this.centerOnContent,this.centerOnSurfaceInfrequent]}));this.handles.add(this.viewState.watch("camera",function(b){return a.cameraChanged(b)},!0));this.handles.add(this.surfaceGeometryUpdates.events.on("request-update",function(){return a.updateCenterPointsOfInterest()}));this.handles.add(this.surface.watch("extent",function(){return a.updateCenterPointsOfInterest()}));
this.cameraChanged(this.viewState.camera);this.forceUpdate()};b.prototype.destroy=function(){w.default(this,"handles","viewState","centerOnSurfaceInfrequent","centerOnSurfaceFrequent","centerOnContent","propertiesPool")};Object.defineProperty(b.prototype,"pointOfView",{get:function(){var a=this.propertiesPool.get("pointOfView");this.renderCoordsHelper.fromRenderCoords(this.renderPointOfView,a,this.viewState.spatialReference);return a},enumerable:!0,configurable:!0});b.prototype.forceUpdate=function(){this.surfaceGeometryUpdates.forceUpdate();
this.centerOnSurfaceInfrequent.forceUpdate();this.centerOnSurfaceFrequent.forceUpdate();this.centerOnContent.forceUpdate()};b.prototype.hasPendingUpdates=function(){return this.surfaceGeometryUpdates.hasPendingUpdates()||this.centerOnContent.hasPendingUpdates()||this.centerOnSurfaceInfrequent.hasPendingUpdates()||this.centerOnSurfaceFrequent.hasPendingUpdates()};b.prototype.estimateSurfaceAltitudeAtCenterWithContent=function(){if(!this.surfaceAltitudeAtCenterWithContentDirty)return this.surfaceAltitudeAtCenterWithContent;
this.surfaceAltitudeAtCenterWithContentDirty=!1;var a=this.viewState.camera;this.pickRay(a.eye,a.center,null,null,null,!1,this.contentSelector);this.contentSelector.minResult.getIntersectionPoint(f)?this.surfaceAltitudeAtCenterWithContent=this.renderCoordsHelper.getAltitude(f):this.surfaceAltitudeAtCenterWithContent=this.estimateSurfaceAltitudeAtCenter();return this.surfaceAltitudeAtCenterWithContent};b.prototype.estimateSurfaceAltitudeAtCenter=function(){if(!this.surface)return 0;if(!this.surfaceAltitudeAtCenterDirty)return this.surfaceAltitudeAtCenter;
this.surfaceAltitudeAtCenterDirty=!1;var a=this.viewState.camera;this.surfaceSelector.init(null,a.eye,a.center,null,a,null,!1);this.surface.intersect(this.surfaceSelector,a.eye,a.center);this.surfaceSelector.minResult.getIntersectionPoint(f)&&(this.surfaceAltitudeAtCenter=this.renderCoordsHelper.getAltitude(f));return this.surfaceAltitudeAtCenter};b.prototype.cameraChanged=function(a){this.updateCenterPointsOfInterest(a);this.cameraParametersChanged(this.lastSeenCameraParameters,a)&&(this.lastSeenCameraParameters.copyFrom(a),
m.camera=a,this.events.emit("camera-parameters-changed",m));a=a.eye;this.renderPointOfView[0]===a[0]&&this.renderPointOfView[1]===a[1]&&this.renderPointOfView[2]===a[2]||this._set("renderPointOfView",k.vec3d.set(a,this.propertiesPool.get("renderPointOfView")))};b.prototype.updateCenterPointsOfInterest=function(a){void 0===a&&(a=this.viewState.camera);this.surfaceAltitudeAtCenterWithContentDirty=this.surfaceAltitudeAtCenterDirty=!0;this.centerOnSurfaceFrequent.update(a);this.centerOnSurfaceInfrequent.update(a);
this.centerOnContent.update(a)};b.prototype.cameraParametersChanged=function(a,b){return a.fov!==b.fov||a.fullViewport[0]!==b.fullViewport[0]||a.fullViewport[1]!==b.fullViewport[1]||a.fullViewport[2]!==b.fullViewport[2]||a.fullViewport[3]!==b.fullViewport[3]||a.padding[0]!==b.padding[0]||a.padding[1]!==b.padding[1]||a.padding[2]!==b.padding[2]||a.padding[3]!==b.padding[3]?!0:!1};d([c.property({constructOnly:!0})],b.prototype,"updateSurfaceAltitudeFrequentInterval",void 0);d([c.property({constructOnly:!0})],
b.prototype,"updateSurfaceAltitudeInfrequentInterval",void 0);d([c.property({readOnly:!0,aliasOf:"viewState.camera"})],b.prototype,"camera",void 0);d([c.property({readOnly:!0})],b.prototype,"centerOnContent",void 0);d([c.property({readOnly:!0})],b.prototype,"centerOnSurfaceFrequent",void 0);d([c.property({readOnly:!0})],b.prototype,"centerOnSurfaceInfrequent",void 0);d([c.property({readOnly:!0})],b.prototype,"events",void 0);d([c.property({readOnly:!0,dependsOn:["renderPointOfView"]})],b.prototype,
"pointOfView",null);d([c.property({constructOnly:!0})],b.prototype,"renderCoordsHelper",void 0);d([c.property({readOnly:!0})],b.prototype,"renderPointOfView",void 0);d([c.property({constructOnly:!0})],b.prototype,"surface",void 0);d([c.property({readOnly:!0})],b.prototype,"surfaceGeometryUpdates",void 0);d([c.property({constructOnly:!0})],b.prototype,"viewState",void 0);d([c.property({constructOnly:!0})],b.prototype,"pickRay",void 0);return b=d([c.subclass("esri.views.3d.support.PointsOfInterest")],
b)}(c.declared(q));g.PointsOfInterest=e;var m={camera:null},f=k.vec3d.create(),z=200,A=3E3;g.default=e});