// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/ArrayPool ../../../../core/screenUtils ../../../../core/libs/earcut/earcut ./Utils ./visualVariablesUtils ./MeshData ./enums ./lineMeshUtil".split(" "),function(M,C,G,E,J,d,K,H,F,L){Object.defineProperty(C,"__esModule",{value:!0});var z=new Float32Array(1),A=new Uint32Array(z.buffer);C.createTextMesh=function(d,m,v,t,z,y,n,q){return null};C.createMesh=function(f,m,v,t,B,y,n,q,a){switch(B){case F.WGLGeometryType.MARKER:B=H.pool.acquire();var x,e,l,r=0,u=0,g,
c,h,k,b;(y=m.heatmapInfo)?(a=Math.round(m.heatmapInfo.radius),x=t=0,l=e=a,g=[1,1,1,1],c=[0,0,0,0],k=h=a,b=0):(l=t.spriteMosaicItem,t=Math.round(l.rect.x/4),x=Math.round(l.rect.y/4),e=t+Math.round(l.rect.width/4),l=x+Math.round(l.rect.height/4),r=a.xoffset|0,u=a.yoffset|0,g=d.isPictureSymbol(a)?[255,255,255,255]:d.copyAndPremultiply(a.color),h=Math.round(E.pt2px(a.width||a.size)),k=Math.round(E.pt2px(a.height||a.size)),a.outline?(c=null!=a.outline.color?d.copyAndPremultiply(a.outline.color):[255,255,
255,255],b=null!=a.outline.width?Math.round(E.pt2px(a.outline.width)):0):(c=[0,0,0,0],b=0));var p=q.centroid||q.geometry;a=[];n=d.i1616to32(p.x+r*n,p.y+u*n);r=d.i8888to32(g[0],g[1],g[2],g[3]);c=d.i8888to32(c[0],c[1],c[2],c[3]);h=d.i8888to32(h,k,b,0);f=d.numTo32(f);var w=b=0;k=g=p=0;if(u=v.vvColor||v.vvOpacity||v.vvRotation||v.vvSizeMinMaxValue||v.vvSizeScaleStops||v.vvSizeFieldStops||v.vvSizeUnitValue)b=m.vvFields,p=b.rotation?m.getValue(q,b.rotation):0,w=b.opacity?m.getValue(q,b.opacity):0,g=b.color?
m.getValue(q,b.color):0,b=b.size&&!v.vvSizeScaleStops?m.getValue(q,b.size):0,v.vvSizeUnitValue&&(b=K.getVisualVariableSizeValueRepresentationRatio(b,m.vvRanges.size.unitValue.valueRepresentation)),isNaN(b)&&(b=1),isNaN(p)&&(p=1),isNaN(w)&&(w=1),isNaN(g)&&(g=1),z[0]=b,b=A[0],z[0]=w,w=A[0],z[0]=p,p=A[0],z[0]=g,g=A[0];y&&(z[0]=m.heatmapInfo.getIntensity(q),k=A[0]);a.push(n);a.push(d.i8888to32(-32,-32,t,x));a.push(f);a.push(r);a.push(c);a.push(h);u?(a.push(b),a.push(g),a.push(w),a.push(p)):y&&a.push(k);
a.push(n);a.push(d.i8888to32(32,-32,e,x));a.push(f);a.push(r);a.push(c);a.push(h);u?(a.push(b),a.push(g),a.push(w),a.push(p)):y&&a.push(k);a.push(n);a.push(d.i8888to32(-32,32,t,l));a.push(f);a.push(r);a.push(c);a.push(h);u?(a.push(b),a.push(g),a.push(w),a.push(p)):y&&a.push(k);a.push(n);a.push(d.i8888to32(32,32,e,l));a.push(f);a.push(r);a.push(c);a.push(h);u?(a.push(b),a.push(g),a.push(w),a.push(p)):y&&a.push(k);B.update({geometry:a},4,[0,1,2,1,3,2]);return B;case F.WGLGeometryType.FILL:B=H.pool.acquire();
c=null!=t?t.spriteMosaicItem:null;r=q.geometry;n=d.isPictureSymbol(a);l=!n&&a.color?d.copyAndPremultiply(a.color):[255,255,255,255];y=d.numTo32(f);v=v.vvColor||v.vvOpacity;x=t=0;v&&(x=m.vvFields,t=x.opacity?m.getValue(q,x.opacity):0,m=x.color?m.getValue(q,x.color):0,isNaN(t)&&(t=1),isNaN(m)&&(m=1),z[0]=t,t=A[0],z[0]=m,x=A[0]);m=d.i8888to32(l[0],l[1],l[2],l[3]);q=[0,0];l=[0,0];c&&(f=c.rect.x,h=c.rect.y,k=c.width,c=c.height,q[0]=f+1,q[1]=h+1,l[0]=f+1+k,l[1]=h+1+c);a=n&&a.width&&a.height?[d.nextHighestPowerOfTwo(a.width),
d.nextHighestPowerOfTwo(a.height),0,0]:[d.nextHighestPowerOfTwo(l[0]-q[0]),d.nextHighestPowerOfTwo(l[1]-q[1]),0,0];a=d.i8888to32(a[0],a[1],a[2],a[3]);f=0;for(n=r.rings;f<n.length;f++)c=n[f];f=G.acquire();n=[];k=h=0;for(r=r.rings;k<r.length;k++){c=r[k];u=h;g=0;b=c.length;p=c[0][0];w=c[0][1];f.push(p);f.push(w);h++;h++;for(var D=1;D<b;++D){var C=c[D][0],I=c[D][1];g-=C*(w+w+I);p+=C;w+=I;f.push(p);f.push(w);h++;h++}0<g?(e&&n.push(e),e={holeIndices:[],offset:u,coordCount:2*b}):0>g?e&&(e.holeIndices.push((u-
e.offset)/2),e.coordCount+=2*b):(h=u,f.splice(u))}e&&n.push(e);e=[];r=[];for(h=c=0;h<n.length;h++)if(k=n[h],b=f.slice(k.offset,k.offset+k.coordCount),u=J(b,k.holeIndices,2),g=u.length,0<g){for(p=0;p<k.coordCount;)e.push(d.i1616to32(b[p++],b[p++])),e.push(y),e.push(m),e.push(d.i1616to32(q[0],q[1])),e.push(d.i1616to32(l[0],l[1])),e.push(a),v&&(e.push(x),e.push(t));for(b=0;b<g;)r.push(u[b++]+c),r.push(u[b++]+c),r.push(u[b++]+c);c+=k.coordCount/2}G.release(f);B.update({geometry:e},c,r);return B;case F.WGLGeometryType.LINE:return L.createLineMeshData(f,
m,v,t,y,n,q,a)}return null}});