// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/ObjectPool ./enums ./MaterialInfo ./Utils".split(" "),function(w,z,q,k,r,n){w=function(){function b(){this.symbolLevels=[]}b.prototype.release=function(){this.symbolLevels.forEach(function(a){t.pool.release(a)});this.symbolLevels.length=0};Object.defineProperty(b.prototype,"empty",{get:function(){return!this.symbolLevels||0===this.symbolLevels.length},enumerable:!0,configurable:!0});b.prototype.addToList=function(a){var f=this;a.forEach(function(a){f._addToList(a)})};
b.prototype.removeFromList=function(a){var f=this;a.forEach(function(a){f._removeFromList(a)})};b.prototype._addToList=function(a){var f=this._getDisplayList(a.symbolLevel,a.zOrder,a.geometryType),e=0<f.length?f[f.length-1]:null;null!==e&&n.isSameMaterialInfo(e.materialInfo,a.materialInfo)&&e.indexFrom+e.indexCount===a.indexFrom?e.indexCount+=a.indexCount:(e=p.pool.acquire(),e.indexFrom=a.indexFrom,e.indexCount=a.indexCount,e.materialInfo=a.materialInfo,e.geometryType=a.geometryType,f.push(e))};b.prototype._removeFromList=
function(a){for(var f=this._getDisplayList(a.symbolLevel,a.zOrder,a.geometryType),e=f.length,c=void 0,b=0;b<e;++b){var d=f[b];a.indexFrom+a.indexCount>d.indexFrom&&a.indexFrom<d.indexFrom+d.indexCount&&(c=b)}if(void 0!==c)if(d=f[c],a.indexFrom<d.indexFrom)d.indexCount-=a.indexCount,d.indexFrom+=a.indexCount;else if(a.indexFrom+a.indexCount>d.indexFrom+d.indexCount)d.indexCount-=a.indexCount;else{var e=d.indexFrom,b=a.indexFrom-d.indexFrom,g=a.indexCount;a=d.indexFrom+d.indexCount-(a.indexFrom+a.indexCount);
d.indexCount=b;var h=p.pool.acquire();h.geometryType=d.geometryType;h.materialInfo=r.pool.acquire();h.materialInfo.copy(d.materialInfo);h.indexFrom=e+b+g;h.indexCount=a;f.splice(c+1,0,h)}};b.prototype._getDisplayList=function(a,f,e){for(var c,b=this.symbolLevels.length,d=0;d<b;d++)if(this.symbolLevels[d].symbolLevel===a){c=this.symbolLevels[d];break}c||(c=t.pool.acquire(),c.symbolLevel=a,this.symbolLevels.push(c));var g;a=c.zLevels.length;for(b=0;b<a;b++)if(c.zLevels[b].zLevel===f){g=c.zLevels[b];
break}g||(g=u.pool.acquire(),g.geometryDPInfo=v.pool.acquire(),g.zLevel=f,c.zLevels.push(g));var h;switch(e){case k.WGLGeometryType.FILL:g.geometryDPInfo.fill||(g.geometryDPInfo.fill=[]);h=g.geometryDPInfo.fill;break;case k.WGLGeometryType.LINE:g.geometryDPInfo.line||(g.geometryDPInfo.line=[]);h=g.geometryDPInfo.line;break;case k.WGLGeometryType.MARKER:g.geometryDPInfo.marker||(g.geometryDPInfo.marker=[]);h=g.geometryDPInfo.marker;break;case k.WGLGeometryType.TEXT:g.geometryDPInfo.text||(g.geometryDPInfo.text=
[]);h=g.geometryDPInfo.text;break;default:console.error("Trying to add a record with geometry type '"+e+"'.")}return h};b.serialize=function(a,b,e){var c=0;b&&(b[e+c]=a.symbolLevels.length);++c;var f=0;for(a=a.symbolLevels;f<a.length;f++){var d=a[f];b&&(b[e+c]=d.symbolLevel);++c;b&&(b[e+c]=d.zLevels.length);++c;for(var g=0,d=d.zLevels;g<d.length;g++){var h=d[g];b&&(b[e+c]=h.zLevel);++c;h=h.geometryDPInfo;c+=this._serializeDisplayListInfo(h.fill,b,e+c);c+=this._serializeDisplayListInfo(h.line,b,e+
c);c+=this._serializeDisplayListInfo(h.marker,b,e+c);c+=this._serializeDisplayListInfo(h.text,b,e+c)}}return c};b.deserialize=function(a,f,e){a.displayList=b.pool.acquire();var c=0,y=f[e+c];++c;for(var d=0;d<y;++d){var g=t.pool.acquire();g.symbolLevel=f[e+c];++c;a.displayList.symbolLevels.push(g);var h=f[e+c];++c;for(var x=0;x<h;++x){var m=u.pool.acquire();m.zLevel=f[e+c];++c;g.zLevels.push(m);var l=[],c=c+this._deserializeDisplayListInfo(l,k.WGLGeometryType.FILL,f,e+c);m.geometryDPInfo.fill=0<l.length?
l:null;l=[];c+=this._deserializeDisplayListInfo(l,k.WGLGeometryType.LINE,f,e+c);m.geometryDPInfo.line=0<l.length?l:null;l=[];c+=this._deserializeDisplayListInfo(l,k.WGLGeometryType.MARKER,f,e+c);m.geometryDPInfo.marker=0<l.length?l:null;l=[];c+=this._deserializeDisplayListInfo(l,k.WGLGeometryType.TEXT,f,e+c);m.geometryDPInfo.text=0<l.length?l:null}}return c};b._serializeDisplayListInfo=function(a,b,e){var c=0;if(a)for(var c=c+n.serializeInteger(a.length,b,e+c),f=0;f<a.length;f++)var d=a[f],c=c+r.serialize(d.materialInfo,
b,e+c),c=c+n.serializeInteger(d.indexFrom,b,e+c),c=c+n.serializeInteger(d.indexCount,b,e+c);else b&&(b[e+c]=0),++c;return c};b._deserializeDisplayListInfo=function(b,f,e,c){var a={n:void 0},d=0,d=d+n.deserializeInteger(a,e,c+d),g=a.n;b.length=g;for(var h=0;h<g;++h){var k=p.pool.acquire();k.geometryType=f;var m={materialInfo:null},d=d+r.deserialize(m,e,c+d);k.materialInfo=m.materialInfo;d+=n.deserializeInteger(a,e,c+d);k.indexFrom=a.n;d+=n.deserializeInteger(a,e,c+d);k.indexCount=a.n;b[h]=k}return d};
b.pool=new q(b);return b}();var p=function(){function b(){this.materialInfo=null;this.indexCount=this.indexFrom=0}b.prototype.release=function(){this.geometryType=k.WGLGeometryType.UNKNOWN;this.materialInfo=null;this.indexCount=this.indexFrom=0};b.pool=new q(b);return b}(),v=function(){function b(){this.text=this.marker=this.line=this.fill=null}b.prototype.release=function(){this.fill&&(this.fill.forEach(function(a){return p.pool.release(a)}),this.fill.length=0);this.line&&(this.line.forEach(function(a){return p.pool.release(a)}),
this.line.length=0);this.marker&&(this.marker.forEach(function(a){return p.pool.release(a)}),this.marker.length=0);this.text&&(this.text.forEach(function(a){return p.pool.release(a)}),this.text.length=0)};b.pool=new q(b);return b}(),u=function(){function b(){}b.prototype.acquire=function(){this.geometryDPInfo=v.pool.acquire()};b.prototype.release=function(){this.zLevel=null;v.pool.release(this.geometryDPInfo);this.geometryDPInfo=null};b.pool=new q(b);return b}(),t=function(){function b(){this.zLevels=
[]}b.prototype.release=function(){this.symbolLevel=null;this.zLevels.forEach(function(a){return u.pool.release(a)});this.zLevels.length=0};b.pool=new q(b);return b}();return w});