// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/accessorSupport/decorators ./Widget ./support/widget dojo/i18n!../nls/common dojo/i18n!./LayerList/nls/LayerList ../core/HandleRegistry ./LayerList/LayerListViewModel ../core/watchUtils".split(" "),function(B,G,C,e,h,D,d,u,v,E,w,q){var F=B.toUrl("./LayerList/images/default-action.svg");return function(x){function c(){var a=x.call(this)||this;a._handleRegistry=new E;a.createActionsFunction=null;
a.statusIndicatorsVisible=!0;a.listItemCreatedFunction=null;a.operationalItems=null;a.view=null;a.viewModel=new w;return a}C(c,x);c.prototype.postInitialize=function(){var a=this,b=this.operationalItems;this.own(q.on(this,"operationalItems","change",function(){return a._itemsChanged(b)}))};c.prototype.destroy=function(){this._handleRegistry.destroy();this._handleRegistry=null};c.prototype.triggerAction=function(a,b){};c.prototype.render=function(){var a=this,b=this._getItems(),c=this.get("viewModel.state"),
b=0===b.length?d.tsx("div",{class:"esri-layer-list__no-items"},v.noItemsToDisplay):d.tsx("ul",{class:d.join("esri-layer-list__list","esri-layer-list__list--root","esri-layer-list__list--independent")},b.map(function(b,d){return a._renderItem(b,null)})),c=(f={},f["esri-hidden"]="loading"===c,f["esri-disabled"]="disabled"===c,f);return d.tsx("div",{class:"esri-layer-list esri-widget esri-widget--panel",classes:c},b);var f};c.prototype._getItems=function(){var a=this;return this.operationalItems.toArray().filter(function(b){return a.errorsVisible||
!b.error})};c.prototype._renderItem=function(a,b){var c=this,f=this.id+"_"+a.uid,g=f+"_actions",t=f+"__list",e=f+"__title",h=!!a.children.length,y=!!a.error,q=y?v.layerError:"",n=a.visibilityMode,A=a.children&&a.children.toArray(),w=(p={},p["esri-layer-list__list--exclusive"]="exclusive"===n,p["esri-layer-list__list--inherited"]="inherited"===n,p["esri-layer-list__list--independent"]="inherited"!==n&&"exclusive"!==n,p),p=(k={},k["esri-layer-list__item--has-children"]=h,k["esri-layer-list__item--error"]=
!!q,k["esri-layer-list__item--updating"]=a.updating&&!b&&this.statusIndicatorsVisible,k["esri-layer-list__item--invisible-at-scale"]=!a.visibleAtCurrentScale,k),z=this._countActions(a.actionsSections),k=z?this._renderActionMenuItem(a,a.actionsSections):null,x=(l={},l["esri-icon-handle-horizontal"]=!a.actionsOpen,l["esri-icon-close"]=a.actionsOpen,l),l=a.actionsOpen?u.close:u.open,l=1<z?d.tsx("div",{key:f+"__actions-menu-toggle","data-item":a,onclick:this._toggleActionsOpen,onkeydown:this._toggleActionsOpen,
class:"esri-layer-list__item-actions-menu-item",tabindex:"0",role:"button","aria-controls":g,"aria-label":l,title:l},d.tsx("span",{"aria-hidden":"true",classes:x})):null,k=z?d.tsx("div",{key:f+"__actions-menu",class:"esri-layer-list__item-actions-menu"},k,l):null,g=1<z?this._renderActionsSections(a,a.actionsSections,g):null,n=h?d.tsx("ul",{key:t,id:t,class:"esri-layer-list__list",classes:w,"aria-expanded":a.open?"true":"false",role:"exclusive"===n?"radiogroup":"group",hidden:a.open?null:!0},A.map(function(b,
d){return c._renderItem(b,a)})):null,A=(r={},r["esri-layer-list__child-toggle--open"]=a.open,r),r=a.open?u.collapse:u.expand,t=h?d.tsx("span",{onclick:this._toggleChildrenClick,onkeydown:this._toggleChildrenClick,"data-item":a,key:f+"__toggle-children",class:"esri-layer-list__child-toggle",classes:A,tabindex:"0",role:"button","aria-controls":t,"aria-label":r,title:r},d.tsx("span",{"aria-hidden":"true",class:d.join("esri-layer-list__child-toggle-icon--closed","esri-icon-right-triangle-arrow")}),d.tsx("span",
{"aria-hidden":"true",class:d.join("esri-layer-list__child-toggle-icon--opened","esri-icon-down-arrow")}),d.tsx("span",{"aria-hidden":"true",class:d.join("esri-layer-list__child-toggle-icon--closed-rtl","esri-icon-left-triangle-arrow")})):null;b=this._createLabelNode(a,b,f,e);y=y?d.tsx("div",{key:f+"__error",class:"esri-layer-list__item-error-message",role:"alert"},d.tsx("span",{"aria-hidden":"true",class:"esri-icon-notice-triangle"}),d.tsx("span",null,q)):null;return d.tsx("li",{key:f+"__list-item",
class:"esri-layer-list__item",classes:p,"aria-labelledby":e},d.tsx("div",{key:f+"__list-item-container",class:"esri-layer-list__item-container"},t,b,k),y,g,n);var p,k,l,r};c.prototype._createLabelNode=function(a,b,c,f){c+="__label";b=b&&b.visibilityMode;var g=(m={},m["esri-icon-radio-checked"]="exclusive"===b&&a.visible,m["esri-icon-radio-unchecked"]="exclusive"===b&&!a.visible,m["esri-icon-visible"]="exclusive"!==b&&a.visible,m["esri-icon-non-visible"]="exclusive"!==b&&!a.visible,m),m="exclusive"===
b?"radio":"checkbox",e=a.title||v.untitledLayer,h=a.visibleAtCurrentScale?e:e+" ("+v.layerInvisibleAtScale+")",e=d.tsx("span",{id:f,title:h,"aria-label":h,class:"esri-layer-list__item-title"},e);return"inherited"===b?d.tsx("div",{key:c,class:"esri-layer-list__item-label"},e):d.tsx("div",{key:c,onclick:this._labelClick,onkeydown:this._labelClick,"data-item":a,"data-parent-visibility":b,tabindex:"0","aria-checked":a.visible?"true":"false",role:m,"aria-labelledby":f,class:"esri-layer-list__item-label"},
d.tsx("span",{class:"esri-layer-list__item-toggle"},d.tsx("span",{class:"esri-layer-list__item-toggle-icon","aria-hidden":"true",classes:g})),e);var m};c.prototype._renderActionMenuItem=function(a,b){if(b=(b=b.getItemAt(0))&&b.getItemAt(0)){var c=this._getActionImageStyles(b),f=(g={},g[b.className]=!!b.className,g["esri-layer-list__item-action-image"]=!!c["background-image"],g),g=b.title;return d.tsx("div",{key:b.uid+"__action-menu-item",bind:this,"data-item":a,"data-action":b,onclick:this._triggerAction,
onkeydown:this._triggerAction,class:"esri-layer-list__item-actions-menu-item",role:"button",tabindex:"0",title:g,"aria-label":g},d.tsx("span",{classes:f,styles:c}))}var g};c.prototype._watchActionSectionChanges=function(a,b){var c=this,d="action-section"+b;this._handleRegistry.add(a.on("change",this.scheduleRender.bind(this)),d);a.forEach(function(a){return c._renderOnActionChanges(a,b)})};c.prototype._renderOnActionChanges=function(a,b){var c=this;b="actions"+b;this._handleRegistry.add([q.init(a,
"className, image, id, title, visible",function(){return c.scheduleRender()})],b)};c.prototype._renderOnItemChanges=function(a){var b=this,c=a.uid,d="items"+c;this._handleRegistry.add([q.init(a,"actionsOpen, visible, open, updating, title, visibleAtCurrentScale, error, visibilityMode",function(){return b.scheduleRender()}),a.actionsSections.on("change",function(){return b.scheduleRender()}),a.children.on("change",function(){return b.scheduleRender()})],d);a.children.forEach(function(a){return b._renderOnItemChanges(a)});
a.actionsSections.forEach(function(a){return b._watchActionSectionChanges(a,c)})};c.prototype._itemsChanged=function(a){var b=this;this._handleRegistry.removeAll();a.forEach(function(a){return b._renderOnItemChanges(a)});this.scheduleRender()};c.prototype._renderActionsSections=function(a,b,c){var f=this,e=this.id+"_"+a.uid;b=b.toArray().map(function(b){return d.tsx("ul",{key:e+"__actions-list",class:"esri-layer-list__item-actions-list"},f._renderActionSection(a,b))});return d.tsx("div",{role:"group",
"aria-expanded":a.actionsOpen?"true":"false",key:e+"__actions-section",id:c,class:"esri-layer-list__item-actions",hidden:a.actionsOpen?null:!0},b)};c.prototype._renderActionSection=function(a,b){var c=this;return(b&&b.toArray()).map(function(b){return c._renderAction(a,b)})};c.prototype._renderAction=function(a,b){var c=this._getActionImageStyles(b),e=(g={},g[b.className]=!!b.className,g["esri-layer-list__item-action-image"]=!!c["background-image"],g);return d.tsx("li",{key:b.uid+"__action",bind:this,
"data-item":a,"data-action":b,onclick:this._triggerAction,onkeydown:this._triggerAction,class:"esri-layer-list__item-action",tabindex:"0",role:"button",title:b.title,"aria-label":b.title},d.tsx("span",{"aria-hidden":"true",class:"esri-layer-list__item-action-icon",classes:e,styles:c}),d.tsx("span",{class:"esri-layer-list__item-action-title"},b.title));var g};c.prototype._countActions=function(a){return a.reduce(function(a,c){return a+c.length},0)};c.prototype._getActionImageStyles=function(a){var b=
a.image||null;a.className||b||(b=F);return{"background-image":b?'url("'+b+'")':null}};c.prototype._toggleActionsOpen=function(a){a=a.currentTarget["data-item"];a.actionsOpen=!a.actionsOpen};c.prototype._triggerAction=function(a){a=a.currentTarget;this.triggerAction(a["data-action"],a["data-item"])};c.prototype._labelClick=function(a){var b=a.currentTarget;a=b.getAttribute("data-parent-visibility");b=b["data-item"];"exclusive"===a&&b.visible||(b.visible=!b.visible)};c.prototype._toggleChildrenClick=
function(a){a=a.currentTarget["data-item"];a.open=!a.open};e([h.aliasOf("viewModel.createActionsFunction"),d.renderable()],c.prototype,"createActionsFunction",void 0);e([h.property(),d.renderable()],c.prototype,"statusIndicatorsVisible",void 0);e([h.property(),d.renderable()],c.prototype,"errorsVisible",void 0);e([h.aliasOf("viewModel.listItemCreatedFunction"),d.renderable()],c.prototype,"listItemCreatedFunction",void 0);e([h.aliasOf("viewModel.operationalItems"),d.renderable()],c.prototype,"operationalItems",
void 0);e([h.aliasOf("viewModel.view"),d.renderable()],c.prototype,"view",void 0);e([d.vmEvent("trigger-action"),h.property({type:w}),d.renderable("viewModel.state")],c.prototype,"viewModel",void 0);e([h.aliasOf("viewModel.triggerAction")],c.prototype,"triggerAction",null);e([d.accessibleHandler()],c.prototype,"_toggleActionsOpen",null);e([d.accessibleHandler()],c.prototype,"_triggerAction",null);e([d.accessibleHandler()],c.prototype,"_labelClick",null);e([d.accessibleHandler()],c.prototype,"_toggleChildrenClick",
null);return c=e([h.subclass("esri.widgets.LayerList")],c)}(h.declared(D))});