// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/tsSupport/assignHelper ./support/widget ../core/accessorSupport/decorators ../core/lang ../core/HandleRegistry ../core/watchUtils ./Widget ../widgets/support/widgetUtils ./Popup/PopupRenderer ./Popup/PopupViewModel dojo/i18n!./Popup/nls/Popup ./Spinner dojo/dom-geometry".split(" "),function(Q,W,R,d,q,c,e,D,S,l,J,M,T,E,n,U,N){function h(c,b){return void 0===b?"esri-popup__"+c:"esri-popup__"+c+"-"+
b}var V=Q.toUrl("./Popup/images/default-action.svg"),P={buttonEnabled:!0,position:"auto",breakpoint:{width:544}};return function(O){function b(a){a=O.call(this)||this;a._containerNode=null;a._mainContainerNode=null;a._featureMenuButtonNode=null;a._featureMenuViewportNode=null;a._handleRegistry=new S;a._displayActionTextLimit=2;a._pointerOffsetInPx=16;a._spinner=null;a._closeFeatureMenuHandle=null;a.actions=null;a.alignment="auto";a.autoCloseEnabled=null;a.content=null;a.collapsed=!1;a.collapseEnabled=
!0;a.dockEnabled=!1;a.featureCount=null;a.featureMenuOpen=!1;a.features=null;a.featureNavigationEnabled=!0;a.highlightEnabled=null;a.location=null;a.popupRenderers=[];a.promises=null;a.selectedFeature=null;a.selectedFeatureIndex=null;a.selectedPopupRenderer=null;a.spinnerEnabled=!0;a.title=null;a.updateLocationEnabled=null;a.view=null;a.viewModel=new E;a.visible=null;return a}R(b,O);b.prototype.postInitialize=function(){var a=this,b=l.pausable(this,"\n      viewModel.visible,\n      dockEnabled,\n      viewModel.selectedFeature\n    ",
function(){return a._closeFeatureMenu()});this._closeFeatureMenuHandle=b;this.own(l.watch(this,"viewModel.screenLocation",function(){return a._positionContainer()}),l.watch(this,["viewModel.visible","dockEnabled"],function(){return a._toggleScreenLocationEnabled()}),l.watch(this,"viewModel.screenLocation",function(b,r){!!b!==!!r&&a.reposition()}),l.watch(this,"viewModel.features",function(b){return a._createPopupRenderers(b)}),l.watch(this,"viewModel.view.padding viewModel.view.size viewModel.visible viewModel.waitingForResult viewModel.location alignment".split(" "),
function(){return a.reposition()}),b,l.watch(this,"spinnerEnabled",function(b){return a._spinnerEnabledChange(b)}),l.watch(this,["title","content"],function(){return a._hasFeatureUpdated()}),l.watch(this,"viewModel.view.size",function(b,r){return a._updateDockEnabledForViewSize(b,r)}),l.watch(this,"viewModel.view",function(b,r){return a._viewChange(b,r)}),l.watch(this,"viewModel.view.ready",function(b,r){return a._viewReadyChange(b,r)}),l.watch(this,["viewModel.waitingForResult","viewModel.location"],
function(){return a._displaySpinner()}),l.watch(this,["popupRenderers","viewModel.selectedFeatureIndex"],function(){return a._updatePopupRenderer()}),l.watch(this,"selectedPopupRenderer.viewModel.title",function(b){return a._setTitleFromPopupRenderer(b)}),l.watch(this,["selectedPopupRenderer.viewModel.content","selectedPopupRenderer.viewModel.waitingForContent"],function(){return a._setContentFromPopupRenderer()}),l.on(this,"viewModel","trigger-action",function(b){return a._zoomToAction(b)}))};b.prototype.destroy=
function(){this._destroyPopupRenderers();this._destroySpinner();this._handleRegistry.destroy();this._handleRegistry=null};Object.defineProperty(b.prototype,"currentAlignment",{get:function(){return this._getCurrentAlignment()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"currentDockPosition",{get:function(){return this._getCurrentDockPosition()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"dockOptions",{get:function(){return this._get("dockOptions")||P},
set:function(a){var b=q({},P),c=this.get("viewModel.view.breakpoints"),m={};c&&(m.width=c.xsmall,m.height=c.xsmall);a=q({},b,a);b=q({},b.breakpoint,m);m=a.breakpoint;!0===m?a.breakpoint=b:"object"===typeof m&&(a.breakpoint=q({},b,m));this._set("dockOptions",a);this._setCurrentDockPosition();this.reposition()},enumerable:!0,configurable:!0});b.prototype.clear=function(){};b.prototype.close=function(){this.visible=!1};b.prototype.next=function(){return null};b.prototype.open=function(a){a=q({visible:!0},
{featureMenuOpen:!1,updateLocationEnabled:!1,promises:[]},a);a.featureMenuOpen&&this._closeFeatureMenuHandle.pause();this.set(a)};b.prototype.previous=function(){return null};b.prototype.reposition=function(){this.renderNow();this._positionContainer();this._setCurrentAlignment()};b.prototype.triggerAction=function(a){return null};b.prototype.render=function(){var a=this.collapsed,b=this.collapseEnabled,k=this.dockEnabled,m=this.dockOptions,g=this.actions,f=this.featureMenuOpen,d=this.featureNavigationEnabled,
e=this.popupRenderers,l=this.visible,A=this.viewModel,q=A.featureCount,J=A.promiseCount,F=A.pendingPromisesCount,z=A.selectedFeatureIndex,C=A.title,A=A.waitingForResult,d=1<q&&d,f=1<q&&f,B=b&&!f&&a,E=g&&g.length,v=d&&this._getPageText(q,z),K=this._renderContent(),t=M.isRtl(),G=this.get("selectedPopupRenderer")?this.get("selectedPopupRenderer.viewModel.waitingForContent")||this.get("selectedPopupRenderer.viewModel.content"):K,L=k?n.undock:n.dock,g=this.currentAlignment,a=this.currentDockPosition,F=
F?c.tsx("div",{key:h("loading-container"),role:"presentation",class:"esri-popup__loading-container","aria-label":n.loading,title:n.loading},c.tsx("span",{"aria-hidden":"true",class:c.join("esri-popup__icon","esri-rotating esri-icon-loading-indicator")})):null,H=(w={},w["esri-icon-layer-list"]=!f,w["esri-icon-close"]=f,w),w=c.tsx("span",{"aria-hidden":"true",class:"esri-popup__icon",classes:H}),H=(u={},u["esri-icon-right-triangle-arrow"]=t,u["esri-popup__pagination-previous-icon--rtl"]=t,u["esri-icon-left-triangle-arrow"]=
!t,u["esri-popup__pagination-previous-icon"]=!t,u),u=c.tsx("span",{"aria-hidden":"true",class:"esri-popup__icon",classes:H}),u=c.tsx("div",{role:"button",tabIndex:0,bind:this,onclick:this._previous,onkeydown:this._previous,class:c.join("esri-popup__button","esri-popup__pagination-previous"),"aria-label":n.previous,title:n.previous},u),t=(x={},x["esri-icon-left-triangle-arrow"]=t,x["esri-popup__pagination-next-icon--rtl"]=t,x["esri-icon-right-triangle-arrow"]=!t,x["esri-popup__pagination-next-icon"]=
!t,x),x=c.tsx("span",{"aria-hidden":"true",class:"esri-popup__icon",classes:t}),x=c.tsx("div",{role:"button",tabIndex:0,bind:this,onclick:this._next,onkeydown:this._next,class:c.join("esri-popup__button","esri-popup__pagination-next"),"aria-label":n.next,title:n.next},x),w=c.tsx("div",{role:"button",tabIndex:0,bind:this,onclick:this._toggleFeatureMenu,onkeydown:this._toggleFeatureMenu,afterCreate:this._storeFeatureMenuButtonNode,afterUpdate:this._storeFeatureMenuButtonNode,class:c.join("esri-popup__button",
"esri-popup__feature-menu-button"),"aria-label":n.menu,title:n.menu},w),v=c.tsx("div",{class:"esri-popup__pagination-page-text"},v),x=d?c.tsx("div",{class:"esri-popup__navigation-buttons"},u,v,x,w):null,v=this._wouldDockTo(),w="top-left"===v||"bottom-left"===v,t="top-center"===v,u="bottom-center"===v,v="top-right"===v||"bottom-right"===v?c.tsx("span",{"aria-hidden":"true",key:h("dock-right-icon"),class:c.join("esri-popup__icon","esri-popup__icon--dock-icon","esri-icon-dock-right")}):null,w=w?c.tsx("span",
{"aria-hidden":"true",key:h("dock-left-icon"),class:c.join("esri-popup__icon","esri-popup__icon--dock-icon","esri-icon-dock-left")}):null,t=t?c.tsx("span",{"aria-hidden":"true",key:h("dock-top-icon"),class:c.join("esri-popup__icon","esri-popup__icon--dock-icon","esri-icon-maximize")}):null,u=u?c.tsx("span",{"aria-hidden":"true",key:h("dock-bottom-icon"),class:c.join("esri-popup__icon","esri-popup__icon--dock-icon","esri-icon-dock-bottom")}):null,H=k?c.tsx("span",{"aria-hidden":"true",key:h("undocked-icon"),
class:c.join("esri-popup__icon","esri-icon-minimize")}):null,m=m.buttonEnabled?c.tsx("div",{role:"button","aria-label":L,title:L,tabIndex:0,bind:this,onclick:this._toggleDockEnabled,onkeydown:this._toggleDockEnabled,class:c.join("esri-popup__button","esri-popup__button--dock")},v,t,w,u,H):null,b=b&&(G||E||d),L=(y={},y["esri-popup__header-title--button"]=b,y),y=b?B?n.expand:n.collapse:"",C=C?c.tsx("h1",{class:"esri-popup__header-title",role:b?"button":"heading","aria-label":y,title:y,classes:L,bind:this,
tabIndex:b?0:-1,onclick:this._toggleCollapsed,onkeydown:this._toggleCollapsed,innerHTML:C}):null,y=c.tsx("span",{"aria-hidden":"true",class:c.join("esri-popup__icon","esri-icon-close")}),y=c.tsx("div",{role:"button",tabIndex:0,bind:this,onclick:this._close,onkeydown:this._close,class:"esri-popup__button","aria-label":n.close,title:n.close},y),C=c.tsx("header",{class:"esri-popup__header"},C,c.tsx("div",{class:"esri-popup__header-buttons"},m,y)),K=G&&!B?c.tsx("article",{key:h("content-container"),class:"esri-popup__content"},
K):null,G=!B&&("bottom-left"===g||"bottom-center"===g||"bottom-right"===g||"top-left"===a||"top-center"===a||"top-right"===a),B=!B&&("top-left"===g||"top-center"===g||"top-right"===g||"bottom-left"===a||"bottom-center"===a||"bottom-right"===a),y=f?null:c.tsx("div",{key:h("actions"),class:"esri-popup__actions"},this._renderActions()),F=c.tsx("section",{key:h("navigation"),class:"esri-popup__navigation"},F,x),d=d||E?c.tsx("div",{key:h("feature-buttons"),class:"esri-popup__feature-buttons"},y,F):null;
(z=this._renderFeatureMenuNode(e,z,f))&&this._closeFeatureMenuHandle.resume();e=D.substitute({total:e.length},n.selectedFeatures);z=c.tsx("section",{key:h("menu"),class:"esri-popup__feature-menu"},c.tsx("h2",{class:"esri-popup__feature-menu-header"},e),c.tsx("nav",{class:"esri-popup__feature-menu-viewport",afterCreate:this._storeFeatureMenuViewportNode,afterUpdate:this._storeFeatureMenuViewportNode},z));this._featureMenuViewportNode&&(this._featureMenuViewportNode.scrollTop=0);e=k?null:c.tsx("div",
{key:h("pointer"),class:"esri-popup__pointer",role:"presentation"},c.tsx("div",{class:c.join("esri-popup__pointer-direction","esri-popup--shadow")}));f=(p={},p["esri-popup--aligned-top-center"]="top-center"===g,p["esri-popup--aligned-bottom-center"]="bottom-center"===g,p["esri-popup--aligned-top-left"]="top-left"===g,p["esri-popup--aligned-bottom-left"]="bottom-left"===g,p["esri-popup--aligned-top-right"]="top-right"===g,p["esri-popup--aligned-bottom-right"]="bottom-right"===g,p["esri-popup--is-docked"]=
k,p["esri-popup--shadow"]=!k,p["esri-popup--feature-updated"]=l,p["esri-popup--is-docked-top-left"]="top-left"===a,p["esri-popup--is-docked-top-center"]="top-center"===a,p["esri-popup--is-docked-top-right"]="top-right"===a,p["esri-popup--is-docked-bottom-left"]="bottom-left"===a,p["esri-popup--is-docked-bottom-center"]="bottom-center"===a,p["esri-popup--is-docked-bottom-right"]="bottom-right"===a,p["esri-popup--feature-menu-open"]=f,p);p=this.get("selectedFeature.layer.title");g=this.get("selectedFeature.layer.id");
k=(I={},I["esri-popup--shadow"]=k,I);I=G?z:null;z=B?z:null;a=G?d:null;d=B?d:null;l=l&&!A&&(J?q:1)?c.tsx("div",{key:h("container"),class:"esri-popup__position-container",classes:f,"data-layer-title":p,"data-layer-id":g,bind:this,afterCreate:this._positionContainer,afterUpdate:this._positionContainer},c.tsx("div",{class:c.join("esri-popup__main-container","esri-widget"),classes:k,bind:this,afterCreate:this._storeMainContainerNode,afterUpdate:this._storeMainContainerNode},a,I,C,K,d,z),e):null;return c.tsx("div",
{key:h("base"),class:"esri-popup",role:"presentation"},l);var w,u,x,y,p,I};b.prototype._setTitleFromPopupRenderer=function(a){this.viewModel.title=a||""};b.prototype._setContentFromPopupRenderer=function(){this.viewModel.content=this.selectedPopupRenderer||null;this.scheduleRender()};b.prototype._zoomToAction=function(a){a.action&&"zoom-to"===a.action.id&&this.viewModel.zoomToLocation()};b.prototype._spinnerEnabledChange=function(a){this._destroySpinner();a&&(a=this.get("viewModel.view"),this._createSpinner(a))};
b.prototype._displaySpinner=function(){var a=this._spinner;if(a){var b=this.viewModel,c=b.location;b.waitingForResult?a.show({location:c}):a.hide()}};b.prototype._getIconStyles=function(a){return{"background-image":a?"url("+a+")":""}};b.prototype._renderAction=function(a,b,k,m){var r=this,f=l.watch(a,["id","className","title","image","visible"],function(){return r.scheduleRender()});this._handleRegistry.add(f,m);f=this.get("selectedFeature.attributes");"zoom-to"===a.id&&(a.title=n.zoom,a.className=
"esri-icon-zoom-in-magnifying-glass");m=a.title;var d=a.className,e=a.image||d?a.image:V;m=m&&f?D.substitute(f,m):m;d=d&&f?D.substitute(f,d):d;f=e&&f?D.substitute(f,e):e;e=(q={},q[d]=!!d,q["esri-popup__action-image"]=!!f,q);k=k<=this._displayActionTextLimit?c.tsx("span",{key:h("action-text-"+b+"-"+a.uid),class:"esri-popup__action-text"},m):null;return a.visible?c.tsx("div",{key:h("action-"+b+"-"+a.uid),role:"button",tabIndex:0,title:m,"aria-label":m,class:c.join("esri-popup__button","esri-popup__action"),
bind:this,"data-action-index":b,onclick:this._triggerAction,onkeydown:this._triggerAction},c.tsx("span",{key:h("action-icon-"+b+"-"+a.uid),"aria-hidden":"true",class:"esri-popup__icon",classes:e,styles:this._getIconStyles(f)}),k):null;var q};b.prototype._renderActions=function(){var a=this;this._handleRegistry.remove("actions");var b=this.actions;if(b){var k=b.length,b=b.toArray().map(function(b,c){return a._renderAction(b,c,k,"actions")});return c.tsx("div",{key:h("actions"),class:"esri-popup__actions"},
b)}};b.prototype._updatePopupRenderer=function(){var a=this.popupRenderers[this.viewModel.selectedFeatureIndex]||null;a&&!a.contentEnabled&&(a.contentEnabled=!0);this._set("selectedPopupRenderer",a)};b.prototype._destroyPopupRenderers=function(){this.popupRenderers.forEach(function(a){return a.destroy()});this._set("popupRenderers",[])};b.prototype._createPopupRenderers=function(a){var b=this;this._destroyPopupRenderers();var c=[];a&&a.forEach(function(a){a=new T({contentEnabled:!1,graphic:a,view:b.get("viewModel.view")});
c.push(a)});this._set("popupRenderers",c)};b.prototype._isScreenLocationWithinView=function(a,b){return-1<a.x&&-1<a.y&&a.x<=b.width&&a.y<=b.height};b.prototype._isOutsideView=function(a){var b=a.popupHeight,c=a.popupWidth,d=a.screenLocation,g=a.side;a=a.view;if(isNaN(c)||isNaN(b)||!a||!d)return!1;var f=a.padding;return"right"===g&&d.x+c/2>a.width-f.right||"left"===g&&d.x-c/2<f.left||"top"===g&&d.y-b<f.top||"bottom"===g&&d.y+b>a.height-f.bottom?!0:!1};b.prototype._determineCurrentAlignment=function(){var a=
this._pointerOffsetInPx,b=this._containerNode,c=this._mainContainerNode,d=this.viewModel,g=d.screenLocation,d=d.view;if(!g||!d||!b)return"top-center";if(!this._isScreenLocationWithinView(g,d))return this._get("currentAlignment")||"top-center";var f=c?window.getComputedStyle(c,null):null,c=f?parseInt(f.getPropertyValue("max-height").replace(/[^-\d\.]/g,""),10):0,f=f?parseInt(f.getPropertyValue("height").replace(/[^-\d\.]/g,""),10):0,e=N.getContentBox(b),b=e.w+a,e=Math.max(e.h,c,f)+a,a=this._isOutsideView({popupHeight:e,
popupWidth:b,screenLocation:g,side:"right",view:d}),c=this._isOutsideView({popupHeight:e,popupWidth:b,screenLocation:g,side:"left",view:d}),f=this._isOutsideView({popupHeight:e,popupWidth:b,screenLocation:g,side:"top",view:d}),g=this._isOutsideView({popupHeight:e,popupWidth:b,screenLocation:g,side:"bottom",view:d});return c?f?"bottom-right":"top-right":a?f?"bottom-left":"top-left":f?g?"top-center":"bottom-center":"top-center"};b.prototype._getCurrentAlignment=function(){var a=this.alignment;return this.dockEnabled?
null:"auto"===a?this._determineCurrentAlignment():"function"===typeof a?a.call(this):a};b.prototype._setCurrentAlignment=function(){this._set("currentAlignment",this._getCurrentAlignment())};b.prototype._setCurrentDockPosition=function(){this._set("currentDockPosition",this._getCurrentDockPosition())};b.prototype._getDockPosition=function(){var a=this.get("dockOptions.position");return"auto"===a?this._determineCurrentDockPosition():"function"===typeof a?a.call(this):a};b.prototype._getCurrentDockPosition=
function(){return this.dockEnabled?this._getDockPosition():null};b.prototype._wouldDockTo=function(){return this.dockEnabled?null:this._getDockPosition()};b.prototype._renderFeatureMenuItemNode=function(a,b,d,e){var r=b===d,f=(k={},k["esri-popup__feature-menu-item--selected"]=r,k);a=a.title||n.untitled;k=r?c.tsx("span",{key:h("feature-menu-selected-feature-"+d),title:n.selectedFeature,"aria-label":n.selectedFeature,class:"esri-icon-check-mark"}):null;return c.tsx("li",{role:"menuitem",tabIndex:r||
!e?-1:0,key:h("feature-menu-feature-"+d),classes:f,class:"esri-popup__feature-menu-item",title:a,"aria-label":a,bind:this,"data-feature-index":b,onclick:this._selectFeature,onkeydown:this._selectFeature},c.tsx("span",{class:"esri-popup__feature-menu-title"},a,k));var k};b.prototype._renderFeatureMenuNode=function(a,b,d){var r=this;return 1<a.length?c.tsx("ol",{class:"esri-popup__feature-menu-list",role:"menu"},a.map(function(a,c){return r._renderFeatureMenuItemNode(a,c,b,d)})):null};b.prototype._determineCurrentDockPosition=
function(){var a=this.get("viewModel.view"),b=M.isRtl()?"top-left":"top-right";if(!a)return b;var c=a.padding||{left:0,right:0,top:0,bottom:0},c=a.width-c.left-c.right;return(a=a.get("breakpoints"))&&c<=a.xsmall?"bottom-center":b};b.prototype._renderContent=function(){var a=this.get("viewModel.content");if("string"===typeof a)return c.tsx("div",{key:h("content-string"),innerHTML:a});if(a&&a.isInstanceOf&&a.isInstanceOf(J))return c.tsx("div",{key:h("content-widget")},a.render());if(a instanceof HTMLElement)return c.tsx("div",
{key:h("content-html-element"),bind:a,afterUpdate:this._attachToNode,afterCreate:this._attachToNode});if(a&&"function"===typeof a.postMixInProperties&&"function"===typeof a.buildRendering&&"function"===typeof a.postCreate&&"function"===typeof a.startup)return c.tsx("div",{key:h("content-dijit"),bind:a.domNode,afterUpdate:this._attachToNode,afterCreate:this._attachToNode})};b.prototype._attachToNode=function(a){a.appendChild(this)};b.prototype._positionContainer=function(a){void 0===a&&(a=this._containerNode);
a&&(this._containerNode=a);if(a){var b=this.viewModel.screenLocation,c=N.getContentBox(a);if(b=this._calculatePositionStyle(b,c))a.style.top=b.top,a.style.left=b.left,a.style.bottom=b.bottom,a.style.right=b.right}};b.prototype._calculateFullWidth=function(a){var b=this.currentAlignment,c=this._pointerOffsetInPx;return"top-left"===b||"bottom-left"===b||"top-right"===b||"bottom-right"===b?a+c:a};b.prototype._calculateAlignmentPosition=function(a,b,c,d){var e=this.currentAlignment,f=this._pointerOffsetInPx;
d/=2;var k=c.height-b;c=c.width-a;if("bottom-center"===e)return{top:b+f,left:a-d};if("top-left"===e)return{bottom:k+f,right:c+f};if("bottom-left"===e)return{top:b+f,right:c+f};if("top-right"===e)return{bottom:k+f,left:a+f};if("bottom-right"===e)return{top:b+f,left:a+f};if("top-center"===e)return{bottom:k+f,left:a-d}};b.prototype._calculatePositionStyle=function(a,b){var c=this.view;if(c){var d=c.padding;if(this.dockEnabled)return{left:d.left?d.left+"px":"",top:d.top?d.top+"px":"",right:d.right?d.right+
"px":"",bottom:d.bottom?d.bottom+"px":""};if(a&&b&&(b=this._calculateFullWidth(b.w),a=this._calculateAlignmentPosition(a.x,a.y,c,b)))return{top:void 0!==a.top?a.top+"px":"auto",left:void 0!==a.left?a.left+"px":"auto",bottom:void 0!==a.bottom?a.bottom+"px":"auto",right:void 0!==a.right?a.right+"px":"auto"}}};b.prototype._viewChange=function(a,b){a&&b&&(this.close(),this.clear())};b.prototype._viewReadyChange=function(a,b){a?(a=this.get("viewModel.view"),this._wireUpView(a)):b&&(this.close(),this.clear())};
b.prototype._wireUpView=function(a){this._destroySpinner();a&&(this.spinnerEnabled&&this._createSpinner(a),this._setDockEnabledForViewSize(this.dockOptions))};b.prototype._dockingThresholdCrossed=function(a,b,c){var d=a[0];a=a[1];var e=b[0];b=b[1];var f=c.width;c=c.height;return d<=f&&e>f||d>f&&e<=f||a<=c&&b>c||a>c&&b<=c};b.prototype._updateDockEnabledForViewSize=function(a,b){if(a&&b){var c=this.get("viewModel.view.padding")||{left:0,right:0,top:0,bottom:0},d=c.left+c.right,e=c.top+c.bottom,c=[],
f=[];c[0]=a[0]-d;c[1]=a[1]-e;f[0]=b[0]-d;f[1]=b[1]-e;a=this.dockOptions;this._dockingThresholdCrossed(c,f,a.breakpoint)&&this._setDockEnabledForViewSize(a);this._setCurrentDockPosition()}};b.prototype._hasFeatureUpdated=function(){var a=this._containerNode,b=this.viewModel.pendingPromisesCount,c=this.get("selectedPopupRenderer.viewModel.waitingForContent");!a||b||c||(a.classList.remove("esri-popup--feature-updated"),a.offsetHeight,a.classList.add("esri-popup--feature-updated"))};b.prototype._storeMainContainerNode=
function(a){this._mainContainerNode=a};b.prototype._storeFeatureMenuButtonNode=function(a){this._featureMenuButtonNode=a};b.prototype._storeFeatureMenuViewportNode=function(a){this._featureMenuViewportNode=a};b.prototype._toggleScreenLocationEnabled=function(){var a=this.dockEnabled,b=this.viewModel;b&&(b.screenLocationEnabled=this.visible&&!a)};b.prototype._shouldDockAtCurrentViewSize=function(a){a=a.breakpoint;var b=this.get("viewModel.view.ui"),c=b.width,b=b.height;if(isNaN(c)||isNaN(b))return!1;
c=a.hasOwnProperty("width")&&c<=a.width;a=a.hasOwnProperty("height")&&b<=a.height;return c||a};b.prototype._setDockEnabledForViewSize=function(a){a.breakpoint&&(this.dockEnabled=this._shouldDockAtCurrentViewSize(a))};b.prototype._getPageText=function(a,b){return D.substitute({index:b+1,total:a},n.pageText)};b.prototype._destroySpinner=function(){this._spinner&&(this._spinner.destroy(),this._spinner=null)};b.prototype._createSpinner=function(a){a&&(this._spinner=new U({container:document.createElement("div"),
view:a}),a.root.appendChild(this._spinner.container))};b.prototype._closeFeatureMenu=function(){this.featureMenuOpen=!1};b.prototype._toggleCollapsed=function(){this.collapsed=!this.collapsed};b.prototype._close=function(){this.close()};b.prototype._toggleDockEnabled=function(){this.dockEnabled=!this.dockEnabled};b.prototype._toggleFeatureMenu=function(){this.featureMenuOpen=!this.featureMenuOpen};b.prototype._triggerAction=function(a){this.viewModel.triggerAction(a.currentTarget["data-action-index"])};
b.prototype._selectFeature=function(a){a=a.currentTarget["data-feature-index"];isNaN(a)||(this.viewModel.selectedFeatureIndex=a);this._featureMenuButtonNode&&this._featureMenuButtonNode.focus()};b.prototype._next=function(){this.next()};b.prototype._previous=function(){this.previous()};d([e.aliasOf("viewModel.actions"),c.renderable()],b.prototype,"actions",void 0);d([e.property()],b.prototype,"alignment",void 0);d([e.aliasOf("viewModel.autoCloseEnabled")],b.prototype,"autoCloseEnabled",void 0);d([e.aliasOf("viewModel.content"),
c.renderable()],b.prototype,"content",void 0);d([e.property(),c.renderable()],b.prototype,"collapsed",void 0);d([e.property(),c.renderable()],b.prototype,"collapseEnabled",void 0);d([e.property({readOnly:!0,dependsOn:["dockEnabled","alignment"]}),c.renderable()],b.prototype,"currentAlignment",null);d([e.property({readOnly:!0,dependsOn:["dockEnabled","dockOptions"]}),c.renderable()],b.prototype,"currentDockPosition",null);d([e.property(),c.renderable()],b.prototype,"dockOptions",null);d([e.property(),
c.renderable()],b.prototype,"dockEnabled",void 0);d([e.aliasOf("viewModel.featureCount"),c.renderable()],b.prototype,"featureCount",void 0);d([e.property(),c.renderable()],b.prototype,"featureMenuOpen",void 0);d([e.aliasOf("viewModel.features"),c.renderable()],b.prototype,"features",void 0);d([e.property(),c.renderable()],b.prototype,"featureNavigationEnabled",void 0);d([e.aliasOf("viewModel.highlightEnabled")],b.prototype,"highlightEnabled",void 0);d([e.aliasOf("viewModel.location"),c.renderable()],
b.prototype,"location",void 0);d([e.property({readOnly:!0}),c.renderable()],b.prototype,"popupRenderers",void 0);d([e.aliasOf("viewModel.promises")],b.prototype,"promises",void 0);d([e.aliasOf("viewModel.selectedFeature"),c.renderable()],b.prototype,"selectedFeature",void 0);d([e.aliasOf("viewModel.selectedFeatureIndex"),c.renderable()],b.prototype,"selectedFeatureIndex",void 0);d([e.property({readOnly:!0}),c.renderable()],b.prototype,"selectedPopupRenderer",void 0);d([e.property()],b.prototype,"spinnerEnabled",
void 0);d([e.aliasOf("viewModel.title"),c.renderable()],b.prototype,"title",void 0);d([e.aliasOf("viewModel.updateLocationEnabled")],b.prototype,"updateLocationEnabled",void 0);d([e.aliasOf("viewModel.view")],b.prototype,"view",void 0);d([e.property({type:E}),c.renderable("viewModel.screenLocation viewModel.screenLocationEnabled viewModel.state viewModel.pendingPromisesCount viewModel.promiseCount viewModel.waitingForResult".split(" ")),c.vmEvent(["triggerAction","trigger-action"])],b.prototype,"viewModel",
void 0);d([e.aliasOf("viewModel.visible"),c.renderable()],b.prototype,"visible",void 0);d([e.aliasOf("viewModel.clear")],b.prototype,"clear",null);d([e.aliasOf("viewModel.next")],b.prototype,"next",null);d([e.aliasOf("viewModel.previous")],b.prototype,"previous",null);d([e.aliasOf("viewModel.triggerAction")],b.prototype,"triggerAction",null);d([c.accessibleHandler()],b.prototype,"_toggleCollapsed",null);d([c.accessibleHandler()],b.prototype,"_close",null);d([c.accessibleHandler()],b.prototype,"_toggleDockEnabled",
null);d([c.accessibleHandler()],b.prototype,"_toggleFeatureMenu",null);d([c.accessibleHandler()],b.prototype,"_triggerAction",null);d([c.accessibleHandler()],b.prototype,"_selectFeature",null);d([c.accessibleHandler()],b.prototype,"_next",null);d([c.accessibleHandler()],b.prototype,"_previous",null);return b=d([e.subclass("esri.widgets.Popup")],b)}(e.declared(J))});