// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ./Graphics3DSymbolLayer ./Graphics3DGraphicLayer ./Graphics3DSymbolCommonCode ../../../../geometry/Polygon ../../../../geometry/Point ../../support/projectionUtils ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/materials/Material ../../webgl-engine/lib/Util ./earcut/earcut ./graphicUtils".split(" "),function(M,oa,Y,Z,aa,
H,ba,ca,da,N,O,ea,fa,ga,ha,ia,ja,ka){function la(d,e,a,b,c,h,f,v,w,k,l,t,m,ma){var n=a.length/3,C=0;l+=2*b.count;var g=b.index,y=b.count,p=w,u=l;q.set(m,r);var x=0<t?1:-1,g=3*g,z=p;m=3*z;for(var A=p+y,p=3*A,D=0;D<y;++D)ma&&(r[0]=d[g+0],r[1]=d[g+1],r[2]=d[g+2],q.normalize(r)),c[m+0]=d[g+0],c[m+1]=d[g+1],c[m+2]=d[g+2],h[m+0]=e[g+0],h[m+1]=e[g+1],h[m+2]=e[g+2],f[m+0]=-x*r[0],f[m+1]=-x*r[1],f[m+2]=-x*r[2],v[z]=0,c[p+0]=d[g+0]+t*r[0],c[p+1]=d[g+1]+t*r[1],c[p+2]=d[g+2]+t*r[2],h[p+0]=e[g+0],h[p+1]=e[g+1],
h[p+2]=e[g+2],f[p+0]=x*r[0],f[p+1]=x*r[1],f[p+2]=x*r[2],v[A]=t,m+=3,p+=3,g+=3,z+=1,A+=1;g=0;m=3*u;p=3*(u+n);m=3*(u+n);p=3*u;d=P;e=Q;0>t&&(d=Q,e=P);for(D=0;D<n;++D)k[m+0]=a[g+d[0]],k[m+1]=a[g+d[1]],k[m+2]=a[g+d[2]],k[p+0]=a[g+e[0]]+y,k[p+1]=a[g+e[1]]+y,k[p+2]=a[g+e[2]]+y,m+=3,p+=3,g+=3;w+=2*b.count;l=l+2*n-(2*b.count+2*n);R(c,h,v,f,C,b.pathLengths[0],b.count,w,k,l,t);w+=4*b.pathLengths[0];l+=2*b.pathLengths[0];C+=b.pathLengths[0];for(a=1;a<b.pathLengths.length;++a)R(c,h,v,f,C,b.pathLengths[a],b.count,
w,k,l,t),w+=4*b.pathLengths[a],l+=2*b.pathLengths[a],C+=b.pathLengths[a]}function K(d,e,a,b,c,h,f){b[h]=b[f];f*=3;h*=3;d[h+0]=d[f+0];d[h+1]=d[f+1];d[h+2]=d[f+2];e[h+0]=e[f+0];e[h+1]=e[f+1];e[h+2]=e[f+2];a[h+0]=c[0];a[h+1]=c[1];a[h+2]=c[2]}function R(d,e,a,b,c,h,f,v,w,k,l){var t=c,m=c+1,r=c+f,n=c+f+1,C=v,g=v+1,y=v+2*h;v=v+2*h+1;0>l&&(t=c+f+1,n=c);k*=3;for(var p=0;p<h;++p){p===h-1&&(0<l?(m=c,n=c+f):(m=c,t=c+f));var u=d,x=t,z=m,A=r,D=I,x=3*x,z=3*z,A=3*A;q.set3(u[x++],u[x++],u[x++],L);q.set3(u[z++],u[z++],
u[z++],S);q.set3(u[A++],u[A++],u[A++],T);q.subtract(S,L,U);q.subtract(T,L,V);q.cross(V,U,D);q.normalize(D,D);K(d,e,b,a,I,C,t);K(d,e,b,a,I,g,m);K(d,e,b,a,I,y,r);K(d,e,b,a,I,v,n);w[k++]=C;w[k++]=y;w[k++]=v;w[k++]=C;w[k++]=v;w[k++]=g;t++;m++;r++;n++;C+=2;g+=2;y+=2;v+=2}}function na(d,e,a,b){var c=b.setAltitude;J.spatialReference=a.spatialReference;for(var h=d.getGeometryRecords(),f=h.length,v="absolute-height"!==e.mode,w=0,k=0;k<f;k++){var l=h[k].geometry,t=h[k].transformation;E[0]=t[12];E[1]=t[13];
E[2]=t[14];l.invalidateBoundingInfo();for(var m=l.getData().getVertexAttr(),l=m[F.POSITION].data,t=m[F.SIZE].data,m=m.mapPos.data,q=l.length/3,n=0,r=0,g=!1,y=0,p=0;p<q;p++){J.x=m[r];J.y=m[r+1];J.z=m[r+2];G[0]=l[n];G[1]=l[n+1];G[2]=l[n+2];var u=H.computeElevation(a,J,e,b,v?W:null);v&&(y+=W.terrainElevation);B[0]=l[n]+E[0];B[1]=l[n+1]+E[1];B[2]=l[n+2]+E[2];c(u+t[n/3],B,0);l[n]=B[0]-E[0];l[n+1]=B[1]-E[1];l[n+2]=B[2]-E[2];u=.01/b.unitInMeters;if(Math.abs(G[0]-l[n])>u||Math.abs(G[1]-l[n+1])>u||Math.abs(G[2]-
l[n+2])>u)g=!0;r+=3;n+=3}g&&d.geometryVertexAttrsUpdated(k);w+=y/q}return w/f}var F=ia.VertexAttrConstants,q=N.vec3d,X=N.mat4d,B=q.create(),r=q.create(),P=[0,2,1],Q=[0,1,2],J=new ca,W={verticalDistanceToGround:0,terrainElevation:0};M=function(d){function e(){return null!==d&&d.apply(this,arguments)||this}Y(e,d);e.prototype._prepareResources=function(){if(!this._isPropertyDriven("size")){var a=ka.validateSymbolLayerSize(this._getSymbolSize());if(a){this._logWarning(a);this.reject();return}}var a=this._getStageIdHint(),
b=this._getMaterialOpacityAndColor(),c=q.create(b),b=b[3],c={diffuse:c,ambient:c,opacity:b,transparent:1>b||this._isPropertyDriven("opacity"),vertexColors:!0};this._material=new ha(c,a+"_3dlinemat");this._context.stage.add(O.ModelContentType.MATERIAL,this._material);this.resolve()};e.prototype.destroy=function(){d.prototype.destroy.call(this);this.isFulfilled()||this.reject();this._material&&this._context.stage.remove(O.ModelContentType.MATERIAL,this._material.getId())};e.prototype.createGraphics3DGraphic=
function(a,b){var c=this._validateGeometry(a.geometry);if("polygon"!==c.type&&"extent"!==c.type)return this._logWarning("unsupported geometry type for extrude symbol: "+c.type),null;var c="polygon"===c.type||"extent"===c.type?"rings":"paths",h="graphic"+a.uid,f=this._getVertexOpacityAndColor(b,Float32Array,255),e=this.getGraphicElevationInfo(a);return this._createAs3DShape(a,c,b,f,e,h,a.uid)};e.prototype.layerPropertyChanged=function(a,b,c){if("opacity"===a)return b=this._getMaterialOpacity(),c=1>
b||this._isPropertyDriven("opacity"),this._material.setParameterValues({opacity:b,transparent:c}),!0;if("elevationInfo"===a){this._updateElevationInfo();for(var h in b){var f=b[h];if(a=c(f))f=this.getGraphicElevationInfo(f.graphic),a.needsElevationUpdates=H.needsElevationUpdates3D(f.mode),a.elevationInfo.set(f)}return!0}return!1};e.prototype._getExtrusionSize=function(a){a=a.size&&this._isPropertyDriven("size")?H.getSingleSizeDriver(a.size,2):this._getSymbolSize();return a/=this._context.renderCoordsHelper.unitInMeters};
e.prototype._getSymbolSize=function(){return this.symbol.size||1};e.prototype._createAs3DShape=function(a,b,c,h,f,e,d){var k=a.geometry;"extent"===k.type&&(k=ba.fromExtent(k));a=k[b];var l=k.hasZ,v=[],m=[],r=[],n=q.create(),w=Array(6),g=this._context.renderSpatialReference===da.SphericalRenderSpatialReference,y=this._getExtrusionSize(c),p=q.create();g||this._context.renderCoordsHelper.worldUpAtPosition(null,p);c=H.getGeometryVertexData3D(a,l,k.spatialReference,this._context.renderSpatialReference,
this._context.elevationProvider,this._context.renderCoordsHelper,f);this._logGeometryCreationWarnings(c,a,b,"ExtrudeSymbol3DLayer");if(0<a.length){var u=c.geometryData.polygons,x=c.eleVertexData,z=c.vertexData;b=z.length/3;var A=new Float64Array(18*b),D=new Float64Array(18*b),E=new Float64Array(18*b),F=new Float64Array(6*b),B=0;b=function(a){var b=u[a],c=b.count,d=b.index;if(G._context.clippingExtent&&(H.computeBoundingBox(x,d,c,w),H.boundingBoxClipped(w,G._context.clippingExtent)))return"continue";
var f=new Float64Array(x.buffer,3*d*A.BYTES_PER_ELEMENT,3*c),l=b.holeIndices.map(function(a){return a-d}),f=ja(f,l,3);if(0<f.length){H.chooseOrigin(z,d,c,n);var l=new Uint32Array(6*c+2*f.length),k=6*c,q=new Float64Array(A.buffer,3*B*A.BYTES_PER_ELEMENT,3*k),t=new Float64Array(D.buffer,3*B*D.BYTES_PER_ELEMENT,3*k),C=new Float64Array(E.buffer,3*B*E.BYTES_PER_ELEMENT,3*k),I=new Float64Array(F.buffer,1*B*F.BYTES_PER_ELEMENT,1*k);la(z,x,f,b,q,C,t,I,0,l,0,y,p,g);H.subtractCoordinates(q,0,k,n);B+=6*c;b=
G._createExtrudeGeometry(l,{positions:q,elevation:C,normals:t,heights:I},h);a=new fa(b,e+"path"+a);a.singleUse=!0;v.push(a);m.push([G._material]);a=X.identity();X.translate(a,n,a);r.push(a)}};var G=this;for(a=0;a<u.length;++a)b(a);if(0<v.length)return d=new ea({geometries:v,materials:m,transformations:r,castShadow:!0,metadata:{layerUid:this._context.layer.uid,graphicId:d},idHint:e}),d=new aa(this,d,v,null,null,na,f),d.alignedTerrainElevation=c.terrainElevation,d.needsElevationUpdates=H.needsElevationUpdates3D(f.mode),
d}return null};e.prototype._createExtrudeGeometry=function(a,b,c){for(var d=a.length,f=new Uint32Array(d),e=0;e<d;e++)f[e]=0;d={};e={};d[F.POSITION]=a;d[F.NORMAL]=a;d[F.COLOR]=f;e[F.POSITION]={size:3,data:b.positions};e[F.NORMAL]={size:3,data:b.normals};e[F.COLOR]={size:4,data:c};e[F.SIZE]={size:1,data:b.heights};b.elevation&&(e.mapPos={size:3,data:b.elevation},d.mapPos=a);return new ga(e,d)};return e}(Z);var I=q.create(),L=q.create(),S=q.create(),T=q.create(),U=q.create(),V=q.create(),G=q.create(),
E=q.create();return M});