// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper dojo/_base/lang dojo/Deferred dojo/errors/CancelError ../../../../request ../../../../core/Error ../../../../core/Version ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Util ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/materials/Material ../../webgl-engine/lib/Texture ../../support/aaBoundingBox".split(" "),function(W,g,X,M,r,y,N,O,H,P,C,Q,R,S,T,U,I){function J(a){return new O("",
"Request for object resource failed: "+a)}function z(a,d){var w=[],K=[],h=[],m=[],q=[],p=H.Version.parse(a.version||"1.0","wosr");V.validate(p);var p="meshsymbol_"+a.model.name,c=a.textureDefinitions,D={},t;for(t in c){var u=c[t],e=u.images[0].data;E(e,"symbol resources must have embedded texture data (at the moment)");var k="/textureDefinitions/"+t,e=new U(u.encoding+";base64,"+e,p,{noUnpackFlip:!0});q.push(e);D[k]={engineTexObj:e,transparent:"rgba"===u.channels}}t=a.model.geometries;c=a.materialDefinitions;
for(u=0;u<t.length;u++){var l=t[u];l.params.components||(k=l,e=k.params,E(e.material),e.components=[{id:1,material:k.params.material,texture:k.params.texture,region:k.params.texture}],e.faces&&(e.faces.componentIndices=[e.faces.position.count]));var k=l.params.components,v=k.length,e=l.params.faces,A=l.params.vertexAttributes,f=l.params.topology||"Indexed",l={},g;for(g in A){var x=A[g],n=x.values;E(x.values,"symbol resources with external geometry bin not yet supported");l[g]={data:n,size:x.valuesPerElement}}A=
void 0;x=Array(v);if("Indexed"===f){var A=e.componentIndices,z;for(z in e);}else"PerAttributeArray"!==f?console.warn("I3S symbol loader: unsupported topology type "+f):1!==v&&console.warn("I3S symbol loader: if topology is not Indexed, only single component geometries are supported");h.push([]);for(v=0;v<k.length;v++){f=k[v];n={type:"triangle",positionKey:"position",indices:{}};if(A)for(var G in e){if("componentIndices"!==G){var b=e[G];E(b.values,"symbol resources with external geometry bin not yet supported");
n.indices[G]=new Uint32Array(b.values)}}else{for(var b=l.position.data.length/l.position.size,r=new Uint32Array(b),F=0;F<b;F++)r[F]=F;var b=r,y;for(y in l)n.indices[y]=b}x[v]=n;n=void 0;f.texture&&(n=D[f.texture].engineTexObj.getId());b=m[f.material]?m[f.material][f.texture]:null;b||(b=f.material.substring(f.material.lastIndexOf("/")+1),b=c[b].params,1===b.transparency&&(b.transparency=0),n={ambient:b.diffuse,diffuse:b.diffuse,specular:[0,0,0],shininess:0,opacity:1-b.transparency,transparent:0<b.transparency,
textureId:n,doubleSided:!0,cullFace:"none",flipV:!1,colorMixMode:b.externalColorMixMode||"tint"},d.materialParamsMixin&&M.mixin(n,d.materialParamsMixin),b=new T(n,p),m[f.material]||(m[f.material]={}),m[f.material][f.texture]=b,K.push(b));h[u].push(b)}k=new R(new S(x,l),p);w.push(k)}return{stageResources:(B={},B[C.ModelContentType.TEXTURE]=q,B[C.ModelContentType.MATERIAL]=K,B[C.ModelContentType.GEOMETRY]=w,B),materialsByComponent:h,pivotOffset:a.model.pivotOffset};var B}Object.defineProperty(g,"__esModule",
{value:!0});var L=P.vec3d,E=Q.assert,V=new H.Version(1,1,"wosr");g.fetch=function(a,d){d=d||{};var w=d.streamDataSupplier;if(w){var g=w.request(a,"json"),h=new r(function(){return w.cancelRequest(g)});g.then(function(p,c){try{var a=z(c,d);return h.resolve(a)}catch(t){return h.reject(t)}},function(a){h.reject(a instanceof y?a:J(a))});return h.promise}var m=N(a),q=new r(function(){return m.cancel()});m.then(function(a){try{var c=z(a.data,d);return q.resolve(c)}catch(D){return q.reject(D)}},function(d){q.reject(d instanceof
y?d:J(a))});return q.promise};g.computeBoundingBox=function(a){a=a.stageResources[C.ModelContentType.GEOMETRY];for(var d=I.create(I.NEGATIVE_INFINITY),g=[0,0,0],r=[0,0,0],h=0;h<a.length;h++)for(var m=a[h],q=m.getNumGroups(),p=0;p<q;++p){var c=m.getBoundingInfo(p);L.set(c.getBBMin(),g);L.set(c.getBBMax(),r);for(c=0;3>c;++c)d[c]=Math.min(d[c],g[c]),d[c+3]=Math.max(d[c+3],r[c])}return d};g.createStageResources=z});