// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define(["./core/JSONSupport","./core/kebabDictionary","./core/Collection","./core/lang","./support/Action"],function(l,d,m,c,n){var g=d({richtext:"rich-text",textarea:"text-area",textbox:"text-box"}),e=d({shortDate:"short-date",shortDateLE:"short-date-le",longDate:"long-date",dayShortMonthYear:"day-short-month-year",longMonthDayYear:"long-month-day-year",shortDateLongTime:"short-date-long-time",shortDateLELongTime:"short-date-le-long-time",shortDateShortTime:"short-date-short-time",shortDateLEShortTime:"short-date-le-short-time",
shortDateShortTime24:"short-date-short-time-24",shortDateLEShortTime24:"short-date-le-short-time-24",shortDateLongTime24:"short-date-long-time-24",shortDateLELongTime24:"short-date-le-long-time-24",longMonthYear:"long-month-year",shortMonthYear:"short-month-year"}),h=d({barchart:"bar-chart",columnchart:"column-chart",linechart:"line-chart",piechart:"pie-chart"}),k=l.createSubclass({properties:{actions:{type:m.ofType(n)},content:{value:null,json:{read:{source:["description","popupElements","mediaInfos",
"showAttachments"]}}},expressionInfos:{value:null},fieldInfos:{value:null},layerOptions:{value:null},overwriteActions:{value:!1},title:{value:""},relatedRecordsInfo:{value:null}},declaredClass:"esri.PopupTemplate",actions:null,content:"",expressionInfos:null,fieldInfos:null,_fieldInfosReader:function(a){return this._readFieldInfos(a)},layerOptions:null,_layerOptionsReader:function(a){return a?c.clone(a):a},overwriteActions:!1,title:"",relatedRecordsInfo:null,_relatedRecordsInfoReader:function(a){return a?
c.clone(a):a},_dateFormatKebabDict:e,clone:function(){var a=this.actions;a&&(a=c.clone(a.toArray()));return new k({actions:a||[],content:Array.isArray(this.content)?c.clone(this.content):this.content,fieldInfos:this.fieldInfos?c.clone(this.fieldInfos):null,layerOptions:this.layerOptions?c.clone(this.layerOptions):null,overwriteActions:this.overwriteActions,relatedRecordsInfo:this.relatedRecordsInfo?c.clone(this.relatedRecordsInfo):null,title:this.title})},toJSON:function(){var a={showAttachments:!1,
title:this.title};this.expressionInfos&&(a.expressionInfos=c.clone(this.expressionInfos));this.fieldInfos&&(a.fieldInfos=this._writeFieldInfos(c.clone(this.fieldInfos)));this.layerOptions&&(a.layerOptions=c.clone(this.layerOptions));this.relatedRecordsInfo&&(a.relatedRecordsInfo=c.clone(this.relatedRecordsInfo));var b=this.content;"string"===typeof b?a.description=b:Array.isArray(b)&&(a.popupElements=c.clone(b),a.popupElements.forEach(function(b){"attachments"!==b.type||a.showAttachments?"media"!==
b.type||a.mediaInfos?"text"!==b.type||a.description?"fields"!==b.type||a.fieldInfos||(b.fieldInfos&&(a.fieldInfos=this._writeFieldInfos(c.clone(b.fieldInfos))),delete b.fieldInfos):(b.text&&(a.description=b.text),delete b.text):(b.mediaInfos&&(a.mediaInfos=c.clone(b.mediaInfos),a.mediaInfos.forEach(function(b){b.type=h.toJSON(b.type)})),delete b.mediaInfos):a.showAttachments=!0;return b}.bind(this)));return a},_contentReader:function(a,b){a=b.description;var c=[],f=b.popupElements;f&&f.length?c=f.map(function(a){"text"!==
a.type||a.text?"media"===a.type&&(a.mediaInfos||b.mediaInfos)&&(a.mediaInfos||(a.mediaInfos=b.mediaInfos),a.mediaInfos=this._readMediaInfos(a.mediaInfos)):a.text=b.description;return a}.bind(this)):(b.description?c.push({type:"text",text:b.description}):c.push({type:"fields"}),b.mediaInfos&&b.mediaInfos.length&&c.push({type:"media",mediaInfos:this._readMediaInfos(b.mediaInfos)}),b.showAttachments&&c.push({type:"attachments",displayType:"list"}));c.length&&(a=c);return a},_readFieldInfos:function(a){a&&
a.forEach(function(a){var b=a.format&&a.format.dateFormat,c=a.stringFieldOption;b&&(a.format.dateFormat=e.fromJSON(b));c&&(a.stringFieldOption=g.fromJSON(c))});return a},_writeFieldInfos:function(a){a.forEach(function(a){var b=a.format&&a.format.dateFormat,c=a.stringFieldOption;b&&(a.format.dateFormat=e.toJSON(b));c&&(a.stringFieldOption=g.toJSON(c));a.format||delete a.format});return a},_readMediaInfos:function(a){a.forEach(function(a){a.type=h.fromJSON(a.type)});return a}});return k});