// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require dojo/_base/config dojo/Deferred dojo/_base/lang dojo/_base/url dojo/request dojo/io-query ./config ./core/Error ./core/global ./core/sniff ./core/lang ./core/urlUtils ./core/deferredUtils ./core/promiseUtils ./core/requireUtils dojo/has!host-browser?./core/request/script dojo/has!host-webworker?./core/workers/request".split(" "),function(R,S,w,p,J,D,E,T,u,U,h,y,m,V,x,W,X,K){function Y(a){var c=E.objectToQuery(a.content);c&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+c);if(2E3<a.url.length){if(!m.isDataProtocol(a.url))return x.reject(p.mixin(Error(),
{message:"When using responseType 'image', URL length cannot exceed 2000 characters."}));if(3E6<a.url.length)return x.reject(p.mixin(Error(),{message:"When using responseType 'image', data URL length cannot exceed 3000000 characters."}))}var b=new Image;a.allowImageDataAccess&&(b.crossOrigin=a.withCredentials?"use-credentials":"anonymous");var f=!1,d=new w(function(a){f=!0;b.onload=b.onerror=b.onabort=null;b.src=""}),c=function(a){b.onload=b.onerror=b.onabort=null;f||d.reject(Error("Unable to load the resource"))};
b.onload=function(){b.onload=b.onerror=b.onabort=null;f||d.resolve(this)};b.onerror=c;b.onabort=c;b.alt="";b.src=a.url;return d.promise}function F(a){a=new J(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function Z(){return G?G:G=W.when(R,"./identity/IdentityManager").then(function(a){k=a})}function aa(a,c){var b=!!a.useProxy,f=a.method||"auto",d=y.isDefined(a.crossOrigin)?a.crossOrigin:l.useCors;a=p.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));var e=a.content,n=a.url;a._token&&
(a.content=a.content||{},a.content.token=a._token);var B=0,q;n&&(q=E.objectToQuery(e),B=q.length+n.length+1,h("esri-url-encodes-apostrophe")&&(B=q.replace(/'/g,"%27").length+n.length+1));a.timeout=y.isDefined(a.timeout)?a.timeout:l.timeout;a.handleAs=a.handleAs||"json";try{var r,v,H=d&&m.canUseXhr(a.urlObj)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),L=m.hasSameOrigin(a.urlObj,m.appUrl)||H,g="post"===f||!!a.body||B>l.maxUrlLength,M=!L&&-1!==a.handleAs.indexOf("json")&&a.callbackParamName&&
!a.body,C=!!m.getProxyRule(a.url)||l.forceProxy||b||("image"!==a.handleAs||a.allowImageDataAccess)&&(!M||g)&&!L;if((h("host-browser")||h("host-webworker"))&&C)if(r=m.getProxyUrl(n,d),v=r.path,r._xo&&(H=!0),!g&&v.length+1+B>l.maxUrlLength&&(g=!0),a.url=v+"?"+n,g)a.content=p.mixin(r.query||{},e);else{var N=E.objectToQuery(p.mixin(r.query||{},e));N&&(a.url+=(-1===n.indexOf("?")?"?":"\x26")+N);a.content=null}if(M&&!g&&!C&&h("host-browser"))return a=z?z(a):a,a.jsonp=a.callbackParamName,a.query=a.content,
X.get(a.url,a);var A=a.headers;!h("host-browser")&&!h("host-webworker")||A&&A.hasOwnProperty("X-Requested-With")||(A=a.headers=A||{},A["X-Requested-With"]=null);if(h("host-browser")&&c){var t=a.content&&a.content.token;t&&(c.set?c.set("token",t):c.append("token",t));a.contentType=!1}if(H&&!a.hasOwnProperty("withCredentials")&&"with-credentials"===l.useCors){var b=C?v:n,u=m.getCorsConfig(b);if(u&&u.hasOwnProperty("withCredentials"))u.withCredentials&&(a.withCredentials=!0);else if(k){var x=k.findServerInfo(b);
x&&x.webTierAuth&&(a.withCredentials=!0)}}a=z?z(a):a;if("image"===a.handleAs)return Y(a);if(g)return a.body?(a.data=c||a.body,a.query=a.content):a.data=a.content,delete a.body,delete a.content,!C&&h("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+ba++),D.post(a.url,a);a.query=a.content;delete a.content;return D.get(a.url,a)}catch(ca){return a=new w,a.reject(ca),a.promise}}function da(a){var c=l.corsStatus;try{var b=F(a.url);if(l.corsDetection&&l.useCors&&h("esri-cors")&&
a.url&&-1!==a.url.toLowerCase().indexOf("/rest/services")&&!m.hasSameOrigin(a.urlObj,m.appUrl)&&!m.canUseXhr(a.urlObj)){if(c[b])return c[b];var f=new w;c[b]=f.promise;var d=a.url.substring(0,a.url.toLowerCase().indexOf("/rest/")+6)+"info";D.get(d,{query:{f:"json"},handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*l.corsDetectionTimeout}).then(function(c){c?(m.canUseXhr(a.url)||l.corsEnabledServers.push(b),f.resolve()):f.reject()},function(a){f.reject()});return f.promise}}catch(e){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}return ea}
function t(a,c,b,f){function d(a){a._pendingDfd=aa(b,q);var c=!!a._pendingDfd.response;(a._pendingDfd.response||a._pendingDfd).then(function(a){if(!c||!a.data)return a;var b=a.getHeader("Content-Type");if(b&&(b=b.toLowerCase(),-1===b.indexOf("text/plain")&&-1===b.indexOf("application/json")))return a;b=a.data;if(b instanceof ArrayBuffer&&750>=b.byteLength)b=new Blob([b]);else if(!(b instanceof Blob&&750>=b.size))return a;var g=new w,d=new FileReader;d.readAsText(b);d.onloadend=function(){if(!d.error)try{var b=
JSON.parse(d.result);b.error&&(Object.isExtensible(a)||(a=p.mixin({},a)),a._jsonData=b)}catch(ga){}g.resolve(a)};return g.promise}).then(function(b){var d=c?b.data:b,g=c?b.getHeader.bind(b):O;if(d&&(b=c&&b._jsonData||d,b.error||"error"===b.status))throw d=p.mixin(Error(),b.error||b),d.getHeader=g,d;a.resolve({data:d,url:f.url,requestOptions:f.requestOptions,getHeader:g});a._pendingDfd=null}).otherwise(function(c){var d,g,e;c&&(d=c.code,g=c.subcode,e=(e=c.messageCode)&&e.toUpperCase());if(c&&403==
d&&(4==g||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=!0;t(a,!0,b,f);return}}else if(c&&415==c.status){if(d=b.url,g=l.corsStatus,e=m.getCorsConfig(d,!0),-1<e&&l.corsEnabledServers.splice(e,1),e=new w,e.reject({log:!!S.isDebug}),g[F(d)]=e.promise,!b._err415){b._err415=1;t(a,!0,b,f);return}}else if(n&&"no-prompt"!==b.authMode&&k._errorCodes&&-1!==k._errorCodes.indexOf(d)&&!k._isPublic(b.url)&&(403!=d||
P&&-1===P.indexOf(e)&&(!y.isDefined(g)||2==g&&b._token))){fa(a,b,f,I("request:server",c,f));return}a.reject(I("request:server",c,f));a._pendingDfd=null})}var e=b.body,n=b.useIdentity,h,q=null,r=e instanceof FormData;if(r||e&&e.elements)q=r?e:new FormData(e);var v=!!(-1!==b.url.toLowerCase().indexOf("token\x3d")||b.content&&b.content.token||q&&q.get&&q.get("token")||e&&e.elements&&e.elements.token);c||(!n||v||b._token||k._isPublic(b.url)||(c=function(a){a&&(b._token=a.token,b._ssl=a.ssl)},"immediate"===
b.authMode?h=k.getCredential(b.url).then(c):"no-prompt"===b.authMode?h=k.checkSignInStatus(b.url).then(c).otherwise(function(){}):c(k.findCredential(b.url))),a.then(function(a){if((/\/sharing\/rest\/accounts\/self/i.test(b.url)||/\/sharing\/rest\/portals\/self/i.test(b.url))&&!v&&!b._token&&a.user&&a.user.username){var c=l.corsEnabledServers,d=m.getCorsConfig(b.url,!0),e={host:F(b.url),withCredentials:!0};if(-1===d)c.push(e);else{var f=c[d];"object"===typeof f?f.withCredentials=!0:c.splice(d,1,e)}}if(c=
b._credential)if(d=(d=k.findServerInfo(c.server))&&d.owningSystemUrl)d=d.replace(/\/?$/,"/sharing"),(c=k.findCredential(d,c.userId))&&-1===k._getIdenticalSvcIdx(d,c)&&c.resources.splice(0,0,d);return a}).always(function(a){delete b._credential;if(a){var c=!!b._ssl;a instanceof u?a.details.ssl=c:a.ssl=c}}));h?h.then(function(){d(a)}).otherwise(function(b){a.reject(b)}):d(a);return a.promise}function fa(a,c,b,f){a._pendingDfd=k.getCredential(c.url,{error:f,token:c._token});a._pendingDfd.then(function(d){c._token=
d.token;c._credential=d;c._ssl=c._sslFromServer||d.ssl;t(a,!0,c,b)}).otherwise(function(b){a.reject(b);a._pendingDfd=null})}function I(a,c,b){var f="Error",d={url:b.url,requestOptions:b.requestOptions,getHeader:O};if(c instanceof u)return c.details?(c.details=y.clone(c.details),c.details.url=b.url,c.details.requestOptions=b.requestOptions):c.details=d,c;if(c){var e=c.response;b=e&&e.getHeader;var e=e&&e.status,h=c.message;b=c.getHeader||b;h&&(f=h);b&&(d.getHeader=b);d.httpStatus=(y.isDefined(c.httpCode)?
c.httpCode:c.code)||e;d.subCode=c.subcode;d.messageCode=c.messageCode;d.messages="string"===typeof c.details?[c.details]:c.details}a=new u(a,f,d);c&&"cancel"===c.dojoType&&(a.dojoType="cancel");return a}function Q(a,c){if(K&&U.invokeStaticMessage)return K.execute(a,c);var b=p.mixin({},c),f={url:a,requestOptions:p.mixin({},c)};b.content=b.query;delete b.query;b.preventCache=!!b.cacheBust;delete b.cacheBust;b.handleAs=b.responseType;delete b.responseType;"array-buffer"===b.handleAs&&(b.handleAs="arraybuffer");
if("image"===b.handleAs){if(h("host-webworker"))return x.reject(I("request:invalid-parameters",Error("responseType 'image' is not supported in Web Workers or Node environment"),f));b.preventCache&&(b.content=b.content||{},b.content["request.preventCache"]=Date.now());b.method="auto"}var d=l.useIdentity;"anonymous"===b.authMode&&(d=!1);b.useIdentity=d;b.url=m.normalize(a);b.urlObj=new J(b.url);var e=V.makeDeferredCancellingPending();da(b).always(function(){if(d&&!k)return Z()}).always(function(){t(e,
!1,b,f)});return e.promise}var z,l=T.request,P=["COM_0056","COM_0057"],ba=0,O=function(){return null},ea=(new w).resolve(),k,G;Q.setRequestPreCallback=function(a){z=a};return Q});