// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../core/tsSupport/extendsHelper","../InputHandler","./support"],function(h,f,k,l,m){Object.defineProperty(f,"__esModule",{value:!0});f.DefaultParameters={maximumClickDelay:300,movementUntilDrag:1.5,holdDelay:500};h=function(g){function e(d,c,a){void 0===d&&(d=f.DefaultParameters.maximumClickDelay);void 0===c&&(c=f.DefaultParameters.movementUntilDrag);void 0===a&&(a=f.DefaultParameters.holdDelay);var b=g.call(this,"recognizers.PointerClickHoldAndDrag",!1)||this;b.maximumClickDelay=
d;b.movementUntilDrag=c;b.holdDelay=a;b._pointerState=new Map;b._modifiers=new Set;b._pointerDrag=b.registerOutgoing("pointer-drag");b._pointerClick=b.registerOutgoing("pointer-click");b._pointerHold=b.registerOutgoing("hold");b.registerIncoming("pointer-down",b._handlePointerDown.bind(b));b.registerIncoming("pointer-up",b._handlePointerUpOrLost.bind(b));b.registerIncoming("pointer-capture-lost",b._handlePointerUpOrLost.bind(b));b._moveHandle=b.registerIncoming("pointer-move",b._handlePointerMove.bind(b));
b._moveHandle.pause();return b}k(e,g);e.prototype.onUninstall=function(){this._pointerState.forEach(function(d){0!==d.holdTimeout&&(clearTimeout(d.holdTimeout),d.holdTimeout=0)});g.prototype.onUninstall.call(this)};e.prototype._handlePointerDown=function(d){var c=this,a=d.data,b=a.native.pointerId,e=0;0===this._pointerState.size&&(e=setTimeout(function(){var a=c._pointerState.get(b);a&&(a.isDragging||(c._pointerHold.emit(a.previousEvent,void 0,d.modifiers),a.holdEmitted=!0),a.holdTimeout=0)},this.holdDelay));
1===this._pointerState.size&&this._pointerState.forEach(function(a){0!==a.holdTimeout&&(clearTimeout(a.holdTimeout),a.holdTimeout=0)});this._pointerState.set(b,{startEvent:a,previousEvent:a,startTimestamp:d.timestamp,totalMovement:0,isDragging:!1,downButton:a.native.button,holdTimeout:e});this.startCapturingPointer(a.native);this._moveHandle.resume()};e.prototype._createPointerDragData=function(d,c,a){return{action:d,startEvent:c.startEvent,previousEvent:c.previousEvent,currentEvent:a}};e.prototype._handlePointerMove=
function(d){var c=d.data,a=this._pointerState.get(c.native.pointerId);a&&(a.isDragging?this._pointerDrag.emit(this._createPointerDragData("update",a,c),void 0,this._modifiers):(a.totalMovement+=m.manhattanDistance(c,a.previousEvent),a.totalMovement>this.movementUntilDrag&&(a.isDragging=!0,a.previousEvent=a.startEvent,this._modifiers=d.modifiers,0!==a.holdTimeout&&clearTimeout(a.holdTimeout),this._pointerDrag.emit(this._createPointerDragData("start",a,a.startEvent),a.startTimestamp),this._pointerDrag.emit(this._createPointerDragData("update",
a,c)))),a.previousEvent=c)};e.prototype._handlePointerUpOrLost=function(d){var c=d.data,a=c.native.pointerId,b=this._pointerState.get(a);b&&(0!==b.holdTimeout&&clearTimeout(b.holdTimeout),b.isDragging?this._pointerDrag.emit(this._createPointerDragData("end",b,c),void 0,this._modifiers):b.downButton===c.native.button&&d.timestamp-b.startTimestamp<=this.maximumClickDelay&&!b.holdEmitted&&this._pointerClick.emit(c),this._pointerState.delete(a),this.stopCapturingPointer(c.native),0===this._pointerState.size&&
this._moveHandle.pause())};return e}(l.InputHandler);f.PointerClickHoldAndDrag=h});