// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../../geometry/support/webMercatorUtils ../../core/HandleRegistry ../../core/Accessor ../../core/lang ../../core/watchUtils ../../geometry/Extent".split(" "),function(v,w,p,g,h,q,r,t,m,k,u){return function(n){function b(a){a=n.call(this,a)||this;a._handles=new r;a._pendingAttributionItemsByLayerId={};a._attributionDataByLayerId={};a.itemDelimiter=" | ";a.items=
[];a.view=null;a._updateAttributionItems=a._updateAttributionItems.bind(a);return a}p(b,n);b.prototype.initialize=function(){this._handles.add(k.init(this,"view",this._viewWatcher))};b.prototype.destroy=function(){this._handles.destroy();this.view=this._handles=null};Object.defineProperty(b.prototype,"attributionText",{get:function(){return this.items.join(this.itemDelimiter)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"state",{get:function(){return this.get("view.ready")?"ready":
"disabled"},enumerable:!0,configurable:!0});b.prototype._viewWatcher=function(a){var c=this,e=this._handles;e&&e.remove();a&&(e.add([a.allLayerViews.on("change",function(a){c._addLayerViews(a.added);0<a.removed.length&&(a.removed.forEach(function(a){e.remove(a.uid)}),c._updateAttributionItems())}),k.init(a,"stationary",this._updateAttributionItems)]),this._addLayerViews(a.allLayerViews))};b.prototype._addLayerViews=function(a){var c=this;a.forEach(function(a){c._handles.has(a.uid)||c._handles.add(k.init(a,
"suspended",c._updateAttributionItems),a.uid)})};b.prototype._updateAttributionItems=function(){var a=this,c=[];this._getActiveLayerViews().forEach(function(e){var d=e.layer;if(!d.hasAttributionData)e=d.get("copyright"),a._isUnique(c,e)&&c.push(e);else if(d&&d.tileInfo){var b=a._attributionDataByLayerId;if(b[d.uid])e=a._getDynamicAttribution(b[d.uid],a.view,d),a._isUnique(c,e)&&c.push(e);else{var l=a._pendingAttributionItemsByLayerId;a._inProgress(l[d.uid])||(l[d.uid]=d.fetchAttributionData().then(function(c){c=
a._createContributionIndex(c,a._isBingLayer(d));delete l[d.uid];b[d.uid]=c;a._updateAttributionItems()}))}}});this._itemsChanged(this.items,c)&&this._set("items",c)};b.prototype._itemsChanged=function(a,c){return a.length!==c.length||a.some(function(a,b){return a!==c[b]})};b.prototype._inProgress=function(a){return a&&!a.isFulfilled()};b.prototype._getActiveLayerViews=function(){return this.get("view.allLayerViews").filter(function(a){return!a.suspended&&a.get("layer.attributionVisible")})};b.prototype._isUnique=
function(a,c){return c&&-1===a.indexOf(c)};b.prototype._isBingLayer=function(a){return-1!==a.declaredClass.toLowerCase().indexOf("vetiledlayer")};b.prototype._createContributionIndex=function(a,c){a=a.contributors;var b={};if(!a)return b;a.forEach(function(a,e){var d=a.coverageAreas;d&&d.forEach(function(f){var d=f.bbox,h=f.zoomMin-(c&&f.zoomMin?1:0),g=f.zoomMax-(c&&f.zoomMax?1:0);a={extent:q.geographicToWebMercator(new u({xmin:d[1],ymin:d[0],xmax:d[3],ymax:d[2]})),attribution:a.attribution||"",score:m.isDefined(f.score)?
f.score:100,id:e};for(f=h;f<=g;f++)b[f]=b[f]||[],b[f].push(a)})});b.maxKey=Math.max.apply(null,Object.keys(b));return b};b.prototype._getDynamicAttribution=function(a,b,e){var c=b.extent;b=e.tileInfo.scaleToZoom(b.scale);b=Math.min(a.maxKey,Math.round(b));if(!c||!m.isDefined(b)||-1>=b)return"";a=a[b];var h=c.center.clone().normalize(),g={};return a.filter(function(a){var b=!g[a.id]&&a.extent.contains(h);b&&(g[a.id]=!0);return b}).sort(function(a,b){return b.score-a.score||a.objectId-b.objectId}).map(function(a){return a.attribution}).join(", ")};
g([h.property({dependsOn:["items","itemDelimiter"],readOnly:!0})],b.prototype,"attributionText",null);g([h.property()],b.prototype,"itemDelimiter",void 0);g([h.property({readOnly:!0})],b.prototype,"items",void 0);g([h.property({dependsOn:["view.ready"],readOnly:!0})],b.prototype,"state",null);g([h.property()],b.prototype,"view",void 0);return b=g([h.subclass("esri.widgets.Attribution.AttributionViewModel")],b)}(h.declared(t))});