// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("../Widget ../../core/Accessor ../../core/Error ../../core/HandleRegistry ../../core/lang ../../core/urlUtils ../../core/promiseUtils ../../core/watchUtils ../../request ../../support/arcadeUtils ../../tasks/support/StatisticDefinition ../../tasks/support/Query ../../tasks/QueryTask dojo/_base/lang dojo/promise/all dojo/i18n!dojo/cldr/nls/number dojox/html/entities".split(" "),function(F,G,A,H,l,I,t,J,B,v,K,C,L,q,z,D,M){var N=/\'/g,O=/href\s*=\s*(?:\"([^\"]+)\"|\'([^\']+)\')/ig,E=/^\s*expression\//i,
P=/(\{([^\{\r\n]+)\})/g,r={attachments:"attachments",fields:"fields",media:"media",text:"text"},w={"short-date":"(datePattern: 'M/d/y', selector: 'date')","short-date-le":"(datePattern: 'd/M/y', selector: 'date')","long-month-day-year":"(datePattern: 'MMMM d, y', selector: 'date')","day-short-month-year":"(datePattern: 'd MMM y', selector: 'date')","long-date":"(datePattern: 'EEEE, MMMM d, y', selector: 'date')","short-date-short-time":"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')",
"short-date-le-short-time":"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')","short-date-short-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')","short-date-le-short-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')","short-date-long-time":"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-le-long-time":"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')",
"short-date-long-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')","short-date-le-long-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')","long-month-year":"(datePattern: 'MMMM y', selector: 'date')","short-month-year":"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"};return G.createSubclass({declaredClass:"esri.widgets.Popup.PopupRendererViewModel",properties:{content:{readOnly:!0},contentEnabled:!0,
contentTypes:{readOnly:!0},formattedAttributes:{readOnly:!0},graphic:{},title:{readOnly:!0},view:{},waitingForContent:{readOnly:!0}},constructor:function(){this._handles=new H},initialize:function(){this._handles.add([J.init(this,["graphic","contentEnabled"],function(){this._updateGraphic(this.graphic,this.contentEnabled)}.bind(this))])},destroy:function(){this._handles.destroy();this._handles=null;this._clearRelatedInfo();this._cancelPromises();this.graphic=null;this._set("title",null);this._set("content",
null);this._set("waitingForContent",null)},content:null,contentEnabled:!0,contentTypes:r,formattedAttributes:null,graphic:null,title:"",view:null,waitingForContent:!1,_handles:null,_contentPromise:null,_contentElementPromises:null,_relatedRecordsPromise:null,_relatedRecordsQueryPromises:[],_relatedLayersInfo:null,_relatedInfo:null,_dateFormats:w,_addValuesToHref:function(a,b,c,d){b=this._trimString(b);return l.substitute(b&&"{"===b[0]?c:d,a)},_cancelPromises:function(){this._contentElementPromises&&
(this._contentElementPromises.forEach(function(a){a.cancel()},this),this._contentElementPromises=null);this._contentPromise&&(this._contentPromise.cancel(),this._contentPromise=null);this._relatedRecordsQueryPromises.forEach(function(a){a.cancel()});this._relatedRecordsQueryPromises.length=0;this._relatedRecordsPromise&&(this._relatedRecordsPromise.cancel(),this._relatedRecordsPromise=null)},_clearRelatedInfo:function(){this._relatedInfo=this._relatedLayersInfo=null},_compileContent:function(a,b){var c=
a.content;if(c&&(c.nodeName||c&&c&&"function"===typeof c.postMixInProperties&&"function"===typeof c.buildRendering&&"function"===typeof c.postCreate&&"function"===typeof c.startup||c&&c.isInstanceOf&&c.isInstanceOf(F)))return c;if("string"===typeof c)return this._compileText(a,{type:r.text,text:c}).text;if(Array.isArray(c))return c.map(function(c,f){f=(f=b&&b[f])&&f.value;switch(c.type){case r.attachments:return this._proxyAttachments(c,f);case r.fields:return this._compileFields(a,c);case r.media:return this._compileMedia(a,
c);case r.text:return this._compileText(a,c)}},this);if(c)try{throw new A(this.declaredClass+"::invalid content type.");}catch(d){console.warn(d.stack)}},_compileFields:function(a,b){b=q.clone(b);var c=(a=a.template)&&a.expressionInfos;a=a&&q.clone(a.fieldInfos);a=b.fieldInfos||a;var d=[];a&&a.forEach(function(a){var b=a.fieldName.toLowerCase();if(!a.hasOwnProperty("visible")||a.visible)b=this._isExpressionField(b)?this._getExpressionInfo(c,b):null,a.label=b?b.title:a.label,d.push(a)},this);b.fieldInfos=
d;return b},_compileMedia:function(a,b){b=q.clone(b);var c=b.mediaInfos,d=a.attributes,f=a.layer,e=this.formattedAttributes.global,h=a.substOptions,g,k;c&&(g=[],c.forEach(function(b){k=0;var c=b.value;switch(b.type){case "image":var m=c.sourceURL,m=m&&this._trimString(l.substitute(d,this._fixTokens(m,f)));k=!!m;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":var u,m=c.normalizeField;c.fields=c.fields.map(function(a){return(u=this._getLayerFieldInfo(f,a))?u.name:a},this);
m&&(u=this._getLayerFieldInfo(f,m),c.normalizeField=u?u.name:m);k=c.fields.some(function(a){return l.isDefined(d[a])||-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(k){b=q.clone(b);var c=b.value,m=b.title?this._processFieldsInLinks(this._fixTokens(b.title,f),d):"",p=b.caption?this._processFieldsInLinks(this._fixTokens(b.caption,f),d):"";b.title=m?this._trimString(l.substitute(e,m,h)):"";b.caption=p?this._trimString(l.substitute(e,p,h)):"";if("image"===b.type)c.sourceURL=
l.substitute(d,this._fixTokens(c.sourceURL,f)),c.linkURL&&(c.linkURL=this._trimString(l.substitute(d,this._fixTokens(c.linkURL,f))));else{var x,y=(m=a.template)&&m.fieldInfos;c.fields.forEach(function(a,b){if(-1!==a.indexOf("relationships/"))a=this._getRelatedChartInfos(f,y,a,c,d,h),Array.isArray(a)?c.fields=a:c.fields[b]=a;else{var e=d[a],e=void 0===e?null:e;x=d[c.normalizeField]||0;e&&x&&(e/=x);var n=y&&this._getFieldInfo(y,a);c.fields[b]={y:e,tooltip:(n&&n.label||a)+":"+this._formatValue(e,{fieldInfos:y,
fieldName:a,layer:f,substOptions:h,preventPlacesFormatting:!!x})}}},this)}g.push(b)}},this));b.mediaInfos=g;return b},_compileText:function(a,b){if((b=q.clone(b))&&b.text){var c=a.attributes,d=this.formattedAttributes.global,f=a.substOptions;a=this._processFieldsInLinks(this._fixTokens(b.text,a.layer),c);b.text=this._trimString(l.substitute(d,a,f))}return b},_compileTitle:function(a){var b="",c=a.title,d=a.layer,f=a.attributes,e=a.substOptions,h=this.formattedAttributes.global;c&&("function"===typeof c&&
(c=c.call(null,{graphic:a.graphic})),"string"===typeof c&&(a=this._processFieldsInLinks(this._fixTokens(c,d),f),b=this._trimString(l.substitute(h,a,e))));return b},_getExpressionInfo:function(a,b){if(this._isExpressionField(b)){b=b.replace(E,"");b=b.toLowerCase();var c;a.some(function(a){a.name.toLowerCase()===b&&(c=a);return!!c});return c}},_createGraphicInfo:function(a,b){var c=a.popupTemplate,d=c&&c.title,f=c&&c.content,e=a.layer,h=e&&e._getDateOpts&&e._getDateOpts().properties,g=q.clone(a.attributes)||
{};return{graphic:a,template:c,title:d,content:f,contentEnabled:b,layer:e,attributes:g,properties:h,substOptions:{dateFormat:{properties:h,formatter:"DateFormat"+w["short-date-short-time"]}}}},_fixTokens:function(a,b){return a.replace(P,function(a,d,f){return(a=this._getLayerFieldInfo(b,f))?"{"+a.name+"}":d}.bind(this))},_encodeAttributes:function(a){var b=q.clone(a)||{};Object.keys(b).forEach(function(a){var c=b[a];"string"===typeof c&&(c=encodeURIComponent(c).replace(N,"\x26apos;"),b[a]=c)});return b},
_formatAttributesToFieldInfos:function(a,b,c,d,f){a.forEach(function(e){var h=e.fieldName,g=this._getLayerFieldInfo(b,h);g&&(h=e.fieldName=g.name);f[h]=this._formatValue(f[h],{fieldInfos:a,fieldName:h,layer:b,substOptions:c});d&&e.format&&e.format.dateFormat&&(e=d.indexOf(h),-1<e&&d.splice(e,1))},this)},_getArcadeViewingMode:function(a){return a&&"local"===a.viewingMode?"localScene":"globalScene"},_formatAttributes:function(a,b,c,d,f,e,h,g){var k=q.clone(f);h&&h.forEach(function(a){var b="expression/"+
a.name;a=g[a.name];var c=this.view,c=c&&v.getViewInfo({viewingMode:"3d"===c.type?this._getArcadeViewingMode(c):"map",scale:c.scale,spatialReference:c.spatialReference});a=v.executeFunction(a&&a.compiledFunc,v.createExecContext(e,c));"string"===typeof a&&(a=M.encode(a));k[b]=a},this);this._relatedInfo&&Object.keys(this._relatedInfo).forEach(function(a){var b=this._relatedInfo[a];a=this._relatedLayersInfo[a];b&&(b.relatedFeatures.forEach(this._relatedFeaturesAttributes.bind(this,a,f,k)),b.relatedStatsFeatures.forEach(this._relatedStatsAttributes.bind(this,
a,f,k)))},this);a&&this._formatAttributesToFieldInfos(a,b,c,d,k);if(b){var p=b.typeIdField;Object.keys(f).forEach(function(a){if(-1===a.indexOf("relationships/")){var c=f[a];if(l.isDefined(c)){var d=this._getDomainName(b,e,a,c);l.isDefined(d)?k[a]=d:a===p&&(c=this._getTypeName(b,e,c),l.isDefined(c)&&(k[a]=c))}}},this)}return k},_formatValue:function(a,b){var c=b.fieldInfos,d=b.fieldName,f=b.substOptions,c=c&&this._getFieldInfo(c,d),e=q.clone(c),c=b.preventPlacesFormatting;(b=this._getLayerFieldInfo(b.layer,
d))&&"date"===b.type&&(b=e.format||{},b.dateFormat=b.dateFormat||"short-date-short-time",e.format=b);b=e&&e.format;d="number"===typeof a&&f.dateFormat.properties&&-1===f.dateFormat.properties.indexOf(d)&&(!b||!b.dateFormat);if(!l.isDefined(a)||!e||!l.isDefined(b))return d?this._forceLTR(a):a;var h="",g=[],e=b.hasOwnProperty("places")||b.hasOwnProperty("digitSeparator"),k=b.hasOwnProperty("digitSeparator")?b.digitSeparator:!0;if(e)h="NumberFormat",l.isDefined(b.places)&&(!c||0<b.places)&&(g.push("places: "+
Number(b.places)),h+="("+g.join(",")+")");else if(b.dateFormat)h="DateFormat"+w[b.dateFormat]||w["short-date-short-time"];else return d?this._forceLTR(a):a;a=l.substitute({myKey:a},"{myKey:"+h+"}",f)||"";e&&!k&&D.group&&(a=a.replace(new RegExp("\\"+D.group,"g"),""));return d?this._forceLTR(a):a},_forceLTR:function(a){return"\x26lrm;"+a},_getDomainName:function(a,b,c,d){return(a=a.getDomain&&a.getDomain(c,{feature:b}))&&a.codedValues?a.getName(d):null},_getFieldInfo:function(a,b){b=b.toLowerCase();
for(var c,d=0;d<a.length;d++){var f=a[d];if(f.fieldName&&f.fieldName.toLowerCase()===b){c=f;break}}return c},_getLayerFieldInfo:function(a,b){return b&&a&&a.getField?a.getField(b):null},_getTypeName:function(a,b){return(a=a.getType&&a.getType(b))&&a.name},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b);a&&(a=a.replace(O,function(a,f,e){return this._addValuesToHref(a,f||e,b,c)}.bind(this)));return a},_proxyAttachments:function(a,b){a=q.clone(a);b&&!(b instanceof A)&&b.attachmentInfos&&
b.attachmentInfos.length&&(b=b.attachmentInfos.map(function(a){a.url=I.addProxy(a.url);return a},this),a.attachmentInfos=b);return a},_queryAttachments:function(a){var b=a.layer;if(!b)return t.resolve();"scene"===b.type&&b.companionFeatureLayer&&(b=b.companionFeatureLayer);var c=a.attributes;a=b&&b.objectIdField;c=c&&a&&c[a];if(a&&b.get("capabilities.data.supportsAttachment")&&c)return this._queryAttachmentInfos(b,c)},_queryAttachmentInfos:function(a,b){var c=a.url+"/"+a.layerId+"/"+b+"/attachments",
d=a.token||"";return B(c,{query:{f:"json",token:d},callbackParamName:"callback"}).then(function(a){a=a.data;a.attachmentInfos.forEach(function(a){a.url=c+"/"+a.id;d&&(a.url+="?token\x3d"+d);a.objectId=b});return a})},_queryContentElements:function(a){var b=a.content;if(!b||!Array.isArray(b))return t.resolve();var c=[],d={};b.forEach(function(b,e){b.type===r.attachments&&(b=this._queryAttachments(a))&&(d[e]=b,c.push(b))},this);this._contentElementPromises=c;return 0===c.length?t.resolve():t.eachAlways(d).always(function(a){this._contentElementPromises=
null;return a}.bind(this))},_trimString:function(a){return(a||"").trim()},_getContent:function(a){var b=a.template,b=b&&b.content;"function"===typeof b&&(b=b.call(null,{graphic:a.graphic}));return b&&"function"===typeof b.then?b:t.resolve(b)},_updateContent:function(a){var b;return a.contentEnabled?this._contentPromise=b=this._getContent(a).then(function(b){a.content=b;return this._queryContentElements(a)}.bind(this)).then(function(b){this._set("content",this._compileContent(a,b))}.bind(this)).otherwise(function(a){console.log(this.declaredClass+
"::error loading template",a)}.bind(this)).then(function(){this._contentPromise=null}.bind(this)):b=t.resolve()},_isExpressionField:function(a){return E.test(a)},_compileExpressions:function(a){if(a){var b={};a.forEach(function(a){b[a.name]={compiledFunc:v.createFunction(a.expression)}});return b}},_createFormattedAttributes:function(a){var b=a.graphic,c=a.attributes,d=a.layer,f=a.template,e=f&&f.fieldInfos,h=f&&f.expressionInfos,g=this._compileExpressions(h),k=a.substOptions,p=a.properties,n={global:this._formatAttributes(e,
d,k,p,c,b,h,g),content:[]};a=f&&f.content;Array.isArray(a)&&a.forEach(function(a,e){a.type===r.fields&&a.fieldInfos&&(n.content[e]=this._formatAttributes(a.fieldInfos,d,k,p,c,b,h,g))},this);return n},_queryGraphicInfo:function(a,b){var c=this._createGraphicInfo(a,b);return this._checkForRelatedRecords(c).then(function(){this._set("formattedAttributes",this._createFormattedAttributes(c));this._set("title",this._compileTitle(c));return this._updateContent(c)}.bind(this))},_updateGraphic:function(a,
b){this._handles&&(this._clearRelatedInfo(),this._cancelPromises(),this._set("title",""),this._set("content",null),this._set("formattedAttributes",null),this._set("waitingForContent",!1),a&&(this._set("waitingForContent",!0),this._relatedRecordsPromise=this._queryGraphicInfo(a,b).always(function(){this._relatedRecordsPromise=null;this._relatedRecordsQueryPromises.length=0;this._set("waitingForContent",!1)}.bind(this))))},_getAllFieldInfos:function(a){var b=[],c=a.template,d=c&&c.fieldInfos;a=a.contentEnabled;
d&&(b=b.concat(d));a&&(c=c&&c.content,Array.isArray(c)&&c.forEach(function(a){b=b.concat(a&&a.fieldInfos)},this));return b},_checkForRelatedRecords:function(a){var b=this._getAllFieldInfos(a).filter(function(a){return a&&a.fieldName&&-1!==a.fieldName.indexOf("relationships/")},this);return a.layer&&b&&0<b.length?this._getRelatedRecords({graphic:a.graphic,fieldsInfo:b}):t.resolve()},_relatedFeaturesAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){if("esriRelCardinalityOneToOne"===
a.relation.cardinality){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]}},this)},_relatedStatsAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]},this)},_getRelatedChartInfos:function(a,b,c,d,f,e){var h,g,k,p,n,l;h=[];l=this._fromRelatedFieldName(c);n=l[0];g=this._relatedInfo[n];n=this._relatedLayersInfo[n];g&&g.relatedFeatures.forEach(function(g){var n=g.attributes,m;Object.keys(n).forEach(function(g){if(g===
l[1]){m={};p=n[g];d.normalizeField&&(k=-1!==d.normalizeField.indexOf("relationships/")?n[this._fromRelatedFieldName(d.normalizeField)[1]]:f[d.normalizeField]);p&&k&&(p/=k);if(d.tooltipField)if(-1!==d.tooltipField.indexOf("relationships/"))g=this._fromRelatedFieldName(d.tooltipField)[1],g=n[g],m.tooltip=g+": "+this._formatValue(p,{fieldInfos:b,fieldName:g,layer:a,substOptions:e,preventPlacesFormatting:!!k});else{if(g=this._getLayerFieldInfo(a,c))c=g.name;m.tooltip=c+": "+this._formatValue(p,{fieldInfos:b,
fieldName:d.tooltipField,layer:a,substOptions:e,preventPlacesFormatting:!!k})}else m.tooltip=p;m.y=p;h.push(m)}},this)},this);return"esriRelCardinalityOneToMany"===n.relation.cardinality||"esriRelCardinalityManyToMany"===n.relation.cardinality?h:h[0]},_getRelatedRecords:function(a){var b=a.graphic;return this._relatedLayersInfo?this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this)):this._getRelatedLayersInfo(a).then(function(a){Object.keys(a).forEach(function(b){a[b]&&
(this._relatedLayersInfo[b].relatedLayerInfo=a[b].data)},this);return this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this))}.bind(this))},_getRelatedLayersInfo:function(a){var b=a.fieldsInfo,c,d={};c=a.graphic.layer;this._relatedLayersInfo||(this._relatedLayersInfo={});b.forEach(function(a){var b,d,f;b=this._fromRelatedFieldName(a.fieldName);d=b[0];b=b[1];if(d){if(!this._relatedLayersInfo[d]){var k=c&&c.relationships;k&&k.some(function(a){if(a.id==d)return f=
a,!0});f&&(this._relatedLayersInfo[d]={relation:f,relatedFields:[],outStatistics:[]})}this._relatedLayersInfo[d]&&(this._relatedLayersInfo[d].relatedFields.push(b),a.statisticType&&(a=new K({statisticType:a.statisticType,onStatisticField:b,outStatisticFieldName:b}),this._relatedLayersInfo[d].outStatistics.push(a)))}},this);Object.keys(this._relatedLayersInfo).forEach(function(a){var b;this._relatedLayersInfo[a]&&(b=this._relatedLayersInfo[a].relation,b=c.url+"/"+b.relatedTableId,this._relatedLayersInfo[a].relatedLayerUrl=
b,d[a]=B(b,{query:{f:"json"},callbackParamName:"callback"}))},this);return z(d)},_queryRelatedLayers:function(a){var b={};Object.keys(this._relatedLayersInfo).forEach(function(c){b[c]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[c]})},this);return z(b)},_queryRelatedLayer:function(a){var b,c,d,f,e,h,g,k,l;b=a.graphic;c=b.layer.layerId;g=a.relatedInfo;a=g.relatedLayerInfo;k=g.relatedLayerUrl;l=g.relation;a&&a.relationships&&a.relationships.some(function(a){if(a.relatedTableId===
parseInt(c,10))return d=a,!0});d&&(a.fields.some(function(a){if(a.name===d.keyField)return f=-1!==["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"].indexOf(a.type)?"number":"string",!0}),e="string"===f?d.keyField+"\x3d'"+b.attributes[l.keyField]+"'":d.keyField+"\x3d"+b.attributes[l.keyField],e=new C({where:e,outFields:g.relatedFields}),g.outStatistics&&0<g.outStatistics.length&&a.supportsStatistics&&(h=new C({where:e.where,outFields:e.outFields,outStatistics:g.outStatistics})),
a=new L({url:k}),e=[a.execute(e)],h&&e.push(a.execute(h)));this._relatedRecordsQueryPromises=this._relatedRecordsQueryPromises.concat(e);return z(e)},_setRelatedRecords:function(a){this._relatedInfo=[];Object.keys(a).forEach(function(b){if(a[b]){var c=a[b];this._relatedInfo[b]={relatedFeatures:c[0].features};l.isDefined(c[1])&&(this._relatedInfo[b].relatedStatsFeatures=c[1].features)}},this)},_fromRelatedFieldName:function(a){return-1!==a.indexOf("relationships/")?a.split("/").slice(1):[]},_toRelatedFieldName:function(a){return a&&
0<a.length?"relationships/"+a[0]+"/"+a[1]:""}})});