// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("../../core/Accessor ../../core/Collection ../../core/Error ../../core/Evented ../../core/HandleRegistry ../../core/promiseUtils ../../core/watchUtils ../../geometry/geometryEngine ../../geometry/support/webMercatorUtils ../../geometry/Point ../../support/Action ../support/AnchorElementViewModel dojo/fx/easing dojo/_base/lang".split(" "),function(m,n,g,p,q,h,e,r,t,u,v,w,k,x){function y(a,b){return b.allLayerViews.find(function(b){return b.layer===a})}var l={id:"zoom-to"};return m.createSubclass([p,
w],{declaredClass:"esri.widgets.Popup.PopupViewModel",properties:{actions:{type:n.ofType(v)},animationOptions:{},autoCloseEnabled:{},clear:{},content:{},featureCount:{readOnly:!0},features:{},location:{type:u},next:{},pendingPromisesCount:{readOnly:!0},previous:{},promiseCount:{readOnly:!0,dependsOn:["promises"],get:function(){return this.promises?this.promises.length:0}},promises:{},selectedFeature:{readOnly:!0},selectedFeatureIndex:{},state:{dependsOn:["view.ready"],readOnly:!0},title:{},triggerAction:{},
updateLocationEnabled:{},view:{},visible:{},waitingForResult:{dependsOn:["pendingPromisesCount","featureCount"],readOnly:!0},zoomFactor:{}},_handles:null,constructor:function(){this._handles=new q},getDefaults:function(a){return x.mixin(this.inherited(arguments),{actions:[l],animationOptions:{duration:300,easing:k.quadInOut},promises:[]})},initialize:function(){this._handles.add([this.on("view-change",this._autoClose),e.watch(this,"location",this._locationWatcher),e.whenFalse(this,"visible",this._visibleWatcher)])},
destroy:function(){this._handles.destroy();this.view=this._handles=null},actions:[l],animationOptions:{duration:300,easing:k.quadInOut},autoCloseEnabled:!1,content:null,featureCount:0,features:null,_featuresSetter:function(a){this._set("features",a);this._updateFeatureCount(a);this.promiseCount||(this.selectedFeatureIndex=-1,a&&a.length&&(this.selectedFeatureIndex=0))},highlightEnabled:!0,_highlightEnabledSetter:function(a){this._set("highlightEnabled",a);this._highlightFeature(this.selectedFeature,
this.view)},location:null,_locationSetter:function(a){var b=this.get("view.spatialReference.isWebMercator");a&&a.get("spatialReference.isWGS84")&&b&&(a=t.geographicToWebMercator(a));this._set("location",a)},pendingPromisesCount:0,waitingForResult:!1,_waitingForResultGetter:function(){return 0<this.pendingPromisesCount&&0===this.featureCount},promiseCount:0,promises:[],_promisesSetter:function(a){var b=this._get("promises");b&&b.forEach(function(a){a.cancel()});this.features=[];b=a&&a.length;this._set("selectedFeatureIndex",
-1);this._set("selectedFeature",null);this._selectedFeatureChange(this.selectedFeature,this.updateLocationEnabled);this._set("pendingPromisesCount",0);this._set("promises",a);a&&a.length&&(this._set("pendingPromisesCount",b),a=a.slice(0),a.forEach(function(a){a.always(function(b){a.isCanceled()||(this._set("pendingPromisesCount",this.pendingPromisesCount-1),this._updateFeatures(a,b))}.bind(this))},this),h.eachAlways(a).then(function(){this.featureCount||(this.visible=!1)}.bind(this)))},selectedFeature:null,
selectedFeatureIndex:-1,_selectedFeatureIndexSetter:function(a){if(isNaN(a)||-1>a)a=-1;var b=null,c=this.features;c&&c.length&&(a=(a+c.length)%c.length,b=c[a]);this._set("selectedFeature",b);this._set("selectedFeatureIndex",a);this._selectedFeatureChange(b,this.updateLocationEnabled)},state:"disabled",_stateGetter:function(){return this.get("view.ready")?"ready":"disabled"},title:null,updateLocationEnabled:!1,_updateLocationEnabledSetter:function(a){this._selectedFeatureChange(this.selectedFeature,
a);this._set("updateLocationEnabled",a)},view:null,visible:!1,zoomFactor:4,centerAtLocation:function(){return this.location&&this.view?this.view.goTo({target:this.location,scale:this.view.scale},this.animationOptions):h.reject(new g(this.declaredClass+"::Cannot center at location without a location and view."))},clear:function(){this.set({promises:[],features:[],content:null,title:null,location:null})},triggerAction:function(a){(a=this.actions.getItemAt(a))&&this.emit("trigger-action",{action:a})},
next:function(){this.selectedFeatureIndex+=1;return this},previous:function(){--this.selectedFeatureIndex;return this},zoomToLocation:function(){var a=this.view,b=this.location;if(!b||!a)return h.reject(new g(this.declaredClass+"::Cannot zoom to location without a location and view."));var c=a.scale/this.zoomFactor,d=this.selectedFeature,f=d&&d.geometry,e=d&&"3d"===a.type;f||e?(b={target:d},f&&"point"===f.type&&this._isScreenSize(d)&&(b.scale=c,this.location=f)):b={target:b,scale:c};return a.goTo(b,
this.animationOptions)},_autoClose:function(){this.autoCloseEnabled&&(this.visible=!1)},_isScreenSize:function(a){if("3d"!==this.view.type||"esri.Graphic"!==a.declaredClass)return!0;var b=!0,c=this.view.getViewForGraphic(a);c&&c.whenGraphicBounds&&c.whenGraphicBounds(a).then(function(a){b=!a||a[0]===a[3]&&a[1]===a[4]&&a[2]===a[5]});return b},_getSelectedFeatureActions:function(){this._originalActions&&(this.actions=this._originalActions,this._originalActions=null);var a=this.actions.filter(function(a){return!a.temporary},
this),b=a,c=this.selectedFeature.popupTemplate;if(c&&c.actions){for(var b=c.actions,d=0;d<b.length;d++)b.getItemAt(d).temporary=!0;c.overwriteActions?this._originalActions=a:b=a.concat(b)}this.actions=b},_getPointFromGeometry:function(a){switch(a&&a.type){case "point":return a;case "extent":return a.center;case "polygon":return a.centroid;case "multipoint":case "polyline":return a.extent.center;default:return null}},_locationWatcher:function(a,b){var c=this.get("view.extent");this.updateLocationEnabled&&
c&&a&&a!==b&&!r.contains(c,a)&&this.centerAtLocation()},_visibleWatcher:function(a){this._handles.remove("highlight")},_highlightFeature:function(a,b){this._handles.remove("highlight");if(a&&b&&this.highlightEnabled){var c=a.layer;if(c&&(b=y(c,b))&&"function"===typeof b.highlight){var c=c.objectIdField,d=a.attributes;a=b.highlight(d&&d[c]||a);this._handles.add(a,"highlight")}}},_selectedFeatureChange:function(a,b){this._highlightFeature(a,this.view);a&&(b&&(this.location=this._getPointFromGeometry(a.geometry)),
this._getSelectedFeatureActions())},_updateFeatureCount:function(a){var b=0;a&&a.length&&(b=a.length);this._set("featureCount",b)},_updateFeatures:function(a,b){a&&this.promises&&!(!this._validatePromise(a)||b instanceof g||b instanceof Error)&&b&&b.length&&(a={},this.features&&this.features.length?(b=b.filter(function(a){return-1===this.features.indexOf(a)},this),a.features=this.features.concat(b)):(a.features=b,a.selectedFeatureIndex=0),this.set(a))},_validatePromise:function(a){return-1<this.promises.indexOf(a)}})});