// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ./Bucket ../2d/engine/webgl/LineTess ./style/StyleLayer".split(" "),function(u,v,q,w,r,k,t){var g=new k.Tessellator({distanceAlongCorrection:!0});return function(p){function f(a,b,d,c){var e=p.call(this,a,b)||this;e.extrudeVectorsDoubleBuffer=[k.allocExtrudeVectors(),k.allocExtrudeVectors()];e.firstExtrudeVectors=k.allocExtrudeVectors();e.recycledTriangleBridge=k.allocTriangles(20);e.recycledTrianglePie=
k.allocTriangles(20);e.lineVertexBuffer=d;e.lineIndexBuffer=c;a=a.getPaintValue("line-pattern",b);e.hasPattern=void 0!==a;return e}q(f,p);Object.defineProperty(f.prototype,"triangleIndexStart",{get:function(){return this.triangleElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"triangleIndexCount",{get:function(){return this.triangleElementsCount},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"connectorStart",{get:function(){return 0},enumerable:!0,
configurable:!0});Object.defineProperty(f.prototype,"connectorCount",{get:function(){return 0},enumerable:!0,configurable:!0});f.prototype.assignBufferInfo=function(a){a.triangleElementsStart=this.triangleElementsStart;a.triangleElementsCount=this.triangleElementsCount};f.prototype.processFeatures=function(a,b){this.triangleElementsStart=this.lineIndexBuffer.index;this.triangleElementsCount=0;a&&a.setExtent(this.layerExtent);b=new t.LineLayout(this.layer,this.zoom);for(var d=0,c=this._features;d<
c.length;d++){var e=c[d].getGeometry(a);this._processFeature(b,e)}};f.prototype._processFeature=function(a,b){if(b){var d=b.length,c;for(c=0;c<d;c++)this._processGeometry(b[c],a)}};f.prototype._processGeometry=function(a,b){if(!(2>a.length)){for(var d=a[0],c=a[a.length-1],e=c.x-d.x,c=c.y-d.y,d=1E-6>e*e+c*c,h=a[0],l=1;l<a.length;)e=a[l].x-h.x,c=a[l].y-h.y,1E-6>e*e+c*c?a.splice(l,1):(h=a[l],++l);if(!(2>a.length)){this.vertices=a;this.verticesLen=a.length;this.isClosed=d;this.cap=b.cap;this.join=b.join;
this.almostParallelRads=.05;this.veryShallowRads=.1;this.miterSafeRads=k.MITER_SAFE_RADS;this.miterLimitMag=Math.min(b.miterLimit,k.SYSTEM_MAG_LIMIT);this.roundLimitRads=Math.min(b.roundLimit,.5);this.newRoundJoinsSafeRads=2.3;b=this.lineIndexBuffer.index;for(var e=0,f=void 0,c=this.verticesLen,h=0;h<c;++h){var g=a[h],l=f===this.extrudeVectorsDoubleBuffer[h%2]?this.extrudeVectorsDoubleBuffer[(h+1)%2]:this.extrudeVectorsDoubleBuffer[h%2];h<c-1||!d||this.hasPattern?(this._computeExtrudeVectors(l,h),
this._writeGPUVertices(g.x,g.y,e,l),!l.capCenter||d&&h===c-1||this._writeGPUPieElements(l),d&&0===h&&!this.hasPattern&&k.copyExtrudeVectors(this.firstExtrudeVectors,l)):k.copyExtrudeVectors(l,this.firstExtrudeVectors);f&&this._writeGPUBridgeElements(f,l);h<c-1&&(f=a[h+1],g=k.length([f.x-g.x,f.y-g.y]),e+=g);f=l}this.triangleElementsCount+=3*(this.lineIndexBuffer.index-b)}}};f.prototype._computeExtrudeVectors=function(a,b){var d=this.vertices,c=this.verticesLen,e=this.isClosed,h=d[b],f=[void 0,void 0],
g=[void 0,void 0];if(0<b&&b<c-1){var m=d[(b+c-1)%c],n=d[(b+1)%c];k.normalize(f,[h.x-m.x,h.y-m.y]);k.normalize(g,[n.x-h.x,n.y-h.y])}else if(0===b)n=d[(b+1)%c],k.normalize(g,[n.x-h.x,n.y-h.y]),e?(d=d[c-2],k.normalize(f,[h.x-d.x,h.y-d.y])):f=g;else if(b===c-1)m=d[(b+c-1)%c],k.normalize(f,[h.x-m.x,h.y-m.y]),e?(d=d[1],k.normalize(g,[d.x-h.x,d.y-h.y])):g=f;else{console.error("Vertex index 'i' out of range.");return}e||0!==b?e||b!==c-1?this._computeJoinExtrudeVectors(a,f,g):this._computeCapExtrudeVectors(a,
f,g,k.CapPosition.END):this._computeCapExtrudeVectors(a,f,g,k.CapPosition.START)};f.prototype._computeCapExtrudeVectors=function(a,b,d,c){0===this.cap?g.buttCap(a,b,d):1===this.cap?g.roundCap(a,b,d,c,k.getNumberOfSlices(Math.PI),c===k.CapPosition.START?-1:1):2===this.cap?g.squareCap(a,b,d,c):(g.buttCap(a,b,d),console.error("Unknown cap type!"))};f.prototype._computeJoinExtrudeVectors=function(a,b,d){var c=k.getRads(b,d);if(c>Math.PI-this.almostParallelRads)g.rectJoin(a,b,d);else if(2===this.join||
c<this.veryShallowRads)c<this.almostParallelRads?g.fastMiterJoin(a,b,d):c<this.miterSafeRads?g.miterJoin(a,b,d):g.bevelJoin(a,b,d,this.miterLimitMag);else if(0===this.join)g.bevelJoin(a,b,d,1);else if(1===this.join){var e=k.getNumberOfSlices(c);c<this.newRoundJoinsSafeRads?2>e||c<this.roundLimitRads?g.bevelJoin(a,b,d,1):g.roundJoin(a,b,d,e):g.unitRoundJoin(a,b,d,e)}};f.prototype._writeGPUVertices=function(a,b,d,c){var e;for(e=0;e<c.vectors.count;++e){var f=this.lineVertexBuffer.add(a,b,c.vectors.items[e].vector[0],
c.vectors.items[e].vector[1],c.vectors.items[e].texCoords[0],c.vectors.items[e].texCoords[1],d);c.vectors.items[e].base=f}};f.prototype._writeGPUBridgeElements=function(a,b){g.bridge(this.recycledTriangleBridge,a,b);for(a=0;a<this.recycledTriangleBridge.count;++a)b=this.recycledTriangleBridge.items[a],this.lineIndexBuffer.add(b.v1.base,b.v2.base,b.v3.base)};f.prototype._writeGPUPieElements=function(a){g.pie(this.recycledTrianglePie,a);for(a=0;a<this.recycledTrianglePie.count;++a){var b=this.recycledTrianglePie.items[a];
this.lineIndexBuffer.add(b.v1.base,b.v2.base,b.v3.base)}};return f}(r)});