// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../core/libs/gl-matrix/vec2 ../../core/libs/gl-matrix/mat4 ../../core/ObjectPool ../../geometry/support/spatialReferenceUtils ../webgl/BufferObject ../2d/engine/DisplayObject ../2d/tiling/TileKey ./RenderBucket".split(" "),function(A,B,t,u,v,w,x,n,y,z,q){return function(r){function g(){for(var c=[],b=0;b<arguments.length;b++)c[b]=arguments[b];b=r.call(this)||this;b._renderBuckets=[];b._vectorTileData=null;b._symbolUpdateData=null;b.status=
5;b.coords=[0,0];b.tileTransform={transform:Float32Array[16],displayCoord:Float32Array[2]};b.stencilData={mask:0,reference:0};b.status=0;b.tileTransform.transform=v.create();b.tileTransform.displayCoord=u.create();0<c.length&&(l=b.acquire).call.apply(l,[b].concat(c));return b;var l}t(g,r);g.prototype.reset=function(){z.pool.release(this.key);this.refKey=this.key=null;this.coords[0]=0;this.height=this.width=this.coords[1]=0;this.resolution=null;this.rotation=0;this.id=this._connection=this.workerID=
this._glyphsMosaic=this.styleLayers=this._vectorTileData=null;this.tileTransform.transform.fill(0);this.tileTransform.displayCoord.fill(0);this.stencilData.mask=0;this.stencilData.reference=0;this._renderBuckets.length=0;this._symbolUpdateData=null;this.status=0};g.prototype.acquire=function(c,b,l,a,f,d){this.key=c;this.refKey=b;b=l.lodAt(c.level).resolution;var e=l.size[0]*b,h=l.origin,k=c.col*e,e=c.row*e,p=l.spatialReference,m=0;p&&(p._isWrappable?p._isWrappable():p.isWrappable)&&(m=x.getInfo(p),
m=m.valid[1]-m.valid[0]);e=h.y-e;this.coords[0]=h.x+k+c.world*m;this.coords[1]=e;this.widthInPixels=l.size[1];this.coordRange=4096;this.resolution=b;this.rotation=d;this.styleLayers=a;this._glyphsMosaic=f;this.id=c.id;this.status=1};g.prototype.setData=function(c,b,l){this._vectorTileData=c;this.workerID=b;this._connection=l;this.status=3};g.prototype.updateSymbolData=function(c){c&&(this._symbolUpdateData=c,this.requestRender())};g.prototype.dispose=function(){this.polygonTrianglesVertexArrayObject&&
(this.polygonTrianglesVertexArrayObject.dispose(),this.polygonTrianglesVertexArrayObject=null);this.polygonOutlineVertexArrayObject&&(this.polygonOutlineVertexArrayObject.dispose(),this.polygonOutlineVertexArrayObject=null);this.lineTrianglesVertexArrayObject&&(this.lineTrianglesVertexArrayObject.dispose(),this.lineTrianglesVertexArrayObject=null);this.iconVertexArrayObject&&(this.iconVertexArrayObject.dispose(),this.iconVertexArrayObject=null);this.textVertexArrayObject&&(this.textVertexArrayObject.dispose(),
this.textVertexArrayObject=null);this.polygonTrianglesVertexBuffer&&(this.polygonTrianglesVertexBuffer.dispose(),this.polygonTrianglesVertexBuffer=null);this.polygonTrianglesIndexBuffer&&(this.polygonTrianglesIndexBuffer.dispose(),this.polygonTrianglesIndexBuffer=null);this.polygonOutlinesVertexBuffer&&(this.polygonOutlinesVertexBuffer.dispose(),this.polygonOutlinesVertexBuffer=null);this.polygonOutlinesIndexBuffer&&(this.polygonOutlinesIndexBuffer.dispose(),this.polygonOutlinesIndexBuffer=null);
this.lineVertexBuffer&&(this.lineVertexBuffer.dispose(),this.lineVertexBuffer=null);this.lineTrianglesIndexBuffer&&(this.lineTrianglesIndexBuffer.dispose(),this.lineTrianglesIndexBuffer=null);this.iconVertexBuffer&&(this.iconVertexBuffer.dispose(),this.iconVertexBuffer=null);this.iconIndexBuffer&&(this.iconIndexBuffer.dispose(),this.iconIndexBuffer=null);this.textVertexBuffer&&(this.textVertexBuffer.dispose(),this.textVertexBuffer=null);this.textIndexBuffer&&(this.textIndexBuffer.dispose(),this.textIndexBuffer=
null);this.texture&&(this.texture.dispose(),this.texture=null);this._renderBuckets.length=0;this.status=7};g.prototype.attach=function(c){if(4===this.status)return!0;this.status=3;if(!this._vectorTileData)return!1;if(!this._vectorTileData.bufferDataInfo)return this.status=4,!0;if(0===this._renderBuckets.length)for(var b=new Uint32Array(this._vectorTileData.bucketDataInfo),l=b.length,a=0;a<l;){var f=b[a],d=b[a+1];if(0===d)d=new q.BackgroundRenderBucket,d.layerID=f,this._renderBuckets.push(d),a+=2;
else if(1===d)d=new q.FillRenderBucket,d.layerID=f,d.triangleElementStart=b[a+2],d.triangleElementCount=b[a+3],d.outlineElementStart=b[a+4],d.outlineElementCount=b[a+5],this._renderBuckets.push(d),a+=6;else if(2===d)d=new q.LineRenderBucket,d.layerID=f,d.triangleElementStart=b[a+2],d.triangleElementCount=b[a+3],this._renderBuckets.push(d),a+=6;else if(3===d){d=new q.SymbolRenderBucket;d.layerID=f;d.isSDF=0!==b[a+2];var f=b[a+3],e=a+4;if(0<f)for(var e=a+4,h=void 0,k=void 0,p=void 0,m=0;m<f;m++)h=b[e],
k=b[e+1],p=b[e+2],d.markerPerPageElementsMap.set(h,[k,p]),e+=3;var g=b[e];if(0<g)for(e++,p=k=h=void 0,m=0;m<g;m++)h=b[e],k=b[e+1],p=b[e+2],d.glyphPerPageElementsMap.set(h,[k,p]),e+=3;this._renderBuckets.push(d);a+=5+3*f+3*g}else console.error("Bad bucket type!")}c=c.context;b=new Uint32Array(this._vectorTileData.bufferDataInfo);l=b.length;for(d=a=0;d<l;d+=2,a++)if(!(0>=b[d+1]||0===this._vectorTileData.bufferData[a].byteLength))switch(b[d]){case 2:this.polygonTrianglesVertexBuffer?this.polygonTrianglesVertexBuffer.setData(this._vectorTileData.bufferData[a]):
this.polygonTrianglesVertexBuffer=n.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 6:this.polygonTrianglesIndexBuffer?this.polygonTrianglesIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.polygonTrianglesIndexBuffer=n.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 3:this.polygonOutlinesVertexBuffer?this.polygonOutlinesVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.polygonOutlinesVertexBuffer=n.createVertex(c,35044,this._vectorTileData.bufferData[a]);
break;case 7:this.polygonOutlinesIndexBuffer?this.polygonOutlinesIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.polygonOutlinesIndexBuffer=n.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 0:this.lineVertexBuffer?this.lineVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.lineVertexBuffer=n.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 8:this.lineTrianglesIndexBuffer?this.lineTrianglesIndexBuffer.setData(this._vectorTileData.bufferData[a]):
this.lineTrianglesIndexBuffer=n.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 4:this.iconVertexBuffer?this.iconVertexBuffer.setData(this._vectorTileData.bufferData[a]):this.iconVertexBuffer=n.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 9:this.iconIndexBuffer?this.iconIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.iconIndexBuffer=n.createIndex(c,35044,this._vectorTileData.bufferData[a]);break;case 5:this.textVertexBuffer?this.textVertexBuffer.setData(this._vectorTileData.bufferData[a]):
this.textVertexBuffer=n.createVertex(c,35044,this._vectorTileData.bufferData[a]);break;case 10:this.textIndexBuffer?this.textIndexBuffer.setData(this._vectorTileData.bufferData[a]):this.textIndexBuffer=n.createIndex(c,35044,this._vectorTileData.bufferData[a])}this.status=4;return!0};g.prototype.detach=function(c){-1!==this.workerID&&this._connection&&6!==this.status&&7!==this.status&&this._connection.broadcast("destructTileData",{key:this.id,worker:this.workerID},[]);this.dispose();r.prototype.detach.call(this,
c)};g.prototype.doRender=function(c){if(this.visible&&4===this.status){var b=c.context,l=c.renderer;if(b&&l){var a=c.drawphase;this._symbolUpdateData&&this._updateSymbolData(c);b.setStencilFunction(514,this.stencilData.reference,this.stencilData.mask);var f=this.styleLayers,d=void 0!==c.layerOpacity?c.layerOpacity:1;if(0!==d){var e,h=this._renderBuckets.length,k=0;if(0===a)for(k=h-1;0<=k;k--)e=this._renderBuckets[k],3!==e.type&&e.hasData()&&l.renderBucket(b,e,c.displayLevel,c.requiredLevel,a,this,
f.layers[e.layerID],d);else for(k=0;k<h;k++)e=this._renderBuckets[k],e.hasData()&&l.renderBucket(b,e,c.displayLevel,c.requiredLevel,a,this,f.layers[e.layerID],d)}}}};g.prototype._updateSymbolData=function(c){var b=new Uint32Array(this._symbolUpdateData.bucketDataInfo),l=b.length;if(0===l)return this._symbolUpdateData=null,!0;if(1>c.budget.remaining||4!==this.status)return this.requestRender(),!1;c=c.context;for(var a=new Uint32Array(this._symbolUpdateData.bufferDataInfo),f=a.length,d=0,e=0;e<f;e+=
2,d++)switch(a[e]){case 4:this.iconVertexBuffer&&(this.iconVertexBuffer.dispose(),this.iconVertexBuffer=null);this.iconVertexBuffer=n.createVertex(c,35044,this._symbolUpdateData.bufferData[d]);break;case 9:this.iconIndexBuffer&&(this.iconIndexBuffer.dispose(),this.iconIndexBuffer=null);this.iconIndexBuffer=n.createIndex(c,35044,this._symbolUpdateData.bufferData[d]);break;case 5:this.textVertexBuffer&&(this.textVertexBuffer.dispose(),this.textVertexBuffer=null);this.textVertexBuffer=n.createVertex(c,
35044,this._symbolUpdateData.bufferData[d]);break;case 10:this.textIndexBuffer&&(this.textIndexBuffer.dispose(),this.textIndexBuffer=null),this.textIndexBuffer=n.createIndex(c,35044,this._symbolUpdateData.bufferData[d])}c=this._renderBuckets.length;for(a=0;a<c;a++)this._renderBuckets[a]instanceof q.SymbolRenderBucket&&(f=this._renderBuckets[a],f.markerPerPageElementsMap.clear(),f.glyphPerPageElementsMap.clear());for(c=0;c<l;){f=b[c];d=-1;e=this._renderBuckets.length;for(a=0;a<e;a++)if(this._renderBuckets[a].layerID===
f){d=a;break}a=this._renderBuckets[d];a||(a=new q.SymbolRenderBucket,a.layerID=f,a.isSDF=0!==b[c+2],this._renderBuckets.push(a));var f=b[c+3],h=c+4;if(0<f)for(var h=c+4,k=e=d=void 0,g=0;g<f;g++)d=b[h],e=b[h+1],k=b[h+2],a.markerPerPageElementsMap.set(d,[e,k]),h+=3;var m=b[h];if(0<m)for(h++,k=e=d=void 0,g=0;g<m;g++)d=b[h],e=b[h+1],k=b[h+2],a.glyphPerPageElementsMap.set(d,[e,k]),h+=3;c+=5+3*f+3*m}this.iconVertexArrayObject&&(this.iconVertexArrayObject.dispose(),this.iconVertexArrayObject=null);this.textVertexArrayObject&&
(this.textVertexArrayObject.dispose(),this.textVertexArrayObject=null);this._symbolUpdateData=null;return!0};g.pool=new w(g);return g}(y)});