// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports dojo/Deferred ../../core/promiseUtils ../../core/executeAsync ../../core/ObjectPool ./VertexMemoryBuffer ./IndexMemoryBuffer ./TileParser ./BackgroundBucket ./FillBucket ./LineBucket ./SymbolBucket ./Placement ./GeometryUtils".split(" "),function(F,G,w,q,x,y,f,n,z,A,B,C,D,E,r){return function(){function a(){this.status=this.rotation=0;this._symbolBuckets=[];this.placementEngine=new E.PlacementEngine;this.polygonVertexBuffer=new f.PolygonMemoryBuffer;this.polygonOutlineVertexBuffer=
new f.PolygonOutlineMemoryBuffer;this.polygonIndexBuffer=new n.TriangleElementMemoryBuffer;this.polygonOutlineIndexBuffer=new n.TriangleElementMemoryBuffer;this.lineVertexBuffer=new f.LineMemoryBuffer;this.lineIndexBuffer=new n.TriangleElementMemoryBuffer;this.markerVertexBuffer=new f.SymbolMemoryBuffer;this.markerIndexBuffer=new n.TriangleElementMemoryBuffer;this.textVertexBuffer=new f.SymbolMemoryBuffer;this.textIndexBuffer=new n.TriangleElementMemoryBuffer}a.prototype.initialize=function(a,k,b,
e){void 0===e&&(e=0);this.tileKey=a;this.refKey=k;this._workerTileHandler=b;this.rotation=e;this.placementEngine.setAngle(r.C_DEG_TO_RAD*e)};a.prototype.release=function(){this.tileKey=this.refKey="";this.rotation=this.status=0;this.polygonVertexBuffer.reset();this.polygonOutlineVertexBuffer.reset();this.polygonIndexBuffer.reset();this.polygonOutlineIndexBuffer.reset();this.lineVertexBuffer.reset();this.lineIndexBuffer.reset();this.markerVertexBuffer.reset();this.markerIndexBuffer.reset();this.textVertexBuffer.reset();
this.textIndexBuffer.reset();this.placementEngine.reset();this._symbolBuckets.length=0;this._workerTileHandler=null};a.prototype.setDataAndParse=function(a,k){var b=this,e=new w(function(a){b.status=6});this._parse(a,k).then(function(a){b.status=4;for(var k=new Uint32Array([2,b.polygonVertexBuffer.sizeInBytes,3,b.polygonOutlineVertexBuffer.sizeInBytes,6,b.polygonIndexBuffer.sizeInBytes,7,b.polygonOutlineIndexBuffer.sizeInBytes,0,b.lineVertexBuffer.sizeInBytes,8,b.lineIndexBuffer.sizeInBytes,4,b.markerVertexBuffer.sizeInBytes,
9,b.markerIndexBuffer.sizeInBytes,5,b.textVertexBuffer.sizeInBytes,10,b.textIndexBuffer.sizeInBytes]),d=[],l=a.length,m=0;m<l;m++){var c=a[m];if(c instanceof B)d.push(c.layerIndex),d.push(1),d.push(c.polygonIndexStart),d.push(c.polygonIndexCount),d.push(c.polygonOutlineIndexStart),d.push(c.polygonOutlineIndexCount);else if(c instanceof C)d.push(c.layerIndex),d.push(2),d.push(c.triangleIndexStart),d.push(c.triangleIndexCount),d.push(c.connectorStart),d.push(c.connectorCount);else if(c instanceof D){d.push(c.layerIndex);
d.push(3);d.push(c.sdfMarker?1:0);var g=c.markerPageMap;d.push(g.size);g.forEach(function(c,b){d.push(b);d.push(c[0]);d.push(c[1])});c=c.glyphsPageMap;d.push(c.size);c.forEach(function(c,b){d.push(b);d.push(c[0]);d.push(c[1])})}else c instanceof A&&(d.push(c.layerIndex),d.push(0))}a=new Uint32Array(d);var l=b.polygonVertexBuffer.toBuffer(),m=b.polygonOutlineVertexBuffer.toBuffer(),c=b.polygonIndexBuffer.toBuffer(),g=b.polygonOutlineIndexBuffer.toBuffer(),t=b.lineVertexBuffer.toBuffer(),u=b.lineIndexBuffer.toBuffer(),
v=b.markerVertexBuffer.toBuffer(),h=b.markerIndexBuffer.toBuffer(),p=b.textVertexBuffer.toBuffer(),f=b.textIndexBuffer.toBuffer();e.resolve({data:{bufferDataInfo:k.buffer,bucketDataInfo:a.buffer,bufferData:[l,m,c,g,t,u,v,h,p,f]},buffers:[l,c,m,g,t,u,v,h,p,f,k.buffer,a.buffer]})});return e.promise};a.prototype.addBucket=function(a){this._symbolBuckets.push(a)};a.prototype.updateSymbols=function(a){var k=this,b=this._symbolBuckets;if(!b||0===b.length)return q.resolve({data:null,buffers:null});this.rotation=
a;var e=this.placementEngine;e.reset();e.setAngle(a/256*360*r.C_DEG_TO_RAD);var f=this.markerVertexBuffer;f.reset();var p=this.markerIndexBuffer;p.reset();var d=this.textVertexBuffer;d.reset();var l=this.textIndexBuffer;l.reset();var m=[],c=b.length,g=0;return x(function(){if(6===k.status||0===k.status)return!0;if(g<c){var a=b[g++].copy(f,p,d,l,e);a&&(m.push(a),a.updateSymbols())}return g>=c},5).then(function(){if(6===k.status||0===k.status||0===f.sizeInBytes&&0===p.sizeInBytes&&0===d.sizeInBytes&&
0===l.sizeInBytes)return{data:null,buffers:null};var b=new Uint32Array([4,f.sizeInBytes,9,p.sizeInBytes,5,d.sizeInBytes,10,l.sizeInBytes]),a=[];c=m.length;for(var e=0;e<c;e++){var h=m[e];a.push(h.layerIndex);a.push(3);a.push(h.sdfMarker?1:0);var g=h.markerPageMap;a.push(g.size);g.forEach(function(b,c){a.push(c);a.push(b[0]);a.push(b[1])});h=h.glyphsPageMap;a.push(h.size);h.forEach(function(b,c){a.push(c);a.push(b[0]);a.push(b[1])})}var e=new Uint32Array(a),h=f.toBuffer(),g=p.toBuffer(),n=d.toBuffer(),
q=l.toBuffer();return{data:{bufferDataInfo:b.buffer,bucketDataInfo:e.buffer,bufferData:[h,g,n,q]},buffers:[h,g,n,q,b.buffer,e.buffer]}}).otherwise(function(a){return q.resolve({data:null,buffers:null})})};a.prototype.setObsolete=function(){this.status=6};a.prototype.getLayers=function(){return this._workerTileHandler.getLayers()};a.prototype.getWorkerTileHandler=function(){return this._workerTileHandler};a.prototype._parse=function(a,f){if(!a||0===a.byteLength)return q.resolve([]);this.status=2;return(new z(a,
this,f)).parse()};a.pool=new y(a);return a}()});