// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/accessorSupport/decorators ../core/lang ../core/urlUtils ../core/Logger ../core/Error ../core/arrayUtils ../portal/Portal ../support/arcadeUtils ../symbols/WebStyleSymbol ../symbols/support/jsonUtils ../symbols/support/styleUtils ../symbols/support/typeUtils ./Renderer ./support/diffUtils".split(" "),function(C,D,v,c,e,f,m,w,x,t,q,g,y,n,z,r,A,B){var h=w.getLogger("esri.renderers.UniqueValueRenderer");
return function(u){function a(b){b=u.call(this)||this;b._valueInfoMap={};b._isDefaultSymbolDerived=!1;b.type="unique-value";b.field=null;b.field2=null;b.field3=null;b.valueExpression=null;b.valueExpressionTitle=null;b.legendOptions=null;b.defaultLabel=null;b.fieldDelimiter=null;b.portal=null;b.styleOrigin=null;b.diff={uniqueValueInfos:function(b,a){if(b||a){if(!b||!a)return{type:"complete",oldValue:b,newValue:a};for(var d=!1,k={type:"collection",added:[],removed:[],changed:[],unchanged:[]},e=function(c){var p=
t.find(b,function(b){return b.value===a[c].value});p?B.diff(p,a[c])?k.changed.push({type:"complete",oldValue:p,newValue:a[c]}):k.unchanged.push({oldValue:p,newValue:a[c]}):k.added.push(a[c]);d=!0},c=0;c<a.length;c++)e(c);e=function(c){t.find(a,function(d){return d.value===b[c].value})||(k.removed.push(b[c]),d=!0)};for(c=0;c<b.length;c++)e(c);return d?k:void 0}}};b._set("uniqueValueInfos",[]);return b}v(a,u);l=a;a.prototype.writeType=function(b,d,a,c){d.type="uniqueValue"};Object.defineProperty(a.prototype,
"compiledFunc",{get:function(){return g.createFunction(this.valueExpression)},enumerable:!0,configurable:!0});a.prototype.readLegendOptions=function(b){return f.clone(b)};a.prototype.writeLegendOptions=function(b,d,a,c){c&&"web-scene"===c.origin?b&&c.messages&&c.messages.push(new x("property:unsupported",this.declaredClass+".legendOptions is not supported in Web Scene. Please remove this property to save the Web Scene.",{instance:this,propertyName:"legendOptions",context:c})):d.legendOptions=f.clone(b)};
Object.defineProperty(a.prototype,"defaultSymbol",{set:function(b){this._isDefaultSymbolDerived=!1;this._set("defaultSymbol",b)},enumerable:!0,configurable:!0});a.prototype.readDefaultSymbol=function(b,d,a){return n.read(b,d,a)};a.prototype.writeDefaultSymbol=function(b,d,a,c){!this._isDefaultSymbolDerived&&(b=n.write(b,{},c))&&(d.defaultSymbol=b)};a.prototype.readPortal=function(b,d,a){return a.portal||q.getDefault()};a.prototype.readStyleOrigin=function(b,d,a){if(d.styleName)return Object.freeze({styleName:d.styleName});
if(d.styleUrl)return b=m.read(d.styleUrl,a),Object.freeze({styleUrl:b})};a.prototype.writeStyleOrigin=function(b,d,a,c){b.styleName?d.styleName=b.styleName:b.styleUrl&&(d.styleUrl=m.write(b.styleUrl,c),m.isAbsolute(d.styleUrl)&&(d.styleUrl=m.normalize(d.styleUrl)))};Object.defineProperty(a.prototype,"uniqueValueInfos",{set:function(b){if(this.styleOrigin)h.error("#uniqueValueInfos\x3d","Cannot modify unique value infos of a UniqueValueRenderer created from a web style");else{b=b?b.slice(0):[];for(var d=
0;d<b.length;d++){var a=b[d];a.symbol=r.ensureType(a.symbol)}this._set("uniqueValueInfos",b);this._updateValueInfoMap()}},enumerable:!0,configurable:!0});a.prototype.readUniqueValueInfos=function(b,d,a){if(Array.isArray(b))return b.map(function(b){b=f.clone(b);b.symbol=n.read(b.symbol,d,a);return b})};a.prototype.writeUniqueValueInfos=function(b,d,a,c){this.styleOrigin||(d.uniqueValueInfos=(this.uniqueValueInfos||[]).map(function(b){b=f.clone(b);b.symbol&&(b.symbol=n.write(b.symbol,{},c));b.value+=
"";return f.fixJson(b)}))};a.prototype.addUniqueValueInfo=function(b,d){this.styleOrigin?h.error("#addUniqueValueInfo()","Cannot modify unique value infos of a UniqueValueRenderer created from a web style"):(b="object"===typeof b?f.clone(b):{value:b,symbol:d},b.symbol=r.ensureType(b.symbol),this.uniqueValueInfos.push(b),this._valueInfoMap[b.value+""]=b)};a.prototype.removeUniqueValueInfo=function(b){if(this.styleOrigin)h.error("#removeUniqueValueInfo()","Cannot modify unique value infos of a UniqueValueRenderer created from a web style");
else for(var d=0;d<this.uniqueValueInfos.length;d++)if(this.uniqueValueInfos[d].value+""===b+""){delete this._valueInfoMap[b];this.uniqueValueInfos.splice(d,1);break}};a.prototype.getUniqueValueInfo=function(b,d){var a=this.field,c=b.attributes;if(this.valueExpression)a=g.executeFunction(this.compiledFunc,g.createExecContext(b,g.getViewInfo(d)));else if(this.field2){b=this.field2;d=this.field3;var e=[];a&&e.push(c[a]);b&&e.push(c[b]);d&&e.push(c[d]);a=e.join(this.fieldDelimiter||"")}else a=a&&"function"===
typeof a?a(b):c[a];return this._valueInfoMap[a+""]};a.prototype.getSymbol=function(b,a){return(b=this.getUniqueValueInfo(b,a))&&b.symbol||this.defaultSymbol};a.prototype.getSymbols=function(){for(var b=[],a=0,c=this.uniqueValueInfos;a<c.length;a++){var e=c[a];e.symbol&&b.push(e.symbol)}this.defaultSymbol&&b.push(this.defaultSymbol);return b};a.prototype.clone=function(){var b=new l({field:this.field,field2:this.field2,field3:this.field3,defaultLabel:this.defaultLabel,defaultSymbol:f.clone(this.defaultSymbol),
valueExpression:this.valueExpression,valueExpressionTitle:this.valueExpressionTitle,fieldDelimiter:this.fieldDelimiter,visualVariables:f.clone(this.visualVariables),legendOptions:f.clone(this.legendOptions),authoringInfo:f.clone(this.authoringInfo)});this._isDefaultSymbolDerived&&(b._isDefaultSymbolDerived=!0);b._set("portal",this.portal);var a=f.clone(this.uniqueValueInfos);this.styleOrigin&&(b._set("styleOrigin",Object.freeze(f.clone(this.styleOrigin))),Object.freeze(a));b._set("uniqueValueInfos",
a);b._updateValueInfoMap();return b};a.prototype.collectRequiredFields=function(b){this.inherited(arguments);[this.field,this.field2,this.field3].forEach(function(a){a&&(b[a]=!0)});this.valueExpression&&g.extractFieldNames(this.valueExpression).forEach(function(a){b[a]=!0})};a.prototype.populateFromStyle=function(){var b=this;return z.fetchStyle(this.styleOrigin,{portal:this.portal}).then(function(a){var d=[];b._valueInfoMap={};a&&a.data&&Array.isArray(a.data.items)&&a.data.items.forEach(function(c){var e=
new y({styleUrl:a.styleUrl,styleName:a.styleName,portal:b.portal,name:c.name});b.defaultSymbol||c.name!==a.data.defaultItem||(b.defaultSymbol=e,b._isDefaultSymbolDerived=!0);e={value:c.name,symbol:e};d.push(e);b._valueInfoMap[c.name]=e});b._set("uniqueValueInfos",Object.freeze(d));!b.defaultSymbol&&b.uniqueValueInfos.length&&(b.defaultSymbol=b.uniqueValueInfos[0].symbol,b._isDefaultSymbolDerived=!0);return b})};a.prototype._updateValueInfoMap=function(){var b=this;this._valueInfoMap={};this.uniqueValueInfos.forEach(function(a){return b._valueInfoMap[a.value+
""]=a})};a.fromPortalStyle=function(b,a){var c=new l(a&&a.properties);c._set("styleOrigin",Object.freeze({styleName:b}));c._set("portal",a&&a.portal||q.getDefault());a=c.populateFromStyle();a.otherwise(function(a){h.error("#fromPortalStyle('"+b+"'[, ...])","Failed to create unique value renderer from style name",a)});return a};a.fromStyleUrl=function(b,a){a=new l(a&&a.properties);a._set("styleOrigin",Object.freeze({styleUrl:b}));a=a.populateFromStyle();a.otherwise(function(a){h.error("#fromStyleUrl('"+
b+"'[, ...])","Failed to create unique value renderer from style URL",a)});return a};c([e.property()],a.prototype,"type",void 0);c([e.writer("type")],a.prototype,"writeType",null);c([e.property({json:{read:{source:"field1"},write:{target:"field1"}}})],a.prototype,"field",void 0);c([e.property({json:{write:!0}})],a.prototype,"field2",void 0);c([e.property({json:{write:!0}})],a.prototype,"field3",void 0);c([e.property({json:{write:!0}})],a.prototype,"valueExpression",void 0);c([e.property({json:{write:!0}})],
a.prototype,"valueExpressionTitle",void 0);c([e.property({dependsOn:["valueExpression"]})],a.prototype,"compiledFunc",null);c([e.property({json:{write:!0}})],a.prototype,"legendOptions",void 0);c([e.reader("legendOptions")],a.prototype,"readLegendOptions",null);c([e.writer("legendOptions")],a.prototype,"writeLegendOptions",null);c([e.property({json:{write:!0}})],a.prototype,"defaultLabel",void 0);c([e.property({types:r.types})],a.prototype,"defaultSymbol",null);c([e.reader("defaultSymbol")],a.prototype,
"readDefaultSymbol",null);c([e.writer("defaultSymbol")],a.prototype,"writeDefaultSymbol",null);c([e.property({json:{write:!0}})],a.prototype,"fieldDelimiter",void 0);c([e.property({type:q,readOnly:!0})],a.prototype,"portal",void 0);c([e.reader("portal",["styleName"])],a.prototype,"readPortal",null);c([e.property({readOnly:!0,json:{write:!0}})],a.prototype,"styleOrigin",void 0);c([e.reader("styleOrigin",["styleName","styleUrl"])],a.prototype,"readStyleOrigin",null);c([e.writer("styleOrigin")],a.prototype,
"writeStyleOrigin",null);c([e.property()],a.prototype,"uniqueValueInfos",null);c([e.reader("uniqueValueInfos")],a.prototype,"readUniqueValueInfos",null);c([e.writer("uniqueValueInfos")],a.prototype,"writeUniqueValueInfos",null);c([e.property({dependsOn:["field","field2","field3","valueExpression"],readOnly:!0})],a.prototype,"requiredFields",void 0);return a=l=c([e.subclass("esri.renderers.UniqueValueRenderer")],a);var l}(e.declared(A))});