// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.5/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang ../../../core/lang ../../../core/promiseUtils ../../support/utils ./support/utils ./color ./size ../support/utils".split(" "),function(x,l,e,m,f,n,h,t,p,k){function u(a){if(!(a&&a.layer&&(a.field||a.valueExpression||a.sqlExpression)))return f.reject(h.createError("univariate-colorsize-visual-variables:missing-parameters","'layer' and 'field', 'valueExpression' or 'sqlExpression' parameters are required"));var b=e.mixin({},a);a=[0,1];var d=k.createLayerAdapter(b.layer,
a);return(b.layer=d)?d.load().then(function(){var a=k.getFieldsList({field:b.field,normalizationField:b.normalizationField,valueExpression:b.valueExpression});return(a=h.verifyBasicFieldValidity(d,a,"univariate-colorsize-visual-variables:invalid-parameters"))?f.reject(a):b}):f.reject(h.createError("univariate-colorsize-visual-variables:invalid-parameters","'layer' must be one of these types: "+k.getLayerTypeLabels(a).join(", ")))}function q(a,b){a=e.mixin({},a);b=0===b?a.colorOptions:a.sizeOptions;
delete a.sizeOptions;delete a.colorOptions;return e.mixin(a,b)}function v(a){if(!(a&&a.layer&&(a.field||a.valueExpression||a.sqlExpression)))return f.reject(h.createError("univariate-colorsize-continuous-renderer:missing-parameters","'layer' and 'field', 'valueExpression' or 'sqlExpression' parameters are required"));var b=e.mixin({},a);b.symbolType=b.symbolType||"2d";a=[0,1];var d=k.createLayerAdapter(b.layer,a);return(b.layer=d)?d.load().then(function(){var a=k.getFieldsList({field:b.field,normalizationField:b.normalizationField,
valueExpression:b.valueExpression});return(a=h.verifyBasicFieldValidity(d,a,"univariate-colorsize-continuous-renderer:invalid-parameters"))?f.reject(a):b}):f.reject(h.createError("univariate-colorsize-continuous-renderer:invalid-parameters","'layer' must be one of these types: "+k.getLayerTypeLabels(a).join(", ")))}function w(a){a=e.mixin({},a);var b=a.sizeOptions;delete a.sizeOptions;delete a.colorOptions;return e.mixin(a,b)}function r(a){return u(a).then(function(a){var b;return t.createVisualVariable(q(a,
0)).then(function(g){var c=q(a,1);c.statistics=g.statistics;b=g;return p.createVisualVariables(c)}).then(function(a){var c=b.visualVariable,d=a.visualVariables,g=c.stops.length;d.forEach(function(a){null!=a.minDataValue&&(a.minDataValue=c.stops[0].value,a.maxDataValue=c.stops[g-1].value)});return{basemapId:a.basemapId,statistics:b.statistics,defaultValuesUsed:b.defaultValuesUsed,color:{visualVariable:c,colorScheme:b.colorScheme},size:{visualVariables:d,sizeScheme:a.sizeScheme},authoringInfo:{type:"univariate-color-size",
visualVariables:[m.clone(b.authoringInfo.visualVariables[0]),m.clone(a.authoringInfo.visualVariables[0])]}}})})}Object.defineProperty(l,"__esModule",{value:!0});l.createVisualVariables=r;l.createContinuousRenderer=function(a){return v(a).then(function(a){var b;return p.createContinuousRenderer(w(a)).then(function(g){var c=e.mixin({},a),d=c.symbolType,f=-1<d.indexOf("3d-volumetric");delete c.symbolType;delete c.defaultSymbolEnabled;if(c.worldScale=f)c.sizeOptions=e.mixin({},c.sizeOptions),c.sizeOptions.axis=
"3d-volumetric-uniform"===d?"all":"height";c.statistics=g.statistics;b=g;return r(c)}).then(function(a){var c=b.renderer;c.visualVariables=a.size.visualVariables.map(function(a){return n.cloneSizeVariable(a)});c.visualVariables.push(n.cloneColorVariable(a.color.visualVariable));c.authoringInfo=m.clone(a.authoringInfo);return{renderer:c,statistics:b.statistics,defaultValuesUsed:b.defaultValuesUsed,color:a.color,size:a.size,basemapId:a.basemapId}})})}});